export default {
  conceptual: [
    { question: "equals/hashCode contract?", answer: "Equal objects must have equal hash codes; used by HashMap bucket choice and equality scan." },
    { question: "Average vs worst HashMap?", answer: "Expected O(1); worst O(n) with collisions; Java 8+ treeify mitigates long chains." },
    { question: "Immutable keys why?", answer: "Mutation changes hash bucket placement—lost entries." },
    { question: "HashMap vs TreeMap?", answer: "HashMap faster expected; TreeMap sorted keys O(log n)." },
    { question: "LinkedHashMap when?", answer: "Need stable iteration order or access-order LRU." },
    { question: "ConcurrentHashMap?", answer: "Thread-safe without locking whole map; no null keys/values." },
    { question: "Load factor?", answer: "Triggers resize when size > capacity * lf—time/space tradeoff." },
    { question: "IdentityHashMap?", answer: "Uses reference identity, not equals." },
    { question: "WeakHashMap?", answer: "Weak keys; entries may disappear when only weakly reachable—cache helper." },
    { question: "computeIfAbsent?", answer: "Atomically initialize value if missing—avoid duplicate work races in concurrent contexts with care." },
    { question: "How hashing DOS works?", answer: "Colliding keys degrade to linked lists; mitigated by salted hashes / treeify." },
    { question: "EnumMap?", answer: "Array indexed by enum ordinal—very fast small key universe." },
    { question: "Records as keys?", answer: "Built-in equals/hashCode if components define them—good for DTO keys." },
    { question: "Why not mutable StringBuilder as key?", answer: "Changing contents breaks map invariants." },
    { question: "Resize cost?", answer: "O(n) rehash rare; amortized O(1) inserts." },
    { question: "Multiset with map?", answer: "Count values per key; or Guava Multiset in libraries." },
    { question: "60-second story?", answer: "Contract, immutable keys, pick map variant by ordering/concurrency, cite collision caveats, O(n) frequency patterns." },
  ],
  codeBased: [
    { question: "Two-sum HashMap?", answer: "Map value→index; for each x check target-x." },
    { question: "Anagram buckets?", answer: "Key = sorted chars or char count signature." },
    { question: "First unique character?", answer: "Count then scan string order." },
    { question: "Longest substring k distinct?", answer: "Sliding window + freq map." },
    { question: "Subarray sum K?", answer: "Prefix sum counts in HashMap." },
    { question: "Group anagrams?", answer: "Map signature to list of words." },
    { question: "Copy list with random?", answer: "Map original→clone nodes." },
    { question: "Top K frequent?", answer: "Count map + min-heap of size k." },
    { question: "LRU?", answer: "HashMap + doubly linked list." },
    { question: "Design consistent hashing?", answer: "Ring of virtual nodes—beyond basic map." },
    { question: "Union-Find alternative?", answer: "Sometimes map parent pointers; not HashMap heavy." },
    { question: "Word pattern match?", answer: "Bijection maps pattern char→word and word→char." },
  ],
  seniorScenario: [
    { question: "Cache stampede on hot key?", answer: "Singleflight, locks per key, random TTL jitter." },
    { question: "Large heap map memory?", answer: "Consider off-heap, sharding, eviction, compression of values." },
    { question: "Wrong equals in DTO breaks prod?", answer: "Symptoms: duplicates, missing lookups; add tests for hash/equals." },
    { question: "CHM compute races?", answer: "Use compute methods carefully; avoid long-running callbacks." },
    { question: "Migration from Hashtable?", answer: "Legacy synchronized; prefer CHM or HashMap single-thread." },
    { question: "PII in map keys?", answer: "Logging leaks; redact; prefer opaque IDs." },
  ],
  wrongAnswers: [
    "Equal objects may have different hashCode — violates contract.",
    "TreeMap has O(1) get — false: O(log n).",
    "HashMap allows unlimited null keys — false: one null key.",
    "ConcurrentHashMap allows null values — false.",
    "Changing a key field updates map index automatically — false.",
    "IdentityHashMap uses equals — false: reference identity.",
    "hashCode must be unique per object — false: collisions allowed.",
    "LinkedHashMap sorts keys — false: insertion or access order, not natural sort.",
  ],
};
