export default {
  conceptual: [
    { question: "Bean lifecycle order?", answer: "Instantiate, inject, BPP before, @PostConstruct, InitializingBean, init, BPP after." },
    { question: "Prototype destroy?", answer: "Spring does not call @PreDestroy like singleton; manual cleanup." },
    { question: "@DependsOn when?", answer: "Side-effect ordering beyond dependency graph." },
    { question: "FactoryBean?", answer: "getObject produces actual bean; &name gets factory." },
    { question: "@Primary vs @Qualifier?", answer: "Primary default; qualifier explicit name." },
    { question: "Why constructor injection?", answer: "Immutable, testable, fails fast." },
    { question: "Scoped proxy?", answer: "Inject request bean into singleton." },
    { question: "BeanPostProcessor risk?", answer: "Order; affects all beans; early registration." },
    { question: "InitializingBean vs @PostConstruct?", answer: "Same phase; prefer annotation or initMethod clarity." },
    { question: "Circular dependency?", answer: "@Lazy, setter break, or refactor." },
    { question: "Aware interfaces?", answer: "Tight coupling to container; avoid when possible." },
    { question: "ObjectProvider?", answer: "Lazy or multiple beans resolution." },
    { question: "Slow @PostConstruct impact?", answer: "Startup/readiness latency." },
    { question: "AOP proxy type?", answer: "JDK interface vs CGLIB class targets." },
    { question: "Custom scope?", answer: "Register Scope; often use proxy." },
    { question: "@Order on beans?", answer: "Certain types; not universal for all beans." },
    { question: "60-second lifecycle story?", answer: "Inject, callbacks, proxy, destroy singleton, prototype manual." },
  ],
  codeBased: [
    { question: "@Bean initMethod?", answer: "String name of method on bean class." },
    { question: "Multiple DataSource?", answer: "@Qualifier beans or @ConfigurationProperties binding." },
    { question: "@Configuration proxy?", answer: "@Bean methods intercepted for singleton semantics." },
    { question: "Test @MockBean?", answer: "Replaces bean in slice test." },
    { question: "Profile-specific bean?", answer: "@Profile on @Bean or @Component." },
    { question: "ConditionalOnClass?", answer: "Classpath presence gate for auto-config." },
    { question: "ImportSelector?", answer: "Programmatic @Import of configuration classes." },
    { question: "BeanFactoryPostProcessor?", answer: "Modify bean definitions before instantiation." },
    { question: "Lookup injection?", answer: "Abstract method returns prototype per call." },
    { question: "DisposableBean ordering?", answer: "Depends on destruction callbacks order." },
    { question: "@Autowired List<Service>?", answer: "Injects all beans of type." },
    { question: "Map<String, Service> inject?", answer: "Beans keyed by name." },
  ],
  seniorScenario: [
    { question: "Flaky K8s startup?", answer: "Bean order, readiness, @DependsOn infra." },
    { question: "Memory leak prototype?", answer: "Resources not closed; manual lifecycle." },
    { question: "Wrong bean injected in prod?", answer: "Profiles, @Primary clash, test data." },
    { question: "BPP breaks security?", answer: "Order relative to security configuration." },
    { question: "RefreshScope state loss?", answer: "Counters in fields reset on refresh." },
    { question: "Debug bean creation?", answer: "DEBUG logging, BeanCreationException stack, actuator beans." },
  ],
  wrongAnswers: [
    "@PostConstruct runs before injection — false.",
    "Prototype @PreDestroy always runs — false.",
    "FactoryBean registered bean is always FactoryBean — false consumer gets getObject.",
    "@Primary forces only one bean of type — false multiple allowed with qualifiers.",
    "BeanPostProcessor after every request — false around creation.",
    "Field injection easiest to unit test — false constructor preferred.",
    "Singleton means one per HTTP request — false.",
    "InitializingBean always runs before @PostConstruct — false; order is nuanced within init phase.",
  ],
};
