export default {
  conceptual: [
    { question: "What is type erasure?", answer: "Compile-time generic checks; runtime types mostly erased to bounds/Object." },
    { question: "PECS rule?", answer: "Producer extends, consumer super for wildcards." },
    { question: "Why avoid raw types?", answer: "Lose compile checks; ClassCastException risk." },
    { question: "Why no generic array?", answer: "Arrays covariant; cannot enforce element type at runtime." },
    { question: "Bridge methods?", answer: "Synthetics preserving override after erasure." },
    { question: "Bounded type param vs wildcard?", answer: "T fixed across signatures; ? flexible at call site." },
    { question: "Invariant generics?", answer: "List<Integer> not subtype of List<Number>." },
    { question: "Reifiable vs erased?", answer: "Primitives, raw, unbounded wildcards more reifiable; param types erased." },
    { question: "Class<T> usage?", answer: "Type tokens for reflection when T needed at runtime." },
    { question: "Multiple bounds?", answer: "T extends A & B with class first then interfaces." },
    { question: "Generic method vs class?", answer: "Method-level <T> for static utilities independent of class T." },
    { question: "Heap pollution?", answer: "Unchecked warnings with varargs generic arrays." },
    { question: "Wildcard capture?", answer: "Compiler cannot prove ? type; helper generic method fixes." },
    { question: "extends Number for sum?", answer: "Read numbers uniformly via doubleValue." },
    { question: "super Integer add?", answer: "Can add Integer to List<? super Integer>." },
    { question: "Migration strategy?", answer: "Suppressions minimal; prefer typed APIs gradually." },
    { question: "60-second generics story?", answer: "Compile safety, erasure, PECS, no raw, no generic arrays, bridges awareness." },
  ],
  codeBased: [
    { question: "Signature copy src to dst PECS?", answer: "List<? extends T> src, List<? super T> dst." },
    { question: "max with Comparable?", answer: "<T extends Comparable<T>> T max(List<T>)." },
    { question: "swap Pair<A,B>?", answer: "Return new Pair<>(second, first) with types B,A." },
    { question: "Why List<? extends Number> cannot add int?", answer: "Could be List<Double>; type unsafe." },
    { question: "Diamond in constructor?", answer: "new ArrayList<>() infers from assignment." },
    { question: "Comparator generic?", answer: "Comparator<String> compare method typed." },
    { question: "Stream<T> inference?", answer: "Often inferred from upstream; explicit if ambiguous." },
    { question: "Enum generic?", answer: "Enums cannot be generic type param but can implement interfaces." },
    { question: "Override List<String> get in subclass?", answer: "Return type covariant String ok; erasure compatible." },
    { question: "static T bad in non-static class?", answer: "Cannot refer instance T from static; use own method T." },
    { question: "extends Comparable<? super T> trick?", answer: "Wildcard fix for comparing mixed subtypes." },
    { question: "Generic Throwable forbidden?", answer: "Cannot extend Throwable with type param." },
  ],
  seniorScenario: [
    { question: "JSON mapper loses generic param?", answer: "Use TypeReference/TypeToken; document schemas." },
    { question: "Library exposes raw Collection?", answer: "Wrap or adapt; avoid leaking into app." },
    { question: "Binary compat generic change?", answer: "Erasure helps but signatures/bridges still sensitive." },
    { question: "Performance of generics?", answer: "Mostly same after JIT; erasure no boxing by itself." },
    { question: "Kotlin interop raw?", answer: "Platform types; enforce nullability at boundary." },
    { question: "CI warnings -Xlint:unchecked?", answer: "Treat as debt; fix or justify with narrow suppress." },
  ],
  wrongAnswers: [
    "Generics exist at runtime as List<String> class — false erasure.",
    "List<Integer> subtype List<Number> — false invariant.",
    "You can new List<String>[1] — false.",
    "Raw types preferred in new code — false.",
    "Wildcard ? extends T lets you add T — false producer only reads.",
    "Bridge methods are hand-written — false compiler.",
    "static <T> needs class type param — false method scope.",
    "Arrays and generics covariance same — false.",
  ],
};
