export const basicCode = "package arch.day57;\n\npublic class Day57Basic {\n    public static void main(String[] args) {\n        System.out.println(\"=== CQRS split ===\");\n        System.out.println(\"Command side: validate business rules, mutate aggregates, emit events\");\n        System.out.println(\"Query side: serve denormalized read models optimized for UI/search\");\n        System.out.println();\n        System.out.println(\"=== Event sourcing ===\");\n        System.out.println(\"Truth = ordered append-only events per aggregate stream\");\n        System.out.println(\"State = fold(events) optionally accelerated by snapshots\");\n        System.out.println();\n        System.out.println(\"=== Projection consistency ===\");\n        System.out.println(\"Usually eventual: measure lag SLO between write commit and read freshness\");\n    }\n}\n";

export const basicOutput = "=== CQRS split ===\nCommand side: validate business rules, mutate aggregates, emit events\nQuery side: serve denormalized read models optimized for UI/search\n\n=== Event sourcing ===\nTruth = ordered append-only events per aggregate stream\nState = fold(events) optionally accelerated by snapshots\n\n=== Projection consistency ===\nUsually eventual: measure lag SLO between write commit and read freshness\n";

export const intermediateCode = "package arch.day57;\n\npublic class Day57Intermediate {\n\n    static int fold(int[] deltas) {\n        int bal = 0;\n        for (int d : deltas) {\n            bal += d;\n        }\n        return bal;\n    }\n\n    public static void main(String[] args) {\n        int[] events = {100, -20, -30, 50};\n        System.out.println(\"events=\" + java.util.Arrays.toString(events));\n        System.out.println(\"balance=\" + fold(events));\n    }\n}\n";

export const intermediateOutput = "events=[100, -20, -30, 50]\nbalance=100\n";

export const advancedCode = "package arch.day57;\n\npublic class Day57Advanced {\n\n    static int rebuild(int snapshotBalance, int[] tailAmounts) {\n        int bal = snapshotBalance;\n        for (int a : tailAmounts) {\n            bal += a;\n        }\n        return bal;\n    }\n\n    public static void main(String[] args) {\n        int[] tail = {5, 10, -3};\n        System.out.println(\"replayedBalance=\" + rebuild(100, tail));\n    }\n}\n";

export const advancedOutput = "replayedBalance=112\n";
