export default {
  conceptual: [
    { question: "When are two pointers applicable on arrays?", answer: "When sorted order or a monotone invariant lets you discard half the remaining search space by moving one pointer—common for sorted pair sums, merging, and some partition problems." },
    { question: "Why does two-sum sorted work in O(n)?", answer: "With sorted values, if the sum is too small you must increase the left index; if too large you decrease the right—each move is forced and each index moves at most n steps." },
    { question: "What is a sliding window?", answer: "A contiguous subarray defined by left/right bounds that you expand or shrink while maintaining a constraint—often O(n) total pointer movement." },
    { question: "How do you handle integer overflow in sums?", answer: "Cast to long before adding large ints, or compare with careful subtraction tricks—state this before coding." },
    { question: "Sorted vs unsorted two-sum tradeoff?", answer: "Hash map gives O(n) expected time O(n) space unsorted; sort + two pointers gives O(n log n) time and may allow O(1) extra besides sort output." },
    { question: "What are duplicate-skipping patterns in 3Sum?", answer: "After finding a triplet, advance pointers while skipping equal neighbors to avoid duplicate outputs—only after recording a valid answer." },
    { question: "What invariant do you keep in merge of sorted arrays?", answer: "Always advance the pointer pointing to the smaller head element to maintain global order." },
    { question: "Can two pointers work on linked lists?", answer: "Yes—detect cycles with slow/fast, find middle, reverse half for palindrome checks—different invariant but same two-index idea." },
    { question: "What breaks two-pointer monotonicity?", answer: "Negative numbers in subarray sum problems or unsorted data without preprocessing—need prefix sums + map or sort first." },
    { question: "Explain partition around a pivot.", answer: "Rearrange so elements ≤ pivot sit left and ≥ pivot right in O(n)—foundation of quicksort/quickselect." },
    { question: "What is stable vs unstable partition?", answer: "Stable preserves relative order of equal keys; quicksort partition is typically unstable—matters for labeled records." },
    { question: "How do you prove you do not skip the answer?", answer: "Show that if you move the other pointer, the sum moves away from target under the ordering assumption—case analysis on too small vs too large." },
    { question: "What is two-pointer for container with most water?", answer: "Start at both ends; always move the shorter line inward because width shrinks—only a taller line can improve area." },
    { question: "Difference between subarray and subsequence?", answer: "Subarray is contiguous—sliding window applies; subsequence picks indices without contiguity—often DP." },
    { question: "When is variable-size window linear?", answer: "When each index is added/removed a bounded number of times—typically each element enters and leaves once." },
    { question: "How does merging relate to external sort?", answer: "K-way merge uses heaps or repeated two-pointer merges—same merge kernel scaled up." },
    { question: "Give a 60-second two-pointer story.", answer: "Check sorted/preprocess, set two indices, state monotone rule, handle overflow/duplicates/empties, analyze O(n) moves, mention hash alternative if unsorted." },
  ],
  codeBased: [
    { question: "Time to merge sorted A[n] and B[m]?", answer: "O(n+m) with two indices." },
    { question: "Two-sum sorted space?", answer: "O(1) extra besides input/output arrays." },
    { question: "Reverse array in place?", answer: "O(n) time swap from both ends until pointers meet." },
    { question: "Remove val from array in-place (unsorted)?", answer: "O(n) write index scanning once—two-pointer variant." },
    { question: "Is palindrome check two pointers?", answer: "Yes—compare symmetric chars toward center O(n)." },
    { question: "Squares of sorted array sorted O(n)?", answer: "Two pointers from ends picking larger square magnitude." },
    { question: "Move zeros to end stable?", answer: "Write pointer places non-zeros in order while reader scans—O(n)." },
    { question: "Three sum brute force?", answer: "O(n³); optimized sort + two pointers O(n²)." },
    { question: "Binary search vs two-pointer on sorted array?", answer: "BS finds one position in O(log n); two-pointer scans for pair properties in O(n)." },
    { question: "Subarray sum equals K with negatives?", answer: "Prefix sum + HashMap O(n); pure two-pointer fails without positivity constraint." },
    { question: "Longest substring k distinct?", answer: "Expand right, shrink left while map counts exceed k—O(n)." },
    { question: "Pair with difference in sorted array?", answer: "Two pointers or binary search complement—O(n) or O(n log n) depending variant." },
  ],
  seniorScenario: [
    { question: "Service joins two sorted streams—how scale?", answer: "Stream merge two-pointer style chunk-by-chunk, backpressure, bounded buffers; avoid materializing full lists." },
    { question: "Data unsorted but memory tiny—two-sum?", answer: "External sort chunks then merge streams with pointers; or disk-backed hash if feasible; discuss constraints." },
    { question: "p99 regression after ‘small’ feature—what check?", answer: "Profile for nested loops on request payload; add metrics on list sizes; cap batch with product agreement." },
    { question: "Duplicates explode output in k-sum—mitigation?", answer: "Sort + skip rules, early pruning, or switch representation; warn interviewer about output size." },
    { question: "Parallelizing two-pointer merge?", answer: "Harder than divide partitions; often parallel merge sort uses copies; discuss tradeoffs and stability." },
    { question: "Testing two-pointer correctness?", answer: "Property tests on random sorted arrays vs brute for small n; edge cases empty, single, all equal, negatives." },
  ],
  wrongAnswers: [
    "Two pointers always work in O(n) on any array — false: needs monotonic structure or preprocessing; unsorted arbitrary two-sum needs hash or sort.",
    "Sliding window solves every substring problem in O(n) — false: some need DP or exponential sets; only certain constraints allow linear two-pointer.",
    "You never need long for int sums in Java — false: adjacent large ints overflow and break comparisons.",
    "Sorting is free if you call `sort` once — false: O(n log n) cost must be included in total analysis.",
    "Two pointers and double-ended queue are the same — false: deque is a structure; two pointers is a technique on sequences.",
    "Stable partition is automatic in quicksort — false: standard partition is unstable; mergesort is stable.",
    "Binary search replaces two pointers for pair sum — false: BS helps variants but classic linear two-pointer is O(n) after sort.",
    "Moving both pointers inward always is safe — false: must follow the rule derived from problem invariant; wrong rule skips answers.",
  ],
};
