export default {
  conceptual: [
    { question: "Optional purpose?", answer: "Model optional return without null." },
    { question: "map vs flatMap?", answer: "flatMap when mapper returns Optional." },
    { question: "orElse vs orElseGet?", answer: "Eager default vs lazy Supplier." },
    { question: "Why avoid Optional fields?", answer: "Serialization, JPA, noise." },
    { question: "get() danger?", answer: "Throws if empty; prefer orElse variants." },
    { question: "ifPresentOrElse?", answer: "Handle both branches functionally." },
    { question: "Optional.stream?", answer: "0/1 elements for flatMap pipelines." },
    { question: "ofNullable?", answer: "Convert nullable to Optional." },
    { question: "filter?", answer: "Empty if predicate fails." },
    { question: "orElseThrow?", answer: "Fail with specific exception supplier." },
    { question: "equals/hashCode?", answer: "Value-based for Optional." },
    { question: "Optional param smell?", answer: "Double negation; use overloads or nullable with docs." },
    { question: "Monad analogy?", answer: "map/flatMap/filter similar pattern." },
    { question: "JSON mapping?", answer: "May need adapters; absent vs null distinction." },
    { question: "Kotlin null vs Optional?", answer: "Different platform idioms at boundaries." },
    { question: "Guava Optional migration?", answer: "java.util.Optional standard now." },
    { question: "60-second Optional story?", answer: "Return type clarity, chain, lazy defaults, no fields." },
  ],
  codeBased: [
    { question: "Nested user address city?", answer: "user.flatMap(User::address).map(Address::city)." },
    { question: "First non-empty string list?", answer: "Stream map Optional flatMap." },
    { question: "Default if empty lazy expensive?", answer: "orElseGet(() -> load())." },
    { question: "Convert optional to list?", answer: "optional.stream().toList()." },
    { question: "Combine two optionals?", answer: "flatMap + map or use or() Java 9." },
    { question: "Throw if missing?", answer: "orElseThrow(IllegalStateException::new)." },
    { question: "Primitive optional?", answer: "OptionalInt OptionalLong OptionalDouble." },
    { question: "Optional in record?", answer: "Allowed; document semantics." },
    { question: "JPA attribute Optional?", answer: "Often problematic; nullable column simpler." },
    { question: "Rest controller Optional?", answer: "Usually unwrap to 404/204 explicitly." },
    { question: "Cache get Optional?", answer: "empty means miss; separate error channel." },
    { question: "Test empty?", answer: "assertTrue(opt.isEmpty()) or assertEquals(Optional.empty(), opt)." },
  ],
  seniorScenario: [
    { question: "API returns Optional but clients want null?", answer: "Document; adapter at boundary." },
    { question: "Logging absent?", answer: "Structured field absent vs null in logs." },
    { question: "Reactive Optional?", answer: "Mono maybe better model for async absence." },
    { question: "Performance of Optional?", answer: "Small object; usually fine; avoid hot loops allocation if critical." },
    { question: "Code review rule?", answer: "No Optional fields; no Optional params unless API design demands." },
    { question: "Migration from null returns?", answer: "Gradual; keep backward compat helpers." },
  ],
  wrongAnswers: [
    "Optional.of(null) is empty — false throws.",
    "Optional replaces null everywhere — false.",
    "get() is preferred — false risky.",
    "orElseGet eager — false lazy.",
    "flatMap same as map always — false.",
    "Optional fields best practice — false debated.",
    "Optional serializes cleanly always — false frameworks vary.",
    "Stream from Optional infinite — false 0/1.",
  ],
};
