export default [
  { level: "basic", category: "theory", question: "Optional primary intent:", options: { A: "Explicit absent value", B: "Replace all nulls", C: "Faster than null", D: "Thread lock" }, answer: "A", explanation: "API clarity." },
  { level: "basic", category: "code", question: "Optional.of(null):", options: { A: "Throws NPE", B: "empty", C: "Optional null", D: "Silent" }, answer: "A", explanation: "Contract." },
  { level: "basic", category: "theory", question: "ofNullable(null) yields:", options: { A: "empty", B: "of null", C: "error", D: "Optional absent" }, answer: "A", explanation: "Factory." },
  { level: "intermediate", category: "code", question: "map on empty:", options: { A: "Stays empty", B: "NPE", C: "of null", D: "throws ISE" }, answer: "A", explanation: "Short-circuit." },
  { level: "intermediate", category: "theory", question: "flatMap avoids:", options: { A: "Optional<Optional<T>>", B: "boxing", C: "streams", D: "synchronized" }, answer: "A", explanation: "Flatten." },
  { level: "intermediate", category: "code", question: "orElseGet vs orElse:", options: { A: "Lazy vs eager default", B: "Same", C: "Only name", D: "throws" }, answer: "A", explanation: "Supplier." },
  { level: "advanced", category: "theory", question: "Optional as field anti-pattern because:", options: { A: "Serialization/bean noise", B: "Always best", C: "Required JPA", D: "Faster" }, answer: "A", explanation: "Style guides." },
  { level: "intermediate", category: "code", question: "ifPresent takes:", options: { A: "Consumer", B: "Supplier", C: "Runnable", D: "Comparator" }, answer: "A", explanation: "Side effect." },
  { level: "basic", category: "theory", question: "get() without check:", options: { A: "NoSuchElement if empty", B: "null", C: "empty", D: "0" }, answer: "A", explanation: "Discouraged." },
  { level: "intermediate", category: "code", question: "filter on Optional:", options: { A: "Empty if predicate false", B: "Throws", C: "Ignores", D: "Maps" }, answer: "A", explanation: "Monad-like." },
  { level: "intermediate", category: "theory", question: "Optional.stream Java 9:", options: { A: "0 or 1 elements", B: "Always 2", C: "Infinite", D: "Error" }, answer: "A", explanation: "Bridge." },
  { level: "advanced", category: "code", question: "orElseThrow Supplier:", options: { A: "Custom exception", B: "Always NPE", C: "No overload", D: "Returns null" }, answer: "A", explanation: "Java 10+." },
  { level: "intermediate", category: "theory", question: "Optional in method param:", options: { A: "Usually discouraged", B: "Required", C: "Best practice", D: "JLS mandates" }, answer: "A", explanation: "Clean code." },
  { level: "basic", category: "code", question: "isPresent:", options: { A: "Boolean guard", B: "Gets value", C: "Maps", D: "Throws" }, answer: "A", explanation: "Check." },
  { level: "intermediate", category: "code", question: "nested optional flatMap:", options: { A: "Single level Optional", B: "Always double", C: "Illegal", D: "raw" }, answer: "A", explanation: "Chaining." },
  { level: "advanced", category: "theory", question: "JSON Optional fields:", options: { A: "Framework dependent pain", B: "Always trivial", C: "Banned", D: "Primitive" }, answer: "A", explanation: "Interop." },
  { level: "intermediate", category: "code", question: "Optional equals:", options: { A: "Both empty or equal values", B: "Identity", C: "Always false", D: "Reference only" }, answer: "A", explanation: "Value semantics." },
  { level: "basic", category: "theory", question: "Why not Optional everywhere?", options: { A: "Noise and cost", B: "Illegal", C: "Slower GC always", D: "JDK forbids" }, answer: "A", explanation: "Pragmatic." },
  { level: "intermediate", category: "code", question: "map to Optional flatMap needed when:", options: { A: "Mapper returns Optional", B: "Never", C: "Always use map", D: "Only int" }, answer: "A", explanation: "Avoid nesting." },
  { level: "advanced", category: "code", question: "Optional to nullable bridge:", options: { A: "orElse(null) discouraged pattern", B: "Only way", C: "Illegal", D: "get always" }, answer: "A", explanation: "Legacy interop." },
  { level: "intermediate", category: "theory", question: "ifPresentOrElse Java 9:", options: { A: "Consumer + empty Runnable", B: "No such", C: "Two optionals", D: "throws" }, answer: "A", explanation: "API." },
  { level: "intermediate", category: "code", question: "Optional chain for nested field:", options: { A: "flatMap each layer", B: "get chaining", C: "cast", D: "synchronized" }, answer: "A", explanation: "Null-safe." },
  { level: "basic", category: "theory", question: "empty() singleton:", options: { A: "Shared empty instance", B: "New each time", C: "null", D: "random" }, answer: "A", explanation: "Optional.empty." },
  { level: "advanced", category: "theory", question: "Stream single optional flatten:", options: { A: "flatMap Optional::stream", B: "map only", C: "get", D: "cast" }, answer: "A", explanation: "Java 9+." },
  { level: "intermediate", category: "code", question: "or with Optional:", options: { A: "First present wins Java 9+", B: "Union all", C: "Illegal", D: "Adds values" }, answer: "A", explanation: "Alternative." },
  { level: "intermediate", category: "theory", question: "Optional and records:", options: { A: "Optional components ok in API", B: "Forbidden", C: "Only static", D: "JPA perfect" }, answer: "A", explanation: "Modeling." },
  { level: "basic", category: "code", question: "Optional.ofNullable for chain start:", options: { A: "Safe from null input", B: "Always throws", C: "Only primitives", D: "Returns void" }, answer: "A", explanation: "Boundary." },
  { level: "intermediate", category: "code", question: "stream flatMap Optional::stream:", options: { A: "Drops empty", B: "Error on empty", C: "Adds null", D: "Sorts" }, answer: "A", explanation: "Flatten list." },
  { level: "advanced", category: "theory", question: "Domain Optional vs exception:", options: { A: "Expected absent vs exceptional", B: "Same", C: "Exception always", D: "Optional always throw" }, answer: "A", explanation: "Design." },
  { level: "intermediate", category: "code", question: "Optional describeConstable:", options: { A: "Java 12+ API for symbolic", B: "Stream op", C: "GC", D: "Thread" }, answer: "A", explanation: "Advanced." },
];
