export default {
  conceptual: [
    { question: "What is SAM?", answer: "Single abstract method interface; lambda target." },
    { question: "Effectively final?", answer: "Local not reassigned; capturable." },
    { question: "invokedynamic role?", answer: "Lambda linkage via metafactory." },
    { question: "Method ref kinds?", answer: "Static, bound instance, unbound, constructor." },
    { question: "Why Comparator.comparing?", answer: "Readable key extract + nullsFirst options." },
    { question: "Checked exceptions in lambda?", answer: "Try/catch or change API to unchecked." },
    { question: "@FunctionalInterface?", answer: "Compiler enforces SAM intent." },
    { question: "Lambda vs anonymous?", answer: "Different bytecode; lambda lighter linkage." },
    { question: "this capture?", answer: "Instance lambdas capture enclosing this." },
    { question: "Serialization concern?", answer: "Synthetic classes fragile across releases." },
    { question: "Predicate composition?", answer: "and/or/negate combine boolean tests." },
    { question: "Function composition?", answer: "andThen compose chain transformations." },
    { question: "Stream lazy?", answer: "Intermediate ops lazy; terminal triggers." },
    { question: "Target typing?", answer: "Lambda type from assignment/parameter context." },
    { question: "Variable shadowing?", answer: "Lambda params can shadow; careful readability." },
    { question: "JDK version lambda?", answer: "Java 8+." },
    { question: "60-second lambda story?", answer: "SAM, capture rules, refs, composition, stream fit." },
  ],
  codeBased: [
    { question: "s -> s.trim() method ref?", answer: "String::trim as Function." },
    { question: "Sort by length then name?", answer: "comparing length thenComparing naturalOrder." },
    { question: "Print consumer ref?", answer: "System.out::println Consumer." },
    { question: "Supplier random seed?", answer: "() -> value or method ref no-arg factory." },
    { question: "Runnable in thread?", answer: "() -> { ... } passed to Thread." },
    { question: "BiConsumer usage?", answer: "(k,v) -> map put style in forEach." },
    { question: "mapToInt purpose?", answer: "Avoid boxing in numeric pipelines." },
    { question: "Optional.ifPresent takes?", answer: "Consumer." },
    { question: "Collectors joining?", answer: "Terminal concat with delimiter." },
    { question: "flatMap in stream?", answer: "Function to stream flatten." },
    { question: "distinct stable?", answer: "Encounter order for ordered streams." },
    { question: "peek for debugging?", answer: "Side-effect view; do not rely for logic." },
  ],
  seniorScenario: [
    { question: "Team overuses lambdas?", answer: "Extract methods when >3 lines; readability." },
    { question: "Performance myth?", answer: "Measure; lambdas not free but usually fine." },
    { question: "Framework requires Serializable lambda?", answer: "Avoid; pass class or explicit fn object." },
    { question: "Migration from anonymous?", answer: "Mechanical except capture subtlety." },
    { question: "Kotlin SAM?", answer: "Single abstract fun interop; be explicit at boundaries." },
    { question: "Code review lambda rule?", answer: "Complex logic named method; tests target behavior." },
  ],
  wrongAnswers: [
    "Lambdas can implement two SAMs — false.",
    "Locals can be reassigned and captured — false effectively final.",
    "Method references always static — false kinds vary.",
    "Lambda is same anonymous class bytecode — false invokedynamic.",
    "Predicate returns int — false boolean.",
    "Comparator.comparing needs lambda only — false method refs ok.",
    "Streams always parallel faster — false overhead.",
    "Lambda may throw checked without handling — false must satisfy SAM.",
  ],
};
