export default {
  conceptual: [
    { question: "Stack vs queue use?", answer: "Stack for LIFO (DFS, undo, parentheses); queue for FIFO (BFS, fair scheduling)." },
    { question: "Why avoid java.util.Stack?", answer: "Legacy, extends Vector, synchronized overhead; prefer ArrayDeque." },
    { question: "Monotonic stack idea?", answer: "Maintain increasing/decreasing values/indices to resolve next-greater/smaller in one pass." },
    { question: "PriorityQueue vs queue?", answer: "PQ orders by priority comparator—not arrival order." },
    { question: "BlockingQueue purpose?", answer: "Coordinate producers/consumers with backpressure." },
    { question: "Deque advantages?", answer: "O(1) both ends; sliding window max, palindrome deque checks." },
    { question: "Recursive DFS vs explicit stack?", answer: "Same order; explicit avoids deep recursion stack overflow." },
    { question: "Balanced parentheses algorithm?", answer: "Push opens, on close pop and match; empty invalid early; end stack empty." },
    { question: "Min stack design?", answer: "Parallel stack tracking current minimum at each depth." },
    { question: "ArrayDeque limitations?", answer: "Not thread-safe; no null elements; resizable array ring." },
    { question: "Histogram rectangle stack?", answer: "Pop when lower height seen; compute width with index stack." },
    { question: "When LinkedList queue?", answer: "Rarely hot paths; nodes allocate; ArrayDeque often better." },
    { question: "offer vs add?", answer: "offer signals failure on full bounded queue; add throws." },
    { question: "Concurrent queues?", answer: "java.util.concurrent for producer/consumer without external lock in many cases." },
    { question: "Stack in expression eval?", answer: "Operands and operators; RPN especially simple." },
    { question: "Memory of explicit stack?", answer: "Still O(depth) but controllable vs hidden recursion frames." },
    { question: "60-second story?", answer: "Pick deque/stack/queue by traversal; ArrayDeque default; monotonic stack for next greater; parentheses with map; mention PQ not FIFO." },
  ],
  codeBased: [
    { question: "Next greater O(n)?", answer: "Monotonic decreasing stack of indices." },
    { question: "Daily temperatures?", answer: "Stack stores indices awaiting warmer temp." },
    { question: "Largest rectangle histogram?", answer: "Stack bars increasing heights; compute area on pop." },
    { question: "Reverse polish evaluation?", answer: "Stack numbers; on operator pop two apply push." },
    { question: "Decode nested string k[...]?", answer: "Stack of repeat counts and built strings." },
    { question: "Remove duplicate adjacent chars?", answer: "Stack push if top differs." },
    { question: "Implement queue using stacks?", answer: "Two stacks amortized O(1) enqueue/dequeue." },
    { question: "Implement stack using queues?", answer: "Rotate queue on push—O(n) per push naive." },
    { question: "Binary tree inorder iterative?", answer: "Stack simulate recursion left spine." },
    { question: "Validate BST preorder serialization?", answer: "Stack lower/upper bounds per frame." },
    { question: "Exclusive time of functions?", answer: "Stack active function with timeline parsing." },
    { question: "Asteroid collision?", answer: "Stack simulates signed masses collisions." },
  ],
  seniorScenario: [
    { question: "Service queue backlog grows—what structurally?", answer: "Check consumer rate, bounded queue policy, drop vs block, scale-out consumers." },
    { question: "Thread pool unbounded queue risk?", answer: "Memory exhaustion; use bounded queues + rejection policy." },
    { question: "Event loop starvation?", answer: "Fair scheduling, prioritize queues, split hot tasks." },
    { question: "Parser stack depth attack?", answer: "Limit nesting depth, streaming parser, stack depth counters." },
    { question: "Metrics for queue health?", answer: "Depth, age of oldest item, consumer lag, drop counts." },
    { question: "Choosing concurrent deque?", answer: "Work-stealing for fork/join; lock-free for low contention producers." },
  ],
  wrongAnswers: [
    "PriorityQueue is a FIFO queue — false: it orders by priority.",
    "Stack is always thread-safe in Java — false: ArrayDeque is not; old Stack synchronized but still discouraged.",
    "BFS uses stack — false: uses queue.",
    "Monotonic stack is O(n^2) always — false: amortized linear.",
    "Deque cannot be used as stack — false: ArrayDeque supports push/pop at head.",
    "Balanced parentheses only needs counting — false: must match type of bracket.",
    "LinkedList is always faster than ArrayDeque for queues — false: allocation overhead often loses.",
    "Unbounded queues are always safe — false: can exhaust memory under overload.",
  ],
};
