export const basicCode = "package arch.day55;\n\npublic class Day55Basic {\n    public static void main(String[] args) {\n        System.out.println(\"=== Sync HTTP request chain ===\");\n        System.out.println(\"Pros: simple to reason, great for read-after-write consistency\");\n        System.out.println(\"Cons: multiplies latency; failure anywhere fails the user request\");\n        System.out.println();\n        System.out.println(\"=== Async event choreography ===\");\n        System.out.println(\"Pros: decouples availability; absorbs bursts with broker buffering\");\n        System.out.println(\"Cons: eventual consistency; needs idempotent consumers + schema discipline\");\n        System.out.println();\n        System.out.println(\"=== Hybrid rule of thumb ===\");\n        System.out.println(\"User-facing critical path: short sync + outbox for side effects\");\n        System.out.println(\"Cross-domain notifications: durable events with outbox or log\");\n    }\n}\n";

export const basicOutput = "=== Sync HTTP request chain ===\nPros: simple to reason, great for read-after-write consistency\nCons: multiplies latency; failure anywhere fails the user request\n\n=== Async event choreography ===\nPros: decouples availability; absorbs bursts with broker buffering\nCons: eventual consistency; needs idempotent consumers + schema discipline\n\n=== Hybrid rule of thumb ===\nUser-facing critical path: short sync + outbox for side effects\nCross-domain notifications: durable events with outbox or log\n";

export const intermediateCode = "package arch.day55;\n\nimport java.util.*;\n\npublic class Day55Intermediate {\n\n    public static void main(String[] args) {\n        List<String> log = new ArrayList<>();\n        log.add(\"OrderService: persist order row + outbox OrderPlaced\");\n        log.add(\"OutboxRelay: publish OrderPlaced to broker\");\n        log.add(\"InventoryConsumer: reserve stock idempotently\");\n        log.add(\"PaymentConsumer: attempt charge idempotently\");\n        log.add(\"ShippingConsumer: create shipment when both succeed\");\n        System.out.println(\"=== Choreography timeline (happy path) ===\");\n        for (String line : log) {\n            System.out.println(line);\n        }\n    }\n}\n";

export const intermediateOutput = "=== Choreography timeline (happy path) ===\nOrderService: persist order row + outbox OrderPlaced\nOutboxRelay: publish OrderPlaced to broker\nInventoryConsumer: reserve stock idempotently\nPaymentConsumer: attempt charge idempotently\nShippingConsumer: create shipment when both succeed\n";

export const advancedCode = "package arch.day55;\n\npublic class Day55Advanced {\n\n    static int scoreSync(int hops, int blast) {\n        return hops * 4 + blast * 3;\n    }\n\n    static int scoreAsync(int schemaCost, int opsMaturity) {\n        return schemaCost * 2 + (10 - opsMaturity) * 5;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(\"=== Pattern scorecard (lower is better for that column intent) ===\");\n        int s = scoreSync(4, 3);\n        int a = scoreAsync(3, 7);\n        System.out.println(\"syncChainScore=\" + s + \" asyncEventScore=\" + a);\n        System.out.println(s < a ? \"Pick: tighten sync chain (fewer hops)\" : \"Pick: invest in async + ops maturity\");\n    }\n}\n";

export const advancedOutput = "=== Pattern scorecard (lower is better for that column intent) ===\nsyncChainScore=25 asyncEventScore=21\nPick: invest in async + ops maturity\n";
