name: Subscribe to Newsletter
description: Add your email to receive new Satyverse blog posts
labels: [subscribe]
body:
  - type: input
    id: email
    attributes:
      label: Email Address
      description: We'll add this address to data/subscribers.json
      placeholder: you@example.com
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Optional Note
      description: Anything you'd like us to know
      placeholder: (optional)
    validations:
      required: false
