export default {
  conceptual: [
    { question: "Heap vs stack?", answer: "Heap objects; stack frames and locals." },
    { question: "What is STW?", answer: "Stop-the-world pause all mutators." },
    { question: "G1 regions?", answer: "Heap divided; collect subsets; pause targets." },
    { question: "Metaspace vs PermGen?", answer: "Native class metadata; unbounded by default." },
    { question: "JIT tiers?", answer: "Interpreted C1 C2 tiered compilation." },
    { question: "Safepoint operations?", answer: "GC deopt some JVMTI activities." },
    { question: "GC throughput vs latency?", answer: "CPU for GC vs pause length trade-off." },
    { question: "Weak references?", answer: "Collected eagerly when weak only refs." },
    { question: "Why avoid finalize?", answer: "Non-deterministic; use try-with-resources." },
    { question: "Classloader leak?", answer: "Dynamic classes keep loader alive." },
    { question: "What is TLAB?", answer: "Per-thread allocation buffers reduce contention." },
    { question: "Humongous objects?", answer: "Large arrays special cases in G1." },
    { question: "NMT purpose?", answer: "Track native allocations beyond heap." },
    { question: "JFR value?", answer: "Low overhead profiling and GC events." },
    { question: "Xms vs Xmx?", answer: "Initial vs max heap reservation." },
    { question: "Container memory?", answer: "CGroup limits affect JVM ergonomics." },
    { question: "60-second JVM story?", answer: "Heap/stack, GC goals, metrics before flags, Metaspace watch." },
  ],
  codeBased: [
    { question: "Read heap usage?", answer: "MemoryMXBean or Runtime totals/free." },
    { question: "Runtime metrics?", answer: "maxMemory totalMemory freeMemory." },
    { question: "Trigger GC in prod?", answer: "Rare; fix allocation; System.gc only diagnostics." },
    { question: "Stack depth error?", answer: "StackOverflowError increase stack or fix recursion." },
    { question: "Heap OOM fix?", answer: "Leak hunt or raise Xmx after evidence." },
    { question: "Off-heap buffer?", answer: "DirectByteBuffer native memory outside heap." },
    { question: "String intern growth?", answer: "Metaspace/perm issues; avoid abuse." },
    { question: "Large heap pause?", answer: "Tune collector; reduce live set; structural fix." },
    { question: "GC log flags?", answer: "JDK version specific unified logging." },
    { question: "jcmd tools?", answer: "Thread dump heap dump GC.run_finalization." },
    { question: "Object sizing?", answer: "Headers alignment arrays tools estimate." },
    { question: "Compressed oops?", answer: "Pointer compression under thresholds." },
  ],
  seniorScenario: [
    { question: "p99 latency spikes GC?", answer: "Correlate pause events; tune IHOP; reduce allocation." },
    { question: "K8s OOMKilled?", answer: "Heap + native + metaspace vs cgroup limit." },
    { question: "Upgrade JDK GC change?", answer: "Default collector shifts; retest." },
    { question: "Large young GC?", answer: "Allocation rate high; object churn profiling." },
    { question: "Remote profiling overhead?", answer: "Sample rates; avoid always-on full detail." },
    { question: "Native crash hs_err?", answer: "Analyze alongside core; version native libs." },
  ],
  wrongAnswers: [
    "System.gc guarantees immediate full GC — false.",
    "Stack stores all objects — false heap.",
    "Metaspace is part of Xmx heap — false native separate accounting.",
    "More heap always reduces pauses — false can worsen.",
    "JIT compiles everything at start — false tiered.",
    "Weak ref prevents GC — false.",
    "finalize runs promptly — false.",
    "Runtime.freeMemory exact committed free — false approximate.",
  ],
};
