export default [
  { level: "basic", category: "theory", question: "Heap stores:", options: { A: "Objects", B: "Only primitives local", C: "Bytecode", D: "Sockets" }, answer: "A", explanation: "Shared heap." },
  { level: "basic", category: "code", question: "Runtime.getRuntime():", options: { A: "Singleton runtime", B: "New each call", C: "GC object", D: "Thread" }, answer: "A", explanation: "API." },
  { level: "basic", category: "theory", question: "JIT stands for:", options: { A: "Just-In-Time compile", B: "Java IO Thread", C: "Join In Time", D: "JVM Internal Table" }, answer: "A", explanation: "Compilation." },
  { level: "intermediate", category: "code", question: "maxMemory:", options: { A: "Upper bound heap", B: "Stack size", C: "Metaspace exact", D: "CPU count" }, answer: "A", explanation: "Runtime." },
  { level: "intermediate", category: "theory", question: "Stop-the-world:", options: { A: "All mutators pause", B: "Never happens", C: "Only ZGC", D: "Only JDK8" }, answer: "A", explanation: "GC phases." },
  { level: "intermediate", category: "code", question: "freeMemory:", options: { A: "Approx free heap now", B: "Exact forever", C: "Stack", D: "Threads" }, answer: "A", explanation: "Heuristic." },
  { level: "advanced", category: "theory", question: "Metaspace replaced:", options: { A: "PermGen", B: "Heap", C: "Stack", D: "Code cache" }, answer: "A", explanation: "Java8+." },
  { level: "intermediate", category: "code", question: "System.gc():", options: { A: "Hint not guarantee", B: "Forces immediately always", C: "Disables GC", D: "Allocates" }, answer: "A", explanation: "Advisory." },
  { level: "basic", category: "theory", question: "Stack per thread holds:", options: { A: "Frames locals", B: "All objects", C: "Classes", D: "GC roots only" }, answer: "A", explanation: "Thread stack." },
  { level: "intermediate", category: "code", question: "availableProcessors:", options: { A: "Runtime capacity hint", B: "Exact hardware always", C: "GC threads", D: "Heap size" }, answer: "A", explanation: "Pools." },
  { level: "intermediate", category: "theory", question: "G1 collector target:", options: { A: "Balance pause and throughput", B: "Zero pause always", C: "No tuning", D: "Only tiny heap" }, answer: "A", explanation: "Default many svc." },
  { level: "advanced", category: "code", question: "NMT:", options: { A: "Native memory tracking", B: "New thread map", C: "Network", D: "Null" }, answer: "A", explanation: "Diagnostic." },
  { level: "intermediate", category: "theory", question: "Classloader leaks symptom:", options: { A: "Metaspace growth", B: "Faster GC", C: "Smaller heap", D: "Fewer threads" }, answer: "A", explanation: "Old gen classes." },
  { level: "basic", category: "code", question: "totalMemory:", options: { A: "Current heap committed to JVM", B: "Max always", C: "Stack", D: "CPU" }, answer: "A", explanation: "Runtime." },
  { level: "intermediate", category: "code", question: "OOME Java heap:", options: { A: "Cannot allocate object", B: "Stack overflow", C: "Compile error", D: "NPE" }, answer: "A", explanation: "Error." },
  { level: "advanced", category: "theory", question: "ZGC goal:", options: { A: "Low latency scalable heaps", B: "Smallest throughput", C: "No GC", D: "Only embedded" }, answer: "A", explanation: "Collector." },
  { level: "intermediate", category: "theory", question: "Safepoint:", options: { A: "Coordination for VM ops", B: "User lock", C: "File flush", D: "Socket" }, answer: "A", explanation: "STW related." },
  { level: "intermediate", category: "code", question: "StackOverflowError:", options: { A: "Deep recursion frames", B: "Heap full", C: "GC", D: "IO" }, answer: "A", explanation: "Stacks." },
  { level: "basic", category: "theory", question: "Bytecode executed by:", options: { A: "Interpreter then JIT", B: "CPU direct", C: "OS loader", D: "GC" }, answer: "A", explanation: "Execution." },
  { level: "advanced", category: "code", question: "JFR:", options: { A: "Flight recordings profiling", B: "Garbage flag", C: "Remote only", D: "Compiler off" }, answer: "A", explanation: "Observability." },
  { level: "intermediate", category: "theory", question: "Generational hypothesis:", options: { A: "Most objects die young", B: "All old", C: "No young gen", D: "Equal lifetimes" }, answer: "A", explanation: "GC theory." },
  { level: "intermediate", category: "code", question: "-Xmx sets:", options: { A: "Max heap", B: "Stack", C: "Threads", D: "Metaspace exact" }, answer: "A", explanation: "Flag." },
  { level: "basic", category: "theory", question: "GC roots include:", options: { A: "Stacks statics JNI", B: "Only heap", C: "Only young", D: "Disk" }, answer: "A", explanation: "Reachability." },
  { level: "advanced", category: "code", question: "Humongous objects G1:", options: { A: "Special region handling", B: "Never", C: "Only arrays", D: "Ignored" }, answer: "A", explanation: "Detail." },
  { level: "intermediate", category: "theory", question: "TLAB:", options: { A: "Thread local allocation buffer", B: "GC algorithm", C: "Lock", D: "Socket buffer" }, answer: "A", explanation: "Allocation." },
  { level: "intermediate", category: "code", question: "finalize deprecated:", options: { A: "Avoid for resource cleanup", B: "Preferred", C: "Fast", D: "Deterministic" }, answer: "A", explanation: "try-with-resources." },
  { level: "basic", category: "theory", question: "Reference types:", options: { A: "Strong soft weak phantom", B: "Only strong", C: "Two", D: "None" }, answer: "A", explanation: "GC interaction." },
  { level: "advanced", category: "code", question: "Shenandoah concurrent:", options: { A: "Low pause collector", B: "Serial only", C: "No concurrent", D: "Removed" }, answer: "A", explanation: "Collector." },
  { level: "intermediate", category: "theory", question: "Tuning without metrics:", options: { A: "Guesswork harmful", B: "Always good", C: "Required", D: "Zero risk" }, answer: "A", explanation: "Methodology." },
  { level: "intermediate", category: "code", question: "MemoryMXBean:", options: { A: "JMX heap pools info", B: "Thread dump", C: "Socket", D: "Compiler" }, answer: "A", explanation: "Monitoring." },
];
