export default {
  conceptual: [
    { question: "Define DP?", answer: "Break into overlapping subproblems with optimal substructure; cache or tabulate." },
    { question: "Memo vs tab?", answer: "Top-down recursion+cache vs bottom-up loops; trade stack vs iteration." },
    { question: "Fibonacci complexity memo?", answer: "O(n) time O(n) space; O(1) space iterative." },
    { question: "State meaning?", answer: "Precise definition of dp[i] or dp[i][w] before transitions." },
    { question: "Base cases?", answer: "Smallest inputs with direct answer—prevent infinite recursion." },
    { question: "When greedy fails?", answer: "When local optimal doesn't build global—coin change arbitrary." },
    { question: "0/1 knapsack vs unbounded?", answer: "Inner loop direction differs—once vs infinite uses." },
    { question: "LCS intuition?", answer: "Match extends diagonal; else max of up/left." },
    { question: "House robber?", answer: "Max money without adjacent picks—linear DP." },
    { question: "Climbing stairs?", answer: "Ways = fib-like recurrence." },
    { question: "Unique paths?", answer: "Sum from top and left cells." },
    { question: "Edit distance?", answer: "Insert delete replace costs table." },
    { question: "Bitmask DP?", answer: "Subsets over n items—exponential states." },
    { question: "DAG DP?", answer: "Process nodes in topological order." },
    { question: "Space roll?", answer: "Keep only previous row/column when dependencies local." },
    { question: "Divide & conquer vs DP?", answer: "D&C disjoint subproblems (merge sort); DP overlaps." },
    { question: "60-second story?", answer: "State, recurrence, base, order, complexity, space optimize—Fibonacci as example." },
  ],
  codeBased: [
    { question: "Min path sum grid?", answer: "dp[i][j]=grid+min(up,left)." },
    { question: "Decode ways?", answer: "DP[i] += DP[i-1] if valid single; += DP[i-2] if valid double." },
    { question: "Target sum +/-?", answer: "Transform subset sum or DP over range." },
    { question: "Longest palindromic substring?", answer: "Expand centers or interval DP." },
    { question: "Maximal square?", answer: "DP side length from neighbors." },
    { question: "Buy/sell stock k times?", answer: "DP states hold/sold transactions." },
    { question: "Jump game?", answer: "Greedy reach or DP reachable." },
    { question: "Palindrome partition II cuts?", answer: "DP cuts + precompute palindrome." },
    { question: "Word break 2 all sentences?", answer: "DFS + memo strings." },
    { question: "Cherry pickup grid?", answer: "Two paths simultaneous DP." },
    { question: "Dice combinations?", answer: "Unbounded or bounded DP on sum." },
    { question: "Minimum cost tickets?", answer: "DP on day coverage." },
  ],
  seniorScenario: [
    { question: "DP in production solvers?", answer: "Often OR-Tools; interviews toy versions." },
    { question: "Memoization memory blow?", answer: "State explosion; prune or use iterative compact representation." },
    { question: "Floating errors in DP costs?", answer: "Use integers cents; careful rounding." },
    { question: "Parallelizing DP?", answer: "Hard dependencies; wavefront methods niche." },
    { question: "Testing DP?", answer: "Brute force small n compare." },
    { question: "Stack overflow top-down?", answer: "Switch to bottom-up for deep n." },
  ],
  wrongAnswers: [
    "DP applies to merge sort — false disjoint subproblems.",
    "Fibonacci naive recursion is O(n) — false exponential.",
    "Greedy works for all coin changes — false.",
    "Memo always uses more memory than tab — not always; tab may fill full table while memo sparse.",
    "DP never uses exponential time — some state spaces exponential.",
    "Base cases optional — false.",
    "LCS only hash maps — classic 2D DP.",
    "0/1 knapsack unbounded loop same as coin unbounded without care — direction matters.",
  ],
};
