export default {
  conceptual: [
    { question: "Binary heap properties?", answer: "Complete tree + heap order parent/children." },
    { question: "Java PriorityQueue default order?", answer: "Min-heap smallest first." },
    { question: "offer vs poll complexity?", answer: "O(log n); peek O(1)." },
    { question: "kth largest with heap?", answer: "Maintain min-heap size k of largest elements; peek is answer." },
    { question: "Why not FIFO queue?", answer: "PQ orders by priority comparator, not arrival." },
    { question: "Comparator tie handling?", answer: "Add secondary key for deterministic ordering." },
    { question: "Build heap O(n)?", answer: "Bottom-up heapify all nodes." },
    { question: "Indexed heap?", answer: "Map element→index for decrease-key." },
    { question: "Median streaming?", answer: "Two heaps: low max-heap, high min-heap balanced." },
    { question: "k-way merge?", answer: "Min-heap tracks smallest head among k lists." },
    { question: "Dijkstra role?", answer: "PQ selects minimum tentative distance vertex." },
    { question: "Stable ordering?", answer: "PQ not stable; encode order in comparator." },
    { question: "Duplicates in PQ?", answer: "Allowed; TreeSet would dedupe." },
    { question: "remove(object) cost?", answer: "O(n) find + log n bubble." },
    { question: "When heapsort?", answer: "In-place O(n log n) not stable." },
    { question: "Blocking PQ?", answer: "PriorityBlockingQueue for concurrent schedulers." },
    { question: "60-second story?", answer: "Min vs max comparator, k-top patterns, log ops, not FIFO, O(n) build, tie-break comparator." },
  ],
  codeBased: [
    { question: "Top K frequent?", answer: "Count map + heap on frequency." },
    { question: "Merge k lists?", answer: "Heap Node{listHead,val}." },
    { question: "Closest points?", answer: "Max-heap size k on squared distance." },
    { question: "Task scheduler?", answer: "Heap ready time + queue wait." },
    { question: "Rearrange string k distance?", answer: "Max-heap counts greedy placement." },
    { question: "Sliding window median?", answer: "Two heaps lazy deletion tricky." },
    { question: "Ugly numbers II?", answer: "Pointer merge or PQ BFS on factors." },
    { question: "Smallest range covering k lists?", answer: "Heap track min/max across lists." },
    { question: "Meeting rooms II?", answer: "Min-heap of end times sweep starts." },
    { question: "Find median from data stream?", answer: "Two heaps balance sizes." },
    { question: "Super ugly numbers?", answer: "Generalize primes heap merge." },
    { question: "Sort characters by frequency?", answer: "Heap or bucket sort by freq." },
  ],
  seniorScenario: [
    { question: "Starvation in priority schedulers?", answer: "Aging boosts priority over time." },
    { question: "Comparator hot path perf?", answer: "Avoid expensive compares; cache keys." },
    { question: "Distributed priority queues?", answer: "Shards, clock sync, tie external ordering." },
    { question: "Backpressure with bounded PQ?", answer: "Drop lowest priority or block producers." },
    { question: "Observability?", answer: "Depth, wait time, stale tasks metrics." },
    { question: "GC impact of many boxed entries?", answer: "Primitive arrays or specialized heaps." },
  ],
  wrongAnswers: [
    "PriorityQueue is FIFO — false.",
    "peek removes element — false: poll does.",
    "Heap insert always O(1) — false: O(log n).",
    "Cannot max-heap in Java — false: reverseOrder comparator.",
    "kth largest uses max-heap size k directly — usually min-heap size k.",
    "PriorityQueue allows null — false.",
    "Build heap from n inserts always O(n) — successive inserts O(n log n); batch heapify O(n).",
    "Comparator can violate equals freely — risks contract issues.",
  ],
};
