export const basicCode = "package arch.day56;\n\npublic class Day56Basic {\n    public static void main(String[] args) {\n        System.out.println(\"=== Saga forward steps (example checkout) ===\");\n        System.out.println(\"1. Reserve inventory (local TX in inventory service)\");\n        System.out.println(\"2. Capture payment (local TX in payments service)\");\n        System.out.println(\"3. Create shipment (local TX in shipping service)\");\n        System.out.println();\n        System.out.println(\"=== Compensations (reverse order) ===\");\n        System.out.println(\"3c. Cancel shipment if created\");\n        System.out.println(\"2c. Refund payment if captured\");\n        System.out.println(\"1c. Release inventory reservation\");\n        System.out.println();\n        System.out.println(\"=== Styles ===\");\n        System.out.println(\"Orchestration: coordinator issues commands + stores state\");\n        System.out.println(\"Choreography: services publish facts; peers react\");\n    }\n}\n";

export const basicOutput = "=== Saga forward steps (example checkout) ===\n1. Reserve inventory (local TX in inventory service)\n2. Capture payment (local TX in payments service)\n3. Create shipment (local TX in shipping service)\n\n=== Compensations (reverse order) ===\n3c. Cancel shipment if created\n2c. Refund payment if captured\n1c. Release inventory reservation\n\n=== Styles ===\nOrchestration: coordinator issues commands + stores state\nChoreography: services publish facts; peers react\n";

export const intermediateCode = "package arch.day56;\n\npublic class Day56Intermediate {\n\n    public static void main(String[] args) {\n        System.out.println(\"=== Happy path trace ===\");\n        System.out.println(\"START -> RESERVE_OK -> PAY_OK -> SHIP_OK -> DONE\");\n        System.out.println();\n        System.out.println(\"=== Failure after payment (inventory short) ===\");\n        System.out.println(\"START -> RESERVE_OK -> PAY_OK -> INVENTORY_FAIL\");\n        System.out.println(\"COMPENSATE -> REFUND_OK -> RELEASE_OK -> ABORTED\");\n    }\n}\n";

export const intermediateOutput = "=== Happy path trace ===\nSTART -> RESERVE_OK -> PAY_OK -> SHIP_OK -> DONE\n\n=== Failure after payment (inventory short) ===\nSTART -> RESERVE_OK -> PAY_OK -> INVENTORY_FAIL\nCOMPENSATE -> REFUND_OK -> RELEASE_OK -> ABORTED\n";

export const advancedCode = "package arch.day56;\n\npublic class Day56Advanced {\n\n    static String compensationOrder(boolean shipped) {\n        StringBuilder b = new StringBuilder();\n        if (shipped) {\n            b.append(\"cancelShipment;\");\n        }\n        b.append(\"refundPayment;\");\n        b.append(\"releaseInventory;\");\n        return b.toString();\n    }\n\n    public static void main(String[] args) {\n        System.out.println(\"order_if_shipped=\" + compensationOrder(true));\n        System.out.println(\"order_if_not_shipped=\" + compensationOrder(false));\n    }\n}\n";

export const advancedOutput = "order_if_shipped=cancelShipment;refundPayment;releaseInventory;\norder_if_not_shipped=refundPayment;releaseInventory;\n";
