export default {
  "conceptual": [
    {
      "question": "What is the REST architectural style? What are its constraints?",
      "answer": "REST (Representational State Transfer) is an **architectural style** — not a protocol — defined by Roy Fielding in his 2000 dissertation. Six constraints: **client–server** (UI separated from data storage), **stateless** (each request is self-contained, no server-side session between requests), **cacheable** (responses explicitly label themselves as cacheable or not), **uniform interface** (URI identifies resources; clients manipulate via representations; self-descriptive messages; HATEOAS optional), **layered system** (client cannot tell if it's talking to origin server or proxy), and optional **code on demand** (server may send executable code). In practice, 'RESTful' usually means: plural-noun URIs, correct HTTP verbs, proper status codes, and a documented OpenAPI contract. Most internal APIs stop at Richardson Level 2 (HTTP verbs + status codes) and skip full HATEOAS."
    },
    {
      "question": "What does idempotent mean? Which HTTP methods are idempotent and why?",
      "answer": "**Idempotent** means: making the same request N times produces the same **server state** as making it once (the response may differ, but the effect converges). **GET, HEAD, OPTIONS** are idempotent **and** safe (no side effects). **PUT** is idempotent: it replaces the full resource at a known URI — send the same body twice, the resource ends up in the same state. **DELETE** is idempotent: after deletion the resource is gone; a second DELETE may return 404 but the effect (resource absent) is the same. **POST** is **not** idempotent by default: `POST /orders` twice creates two orders. **PATCH** is not automatically idempotent — the semantics depend on how you define merge (e.g., append-to-list vs set-field). POST and PATCH can be **designed** to be idempotent by adding `Idempotency-Key` deduplication. Idempotency matters for **retry safety**: load balancers and clients can safely retry an idempotent call on timeout."
    },
    {
      "question": "What is the Richardson Maturity Model? Where do most real-world APIs sit?",
      "answer": "The **Richardson Maturity Model** describes four levels of REST adoption: **Level 0** — one URI, one HTTP method (POX/SOAP tunnel, e.g. `POST /api` for everything). **Level 1** — multiple URIs representing resources, but still using one method. **Level 2** — correct HTTP verbs (GET/POST/PUT/DELETE) and meaningful status codes per operation — this is where most production APIs live. **Level 3** — HATEOAS: responses include hypermedia links that tell clients what actions are available next (`_links` in HAL, `actions` in Siren). Full HATEOAS is common in **public APIs** and SDKs where discoverability matters, but most **internal microservice** APIs stop at Level 2 with a well-maintained OpenAPI document instead of runtime links."
    },
    {
      "question": "When do you return 400 vs 422? When 401 vs 403?",
      "answer": "**400 Bad Request** — the request could not be parsed or has wrong types: malformed JSON, missing required header, numeric field passed a string. The problem is at the **protocol/syntax** level. **422 Unprocessable Entity** — the JSON parsed successfully but **business/domain rules** failed: stock insufficient, account suspended, duplicate email, invalid state transition. The server understood the request but cannot process it. (Some teams use 400 for both; the important thing is to pick one convention and apply it consistently.) **401 Unauthorized** — the caller is **not authenticated**: no token, expired token, invalid signature. The fix is to log in and get a valid credential. HTTP spec requires `WWW-Authenticate` header. **403 Forbidden** — the caller **is** authenticated but does **not have permission** for this resource/action. The fix is to request a higher privilege or contact an admin. Confusing 401 and 403 breaks security auditing, client retry logic, and UX error messages."
    },
    {
      "question": "What is the Idempotency-Key pattern? When and why do you use it?",
      "answer": "**Idempotency-Key** is a client-generated unique ID (usually UUID v4) sent as a request header (e.g. `Idempotency-Key: a3f8c1d2-...`). The **server** stores `(key → response fingerprint)` with a TTL (typically 24 h in Redis using `SETNX + EXPIRE`). On a **duplicate request with the same key**, the server replays the cached response **without re-executing side effects** (no second DB write, no second charge, no second event). This makes **POST** safe to retry. Use it for any operation with **non-idempotent side effects**: payments, order creation, inventory holds, email sends. Key design decisions: (1) **scope** — key is per `(userId, key)` pair, not globally unique; (2) **TTL** — 24 h balances replay window vs Redis size; (3) **conflict handling** — same key + different payload → 409 Conflict, not a replay."
    },
    {
      "question": "Offset vs keyset (cursor) pagination — what are the trade-offs?",
      "answer": "**Offset pagination** (`?page=5&size=20` → SQL `OFFSET 100 LIMIT 20`) is simple and allows random-access page jumps. Problems: (1) **Performance degrades** at high offsets — the DB must scan and discard all preceding rows; `OFFSET 50000` can be 100x slower than `OFFSET 0` on a large table. (2) **Unstable results** — if a row is inserted or deleted between page 1 and page 2 requests, items shift and you see duplicates or miss items. **Keyset (cursor) pagination** uses the last-seen sort key (`WHERE (created_at, id) < (:lastCreatedAt, :lastId) ORDER BY created_at DESC LIMIT 20`). (1) **Constant performance** regardless of how deep — the DB uses the sort index directly. (2) **Stable** — new inserts do not shift existing pages. Trade-off: keyset requires a **stable sort column with an index**, cannot jump to an arbitrary page, and you expose an opaque cursor (base-64 encoded sort key) instead of page numbers. Use keyset for **large datasets and feeds**; offset for small admin tables where page-jump UX matters."
    },
    {
      "question": "What is RFC 7807 Problem Details? Why is it better than a custom error shape?",
      "answer": "**RFC 7807 Problem Details for HTTP APIs** defines a standard JSON error body with fields: `type` (URI identifying the problem class), `title` (human-readable short description), `status` (HTTP status code), `detail` (human-readable specific explanation), `instance` (URI identifying the specific occurrence). Example: `{\"type\":\"https://api.example.com/problems/insufficient-stock\",\"title\":\"Insufficient Stock\",\"status\":422,\"detail\":\"SKU PROD-42: requested 10, available 3\",\"instance\":\"/orders/ord-789\"}`. Benefits: (1) **Machine-readable** `type` URI allows clients to switch on error class without string matching. (2) **Standard field names** across all services — one SDK handles all errors. (3) **Extendable** — you add `traceId`, `errors[]` as extension fields. (4) **Spring 6** ships `ProblemDetail` natively (`ResponseEntityExceptionHandler` emits it by default for `@Valid` failures). The alternative — a custom `{\"error\":\"...\",\"message\":\"...\"}` — forces every consumer to write bespoke error parsing."
    },
    {
      "question": "How do you version a REST API? What are the trade-offs of URL vs header versioning?",
      "answer": "Three main strategies: (1) **URL versioning** (`/v1/orders`, `/v2/orders`) — the version is visible in logs, browser history, and API gateways. Routing is trivial. The downside is that `/v1` and `/v2` are treated as different resources by HTTP caches (same ETag on `/v1/orders/1` and `/v2/orders/1` is unrelated). (2) **Accept header / content negotiation** (`Accept: application/vnd.example.orders+json;version=2`) — keeps URIs clean and stable; the resource is the same, only the representation changes. Harder to test in browsers and tools; requires disciplined gateway routing. (3) **Hostname** (`v2.api.example.com`) — clean separation, easy DNS routing, but heavyweight. **Best practice regardless of strategy**: (a) **pick one** standard org-wide, (b) prefer **additive non-breaking changes** (new optional fields) to avoid bumping versions at all, (c) set a **deprecation window** with `Sunset` response header, (d) use **consumer contract tests** (e.g. Pact) in CI so breaking changes are caught before deploy."
    },
    {
      "question": "How do conditional GET and ETags work? Why do they matter?",
      "answer": "The server includes an **`ETag`** header (a hash of the resource representation, e.g. `ETag: \"a1b2c3d4\"`) in GET responses. The client caches the response along with the ETag. On the **next GET**, the client sends `If-None-Match: \"a1b2c3d4\"`. If the resource is **unchanged**, the server returns **304 Not Modified** with no body — saving bandwidth and server CPU for serialization. If **changed**, the server returns **200 OK** with the new body and a new ETag. For **writes**, `If-Match: \"a1b2c3d4\"` enables **optimistic locking**: the server applies the update only if the current ETag matches; if someone else has modified it meanwhile, the server returns **412 Precondition Failed** instead of silently overwriting (lost update problem). In Spring: `ResponseEntity.ok().eTag(etag).body(resource)` and `@RequestHeader(\"If-None-Match\") String ifNoneMatch` in the controller."
    },
    {
      "question": "HATEOAS in REST — what is it, when is it actually useful in production?",
      "answer": "**HATEOAS (Hypermedia as the Engine of Application State)** means that API responses include links describing which **actions/transitions** are available next, rather than requiring clients to have prior knowledge of URLs. Example response for an order: `{\"orderId\":\"ord-789\",\"status\":\"PENDING\",\"_links\":{\"self\":\"/orders/ord-789\",\"cancel\":\"/orders/ord-789/cancel\",\"pay\":\"/orders/ord-789/payment\"}}`. Benefits: the server can **change URLs** without breaking clients (clients follow links, not hardcoded paths); API is **self-describing**. In practice: **public partner APIs and SDKs** (e.g. PayPal, Stripe) use HATEOAS to reduce coupling and documentation overhead. **Internal microservice** APIs usually skip it — teams maintain OpenAPI specs and know the URLs at build time; the operational complexity of runtime link generation is not worth it. The pragmatic answer in an interview: 'useful for public/exploratory APIs; most internal teams stop at Level 2 with good OpenAPI docs.'"
    },
    {
      "question": "How does rate limiting work in REST APIs? What headers should you return?",
      "answer": "Rate limiting caps how many requests a client can make in a time window to protect the server and enforce fair use. Common algorithms: **token bucket** (smooth bursts allowed), **leaky bucket** (strict rate), **sliding window log** (precise but memory-heavy), **fixed window counter** (simple, slight burst at window boundary). HTTP semantics: when a client exceeds the limit, return **429 Too Many Requests** with a `Retry-After` header indicating when to retry (absolute date or seconds). Good APIs also return proactive headers on every response: `X-RateLimit-Limit` (window cap), `X-RateLimit-Remaining` (requests left), `X-RateLimit-Reset` (epoch when counter resets). Without `Retry-After`, well-behaved clients use exponential backoff but ill-behaved ones hammer the service continuously. Rate limits should be **scoped** (per API key, per user, per IP) and **documented** in the OpenAPI spec."
    },
    {
      "question": "What is content negotiation? When does 406 Not Acceptable get returned?",
      "answer": "**Content negotiation** is the mechanism by which client and server agree on the format of the response. The client sends an `Accept` header listing its preferred media types (e.g. `Accept: application/json, application/xml;q=0.8, */*;q=0.5`). The server chooses the best match and responds with `Content-Type` indicating what it actually sent. If the server cannot produce any of the client's requested formats, it returns **406 Not Acceptable**. Similarly, for request bodies, the client declares `Content-Type: application/json` and if the server cannot process that type it returns **415 Unsupported Media Type**. Content negotiation is also used for **API versioning via Accept headers**: `Accept: application/vnd.example.api+json;version=2`. In practice, 406 is rare because most REST APIs produce only `application/json`; but in public APIs with XML/CSV support it matters."
    },
    {
      "question": "What is JSON Patch vs JSON Merge Patch? How do you choose for PATCH endpoints?",
      "answer": "Two RFC standards for partial updates: **JSON Merge Patch (RFC 7396)** — send a JSON object where present fields overwrite, and fields set to `null` are deleted. Simple and readable. Limitation: you cannot distinguish 'set field to null' from 'do not touch this field' in many scenarios; also cannot address array elements individually. Content-Type: `application/merge-patch+json`. **JSON Patch (RFC 6902)** — send an array of operations (`add`, `remove`, `replace`, `move`, `copy`, `test`), each with a JSON Pointer path. Precise, supports atomic test-then-modify, and handles arrays correctly. More verbose. Content-Type: `application/json-patch+json`. **How to choose**: use **Merge Patch** for simple document-style resources where you update top-level fields and null means delete. Use **JSON Patch** when you need atomic conditional operations, array manipulation, or when you want to guarantee no data is accidentally erased. Always document which semantics you implement — PATCH without documented semantics is a common source of bugs."
    },
    {
      "question": "How do you design bulk/batch endpoints in REST?",
      "answer": "Three common patterns: (1) **Batch request body** — `POST /orders/batch` with an array of create requests; server processes all and returns a **207 Multi-Status** response with per-item status. Good when items are independent. (2) **Async batch job** — `POST /batch-jobs` creates a job resource; client polls `GET /batch-jobs/{id}` for status. Good for large, long-running batches. Returns 202 Accepted immediately. (3) **Bulk import via file** — client uploads CSV/JSON file; server processes in background. Trade-offs of sync batch: (a) **all-or-nothing vs partial success** — define which; 207 signals partial; (b) **payload size limits** — cap batch size and document it; (c) **timeout risk** for large batches on sync endpoints. Idempotency at the item level: each item in a batch request should carry its own idempotency key or natural unique key so the server can deduplicate partial replays. Document the exact failure semantics — clients must know if a partial failure rolls everything back or commits successful items."
    },
    {
      "question": "What is the API deprecation and Sunset process?",
      "answer": "Deprecation is the process of signaling to consumers that a version or endpoint will be removed so they have time to migrate. Best practices: (1) **Sunset header** (RFC 8594) — include `Sunset: Sat, 01 Jan 2026 00:00:00 GMT` in responses for deprecated endpoints; clients and gateways can react programmatically. (2) **Deprecation header** — `Deprecation: true` or a timestamp marking when deprecation started. (3) **Documentation** — mark endpoint deprecated in OpenAPI spec with `deprecated: true`; add migration guide. (4) **Usage analytics** — monitor which API keys are still calling deprecated endpoints; reach out to consumers before the sunset date. (5) **Compatibility window** — at minimum 3–6 months for internal consumers, 6–12 months for external partners (check contracts). (6) **Consumer contract tests** — running provider contract tests for all consumers in CI catches breaking changes automatically before deploy. Skipping a proper deprecation process is a common source of production outages when a team removes an endpoint they thought was unused."
    },
    {
      "question": "When would you return **422 Unprocessable Entity** instead of **400 Bad Request**?",
      "answer": "**400** signals malformed syntax or invalid types (bad JSON, wrong content-type). **422** signals syntactically valid input that fails business or validation rules (insufficient stock, illegal state transition). Consistency matters: pick one convention per API and document it so clients and gateways interpret failures uniformly."
    },
    {
      "question": "What does it mean for a pagination **cursor** to be **opaque**, and why enforce it?",
      "answer": "Clients must treat the cursor as an encoded bookmark, not parse or construct it. That lets the server change sort keys, shard layout, or encoding without breaking clients. Document that only the server issues cursors and clients pass them back unchanged on `next` requests."
    }
  ],
  "codeBased": [
    {
      "question": "Show how to return 201 Created with a Location header in Spring",
      "answer": "// @PostMapping(\"/orders\")\n// ResponseEntity<Order> createOrder(@Valid @RequestBody CreateOrderRequest req) {\n//     Order saved = orderService.create(req);\n//     URI location = ServletUriComponentsBuilder\n//         .fromCurrentRequest()\n//         .path(\"/{id}\")\n//         .buildAndExpand(saved.getId())\n//         .toUri();\n//     return ResponseEntity.created(location).body(saved);\n// }\n// HTTP response: 201 Created\n// Location: https://api.example.com/orders/ord-789\n// Content-Type: application/json\n// Body: {\"orderId\":\"ord-789\",\"status\":\"PENDING\"}"
    },
    {
      "question": "Show how to return 204 No Content after a DELETE in Spring",
      "answer": "// @DeleteMapping(\"/orders/{id}\")\n// ResponseEntity<Void> deleteOrder(@PathVariable String id) {\n//     orderService.delete(id);   // throws 404 if not found\n//     return ResponseEntity.noContent().build();\n// }\n// HTTP response: 204 No Content\n// (no body — clients must NOT expect a body on 204)"
    },
    {
      "question": "Show RFC 7807 ProblemDetail for a validation error in Spring 6",
      "answer": "// Spring 6: ProblemDetail is a first-class type\n// @ExceptionHandler(MethodArgumentNotValidException.class)\n// ProblemDetail handleValidation(MethodArgumentNotValidException ex) {\n//     ProblemDetail pd = ProblemDetail\n//         .forStatusAndDetail(HttpStatus.UNPROCESSABLE_ENTITY,\n//             \"Validation failed: \" + ex.getBindingResult().getAllErrors());\n//     pd.setType(URI.create(\"https://api.example.com/problems/validation-error\"));\n//     pd.setProperty(\"traceId\", MDC.get(\"traceId\"));\n//     return pd;\n// }\n// HTTP 422, Content-Type: application/problem+json\n// {\"type\":\"https://api.example.com/problems/validation-error\",\n//  \"title\":\"Unprocessable Entity\",\"status\":422,\n//  \"detail\":\"items: must not be empty\",\"traceId\":\"abc123\"}"
    },
    {
      "question": "Show a keyset-paginated GET /orders response DTO",
      "answer": "// Response DTO for cursor-paginated collection\n// record OrderPage(\n//     List<OrderSummary> items,\n//     String nextCursor,   // opaque token — Base64(createdAt + id)\n//     boolean hasMore\n// ) {}\n//\n// Controller:\n// @GetMapping(\"/orders\")\n// OrderPage listOrders(\n//     @RequestParam(required = false) String cursor,\n//     @RequestParam(defaultValue = \"20\") @Max(100) int limit) {\n//     return orderService.getPage(cursor, limit);\n// }\n//\n// Response:\n// {\"items\":[...],\"nextCursor\":\"eyJpZCI6Im9yZC04OTYifQ==\",\"hasMore\":true}\n// Next page: GET /orders?cursor=eyJpZCI6Im9yZC04OTYifQ==&limit=20"
    },
    {
      "question": "Show ETag conditional GET implementation in Spring",
      "answer": "// @GetMapping(\"/orders/{id}\")\n// ResponseEntity<Order> getOrder(\n//     @PathVariable String id,\n//     @RequestHeader(value=\"If-None-Match\", required=false) String ifNoneMatch) {\n//     Order order = orderService.findById(id);  // throws 404 if absent\n//     String etag = '\"' + Integer.toHexString(order.hashCode()) + '\"';\n//     if (etag.equals(ifNoneMatch)) {\n//         return ResponseEntity.status(304).eTag(etag).build();\n//     }\n//     return ResponseEntity.ok().eTag(etag).body(order);\n// }\n// First call  : 200 OK + ETag: \"a1b2c3d4\" + body\n// Second call : If-None-Match: \"a1b2c3d4\" -> 304 Not Modified (no body)"
    },
    {
      "question": "Show an Idempotency-Key filter/interceptor sketch in Spring",
      "answer": "// @Component\n// class IdempotencyFilter implements Filter {\n//     @Autowired RedisTemplate<String,String> redis;\n//\n//     public void doFilter(ServletRequest req, ...) {\n//         String key = ((HttpServletRequest)req).getHeader(\"Idempotency-Key\");\n//         if (key != null) {\n//             String cached = redis.opsForValue().get(\"idem:\" + key);\n//             if (cached != null) {\n//                 // replay: write cached response and return early\n//                 HttpServletResponse res = (HttpServletResponse) response;\n//                 res.setStatus(Integer.parseInt(cached.split(\"|\")[0]));\n//                 res.getWriter().write(cached.split(\"|\")[1]);\n//                 return;\n//             }\n//         }\n//         chain.doFilter(req, wrappedResponse);\n//         if (key != null) {\n//             redis.opsForValue().set(\"idem:\" + key,\n//                 status + \"|\" + body, Duration.ofHours(24));\n//         }\n//     }\n// }"
    },
    {
      "question": "Show how to implement header-based API versioning in Spring",
      "answer": "// Option A: URL versioning (most common)\n// @RequestMapping(\"/v1/orders\")  ->  /v1/orders\n// @RequestMapping(\"/v2/orders\")  ->  /v2/orders\n//\n// Option B: Accept header versioning\n// @GetMapping(value=\"/orders/{id}\",\n//     produces=\"application/vnd.example.orders.v2+json\")\n// OrderV2 getOrderV2(@PathVariable String id) { ... }\n//\n// @GetMapping(value=\"/orders/{id}\",\n//     produces=\"application/vnd.example.orders.v1+json\")\n// OrderV1 getOrderV1(@PathVariable String id) { ... }\n//\n// Client sends: Accept: application/vnd.example.orders.v2+json\n// Spring routes to v2 handler automatically via content negotiation"
    },
    {
      "question": "Show a bulk operation endpoint returning 207 Multi-Status",
      "answer": "// @PostMapping(\"/orders/batch\")\n// ResponseEntity<List<BatchResult>> createBatch(\n//     @RequestBody List<CreateOrderRequest> requests) {\n//     List<BatchResult> results = requests.stream()\n//         .map(req -> {\n//             try {\n//                 Order o = orderService.create(req);\n//                 return BatchResult.success(req.clientRef(), o.getId(), 201);\n//             } catch (ValidationException e) {\n//                 return BatchResult.failure(req.clientRef(), 422, e.getMessage());\n//             }\n//         }).toList();\n//     boolean anyFailed = results.stream().anyMatch(r -> r.status() >= 400);\n//     return ResponseEntity\n//         .status(anyFailed ? 207 : 201)\n//         .body(results);\n// }\n// 207 Multi-Status: some items succeeded, some failed\n// [{\"ref\":\"c1\",\"status\":201,\"orderId\":\"ord-789\"},\n//  {\"ref\":\"c2\",\"status\":422,\"error\":\"items required\"}]"
    },
    {
      "question": "Show mapping an exception to 409 Conflict with ProblemDetail",
      "answer": "// @ExceptionHandler(DuplicateResourceException.class)\n// ProblemDetail handleConflict(DuplicateResourceException ex,\n//                              HttpServletRequest req) {\n//     ProblemDetail pd = ProblemDetail\n//         .forStatusAndDetail(HttpStatus.CONFLICT, ex.getMessage());\n//     pd.setType(URI.create(\n//         \"https://api.example.com/problems/duplicate-resource\"));\n//     pd.setInstance(URI.create(req.getRequestURI()));\n//     pd.setProperty(\"conflictingId\", ex.getConflictingId());\n//     pd.setProperty(\"traceId\", MDC.get(\"traceId\"));\n//     return pd;\n// }\n// HTTP 409 Conflict, Content-Type: application/problem+json\n// {\"type\":\"...duplicate-resource\",\"status\":409,\n//  \"detail\":\"Order with ref REF-42 already exists\",\n//  \"conflictingId\":\"ord-789\",\"traceId\":\"abc\"}"
    },
    {
      "question": "Show how to add rate-limit headers and return 429 in Spring",
      "answer": "// @ExceptionHandler(RateLimitExceededException.class)\n// ResponseEntity<ProblemDetail> handleRateLimit(\n//     RateLimitExceededException ex) {\n//     ProblemDetail pd = ProblemDetail\n//         .forStatusAndDetail(HttpStatus.TOO_MANY_REQUESTS,\n//             \"Rate limit exceeded. Retry after \" + ex.retryAfterSeconds() + \"s\");\n//     return ResponseEntity\n//         .status(429)\n//         .header(\"Retry-After\", String.valueOf(ex.retryAfterSeconds()))\n//         .header(\"X-RateLimit-Limit\", \"100\")\n//         .header(\"X-RateLimit-Remaining\", \"0\")\n//         .header(\"X-RateLimit-Reset\",\n//             String.valueOf(ex.resetEpochSeconds()))\n//         .body(pd);\n// }\n// HTTP 429, Retry-After: 47\n// X-RateLimit-Limit: 100, X-RateLimit-Remaining: 0"
    },
    {
      "question": "A client retries **POST /payments** with the same **Idempotency-Key** but a **different JSON body**. What HTTP outcome do you design?",
      "answer": "Return **409 Conflict** (often with Problem Details) because the key is bound to a specific request fingerprint. Replaying the same key must return the same response; a body mismatch indicates client misuse or a bug. Log correlation ids for support."
    },
    {
      "question": "You expose **GET /orders/{id}** with **ETag**. How should **If-Match** on **PATCH** behave when the ETag does not match?",
      "answer": "Return **412 Precondition Failed** — the resource changed since the client read it. This enables optimistic concurrency without locks. The client should refetch, merge, and retry. Spring can map this via `If-Match` handling and `ResponseEntity.status(412)`."
    }
  ],
  "seniorScenario": [
    {
      "question": "Your team deployed a change that removed a field from GET /orders/{id}. Three partner integrations broke. How do you respond, and how do you prevent this in the future?",
      "answer": "**Immediate response**: (1) Roll back the change or add the field back as a nullable deprecated field — minimise time-to-restore for partners. (2) Communicate to affected partners with a specific timeline. **Root cause**: no consumer contract tests; no deprecation window; team assumed the field was unused. **Prevention**: (1) **Consumer-driven contract tests** (Pact) — each consumer publishes a pact file stating what fields it reads; CI runs `pact-verify` on the provider repo and the build breaks if a field is removed. (2) **API linting** (Optic, Spectral) in CI — detect breaking changes (field removal, type change) between the current OpenAPI spec and the previous version before merge. (3) **Deprecation process** — mark field `deprecated: true` in OpenAPI, add `X-Deprecated-Field: fieldName` warning header, set a sunset date (minimum 3 months internal, 6 months external), monitor usage in access logs. **Cultural change**: define 'breaking change' in the team's definition of done."
    },
    {
      "question": "Your API serves 10 M requests/day. A partner reports timeouts on GET /orders. Logs show DB CPU spikes every few minutes. How do you diagnose and fix?",
      "answer": "**Diagnosis steps**: (1) Check slow query log — likely deep-offset pagination (`OFFSET 50000+`) or a missing index on the filter column. (2) Check EXPLAIN ANALYZE on the slow query — look for sequential scans. (3) Check if pagination params are unbounded — `limit=10000` causing massive result sets. (4) Check if `GET /orders` is missing a `Cache-Control` header — partners may be polling every second instead of using ETags. **Fixes by root cause**: (a) **Deep offset** → migrate to keyset pagination on `(created_at DESC, id DESC)` with a covering index — eliminates the O(N) scan. (b) **Missing index** → add composite index on filter columns (`status, customer_id`). (c) **No caching** → add `Cache-Control: max-age=30` for list endpoints; add `ETag` on individual resources; partners polling unchanged data will get 304 with no DB hit. (d) **Unbounded limit** → cap at 100 with documented max; return 400 if exceeded. (e) **Thundering herd** → if cache expires simultaneously, use cache stampede protection (probabilistic early refresh or Redis lock)."
    },
    {
      "question": "A finance team asks for POST /payments to be made safe to retry because their gateway retries on 504. How do you implement Idempotency-Key end-to-end?",
      "answer": "**Protocol contract**: Document that `Idempotency-Key` (UUID v4) is required for POST /payments. Enforce it — return 400 if missing. **Server-side store**: Redis hash `SETNX idem:{userId}:{key} 'PENDING' EX 86400`. Transition: (1) On first call — check Redis, get miss, proceed, set key to 'PROCESSING', run payment, update key to serialized `{status, paymentId, amount}`. (2) On duplicate — get hit, return cached response. Use **Redis Lua script** to make check-and-set atomic (no TOCTOU race between two simultaneous retries with the same key). **Conflict detection**: if same key is used with a different payload (amount or recipient changes), return 409 Conflict — this signals the client made a programming error. **TTL considerations**: 24 h means if the client retries after 25 h, they get a miss and could create a duplicate — document this and require clients to use a new key after TTL. **Downstream idempotency**: the payment processor call must also be idempotent (most processors accept their own idempotency-key header). **Testing**: load-test with 3 concurrent retries of the same key; assert only one DB row created."
    },
    {
      "question": "Your public API has external partners on v1 and internal services on v2. How do you manage this multi-version deployment?",
      "answer": "**Routing strategy**: API gateway routes `/v1/*` → v1 deployment, `/v2/*` → v2 deployment (or same service with versioned controllers). **CI/CD**: both versions have separate integration test suites. Pact consumer tests run for all registered consumers against both provider versions. **Non-breaking changes**: add new optional fields to v1 and v2 simultaneously — consumers ignore unknown fields if they follow Postel's law. **Breaking changes in v2**: release v2 endpoint, maintain v1 side-by-side. Set `Sunset` header on v1 responses: `Sunset: 2025-12-01T00:00:00Z`. Monitor which API keys are still hitting v1 — send email/ticket to partners 90, 60, 30 days before sunset. **Shared business logic**: extract into a service layer that both v1 and v2 controllers call — avoid duplicating domain logic. **Eventually**: after v1 sunset date, add 410 Gone to v1 endpoints instead of immediate 404 so partners get a clear message. **Anti-pattern to avoid**: never silently forward v1 requests to v2 logic if there is a contract difference — partners will see unexpected data."
    },
    {
      "question": "GraphQL is proposed as an alternative to your REST API for a mobile client that suffers over-fetching. How do you evaluate the trade-off?",
      "answer": "**REST problems that GraphQL solves**: (1) **Over-fetching** — `GET /users/{id}` returns 50 fields; mobile only needs 3. GraphQL query specifies exactly which fields are needed. (2) **Under-fetching / N+1 requests** — mobile needs user + their last 3 orders + each order's items → 4 round trips in REST vs 1 GraphQL query. (3) **Rapid frontend iteration** — frontend team can evolve queries without waiting for new REST endpoints. **GraphQL problems REST solves**: (1) **Caching** — REST GET responses are cacheable by CDN and browser (by URL); GraphQL uses POST and is not cacheable at HTTP layer without persisted queries. (2) **HTTP semantics** — status codes, idempotency, and observable monitoring are well-understood in REST. GraphQL returns 200 with `{\"errors\":[...]}` even on failure. (3) **Authorization complexity** — field-level authorization in GraphQL is harder to audit than endpoint-level in REST. (4) **N+1 on server side** — GraphQL requires DataLoader patterns to avoid N+1 DB queries for nested resolvers. **Recommendation**: introduce a **BFF (Backend for Frontend)** pattern — REST microservices internally, a thin GraphQL or REST BFF layer that aggregates data for mobile with only the fields needed. This gives mobile over-fetching relief without rebuilding the whole API."
    },
    {
      "question": "How would you design rate limiting for a public API that must be fair across 10,000 API keys with different tiers?",
      "answer": "**Algorithm choice**: **token bucket** per API key — allows controlled bursts (a key can use a small burst after a quiet period) while enforcing an average rate. Leaky bucket is stricter; sliding window log is most precise but memory-heavy at scale. **Tiered limits**: store tier config in Redis hash or a config service: `{\"free\":100,\"pro\":1000,\"enterprise\":10000}` req/min. API key → tier mapping in Redis or DB with a short TTL cache (5 min) in the gateway. **Implementation**: API gateway (Kong, Envoy, AWS API Gateway) typically handles this with a Redis-backed rate limit plugin — do not implement in the application service itself. **Headers**: return `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`, `Retry-After` on 429 — cooperative clients back off. **Distributed correctness**: with multiple gateway replicas, use Redis with atomic Lua script (`INCR` + `EXPIRE`) or Redis Cell module. A small over-counting error is acceptable (eventual consistency); blocking undercounting is not. **DDoS vs legitimate rate limiting**: separate concerns — rate limiting protects fair use; DDoS mitigation (block entire IP ranges, challenge pages) is at the WAF/CDN layer before the gateway."
    }
  ],
  "wrongAnswers": [
    "REST requires using JSON exclusively — REST is format-agnostic; XML, CSV, protobuf are all valid representations.",
    "POST is always idempotent — POST is NOT idempotent by default; without Idempotency-Key, two POST /orders create two orders.",
    "HTTP status codes are optional hints that clients can ignore — status codes are how HTTP infrastructure (proxies, caches, monitors) classifies responses; ignoring them breaks retries, alarms, and caching.",
    "API versioning should change every sprint — versioning is for breaking changes; additive changes (new optional fields) must not bump the version.",
    "HATEOAS means every response must include HTML links only — HATEOAS is about hypermedia controls in any format (HAL JSON, Siren); most REST APIs skip it entirely.",
    "204 responses must include a JSON body — 204 No Content explicitly means no body; sending one violates the spec and will confuse HTTP clients.",
    "401 and 403 mean the same thing — 401 = not authenticated (provide credentials); 403 = authenticated but not authorised (different fix path).",
    "DELETE is not idempotent because the second call returns 404 — idempotency is about the server STATE, not the response code; after deletion the state is the same regardless of how many times you call it."
  ]
};
