export default {
  conceptual: [
    { question: "happens-before?", answer: "Order edges guaranteeing visibility." },
    { question: "volatile vs synchronized?", answer: "Visibility vs mutual exclusion + hb." },
    { question: "Data race?", answer: "Conflicting unsynchronized accesses." },
    { question: "Deadlock?", answer: "Circular wait for locks." },
    { question: "Livelock?", answer: "Threads keep responding but no progress." },
    { question: "Starvation?", answer: "Thread rarely scheduled." },
    { question: "Reentrancy?", answer: "Same thread can re-acquire monitor." },
    { question: "Executor vs thread?", answer: "Pool reuse; control lifecycle." },
    { question: "interrupt policy?", answer: "Document; restore flag; cancel tasks." },
    { question: "ThreadLocal?", answer: "Per-thread variable; avoid leaks in pools." },
    { question: "ForkJoin idea?", answer: "Divide work steal idle threads." },
    { question: "Why avoid Thread.stop?", answer: "Broken invariants." },
    { question: "Safe publication?", answer: "Static init, volatile, final fields rules." },
    { question: "Lock ordering strategy?", answer: "Global id on locks; consistent acquire." },
    { question: "juc primitives?", answer: "CountDownLatch, Semaphore, CyclicBarrier." },
    { question: "Testing concurrency?", answer: "Stress + model checking + code review." },
    { question: "60-second concurrency story?", answer: "hb, races, locks, pools, deadlock ordering." },
  ],
  codeBased: [
    { question: "Fix i++ race?", answer: "synchronized, AtomicInteger, or LongAdder." },
    { question: "Two-lock deadlock?", answer: "Acquire A then B always." },
    { question: "Shutdown executor?", answer: "shutdown; awaitTermination; shutdownNow if needed." },
    { question: "Future timeout?", answer: "get(timeout, unit)." },
    { question: "volatile boolean flag?", answer: "Visibility for stop signal." },
    { question: "Cached thread pool risk?", answer: "Unbounded threads if tasks infinite." },
    { question: "Parallel stream pool?", answer: "commonPool; beware blocking." },
    { question: "ReadWriteLock?", answer: "Many readers exclusive writer." },
    { question: "try/finally unlock?", answer: "ReentrantLock pattern." },
    { question: "wait/notify?", answer: "Must hold monitor; prefer juc." },
    { question: "AtomicReference CAS?", answer: "CompareAndSet loop." },
    { question: "Thread factory?", answer: "Name threads; daemon flags; uncaught handler." },
  ],
  seniorScenario: [
    { question: "Production thread dump?", answer: "Detect deadlocks; blocked threads; pool exhaustion." },
    { question: "Latency spike thread pool?", answer: "Queue depth; rejection policy; slow tasks." },
    { question: "Virtual threads pinning?", answer: "synchronized/native blocks carrier." },
    { question: "Microservice async?", answer: "Separate bounded executor per workload." },
    { question: "CI flaky tests?", answer: "Remove sleeps; use latches; deterministic." },
    { question: "Security manager threads?", answer: "Rare now; permissions model changed." },
  ],
  wrongAnswers: [
    "volatile makes i++ atomic — false.",
    "interrupt stops thread immediately — false.",
    "synchronized guarantees no deadlock — false.",
    "More locks always safer — false ordering.",
    "Executor needs no shutdown — false resource leak.",
    "Data race is defined only for long — false.",
    "join does not establish hb — false.",
    "ThreadLocal never leaks — false pools.",
  ],
};
