export default [
  { level: "basic", category: "theory", question: "Data race definition:", options: { A: "Unsynchronized conflicting access", B: "Deadlock", C: "GC pause", D: "OOM" }, answer: "A", explanation: "JMM." },
  { level: "basic", category: "code", question: "synchronized method locks:", options: { A: "this or class", B: "No lock", C: "Random object", D: "String pool" }, answer: "A", explanation: "Monitor." },
  { level: "basic", category: "theory", question: "volatile guarantees:", options: { A: "Visibility ordering", B: "Atomic i++", C: "Deadlock free", D: "Immutable object" }, answer: "A", explanation: "Not compound atomic." },
  { level: "intermediate", category: "code", question: "Reentrant lock same thread:", options: { A: "Allowed", B: "Deadlock always", C: "Illegal", D: "NPE" }, answer: "A", explanation: "Reentrancy." },
  { level: "intermediate", category: "theory", question: "happens-before from join:", options: { A: "Thread actions before join visible after", B: "Never", C: "Only volatile", D: "Random" }, answer: "A", explanation: "JMM edge." },
  { level: "intermediate", category: "code", question: "ExecutorService benefit:", options: { A: "Reuse threads", B: "No tasks", C: "Single core only", D: "No shutdown" }, answer: "A", explanation: "Pooling." },
  { level: "advanced", category: "theory", question: "Deadlock four conditions:", options: { A: "Mutual hold wait circular", B: "One lock", C: "volatile", D: "GC" }, answer: "A", explanation: "Coffman." },
  { level: "intermediate", category: "code", question: "interrupt does not:", options: { A: "Force stop thread", B: "Set flag", C: "Wake some waits", D: "Cooperative" }, answer: "A", explanation: "Must handle." },
  { level: "basic", category: "theory", question: "Thread.start hb:", options: { A: "run sees start ordering", B: "Nothing", C: "Only join", D: "volatile only" }, answer: "A", explanation: "JMM." },
  { level: "intermediate", category: "code", question: "Future.get blocks:", options: { A: "Until done or cancel", B: "Never", C: "Only void", D: "Illegal" }, answer: "A", explanation: "API." },
  { level: "intermediate", category: "theory", question: "Intrinsic lock same as:", options: { A: "Monitor of object", B: "File lock", C: "DB row", D: "ClassLoader" }, answer: "A", explanation: "synchronized." },
  { level: "advanced", category: "code", question: "tryLock avoids:", options: { A: "Indefinite deadlock", B: "All races", C: "GC", D: "JIT" }, answer: "A", explanation: "Timeout path." },
  { level: "intermediate", category: "theory", question: "Thread-safe class means:", options: { A: "Correct under concurrent use", B: "synchronized methods only", C: "volatile fields only", D: "immutable only" }, answer: "A", explanation: "Specification." },
  { level: "basic", category: "code", question: "join throws:", options: { A: "InterruptedException", B: "IOException", C: "None", D: "Error" }, answer: "A", explanation: "Checked." },
  { level: "intermediate", category: "code", question: "shutdown executor:", options: { A: "Stop accepting new tasks", B: "Kill immediately always", C: "No op", D: "Start tasks" }, answer: "A", explanation: "Lifecycle." },
  { level: "advanced", category: "theory", question: "Double-checked locking needs:", options: { A: "volatile field or holder", B: "Nothing", C: "Two threads only", D: "String intern" }, answer: "A", explanation: "Safe publication." },
  { level: "intermediate", category: "theory", question: "Liveness vs safety:", options: { A: "Deadlock starvation vs races", B: "Same", C: "Only perf", D: "GC" }, answer: "A", explanation: "Properties." },
  { level: "intermediate", category: "code", question: "AtomicInteger uses:", options: { A: "CAS hardware", B: "synchronized always", C: "volatile only", D: "File" }, answer: "A", explanation: "Lock-free." },
  { level: "basic", category: "theory", question: "Race on i++:", options: { A: "Non-atomic read-modify-write", B: "Atomic always", C: "Only long", D: "Safe volatile" }, answer: "A", explanation: "Compound." },
  { level: "advanced", category: "code", question: "ForkJoin common pool:", options: { A: "Shared parallel streams", B: "Per thread", C: "Disabled", D: "File IO" }, answer: "A", explanation: "JDK." },
  { level: "intermediate", category: "theory", question: "Cooperative cancellation:", options: { A: "Check interrupt flag", B: "Thread.stop", C: "GC", D: "finalize" }, answer: "A", explanation: "interrupt." },
  { level: "intermediate", category: "code", question: "synchronized static locks:", options: { A: "Class object", B: "this", C: "First arg", D: "None" }, answer: "A", explanation: "Monitor." },
  { level: "basic", category: "theory", question: "Two threads unsynchronized counter:", options: { A: "May lose updates", B: "Always exact", C: "Deterministic", D: "volatile fixes" }, answer: "A", explanation: "Race." },
  { level: "advanced", category: "code", question: "ReadWriteLock use:", options: { A: "Many readers one writer", B: "Only writes", C: "No readers", D: "Single lock" }, answer: "A", explanation: "Throughput." },
  { level: "intermediate", category: "theory", question: "Visibility without mutex:", options: { A: "Sometimes volatile/atomic", B: "Always", C: "Never possible", D: "final fields rule weak" }, answer: "A", explanation: "Publication." },
  { level: "intermediate", category: "code", question: "awaitTermination:", options: { A: "After shutdown wait finish", B: "Start pool", C: "Submit", D: "Create thread" }, answer: "A", explanation: "API." },
  { level: "basic", category: "theory", question: "Deadlock fix ordering:", options: { A: "Global lock order", B: "More locks", C: "volatile only", D: "Ignore" }, answer: "A", explanation: "Design." },
  { level: "advanced", category: "code", question: "StampedLock mode:", options: { A: "Optimistic read optional", B: "Only write", C: "No read", D: "Database" }, answer: "A", explanation: "Advanced." },
  { level: "intermediate", category: "theory", question: "java.util.concurrent:", options: { A: "Higher-level primitives", B: "Removed", C: "Only List", D: "GUI" }, answer: "A", explanation: "juc." },
  { level: "intermediate", category: "code", question: "BlockingQueue backpressure:", options: { A: "Bounded queue waits", B: "Unbounded always best", C: "No wait", D: "Sorts" }, answer: "A", explanation: "Producer consumer." },
];
