export const basicCode = "package arch.day54;\n\npublic class Day54Basic {\n    public static void main(String[] args) {\n        System.out.println(\"=== Protocol traits (interview frame) ===\");\n        System.out.println(\"REST+JSON  | Cache-friendly edge, human debugging, verbose on wire\");\n        System.out.println(\"gRPC       | Binary protobuf, HTTP/2, great internal RPC\");\n        System.out.println(\"GraphQL    | Client-shaped reads, schema + resolvers, watch N+1\");\n        System.out.println();\n        System.out.println(\"=== Schema boundary rules ===\");\n        System.out.println(\"1. One owning team per protobuf package / federated type\");\n        System.out.println(\"2. Additive changes first; breaking changes need dual-publish plan\");\n        System.out.println(\"3. Public edge avoids leaking internal grpc service names\");\n        System.out.println(\"4. GraphQL limits: depth + complexity + pagination caps\");\n        System.out.println(\"5. gRPC deadlines propagated across every hop\");\n    }\n}\n";

export const basicOutput = "=== Protocol traits (interview frame) ===\nREST+JSON  | Cache-friendly edge, human debugging, verbose on wire\ngRPC       | Binary protobuf, HTTP/2, great internal RPC\nGraphQL    | Client-shaped reads, schema + resolvers, watch N+1\n\n=== Schema boundary rules ===\n1. One owning team per protobuf package / federated type\n2. Additive changes first; breaking changes need dual-publish plan\n3. Public edge avoids leaking internal grpc service names\n4. GraphQL limits: depth + complexity + pagination caps\n5. gRPC deadlines propagated across every hop\n";

export const intermediateCode = "package arch.day54;\n\npublic class Day54Intermediate {\n\n    static String pickProtocol(boolean browserClient, boolean needsStream, boolean strictContract) {\n        if (browserClient && needsStream) {\n            return \"GraphQL subscription or SSE/WS gateway — not raw gRPC to browser\";\n        }\n        if (browserClient) {\n            return \"REST/JSON or GraphQL over HTTPS at edge\";\n        }\n        if (strictContract && needsStream) {\n            return \"gRPC streaming between services\";\n        }\n        if (strictContract) {\n            return \"gRPC unary internal east-west\";\n        }\n        return \"REST acceptable when debugging and cache semantics matter\";\n    }\n\n    static String boundaryRule(String ownerA, String ownerB) {\n        if (ownerA.equals(ownerB)) {\n            return \"SHARED_CONTEXT: protobuf package evolves together\";\n        }\n        return \"BOUNDARY: expose DTO via ACL — no leaking internal entity messages\";\n    }\n\n    public static void main(String[] args) {\n        System.out.println(\"=== Day 54 scenarios ===\\n\");\n        System.out.println(\"S1 mobile app read shape flexible -> \" + pickProtocol(true, false, false));\n        System.out.println(\"S2 service-to-service ledger RPC -> \" + pickProtocol(false, false, true));\n        System.out.println(\"S3 internal live audit stream -> \" + pickProtocol(false, true, true));\n        System.out.println(\"S4 same-team aggregates -> \" + boundaryRule(\"billing\", \"billing\"));\n        System.out.println(\"S5 cross-team legacy monolith -> \" + boundaryRule(\"billing\", \"legacy\"));\n    }\n}\n";

export const intermediateOutput = "=== Day 54 scenarios ===\n\nS1 mobile app read shape flexible -> REST/JSON or GraphQL over HTTPS at edge\nS2 service-to-service ledger RPC -> gRPC unary internal east-west\nS3 internal live audit stream -> gRPC streaming between services\nS4 same-team aggregates -> SHARED_CONTEXT: protobuf package evolves together\nS5 cross-team legacy monolith -> BOUNDARY: expose DTO via ACL — no leaking internal entity messages\n";

export const advancedCode = "package arch.day54;\n\nimport java.util.*;\n\npublic class Day54Advanced {\n\n    static int fieldCost(String name) {\n        return switch (name) {\n            case \"user\" -> 1;\n            case \"orders\" -> 3;\n            case \"lines\" -> 2;\n            default -> 1;\n        };\n    }\n\n    public static void main(String[] args) {\n        List<String> selection = List.of(\"user\", \"orders\", \"lines\");\n        int depth = selection.size();\n        int sum = 0;\n        for (String f : selection) {\n            sum += fieldCost(f);\n        }\n        int score = sum * depth;\n        System.out.println(\"=== GraphQL-style cost estimate ===\");\n        System.out.println(\"selection=\" + selection);\n        System.out.println(\"depthFactor=\" + depth + \" baseSum=\" + sum + \" score=\" + score);\n        System.out.println(score > 18 ? \"REJECT: over budget\" : \"ALLOW: within budget\");\n    }\n}\n";

export const advancedOutput = "=== GraphQL-style cost estimate ===\nselection=[user, orders, lines]\ndepthFactor=3 baseSum=6 score=18\nALLOW: within budget\n";
