export const GLOSSARY_DOMAINS = [
  'All Terms',
  'AI',
  'ML',
  'Deep Learning',
  'NLP',
  'LLM',
  'GenAI',
  'RAG',
  'Vector Databases',
] as const;

export type GlossaryDomain = (typeof GLOSSARY_DOMAINS)[number];

export type GlossaryShellTerm = {
  term: string;
  domain: Exclude<GlossaryDomain, 'All Terms'>;
};

const AI_TERMS = [
  'Artificial Intelligence',
  'Algorithm',
  'Model',
  'Training',
  'Inference',
  'Parameters',
  'Weights',
  'Bias',
  'Neuron',
  'Neural Network',
  'Deep Learning',
  'Supervised Learning',
  'Unsupervised Learning',
  'Reinforcement Learning',
  'Agent (AI)',
  'Environment',
  'Reward',
  'Overfitting',
  'Underfitting',
  'Generalization',
  'Benchmark',
  'Hyperparameter',
  'Gradient Descent',
  'Backpropagation',
  'Loss Function',
  'Activation Function',
  'Epoch',
  'Batch',
  'Batch Size',
  'Learning Rate',
  'Optimizer',
  'Regularization',
  'Dropout',
  'CNN',
  'RNN',
  'Transfer Learning',
  'Evaluation Metric',
] as const;

const ML_TERMS = [
  'Feature',
  'Label',
  'Dataset',
  'Training Set',
  'Validation Set',
  'Test Set',
  'Data Preprocessing',
  'Feature Engineering',
  'Feature Scaling',
  'Normalization',
  'Standardization',
  'One-Hot Encoding',
  'Regression',
  'Classification',
  'Clustering',
  'Dimensionality Reduction',
  'Linear Regression',
  'Logistic Regression',
  'Decision Tree',
  'Random Forest',
  'SVM',
  'KNN',
  'K-Means',
  'PCA',
  'Cross-Validation',
  'Accuracy',
  'Precision',
  'Recall',
  'F1 Score',
  'AUC-ROC',
  'Confusion Matrix',
  'Bias-Variance Tradeoff',
  'Data Augmentation',
  'ML Pipeline',
  'Hyperparameter Tuning',
  'Grid Search',
] as const;

const DEEP_LEARNING_TERMS = [
  'Layer',
  'Hidden Layer',
  'Input Layer',
  'Output Layer',
  'Perceptron',
  'MLP',
  'Weight Initialization',
  'Batch Normalization',
  'Skip Connection',
  'ResNet',
  'Autoencoder',
  'Latent Space',
  'Encoder',
  'Decoder',
  'GAN',
  'Diffusion Model',
  'VAE',
  'Attention Mechanism',
  'Self-Attention',
  'Multi-Head Attention',
  'Positional Encoding',
] as const;

const NLP_TERMS = [
  'Natural Language Processing',
  'Text Preprocessing',
  'Tokenization',
  'Token',
  'Corpus',
  'Vocabulary',
  'Stop Words',
  'Stemming',
  'Lemmatization',
  'Bag of Words',
  'TF-IDF',
  'Word Embedding',
  'Word2Vec',
  'GloVe',
  'Sentence Embedding',
  'Semantic Similarity',
  'Cosine Similarity',
  'NER',
  'POS Tagging',
  'Dependency Parsing',
  'Sentiment Analysis',
  'Text Classification',
  'Machine Translation',
  'Question Answering',
  'Text Summarization',
  'Seq2Seq',
  'Language Model',
] as const;

const LLM_TERMS = [
  'Large Language Model',
  'Transformer Architecture',
  'BERT',
  'GPT',
  'T5',
  'Claude',
  'Gemini',
  'LLaMA',
  'Mistral',
  'Context Window',
  'Context Length',
  'Token Limit',
  'Tokenizer',
  'Subword Tokenization',
  'BPE',
  'Prompt',
  'Completion',
  'Response',
  'Temperature',
  'Top-K Sampling',
  'Top-P Sampling',
  'Greedy Decoding',
  'Beam Search',
  'Perplexity',
  'Hallucination',
  'Fine-tuning',
  'Instruction Tuning',
  'RLHF',
  'LoRA',
  'QLoRA',
  'Quantization',
  'Zero-Shot',
  'Few-Shot',
  'One-Shot',
  'Chain-of-Thought',
  'In-Context Learning',
  'System Prompt',
  'User Prompt',
  'Multi-Turn',
  'Constitutional AI',
  'Alignment',
  'Safety',
  'Guardrails',
] as const;

const GENAI_TERMS = [
  'Generative AI',
  'Foundation Model',
  'Pre-training',
  'Multimodal',
  'Text-to-Image',
  'Text-to-Code',
  'Text-to-Speech',
  'Image-to-Text',
  'Prompt Engineering',
  'Prompt Injection',
  'Jailbreak',
  'Grounding',
  'Factuality',
  'Responsible AI',
  'AI Safety',
  'Content Filter',
  'Latency',
  'Throughput',
  'Inference Cost',
  'API',
  'Function Calling',
  'Tool Use',
  'Agentic AI',
  'Orchestration',
  'Streaming',
  'Structured Output',
  'JSON Mode',
  'Model Card',
  'Model Hub',
] as const;

const RAG_TERMS = [
  'Retrieval Augmented Generation',
  'Retriever',
  'Generator',
  'Knowledge Base',
  'Document Store',
  'Chunking',
  'Chunk Size',
  'Overlap',
  'Indexing',
  'Query',
  'Semantic Search',
  'Keyword Search',
  'Hybrid Search',
  'Context Injection',
  'Relevance Score',
  'Reranking',
  'BM25',
  'Dense Retrieval',
  'Sparse Retrieval',
  'Embedding Model',
  'Document Embedding',
  'Query Embedding',
  'Top-K Retrieval',
  'Grounded Response',
  'RAG Pipeline',
  'Advanced RAG',
  'Modular RAG',
  'GraphRAG',
] as const;

const VECTOR_DATABASE_TERMS = [
  'Vector',
  'Vector Embedding',
  'Vector Space',
  'Dimensionality',
  'Vector Database',
  'FAISS',
  'Pinecone',
  'Weaviate',
  'ChromaDB',
  'Qdrant',
  'PGVector',
  'Milvus',
  'Index',
  'ANN',
  'HNSW',
  'IVF',
  'Similarity Search',
  'Cosine Similarity',
  'Dot Product',
  'Euclidean Distance',
  'Metadata',
  'Metadata Filtering',
  'Namespace',
  'Collection',
  'Upsert',
  'Query Vector',
  'Embedding Dimension',
  'Scalar Quantization',
  'Product Quantization',
] as const;

export const glossaryShellTerms: GlossaryShellTerm[] = [
  ...AI_TERMS.map((term) => ({ term, domain: 'AI' as const })),
  ...ML_TERMS.map((term) => ({ term, domain: 'ML' as const })),
  ...DEEP_LEARNING_TERMS.map((term) => ({ term, domain: 'Deep Learning' as const })),
  ...NLP_TERMS.map((term) => ({ term, domain: 'NLP' as const })),
  ...LLM_TERMS.map((term) => ({ term, domain: 'LLM' as const })),
  ...GENAI_TERMS.map((term) => ({ term, domain: 'GenAI' as const })),
  ...RAG_TERMS.map((term) => ({ term, domain: 'RAG' as const })),
  ...VECTOR_DATABASE_TERMS.map((term) => ({ term, domain: 'Vector Databases' as const })),
];
