export default {
  conceptual: [
    { question: "CompletableFuture vs Future?", answer: "Composable callbacks; non-blocking style." },
    { question: "thenCompose why?", answer: "Avoid nested CompletableFuture." },
    { question: "Default executor risk?", answer: "Common pool saturation; pass own." },
    { question: "exceptionally vs handle?", answer: "handle sees both success and failure." },
    { question: "allOf limitation?", answer: "Void; combine gets manually." },
    { question: "join vs get interrupt?", answer: "join wraps unchecked." },
    { question: "Virtual thread use case?", answer: "Massive blocking IO with cheap threads." },
    { question: "Pinning causes?", answer: "synchronized, native, some library locks." },
    { question: "StructuredTaskScope benefit?", answer: "Parent-child cancellation." },
    { question: "Timeouts?", answer: "orTimeout/completeOnTimeout Java 9+." },
    { question: "MDC in async?", answer: "Propagate context manually or framework." },
    { question: "Error swallowing?", answer: "Ensure exceptionally/handle covers pipeline." },
    { question: "Backpressure with CF?", answer: "Not built-in; bounded queues upstream." },
    { question: "Testing async?", answer: "Await completion; avoid sleep." },
    { question: "Reactive vs CF?", answer: "Push streams vs single future composition." },
    { question: "ThreadLocal leaks async?", answer: "Copy context per task." },
    { question: "60-second CF story?", answer: "compose, explicit executor, error routes, avoid block, vt pinning." },
  ],
  codeBased: [
    { question: "Chain two async calls?", answer: "thenCompose first.thenCompose(second)." },
    { question: "Combine two CF int sum?", answer: "a.thenCombine(b, Integer::sum)." },
    { question: "Recover fallback?", answer: "exceptionally(t -> default)." },
    { question: "Run after both?", answer: "allOf.thenRun(...)." },
    { question: "Supply from executor?", answer: "supplyAsync(sup, pool)." },
    { question: "Complete explicitly?", answer: "complete(value) or completeExceptionally." },
    { question: "Cancel task?", answer: "cancel(true) cooperative with interruption." },
    { question: "Stream of CF?", answer: "List allOf pattern." },
    { question: "Blocking get in servlet?", answer: "Avoid; use async servlet APIs." },
    { question: "Retry CF?", answer: "Manual loop or resilience4j." },
    { question: "Delay stage?", answer: "CompletableFuture.delayedExecutor Java 9+." },
    { question: "Record result in CF?", answer: "supplyAsync returns DTO." },
  ],
  seniorScenario: [
    { question: "Outage cascading timeouts?", answer: "Bulkhead thread pools; deadlines." },
    { question: "Metrics for async?", answer: "Latency percentiles per stage." },
    { question: "Common pool exhausted?", answer: "Separate executor for app async." },
    { question: "Library uses CF internally?", answer: "Document threading assumptions." },
    { question: "Graal native image?", answer: "Register reflection and substitutions if needed." },
    { question: "Kotlin coroutine interop?", answer: "Bridge executors; structured concurrency." },
  ],
  wrongAnswers: [
    "CompletableFuture always uses new thread per stage — false pools.",
    "Blocking get inside CF callback is fine — false starvation.",
    "allOf returns combined list — false void.",
    "Virtual threads remove all locking concerns — false pinning.",
    "thenApply runs on calling thread always — false async overload.",
    "Cancellation always stops computation — false cooperative.",
    "Failed futures cannot be composed — false exceptionally.",
    "Common pool unbounded threads — false FJP limits.",
  ],
};
