export default [
  { level: "basic", category: "theory", question: "CompletableFuture.get blocks:", options: { A: "Until complete", B: "Never", C: "Only void", D: "Illegal" }, answer: "A", explanation: "API." },
  { level: "basic", category: "code", question: "supplyAsync runs:", options: { A: "Async supplier", B: "Main only", C: "GC", D: "static" }, answer: "A", explanation: "Executor." },
  { level: "basic", category: "theory", question: "thenApply vs thenCompose:", options: { A: "Compose flattens nested CF", B: "Same", C: "Only name", D: "throws" }, answer: "A", explanation: "Monadic." },
  { level: "intermediate", category: "code", question: "allOf returns:", options: { A: "CompletableFuture<Void>", B: "List", C: "String", D: "int" }, answer: "A", explanation: "Aggregate." },
  { level: "intermediate", category: "theory", question: "Default async executor:", options: { A: "ForkJoin common pool", B: "newCached", C: "Single", D: "None" }, answer: "A", explanation: "Default." },
  { level: "intermediate", category: "code", question: "exceptionally maps:", options: { A: "Throwable to value", B: "void", C: "Stream", D: "Thread" }, answer: "A", explanation: "Recovery." },
  { level: "advanced", category: "theory", question: "join vs get:", options: { A: "join unchecked interrupt", B: "Same", C: "join waits forever only", D: "get no wait" }, answer: "A", explanation: "Ergonomic." },
  { level: "intermediate", category: "code", question: "handle takes:", options: { A: "BiFunction value,throwable", B: "Runnable", C: "Supplier", D: "Comparator" }, answer: "A", explanation: "Both paths." },
  { level: "basic", category: "theory", question: "completedFuture:", options: { A: "Already done", B: "Never completes", C: "Error", D: "Random" }, answer: "A", explanation: "Factory." },
  { level: "intermediate", category: "code", question: "thenCombine:", options: { A: "Waits two CFs", B: "One only", C: "void", D: "Sort" }, answer: "A", explanation: "Zip." },
  { level: "intermediate", category: "theory", question: "Blocking in CF callback:", options: { A: "Risk pool starvation", B: "Always good", C: "No effect", D: "Faster" }, answer: "A", explanation: "Care." },
  { level: "advanced", category: "code", question: "anyOf:", options: { A: "First success or failure completes", B: "All must finish", C: "Never", D: "Sort" }, answer: "A", explanation: "Race." },
  { level: "intermediate", category: "theory", question: "Virtual thread cheap:", options: { A: "Many blocking IO tasks", B: "CPU compute bound", C: "Never use", D: "Replaces GC" }, answer: "A", explanation: "Model." },
  { level: "basic", category: "code", question: "runAsync:", options: { A: "Runnable no result", B: "Supplier", C: "Callable", D: "Stream" }, answer: "A", explanation: "Void." },
  { level: "intermediate", category: "code", question: "thenAccept:", options: { A: "Consumer side effect", B: "Returns mapped", C: "throws only", D: "Supplier" }, answer: "A", explanation: "Terminal-ish." },
  { level: "advanced", category: "theory", question: "Pinning virtual thread:", options: { A: "synchronized/native blocks carrier", B: "Never happens", C: "GC", D: "JIT" }, answer: "A", explanation: "Limitation." },
  { level: "intermediate", category: "code", question: "copy with executor:", options: { A: "async methods may use custom pool", B: "Impossible", C: "Only common", D: "static" }, answer: "A", explanation: "*Async overload." },
  { level: "intermediate", category: "theory", question: "Cancellation:", options: { A: "cancel mayInterruptIfRunning", B: "Cannot cancel", C: "Always stops", D: "GC only" }, answer: "A", explanation: "Cooperative." },
  { level: "basic", category: "code", question: "obtrudeValue:", options: { A: "Force complete", B: "Illegal", C: "Join", D: "Sleep" }, answer: "A", explanation: "Rare." },
  { level: "advanced", category: "code", question: "orTimeout:", options: { A: "Fail if late", B: "Extend time", C: "No JDK support", D: "GC hint" }, answer: "A", explanation: "Java 9+." },
  { level: "intermediate", category: "theory", question: "Composition vs raw threads:", options: { A: "Callbacks structured", B: "Same chaos", C: "No difference", D: "Slower always" }, answer: "A", explanation: "DX." },
  { level: "intermediate", category: "code", question: "failedFuture:", options: { A: "Pre-completed exceptionally", B: "Success", C: "Empty", D: "Random" }, answer: "A", explanation: "Factory." },
  { level: "basic", category: "theory", question: "Executor isolation:", options: { A: "Separate pool for latency", B: "Always common", C: "Forbidden", D: "One thread" }, answer: "A", explanation: "Ops." },
  { level: "advanced", category: "code", question: "whenComplete:", options: { A: "Runs on completion success or fail", B: "Success only", C: "Fail only", D: "Never" }, answer: "A", explanation: "Side effect." },
  { level: "intermediate", category: "theory", question: "Structured concurrency idea:", options: { A: "Group tasks with scope cancel", B: "No groups", C: "Only threads", D: "SQL" }, answer: "A", explanation: "Modern." },
  { level: "intermediate", category: "code", question: "thenApplyAsync:", options: { A: "May run on executor async", B: "Same thread always", C: "Illegal", D: "void" }, answer: "A", explanation: "Overload." },
  { level: "basic", category: "theory", question: "CompletableFuture immutable?", options: { A: "Completes once", B: "Reopen", C: "Twice set", D: "Random" }, answer: "A", explanation: "State machine." },
  { level: "advanced", category: "code", question: "nativeImage CF?", options: { A: "May need configuration", B: "Always trivial", C: "Banned", D: "Only GUI" }, answer: "A", explanation: "Graal." },
  { level: "intermediate", category: "theory", question: "Async logging in callbacks:", options: { A: "Care MDC propagation", B: "Auto always", C: "No logs", D: "GC" }, answer: "A", explanation: "Observability." },
  { level: "intermediate", category: "code", question: "allOf then combine results:", options: { A: "Manual get each after join", B: "Automatic tuple", C: "Illegal", D: "List merge" }, answer: "A", explanation: "Pattern." },
];
