export default {
  conceptual: [
    { question: "Binary search precondition?", answer: "Sorted monotonic array with O(1) index access." },
    { question: "Why mid overflow matters?", answer: "lo+hi can overflow int; use lo+(hi-lo)/2." },
    { question: "Lower vs upper bound?", answer: "First >= x vs first > x—predicate binary search." },
    { question: "Stability in sorting?", answer: "Equal keys keep relative input order—important multi-key sorts." },
    { question: "Java Object[] sort?", answer: "TimSort O(n log n) stable." },
    { question: "Primitive int[] sort?", answer: "Dual-pivot quicksort family—fast average." },
    { question: "Comparison lower bound?", answer: "Ω(n log n) comparisons general." },
    { question: "When counting sort?", answer: "Small bounded integer key range." },
    { question: "Binary search on answer?", answer: "Monotonic feasibility check over value space." },
    { question: "Rotated sorted array?", answer: "Determine which half is sorted; compare targets." },
    { question: "Merge sort space?", answer: "O(n) auxiliary for merges." },
    { question: "Quickselect?", answer: "Average O(n) kth element with partition." },
    { question: "External sort?", answer: "Chunk sort + multi-way merge." },
    { question: "Linked list binary search?", answer: "No O(1) mid—use skip list or linear." },
    { question: "Duplicates in BS?", answer: "Use bound variants for first/last occurrence." },
    { question: "Heapsort properties?", answer: "In-place O(n log n) not stable." },
    { question: "60-second story?", answer: "Sort unlocks log search; stable vs speed; BS invariant; safe mid; bound searches for duplicates; rotated variants." },
  ],
  codeBased: [
    { question: "Exact binary search return?", answer: "Index or -1." },
    { question: "Insert position?", answer: "lower_bound for sorted insert." },
    { question: "sqrt int?", answer: "BS on m*m<=x." },
    { question: "Peak element?", answer: "BS on slope." },
    { question: "Split array largest sum?", answer: "BS capacity + greedy segments." },
    { question: "Aggressive cows?", answer: "BS min distance + greedy fit." },
    { question: "First bad version?", answer: "BS on isBad." },
    { question: "Search 2D matrix?", answer: "Treat as sorted list or staircase BS." },
    { question: "Koko eating bananas?", answer: "BS on eating rate." },
    { question: "Median two arrays?", answer: "Partition BS." },
    { question: "Sort colors?", answer: "Dutch flag O(n) three pointers." },
    { question: "Merge two sorted arrays end?", answer: "Fill from rear avoiding overwrite." },
  ],
  seniorScenario: [
    { question: "Sort stability in ETL?", answer: "Preserve duplicate key ties for determinism." },
    { question: "Locale aware sort prod?", answer: "Collator rules; normalization; performance." },
    { question: "Huge file sort?", answer: "External merge; distributed sort; spill to disk." },
    { question: "Index cardinality estimates?", answer: "Order statistics; histograms." },
    { question: "Comparator performance?", answer: "Hot path expensive compares dominate sort." },
    { question: "Binary search micro-benchmark?", answer: "Branch prediction effects; still O(log n) comparisons." },
  ],
  wrongAnswers: [
    "Binary search works on unsorted array — false.",
    "mid = (lo+hi)/2 always safe — overflow risk.",
    "TimSort on int[] — false: primitives use other algorithms.",
    "Heapsort stable — false.",
    "Merge sort O(1) space — false.",
    "Collections.binarySearch works unsorted — undefined behavior.",
    "BS on linked list standard O(log n) — false without extra structure.",
    "Quicksort worst O(n log n) always — false can be O(n²).",
  ],
};
