/** Topic-specific MCQ stems (30 each) for Phase 6 days 52–58. Shape: {q,A,B,C,D,ans,e} */

function S(q, A, B, C, D, ans, e) {
  return { q, A, B, C, D, ans, e };
}

export const GW = [
  S("**Service discovery** primarily solves:", "Mapping logical names to current instances", "Compiling Java", "Rendering React", "DNS root servers", "A", "Ephemeral workloads need dynamic resolution."),
  S("**Kubernetes readiness** probe should fail when:", "Critical dependencies are unavailable", "CPU > 1%", "Pod name is odd", "Logs are JSON", "A", "Remove bad pods from Service endpoints."),
  S("**Liveness** probe should stay:", "Cheap and process-focused", "Same as readiness always", "Always HTTP POST to DB", "Disabled", "A", "Avoid restart loops from slow checks."),
  S("API gateway **rate limiting** protects:", "Upstream capacity and fairness", "Only CSS", "JVM heap only", "Git history", "A", "Per key/user/IP as designed."),
  S("**TLS termination** at the gateway:", "Offloads crypto; still use TLS behind if needed", "Removes all encryption", "Only for UDP", "Illegal in cloud", "A", "Common edge pattern."),
  S("**JWT validation** at the edge:", "Authenticates caller; services still authorize", "Replaces all authz", "Means no HTTPS", "Only for SOAP", "A", "Edge authn ≠ resource authz."),
  S("**Request ID / trace** at gateway:", "Correlates logs across services", "Stores passwords", "Replaces metrics", "Fixes SQL N+1", "A", "Propagate context headers."),
  S("**WAF** placement vs gateway:", "Often in front for exploit filtering", "Inside JVM only", "After payroll", "Same as Redis", "A", "Different from business authorization."),
  S("**Path-based routing** sends:", "/orders to the orders service", "Random instances", "Only WebSocket", "ICMP packets", "A", "Declarative routes."),
  S("**Canary** release means:", "Small traffic slice to new version", "All users instantly", "Only databases", "Rollback forbidden", "A", "Measure errors/latency first."),
  S("**Blue/green** reduces:", "Downtime during deploy switch", "Need for tests", "HTTP entirely", "Need for DNS", "A", "Instant traffic flip between environments."),
  S("**Timeout** at gateway vs client:", "Gateway < client budget to return 504 predictably", "Always infinite", "Client must be shortest", "Irrelevant", "A", "Predictable failure modes."),
  S("**Retrying POST** blindly at gateway:", "Risky without idempotency end-to-end", "Always safe", "Forbidden for GET", "Fixes duplicates", "A", "POST retries can duplicate side effects."),
  S("**Mutual TLS** mesh style:", "Service identities between nodes", "Public only", "Replaces JWT always", "No certificates", "A", "Zero-trust patterns."),
  S("**Sticky sessions** trade:", "Easier server state vs harder scaling", "No trade-off", "Only HTTP/3", "Only GraphQL", "A", "Prefer stateless when possible."),
  S("**CORS** enforcement happens in:", "Browsers using response headers", "Postgres", "Kafka", "JVM GC", "A", "Server sets Allow-* headers."),
  S("**API keys** in query strings:", "Often leak via logs/referrers vs headers", "Safer than headers", "Required by OAuth", "Illegal", "A", "Prefer headers or signed tokens."),
  S("**Global IP rate limit** is:", "Coarse hygiene; layer finer limits", "Perfect fairness", "Replaces auth", "Only for gRPC", "A", "Combine with per-key tiers."),
  S("**Backend timeout** shorter than gateway:", "Lets gateway return controlled error", "Causes hangs", "Illegal", "Only for SQL", "A", "Avoid blind proxy waits."),
  S("**Health checks** hitting dependencies in readiness:", "Reflect real ability to serve", "Always wrong", "Only liveness", "Never for Redis", "A", "Don't route to broken instances."),
  S("**BFF / aggregation** at gateway risk:", "Becoming a domain monolith", "Impossible", "No latency", "Only for SOAP", "A", "Keep thin; domain stays in services."),
  S("**Envoy / data plane** updates via:", "Control plane (xDS APIs)", "FTP", "Manual JVM flags", "CSS", "A", "Dynamic listeners/routes/clusters."),
  S("**DNS-based K8s Service** gives:", "Stable name for changing Pod IPs", "Static bare-metal forever", "No cluster IP", "UDP-only routing", "A", "Kube-proxy or CNI implements."),
  S("**Circuit breaker** at edge:", "Stops hammering failing upstreams", "Replaces unit tests", "Fixes SQL", "Removes metrics", "A", "Fail fast; optional fallback."),
  S("**Max request body** limits:", "Protect memory and upstreams", "Unlimited always", "Only GET", "HTTP/2 forbids", "A", "Reject huge payloads early."),
  S("**IP allowlist** for admin APIs:", "Network guardrail before auth", "Replaces OAuth", "Public only", "Same as CORS", "A", "Defense in depth."),
  S("**Observability** per route at gateway:", "SLO dashboards for p95/errors", "Only stderr", "Only build time", "CPU temp", "A", "RED/USE style metrics."),
  S("**Zero-trust** networking:", "Verify every hop; minimal implicit trust", "Trust VPC fully", "No TLS", "No logs", "A", "Identity + policy everywhere."),
  S("**Header injection** attacks:", "Mitigate by validating/normalizing at trusted edge", "Impossible in HTTP", "Only SQL issue", "Only browser", "A", "Treat headers as untrusted input."),
  S("**WebSocket** through gateway needs:", "Upgrade handling, idle timeouts, limits", "Nothing special", "No TLS", "FTP upgrade", "A", "Operational limits still apply."),
];

export const RES = [
  S("**Circuit breaker OPEN**:", "Fails fast without calling failing dependency", "Always calls through", "Only for GET", "Waits forever", "A", "Protects thread pools."),
  S("**Half-open** state:", "Allows limited probes", "Unlimited traffic", "Only UDP", "Disables metrics", "A", "Close or reopen based on probe outcomes."),
  S("**Client timeout** should align with:", "SLA slice and downstream budgets", "Always infinite", "Random", "Only CPU", "A", "Bound tail latency."),
  S("**Bulkhead** pattern:", "Isolates thread pools per dependency", "Shares one pool always", "Only for SQL", "DNS feature", "A", "Contain blast radius."),
  S("**Retry with jitter**:", "Spreads retries to avoid thundering herd", "Always immediate", "Only GraphQL", "Illegal", "A", "Exponential backoff + jitter."),
  S("**Feign** in Spring Cloud:", "Declarative HTTP with interceptors", "JPA implementation", "Kafka client", "Webpack plugin", "A", "Plugs resilience filters."),
  S("**WebClient** vs **RestTemplate**:", "WebClient is non-blocking; RestTemplate maintenance mode", "Identical", "RestTemplate is reactive", "WebClient is JDBC", "A", "Prefer WebClient for new code."),
  S("**ExchangeFilterFunction** can:", "Add tracing headers and metrics", "Parse PDF", "Compile protos", "Replace SQL", "A", "Cross-cutting client concerns."),
  S("**Micrometer** on outbound calls:", "Timers/counters by host/route/status", "Replaces logging", "Disables TLS", "Fixes sagas", "A", "Dashboards and alerts."),
  S("**429** from downstream should:", "Respect Retry-After / backoff policy", "Retry instantly forever", "Map to 200", "Ignore", "A", "Cooperative clients."),
  S("**Connection pool** exhaustion:", "Threads wait; tune pool and concurrency", "Means fast system", "Only UI symptom", "Impossible", "A", "Watch pool pending metrics."),
  S("**Retry POST** safely when:", "Server is idempotent or Idempotency-Key used", "Always", "Never for payment", "Only with GET", "A", "Know the contract."),
  S("**Shed load** under overload:", "Return 503 quickly to protect survival", "Queue forever", "Hide errors", "Disable metrics", "A", "Prefer explicit degradation."),
  S("**Fallback** responses:", "Should be safe and documented degradation", "Hide all failures", "Always throw", "Block threads", "A", "Users understand limited mode."),
  S("**Cascading failure**:", "One slow dep stalls many requests", "Impossible in microservices", "Only monoliths", "Fixed by REST", "A", "Isolation + timeouts + bulkheads."),
  S("**Reactive backpressure**:", "Signals demand to producers", "Infinite buffer", "JDBC-only", "DNS", "A", "Avoid unbounded queues."),
  S("**Client-side load balancing** (Spring):", "Pick instance per call with health", "Static IP only", "Server-side only", "No discovery", "A", "Works with registry."),
  S("**Feign FULL logging** in prod:", "PII/volume risk — prefer BASIC/NONE", "Always required", "Replaces traces", "Fixes pool", "A", "Balance observability."),
  S("**ErrorDecoder** in Feign:", "Maps HTTP errors to typed exceptions", "Replaces TLS", "Runs migrations", "Parses YAML", "A", "Cleaner application handling."),
  S("**WebClientResponseException**:", "Represents 4xx/5xx with status/body hints", "Never thrown", "Only for SOAP", "JDBC error", "A", "Handle explicitly."),
  S("**Resilience4j Retry** maxAttempts:", "Trade success vs added latency", "Always 1", "Infinite default", "Only SQL", "A", "Tune with budgets."),
  S("**TimeLimiter**:", "Bounds async call duration", "Only JDBC", "DNS only", "Git", "A", "Fail long hangs."),
  S("**RateLimiter** client-side:", "Self-throttle to protect downstream", "Replace server limits", "Illegal", "Only GraphQL", "A", "Align with server policy."),
  S("**Distributed tracing** on client:", "Create child span per outbound call", "Replace logs", "Remove timeouts", "Fix schema", "A", "Propagate W3C/b3 headers."),
  S("**Hystrix** today:", "Maintenance; Resilience4j preferred", "Default Boot 3", "Faster than WebClient", "Required", "A", "Modern Spring Cloud stack."),
  S("**OkHttp / JDK client** tuning:", "Pool max idle and keep-alive matter", "No tuning", "Only server", "Banned", "A", "Match concurrency to workload."),
  S("**DNS caching** staleness:", "Can cause mysterious connection failures", "Never happens", "IPv6 only", "Fixes saga", "A", "Refresh strategies matter."),
  S("**HTTP/2** multiplexing:", "One connection, many streams", "One request only", "No flow control", "No TLS", "A", "Still need per-stream timeouts."),
  S("**Chaos experiments** on clients:", "Validate timeouts/breakers in lower envs", "Only production", "Replace unit tests", "Disable retries", "A", "Inject latency/faults."),
  S("**Thread starvation** symptom:", "All workers blocked on slow I/O", "Low CPU always", "Fast p99", "No timeouts", "A", "Bulkheads/timeouts help."),
];

export const RPC = [
  S("**gRPC** transport defaults:", "HTTP/2 + Protobuf", "HTTP/0.9", "FTP", "SMTP", "A", "Efficient binary framing."),
  S("**Protobuf field numbers** must:", "Stay stable; never repurpose", "Change each release", "Be sequential only", "Match SQL ids", "A", "Wire compatibility."),
  S("**gRPC streaming** kinds:", "Unary, client, server, bidi", "Only unary", "Only UDP", "Only FTP", "A", "Long-lived RPC patterns."),
  S("**GraphQL resolver** N+1:", "Mitigate with DataLoader batching", "Impossible", "Only compile-time", "Only REST", "A", "Per-field resolver cost."),
  S("**GraphQL schema** defines:", "Types, queries, mutations", "TCP ports", "JVM flags", "Kafka topics", "A", "Contract for clients."),
  S("**Proto3 optional / presence**:", "Needs careful modeling vs proto2", "Same as JSON null", "Forbidden", "Only strings", "A", "Language bindings differ."),
  S("**oneof** in protobuf:", "Exactly one branch set", "All fields required", "HTTP verb", "SQL join", "A", "Discriminated union."),
  S("**gRPC deadline**:", "Propagates timeout across callees", "JWT only", "SQL timeout", "CSS", "A", "End-to-end latency budget."),
  S("**gRPC reflection** in prod:", "Often restricted — info disclosure", "Always public", "Required", "JDBC", "A", "Lock down dev tooling."),
  S("**GraphQL introspection** public:", "Often disabled or limited", "Always on", "Law-mandated", "Same as gRPC reflection", "A", "Schema can leak capabilities."),
  S("**GraphQL pagination** best practice:", "Cursors + limits", "Unbounded lists", "OFFSET only", "No pagination", "A", "Protect server."),
  S("**gRPC status codes**:", "Rich canonical codes (UNAVAILABLE, etc.)", "HTTP only", "SQLSTATE", "Shell exit", "A", "Better than numeric HTTP alone."),
  S("**GraphQL mutations** and retries:", "Design idempotency keys where needed", "Always GET", "Never validated", "Only batch", "A", "Networks retry."),
  S("**Proto JSON mapping**:", "May surprise vs hand-written JSON APIs", "Identical always", "No enums", "No lists", "A", "Interop test."),
  S("**gRPC-Web** often needs:", "Envoy or bridge for browsers", "Nothing", "FTP", "SOAP", "A", "Browser constraints."),
  S("**GraphQL complexity** limits:", "Cap query cost", "Unlimited", "REST-only feature", "CPU-only", "A", "Prevent DoS queries."),
  S("**HTTP/2 flow control** on streams:", "Backpressure applies", "Unbounded", "UDP only", "Off", "A", "Streams aren't infinite queues."),
  S("**Proto package** names:", "Reduce type collisions", "HTTP latency", "JWT size", "GC pauses", "A", "Namespace messages."),
  S("**GraphQL subscriptions** transport:", "Often WebSocket/SSE", "Unary only", "JDBC", "FTP", "A", "Timeouts still needed."),
  S("**gRPC interceptors**:", "Metadata, auth, logging", "SQL parsing", "CSS", "Heap dump", "A", "Client and server."),
  S("**DataLoader** batches:", "Loads for many resolver keys", "SQL migrations", "JWT refresh", "DNS", "A", "Kill N+1 hotspots."),
  S("**Wire breaking change**:", "Reusing field number with new type", "Adding optional field", "New message type", "New enum value with unknown", "A", "Never repurpose numbers."),
  S("**gRPC metadata**:", "Headers + trailing metadata", "SQL plans", "Heap", "CSS", "A", "Tracing, auth, etc."),
  S("**@deprecated** GraphQL field:", "Signals migration path", "Deletes immediately", "HTTP 301", "JVM flag", "A", "Communicate to clients."),
  S("**Max message size** gRPC:", "Protect memory", "Unlimited always", "UDP-only rule", "Illegal", "A", "Tune client/server."),
  S("**GraphQL partial errors**:", "data + errors array possible", "Forbidden", "Only 500", "SOAP-only", "A", "Understand nullable schema."),
  S("**Internal gRPC + edge REST**:", "Common efficiency pattern", "Illegal", "GraphQL-only world", "SOAP-only", "A", "BFF may translate."),
  S("**Proto enum unknown** handling:", "Forward-compatible clients ignore unknown", "Crash", "Illegal", "HTTP 400", "A", "Versioning discipline."),
  S("**GraphQL federation** composes:", "Subgraphs into supergraph", "JVM bytecode", "Kafka topics", "SQL views", "A", "Ownership per domain."),
  S("**gRPC health protocol**:", "Standard RPC for readiness", "K8s exec only", "JDBC", "N/A", "A", "Integrate with probes."),
];

export const MSG = [
  S("**At-least-once** delivery:", "Duplicates possible — idempotent consumers", "Exactly one always", "No retries", "Only HTTP", "A", "Dedup keys help."),
  S("**At-most-once** may:", "Drop under failure", "Never drop", "Duplicate always", "Only SQL", "A", "When loss acceptable."),
  S("**Exactly-once** E2E:", "Hard; approximate with idempotency", "Free in Kafka", "TCP guarantees it", "QoS0 only", "A", "Business semantics matter."),
  S("**Kafka partition key**:", "Controls ordering per partition", "Random only", "HTTP path", "JWT", "A", "Hot keys limit throughput."),
  S("**Consumer group**:", "Scales consumption; rebalances members", "SQL join", "TLS only", "DNS cache", "A", "Parallel readers."),
  S("**Dead-letter queue**:", "Quarantine poison messages after retries", "Success queue", "TLS store", "SQL plan", "A", "Inspect and replay."),
  S("**Transactional outbox**:", "Same DB txn as business row + outbox event", "UDP pattern", "No DB", "REST-only", "A", "Reliable publish."),
  S("**Ordering across partitions**:", "Not global — only per partition", "Global always", "Guaranteed cross-topic", "Random", "A", "Key design."),
  S("**Poison message** without DLQ:", "Infinite retry loop risk", "Harmless", "Faster", "Fixes lag", "A", "Cap retries."),
  S("**Schema registry**:", "Versioned Avro/Proto/JSON schemas", "JWT registry", "CSS", "Maven only", "A", "CI compatibility checks."),
  S("**Kafka retention**:", "Time/size bounded (often)", "Infinite always", "Memory-only", "No compaction option", "A", "Tiered storage optional."),
  S("**Compaction topic**:", "Keeps latest per key", "All history forever", "No keys", "Headers only", "A", "Changelog pattern."),
  S("**Consumer lag**:", "How far behind processing is", "CPU metric", "TLS version", "SQL slow query", "A", "Alert on SLO."),
  S("**Idempotent consumer**:", "Same message twice does not double-apply", "Never needed", "Only GET", "Illegal", "A", "Natural keys / dedup store."),
  S("**Transactional producer** (Kafka):", "Atomic multi-partition write — costs latency", "HTTP transaction", "H2 push", "GC", "A", "Use sparingly."),
  S("**SQS visibility timeout** too low:", "Duplicate processing risk", "No effect", "Stops duplicates", "Fixes order", "A", "Tune to handler duration."),
  S("**FIFO SQS** gives:", "Ordering per message group", "Unlimited throughput", "No duplicates ever", "UDP order", "A", "Throughput trade-offs."),
  S("**Pub/sub fan-out**:", "Many subscribers to same topic", "One consumer only", "SQL view", "REST-only", "A", "Decouple producers."),
  S("**Large payloads** in brokers:", "Prefer blob store + reference", "Unlimited", "HTTP-only limit", "No limits", "A", "Avoid huge messages."),
  S("**Ordering vs parallelism**:", "Single partition orders but limits scale", "Same", "Free scale", "Unrelated", "A", "Engineering trade-off."),
  S("**Event replay** rebuilds:", "Projections from log", "TCP stack", "JWT", "CSS", "A", "Event-sourcing style."),
  S("**Backpressure** publishing:", "Slow consumers increase lag — monitor", "Impossible", "REST-only", "SQL-only", "A", "Scale consumers / partitions."),
  S("**CloudEvents**:", "Standard event metadata envelope", "SQL format", "gRPC-only", "PNG", "A", "Interoperability."),
  S("**Kafka Streams exactly-once**:", "Processing guarantee within model; sinks still need care", "Universal E2E", "No state", "Batch-only", "A", "Idempotent sinks."),
  S("**JMS vs Kafka** semantics:", "Not equivalent — migration redesign", "Identical", "Kafka is JMS", "No sessions", "A", "Read docs carefully."),
  S("**Priority queues** risk:", "Starvation of low priority", "No risk", "Fair always", "Kafka-only", "A", "Monitor depth."),
  S("**Scheduled redelivery**:", "Broker delays retry visibility", "Immediate only", "Illegal", "HTTP-only", "A", "Backoff at broker."),
  S("**Encryption at rest** messaging:", "KMS / broker policies", "Always plaintext", "TLS enough always", "Optional never", "A", "Compliance."),
  S("**Multi-region replication lag**:", "Consumers see eventual consistency", "Always zero", "SQL-only", "Impossible", "A", "Design conflicts/UX."),
  S("**Browser CORS** vs brokers:", "Brokers not subject to browser CORS", "Same as REST", "Fixes Kafka", "Always relevant", "A", "Different security model."),
];

export const SAGA = [
  S("**Saga** coordinates long workflows with:", "Local transactions + compensations", "2PC only", "Single DB lock", "Cookies", "A", "Avoid global locks."),
  S("**Compensation** is:", "Business-specific undo", "Always DELETE row", "Automatic always", "SQL ROLLBACK only", "A", "May issue refunds/status reversals."),
  S("**Choreography** saga:", "Peers react to events without central coordinator", "Always orchestrator", "No messages", "REST-only", "A", "Loose coupling."),
  S("**Orchestration** saga:", "Coordinator drives state machine", "Same as choreography", "No persistence", "SQL trigger only", "A", "Central status visibility."),
  S("**2PC** weakness:", "Blocking + coordinator failure modes", "Always best", "No coordinator", "Infinite throughput", "A", "Poor for wide-area."),
  S("**Saga timeout** triggers:", "Compensation or escalation path", "Never used", "UI-only", "Illegal", "A", "Bound stuck flows."),
  S("**Idempotent saga steps**:", "Safe when commands/events redelivered", "Unnecessary", "Impossible", "GET-only", "A", "Networks retry."),
  S("**Saga state store** (orchestrator):", "Tracks current step for resume", "JWT only", "CSS", "DNS", "A", "Durable orchestration."),
  S("**Forward recovery**:", "Retry failed step", "Same as compensation", "Only compensation", "Only SQL", "A", "Choose per rules."),
  S("**Parallel saga branches**:", "Need join + aggregated failure handling", "Always serial", "Forbidden", "SQL-only", "A", "Complex failure modes."),
  S("**Human approval** in saga:", "Waits with timers/escalations", "Impossible", "Automated only", "No state", "A", "Workflow engines help."),
  S("**Duplicate saga start**:", "Prevent with business idempotency key", "Ignore", "Always fine", "UUID-only", "A", "Avoid double orders."),
  S("**Saga vs TCC**:", "Different explicitness; both tackle distributed consistency", "Identical", "Unrelated", "Saga is SQL-only", "A", "Pattern choice."),
  S("**Poison saga message**:", "DLQ + stuck instance handling", "Ignored", "Self-heals", "Metrics-only", "A", "Runbooks."),
  S("**Compensation order** often:", "Reverse forward dependencies", "Random", "Same as forward", "Alphabetical", "A", "Depends on domain."),
  S("**Distributed lock** for saga:", "Sometimes used — mind availability", "Always required", "Never used", "Redis-only", "A", "Prefer idempotent design."),
  S("**Event sourcing + saga**:", "Audit trail of workflow steps", "Incompatible", "No events", "Batch-only", "A", "Traceability."),
  S("**Compensation failure**:", "Escalate manually / alert", "Impossible", "Auto success", "Ignore", "A", "Runbooks critical."),
  S("**Saga monitoring**:", "Per-instance completion/stuck metrics", "Unneeded", "CPU-only", "Logs-only", "A", "Business SLO."),
  S("**Semantic lock / Try** (TCC):", "Reserve resources in try phase", "HTTP lock", "DB only", "JWT", "A", "TCC pattern."),
  S("**Choreography observability**:", "Correlation id across events", "Easy always", "Impossible", "Orchestrator-only", "A", "Tracing required."),
  S("**Orchestrator HA**:", "Stateful — needs HA + persistence", "Stateless always", "No backup", "Irrelevant", "A", "Design recovery."),
  S("**Saga + outbox**:", "Reliable event emission with state changes", "Unrelated", "Replace saga", "REST-only", "A", "Transactional messaging."),
  S("**Partial fan-out failure**:", "Define per-branch compensation", "Always all-or-nothing", "Ignore", "SQL-only", "A", "Document invariants."),
  S("**Long-running saga** storage:", "Durable for hours/days if needed", "Memory-only", "No storage", "Redis-only", "A", "Business dependent."),
  S("**Saga step versioning**:", "Add compatible steps during upgrades", "Never change", "Delete old", "URL-only", "A", "Rolling deploys."),
  S("**Testing sagas**:", "Scenario tests + failure injection", "Unit only", "No tests", "Manual only", "A", "Validate compensations."),
  S("**Business invariants** mid-saga:", "Define acceptable partial states", "Not needed", "Always strong", "ACID-only", "A", "UX for interim."),
  S("**Saga vs nightly batch**:", "Event-driven interactive flow", "Same", "Saga is cron", "SQL-only", "A", "Different triggers."),
  S("**Terminal saga states**:", "Completed or compensated", "Always running", "Only failed", "Infinite loop", "A", "Retention policies."),
];

export const CQRS = [
  S("**CQRS** separates:", "Command model from query model", "Read-only JDBC", "Write-only cache", "JWT", "A", "Optimize each side."),
  S("**Event sourcing** truth:", "Append-only event stream", "Latest row only", "PNG", "SQL view", "A", "Fold to state."),
  S("**Projection rebuild**:", "Replay events to new read model", "DELETE *", "FTP", "Compile proto", "A", "Version handlers."),
  S("**Eventual consistency** UX:", "Read-your-writes strategies if needed", "Always strong", "Invisible", "SQL-only", "A", "Routing/sticky read."),
  S("**Commands** should be:", "Validated; idempotent when possible", "Always GET", "Never validated", "Batch-only", "A", "Explicit intent."),
  S("**Read model denormalization**:", "Pre-join for fast queries", "Forbidden", "3NF always", "OLTP-only", "A", "Space for speed."),
  S("**Projection lag** SLO:", "Measure consumer behind log head", "Ignore", "Always zero", "Unmeasurable", "A", "Alert breaches."),
  S("**Snapshots** (ES):", "Accelerate aggregate replay", "Required always", "Illegal", "HTTP cache", "A", "Periodic checkpoints."),
  S("**CQRS without events**:", "Still split models; sync via other means", "Impossible", "Must use Kafka", "Monolith-only", "A", "Pragmatic path."),
  S("**Two DB CQRS**:", "Need reliable sync (outbox/stream)", "Always one DB", "Illegal", "Same connection", "A", "Avoid dual writes."),
  S("**Read side scaling**:", "Replicas of projections / caches", "Vertical only", "No scale", "Kafka-only", "A", "Elastic reads."),
  S("**Hot write aggregate**:", "Shard/partition or redesign boundaries", "Never happens", "Reads-only issue", "SQL fixes", "A", "Concurrency design."),
  S("**Event schema evolution**:", "Upcasters / versioned events", "Never change", "Delete old", "REST-only", "A", "Backward compatible readers."),
  S("**Temporal / point-in-time** with ES:", "Replay to reconstruct past state", "Impossible", "Logs-only", "SQL-only", "A", "Audit/debug."),
  S("**CQRS complexity**:", "More components than CRUD", "Free", "Zero", "Tests-only", "A", "Use when benefits clear."),
  S("**Materialized view refresh**:", "Stream processing triggers", "Cron only", "Manual only", "HTTP push", "A", "Near real-time."),
  S("**Idempotent projection**:", "Same event twice does not double-apply", "Unneeded", "Impossible", "SQL PK enough", "A", "At-least-once."),
  S("**Team ownership** read/write:", "May split Conway responsibilities", "Always one team", "Forbidden", "DevOps-only", "A", "Align boundaries."),
  S("**Read-after-write strong**:", "Route to primary or wait", "Always default", "Impossible in CQRS", "Cache-only", "A", "Latency trade-off."),
  S("**Event store vs broker**:", "Store is truth; broker transports", "Same", "Interchangeable", "SQS-only", "A", "Different roles."),
  S("**CQRS security**:", "Queries may expose different authz", "Same always", "No authz", "JWT-only", "A", "Read shape leakage."),
  S("**Delete from event log**:", "Usually forbidden for compliance truth", "Always compact freely", "Required", "Kafka-only", "A", "Legal/audit constraints."),
  S("**Projection failure recovery**:", "Replay from checkpoint after fix", "Lose all", "Ignore", "Stop world", "A", "Deterministic handlers."),
  S("**Reporting** often reads:", "Projections / warehouses", "Write DB always", "Excel only", "FTP", "A", "BI off read models."),
  S("**Domain events** naming:", "Past tense facts", "Imperative verbs", "HTTP paths", "SQL", "A", "Clear semantics."),
  S("**CQRS + DDD**:", "Commands target aggregates; queries hit read models", "Unrelated", "Forbidden", "CRUD-only", "A", "Common pairing."),
  S("**Ordering per aggregate**:", "Single stream sequence", "Global total order", "Random", "SQL-only", "A", "Parallel aggregates OK."),
  S("**Cold replay duration**:", "Snapshots reduce downtime", "Instant always", "Impossible", "Unneeded", "A", "Plan maintenance."),
  S("**Read model staleness UX:**", "Show freshness or refresh affordance", "Hide", "Always fresh", "Illegal", "A", "Transparency."),
  S("**Anti-pattern** one giant projection:", "Join-everything view", "Best practice", "Required", "Microservice", "A", "Split read models."),
];

export const ACL = [
  S("**Strangler fig** migrates by:", "Incremental traffic shift behind facade", "Big bang only", "Never route", "DNS only", "A", "Measure parity."),
  S("**ACL** translates:", "Foreign/legacy models into your domain", "JWT only", "SQL plans", "CSS", "A", "Keep core clean."),
  S("**Feature flags** in migration:", "Rollout control + kill switch", "Replace tests", "Remove logs", "UI-only", "A", "Pair with metrics."),
  S("**Parallel run** (shadow):", "Compare legacy vs new outputs", "CPU temp", "JWT size", "DNS", "A", "Validate correctness."),
  S("**ACL tests**:", "Table-driven legacy sample mapping", "Skip", "Manual only", "SQL explain", "A", "CI guardrails."),
  S("**Monolith first modularize**:", "Prove boundaries before splitting", "Extract random service", "Rewrite all", "Delete DB", "A", "Reduce risk."),
  S("**Database per service** goal:", "No shared mutable tables", "Shared DB always", "One table all", "FTP", "A", "Coupling reduction."),
  S("**Synchronous shared DB** choke:", "Connection pools couple services", "Never happens", "NoSQL-only", "gRPC-only", "A", "Strangle data access."),
  S("**ACL at boundary**:", "Single integration edge", "Every entity", "DB trigger", "CDN only", "A", "Avoid scatter."),
  S("**Tenant-based canary**:", "Slice risk per customer segment", "Illegal", "Random", "JWT-only", "A", "Blast radius."),
  S("**Observability strangler**:", "Compare error/latency old vs new", "Skip", "Same logs", "No metrics", "A", "SLO gating."),
  S("**Rollback** with flags:", "Flip traffic back; keep schema compatible", "Delete DB", "No rollback", "Rewrite", "A", "Operational safety."),
  S("**BFF during migration**:", "Route to old/new backends", "Unused", "GraphQL-only", "Illegal", "A", "Presentation aggregation."),
  S("**Temporary data duplication**:", "Plan convergence to single source", "Forbidden", "Permanent always", "SQL-only", "A", "Migration realism."),
  S("**Contract tests** on ACL:", "Translation invariants in CI", "Optional", "Replace unit tests", "Manual", "A", "Prevent regressions."),
  S("**Kill switch** new stack:", "Disable quickly on SLO burn", "Unneeded", "Illegal", "Deploy-only", "A", "Ops confidence."),
  S("**Team ownership** per slice:", "Matches strangler boundaries", "One team all", "Random", "Managers-only", "A", "Conway."),
  S("**Hexagonal ports** + ACL:", "Adapters at edge", "No ports", "REST-only", "SQL-only", "A", "Test doubles."),
  S("**Strangler adds hop**:", "Watch timeouts and latency", "No impact", "Always faster", "CPU-only", "A", "Tune caches."),
  S("**Facade responsibilities**:", "Routing/translation — not domain rules", "All logic", "TLS-only", "SQL-only", "A", "Stay thin."),
  S("**Decommission legacy** when:", "Zero traffic + no hidden dependencies", "Immediately", "Never", "Keep forever", "A", "Dependency graph."),
  S("**Runbooks** for flags/routes:", "On-call clarity", "Skip", "Code-only", "Wiki-only", "A", "Operational docs."),
  S("**Security review** migration:", "New surfaces and auth paths", "Skip", "Same as before", "WAF-only", "A", "Threat model delta."),
  S("**Dual-run cost**:", "Temporary infra + engineering tax", "Free", "Zero", "Cloud bill-only", "A", "Time-box."),
  S("**Federation** during strangler:", "Unify subgraphs gradually", "Illegal", "REST-only", "SOAP-only", "A", "Incremental schema."),
  S("**CDC** for data strangler:", "Sync legacy to new projections", "Impossible", "CSV-only", "FTP", "A", "Consistency."),
  S("**Stakeholder narrative**:", "Incremental wins vs big bang", "Irrelevant", "Tools-only", "Hiring-only", "A", "Communication."),
  S("**Post-migration cleanup**:", "Remove flags/dead code/ACL if absorbed", "Never", "Keep all", "Delete prod", "A", "Reduce debt."),
  S("**ACL vs domain service**:", "ACL translates; domain implements rules", "Same", "ACL runs business logic", "No difference", "A", "Separation of concerns."),
  S("**Metrics comparison** strangler:", "Error budget per path", "Ignore", "Single metric", "Logs-only", "A", "Data-driven cutover."),
];
