export const basicCode = "package arch.day58;\n\npublic class Day58Basic {\n    public static void main(String[] args) {\n        System.out.println(\"=== Strangler Fig ===\");\n        System.out.println(\"Gradually route traffic from legacy to new implementation behind a facade\");\n        System.out.println(\"Measure parity: errors, latency, business KPIs per slice\");\n        System.out.println();\n        System.out.println(\"=== Anti-Corruption Layer ===\");\n        System.out.println(\"Translate legacy DTOs / XML / odd enums into your domain model\");\n        System.out.println(\"Keep foreign concepts from leaking past the boundary\");\n        System.out.println();\n        System.out.println(\"=== Common routing mechanisms ===\");\n        System.out.println(\"API gateway weights, feature flags, reverse proxy path rules\");\n    }\n}\n";

export const basicOutput = "=== Strangler Fig ===\nGradually route traffic from legacy to new implementation behind a facade\nMeasure parity: errors, latency, business KPIs per slice\n\n=== Anti-Corruption Layer ===\nTranslate legacy DTOs / XML / odd enums into your domain model\nKeep foreign concepts from leaking past the boundary\n\n=== Common routing mechanisms ===\nAPI gateway weights, feature flags, reverse proxy path rules\n";

export const intermediateCode = "package arch.day58;\n\npublic class Day58Intermediate {\n\n    static String route(int bucketPercent, int cutoff) {\n        if (bucketPercent < cutoff) {\n            return \"LEGACY\";\n        }\n        return \"NEW_STACK\";\n    }\n\n    public static void main(String[] args) {\n        System.out.println(\"=== Traffic split demo ===\");\n        System.out.println(\"bucket=5 -> \" + route(5, 10));\n        System.out.println(\"bucket=50 -> \" + route(50, 10));\n        System.out.println(\"bucket=9 -> \" + route(9, 10));\n    }\n}\n";

export const intermediateOutput = "=== Traffic split demo ===\nbucket=5 -> LEGACY\nbucket=50 -> NEW_STACK\nbucket=9 -> LEGACY\n";

export const advancedCode = "package arch.day58;\n\nimport java.util.*;\n\npublic class Day58Advanced {\n\n    static String toDomain(String legacyCode) {\n        return switch (legacyCode) {\n            case \"A1\" -> \"OrderPending\";\n            case \"Z9\" -> \"OrderCancelled\";\n            case \"X7\" -> \"OrderShipped\";\n            default -> \"OrderUnknown\";\n        };\n    }\n\n    public static void main(String[] args) {\n        List<String> codes = List.of(\"A1\", \"X7\", \"ZZ\");\n        System.out.println(\"=== ACL translation ===\");\n        for (String c : codes) {\n            System.out.println(c + \" -> \" + toDomain(c));\n        }\n    }\n}\n";

export const advancedOutput = "=== ACL translation ===\nA1 -> OrderPending\nX7 -> OrderShipped\nZZ -> OrderUnknown\n";
