export default {
  conceptual: [
    { question: "Lazy streams?", answer: "Intermediate ops build pipeline; terminal executes." },
    { question: "Stateful intermediate?", answer: "distinct/sorted may buffer; memory cost." },
    { question: "groupingBy?", answer: "Collector partitioning to map of lists." },
    { question: "Downstream collector?", answer: "Nested collector inside groupingBy." },
    { question: "averagingDouble?", answer: "Computes mean per group." },
    { question: "Why avoid parallelStream default?", answer: "ForkJoin overhead; thread safety." },
    { question: "Short-circuit ops?", answer: "findFirst anyMatch limit stop early." },
    { question: "Spliterator?", answer: "Splitable iterator backing streams." },
    { question: "Immutable collectors?", answer: "toList unmodifiable vs collectingAndThen." },
    { question: "flatMap vs map?", answer: "flatMap flattens one level of streams." },
    { question: "reduce requirements?", answer: "Associative for parallel correctness." },
    { question: "peek misuse?", answer: "Side effects in peek hurt clarity." },
    { question: "Stream reuse?", answer: "Create new stream from source." },
    { question: "Primitive streams?", answer: "IntStream avoids boxing." },
    { question: "Collectors.joining?", answer: "Delimiter prefix suffix string build." },
    { question: "Comparator.comparing chain?", answer: "thenComparing tie-break." },
    { question: "60-second streams story?", answer: "Lazy, terminal, collectors, groupingBy, parallel caution." },
  ],
  codeBased: [
    { question: "Avg salary by department?", answer: "groupingBy(dept, averagingDouble(salary))." },
    { question: "Top N by field?", answer: "sorted comparator limit collect." },
    { question: "Partition adults?", answer: "partitioningBy(age>=18)." },
    { question: "Map names length?", answer: "map(String::length)." },
    { question: "Count distinct?", answer: "map distinct count." },
    { question: "Sum salaries double?", answer: "mapToDouble sum." },
    { question: "Group then count?", answer: "groupingBy(fn, counting())." },
    { question: "String join?", answer: "Collectors.joining(\",\")." },
    { question: "First matching?", answer: "filter findFirst Optional." },
    { question: "toMap duplicate key?", answer: "merge function or throwing supplier." },
    { question: "Generate sequence?", answer: "Stream.iterate seed op limit." },
    { question: "Read lines file?", answer: "Files.lines path stream." },
  ],
  seniorScenario: [
    { question: "OOM large toList?", answer: "Stream chunk or DB pagination." },
    { question: "Logging in stream?", answer: "peek debug only; structured logging outside." },
    { question: "Custom collector?", answer: "Collector.of supplier accumulator combiner finisher." },
    { question: "Reactive vs streams?", answer: "Push async vs pull; choose per workload." },
    { question: "JDK upgrade stream change?", answer: "Read release notes toList immutability." },
    { question: "Profiling parallel?", answer: "JFR shows fork join; often not worth it." },
  ],
  wrongAnswers: [
    "Intermediate ops run immediately — false terminal triggers.",
    "Stream can be iterated twice by default — false consumed.",
    "parallelStream always faster — false.",
    "peek should implement business rules — false.",
    "groupingBy returns List always — false type param.",
    "distinct needs Comparable — false uses equals/hash.",
    "findFirst on parallel always deterministic — false unordered case.",
    "collect can be intermediate — false terminal.",
  ],
};
