export default {
  conceptual: [
    { question: "Why no O(1) index access in linked lists?", answer: "Nodes are scattered; you must traverse from head through next references—i steps for index i." },
    { question: "What is a dummy head?", answer: "A sentinel node before the real head so inserts/deletes at front use the same logic as middle cases." },
    { question: "Explain Floyd cycle detection.", answer: "Slow moves 1, fast moves 2; if cycle exists they meet inside; if fast hits null, no cycle—O(n) time, O(1) space." },
    { question: "How find cycle start?", answer: "After meet, reset one pointer to head, advance both one step until they meet at start." },
    { question: "Iterative reverse steps?", answer: "Keep prev, curr, next; point curr.next to prev; advance prev and curr." },
    { question: "Recursive reverse complexity?", answer: "O(n) time, O(n) stack space—risk StackOverflow on deep lists." },
    { question: "Merge two sorted lists approach?", answer: "Dummy tail, repeatedly attach smaller head, advance that list—O(n+m)." },
    { question: "Delete node given only that node (singly)?", answer: "Copy next value into node, delete next node; fails if node is tail." },
    { question: "Intersection of lists meaning?", answer: "Same node object by reference on two chains—align lengths then walk together." },
    { question: "Middle element with slow/fast?", answer: "Advance fast two steps, slow one; when fast ends, slow at middle—clarify even-length policy." },
    { question: "Doubly linked advantages?", answer: "O(1) delete with node reference, backward traversal—more memory." },
    { question: "When prefer ArrayList?", answer: "Random access, cache-friendly scans, fewer pointer overheads." },
    { question: "LRU structure?", answer: "HashMap for key→node plus doubly linked list for recency order." },
    { question: "Common reverse bug?", answer: "Losing access to rest of list—must store next before rewiring." },
    { question: "Why test 0,1,2 nodes?", answer: "Null head, single node reverse, two-node swap expose most pointer errors." },
    { question: "Time to append without tail pointer?", answer: "O(n) to walk to end each time." },
    { question: "60-second linked list story?", answer: "Clarify singly/doubly; dummy for merges; Floyd for cycles; three-pointer reverse; state complexities; mention stack risk for recursion." },
  ],
  codeBased: [
    { question: "Reverse list iterative time?", answer: "O(n) single pass." },
    { question: "Cycle detection HashSet time/space?", answer: "O(n) time, O(n) space." },
    { question: "Remove nth from end one pass?", answer: "Two pointers with gap n." },
    { question: "Add numbers as lists?", answer: "Walk with carry O(max(n,m))." },
    { question: "Palindrome list O(1) space?", answer: "Split, reverse half, compare, restore optional." },
    { question: "Merge k lists with heap?", answer: "O(N log k) where N total nodes." },
    { question: "Rotate list by k right?", answer: "Length, k mod len, connect tail to head, find new tail." },
    { question: "Odd-even reorder?", answer: "Two chains for odd/even indices then connect." },
    { question: "Copy list with random pointer?", answer: "Map original to clone in two passes." },
    { question: "Split list to parts?", answer: "Greedy chunks of k nodes." },
    { question: "Check sublist?", answer: "Match pattern with failure restart or KMP on values." },
    { question: "Swap nodes in pairs?", answer: "Rewire prev, pair heads carefully with dummy." },
  ],
  seniorScenario: [
    { question: "Huge list reverse in service—risk?", answer: "Recursion depth; choose iterative; consider chunked processing if external store." },
    { question: "Memory pressure with many small nodes?", answer: "Pointer overhead + GC; consider array-backed ring buffer for hot paths." },
    { question: "Concurrent linked structure updates?", answer: "Locks or lock-free CAS tricky; often use concurrent deque from java.util.concurrent." },
    { question: "Detect cycle in streaming graph?", answer: "May map to list cycle or use tortoise/hare on iterator if model allows." },
    { question: "Immutable lists in functional style?", answer: "Persistent data structures share tails; different complexity tradeoffs." },
    { question: "Testing pointer algorithms?", answer: "Property-based small n vs brute force array model; stress deep lists for stack safety." },
  ],
  wrongAnswers: [
    "Linked lists always beat arrays — false: poor locality and no random access often lose.",
    "Floyd algorithm uses O(n) memory — false: O(1) extra besides pointers.",
    "You can binary search a linked list in O(log n) — false: no random access to mid in O(1).",
    "Dummy head changes asymptotic class — false: constant overhead only.",
    "Recursive reverse is always best — false: stack depth risk.",
    "Intersection means equal values — false: must be same node reference usually.",
    "Deleting tail with copy-next trick works — false: no next to copy if tail.",
    "Merge sorted lists needs extra O(n) array — false: can relink in place O(1) space.",
  ],
};
