export default {
  conceptual: [
    { question: "instanceof pattern?", answer: "if (o instanceof String s) use s directly." },
    { question: "Switch expression?", answer: "Switch yields value; assign or return." },
    { question: "Arrow vs colon?", answer: "Arrow avoids fall-through." },
    { question: "Exhaustive switch?", answer: "All cases covered or default as required." },
    { question: "Guarded pattern?", answer: "case String s when s.isEmpty()." },
    { question: "Dominance error?", answer: "Broader pattern hides specific; compiler error." },
    { question: "Null handling?", answer: "Guard outside or explicit null case when supported." },
    { question: "Sealed + switch?", answer: "Compiler proves exhaustiveness." },
    { question: "Record pattern?", answer: "Deconstruct in case label when enabled." },
    { question: "yield keyword?", answer: "Return from block in switch expression." },
    { question: "Generic patterns?", answer: "Cannot distinguish List<String> vs List<Integer>." },
    { question: "When polymorphism better?", answer: "Open extension; avoid giant switches." },
    { question: "Enum switch?", answer: "Compile-time check missing cases." },
    { question: "String switch?", answer: "hashCode-based dispatch." },
    { question: "Pattern scope?", answer: "Binding only where case applies." },
    { question: "Traditional fall-through?", answer: "Rare; prefer arrows or break explicitly." },
    { question: "60-second pattern story?", answer: "Less cast, switch expr, guards, sealed exhaust." },
  ],
  codeBased: [
    { question: "Router on Object?", answer: "switch (o) { case Integer i -> ... default -> ... }." },
    { question: "Replace instanceof chain?", answer: "Single switch with patterns." },
    { question: "Return int from switch?", answer: "int x = switch(...) { ... };." },
    { question: "Block case?", answer: "case X: { ... yield v; }." },
    { question: "Combine String cases?", answer: "case \"a\", \"b\" -> same." },
    { question: "Switch on long?", answer: "Supported in modern Java." },
    { question: "Pattern for enum?", answer: "case RED -> same as before." },
    { question: "Nested patterns?", answer: "When language version supports nesting." },
    { question: "instanceof in ternary?", answer: "Pattern binding only in instanceof boolean." },
    { question: "Switch and exceptions?", answer: "Cases may throw; type compatibility." },
    { question: "Coverage testing?", answer: "Each pattern branch tested." },
    { question: "Refactor sealed add case?", answer: "Compiler errors until switch updated." },
  ],
  seniorScenario: [
    { question: "Business rules in switch?", answer: "Extract to methods; keep switch thin." },
    { question: "API stability?", answer: "Sealed public API is commitment." },
    { question: "Bytecode size?", answer: "Large switches ok; profile if needed." },
    { question: "Kotlin when vs Java switch?", answer: "Interop boundaries consistent." },
    { question: "Code review?", answer: "Dominance, null, default necessity." },
    { question: "Migration from old instanceof?", answer: "Mechanical in many places." },
  ],
  wrongAnswers: [
    "Pattern binding works in false instanceof branch — false.",
    "Arrow cases fall through — false.",
    "Switch expression may yield no value — false must complete.",
    "Can pattern match List<String> separately — false erasure.",
    "default must be first — false convention last.",
    "yield starts thread — false.",
    "Switch on void — false.",
    "Pattern vars mutable — false effectively final.",
  ],
};
