/** Interview Drill — Days 41–65 (15 / 10 / 6 / 6) */

export const B_41_65 = {
  41: {
    conceptual: [
      ['What is Spring MVC?', 'Web framework mapping HTTP requests to @Controller/@RestController methods with views or bodies.'],
      ['What is DispatcherServlet?', 'Front controller routing to handlers, resolvers, exception handlers.'],
      ['What is @RequestMapping variants?', '@GetMapping @PostMapping shorthand for HTTP methods and paths.'],
      ['What is @RequestBody @ResponseBody?', 'JSON serialization with HttpMessageConverters—REST APIs.'],
      ['What is content negotiation?', 'Choosing representation via Accept header, extensions, or param—JSON/XML.'],
      ['What is HandlerMethodArgumentResolver?', 'Resolves @RequestParam, @PathVariable, @RequestHeader into method args.'],
      ['What is exception handling @ControllerAdvice?', 'Global @ExceptionHandler for consistent error responses.'],
      ['What is validation @Valid?', 'Bean Validation triggered on request bodies—400 on failure.'],
      ['What is servlet filter vs interceptor?', 'Filters servlet spec all requests; Spring MVC interceptors finer after dispatch.'],
      ['What is REST idempotency for GET/PUT/DELETE?', 'GET safe; PUT/DELETE idempotent—POST not guaranteed.'],
      ['What is status code choice?', '201 Created with Location, 204 No Content, 400 vs 422 semantics team choice.'],
      ['What is HATEOAS?', 'Hypermedia links in responses—maturity level 3 Richardson.'],
      ['What is multipart file upload?', 'MultipartResolver handles file parts—size limits security.'],
      ['What is async MVC Callable/DeferredResult?', 'Release servlet thread during long work—scalability.'],
      ['What is CORS in Spring?', 'CrossOrigin annotation or global WebMvcConfigurer—preflight OPTIONS.'],
    ],
    codeBased: [
      ['@RestController @GetMapping("/users/{id}")', 'PathVariable Long id'],
      ['@PostMapping @Valid @RequestBody UserDto', 'Validation errors to MethodArgumentNotValidException.'],
      ['ResponseEntity with status and headers.', 'ResponseEntity.created(location).body(u)'],
      ['@RequestParam required=false defaultValue', 'Query parameters.'],
      ['@ExceptionHandler on controller method.', 'Return ProblemDetail or ErrorResponse.'],
      ['LocaleResolver i18n messages.', 'Accept-Language header.'],
      ['RedirectView or redirect:', 'PRG pattern after POST.'],
      ['Consumes MediaType.APPLICATION_JSON', 'Restrict content types.'],
      ['Matrix variables optional advanced.', 'Rare—know existence.'],
      ['MockMvc test slice @WebMvcTest.', 'Test controller without full context.'],
    ],
    seniorScenario: [
      ['Giant controller class—refactor?', 'Split by domain, use @ControllerAdvice, service layer fat not controller.'],
      ['OpenAPI contract vs implementation drift?', 'Codegen or contract tests; CI validation.'],
      ['SSE streaming endpoint memory?', 'Backpressure, disconnect handling, heartbeats.'],
      ['Global exception hides root cause?', 'Log with correlation id; sanitize client message.'],
      ['API versioning URI vs header?', 'Trade-offs caching vs cleanliness—document policy.'],
      ['CSRF disabled for REST—safe?', 'Only stateless token APIs with proper auth—not for cookie session forms.'],
    ],
    wrongAnswers: [
      '@Controller always serializes return values to JSON without annotations.',
      'DispatcherServlet is not part of Spring MVC.',
      'PUT requests must never create resources.',
      '@RequestBody works for GET requests by default.',
      'Spring MVC replaces the Servlet API entirely.',
      'ResponseEntity can only return 200 OK.',
    ],
  },

  42: {
    conceptual: [
      ['What is Spring Boot auto-configuration?', 'Classpath conditions register beans automatically—convention over configuration.'],
      ['What is spring.factories / AutoConfiguration.imports?', 'Mechanism to load auto-config classes—Boot 3 uses imports file.'],
      ['What is @SpringBootApplication?', 'Combines @Configuration @EnableAutoConfiguration @ComponentScan.'],
      ['What is embedded servlet container?', 'Tomcat/Jetty/Undertow embedded—fat JAR runnable.'],
      ['What is SpringApplication.run?', 'Bootstrap context, environment, logging, banner.'],
      ['What is Actuator endpoints?', 'Health, metrics, info, env—production observability.'],
      ['What is management.server.port separate?', 'Expose actuator on different port for security.'],
      ['What is graceful shutdown?', 'Complete in-flight requests before exit—server.* lifecycle.'],
      ['What is Spring Boot DevTools?', 'Restart on classpath change—exclude from prod.'],
      ['What is spring-boot-starter-parent?', 'Dependency management BOM versions.'],
      ['What is conditional annotations?', '@ConditionalOnClass, OnMissingBean—auto-config decisions.'],
      ['What is lazy initialization spring.main.lazy-initialization?', 'Beans lazy until first use—startup vs first request latency.'],
      ['What is Spring Boot testing @SpringBootTest?', 'Full application context—heavy vs slices.'],
      ['What is build plugins spring-boot-maven-plugin?', 'Repackage fat jar, layered jars for Docker.'],
      ['What is native image support?', 'GraalVM AOT—smaller footprint faster startup constraints.'],
    ],
    codeBased: [
      ['application.properties server.port', 'Change port.'],
      ['management.endpoint.health.show-details=when_authorized', 'Secure health details.'],
      ['@ConfigurationProperties prefix binding', 'Type-safe config.'],
      ['spring.profiles.active=dev', 'Activate profile.'],
      ['logging.level.org.springframework=DEBUG', 'Verbose logs—dev only.'],
      ['@SpringBootTest(webEnvironment=RANDOM_PORT)', 'Integration test with real port.'],
      ['TestRestTemplate bean in tests.', 'HTTP calls to random port.'],
      ['spring.main.banner-mode=off', 'CI logs cleanliness.'],
      ['ErrorController /whitelabel error customization.', 'Replace default error page.'],
      ['Layered jar docker extract layers', 'Optimize docker cache—spring-boot build-image.'],
    ],
    seniorScenario: [
      ['Actuator endpoints exposed publicly—incident?', 'Lock down, auth, network policies, disable sensitive env dump.'],
      ['Fat JAR vs thin JAR vs native trade-offs?', 'Startup, memory, build time—choose per deployment.'],
      ['Auto-config bean conflict after upgrade?', 'Release notes, exclude, define own bean @Primary.'],
      ['Kubernetes liveness uses actuator health—pitfall?', 'Don’t mark down dependencies you want to restart for—separate readiness.'],
      ['Secrets in application.yml committed?', 'Use externalized config vault, env vars, sealed secrets.'],
      ['Slow Spring Boot startup 5 min—where look?', 'Bean creation logs, classpath scanning breadth, database on startup.'],
    ],
    wrongAnswers: [
      'Spring Boot eliminates the need for a servlet container at runtime.',
      'Auto-configuration cannot be disabled or overridden.',
      'Actuator should always expose all endpoints on the main port without auth.',
      '@SpringBootApplication scans every package on the classpath automatically.',
      'spring-boot-starter includes only compile-time dependencies.',
      'DevTools should be enabled in production for faster restarts.',
    ],
  },

  43: {
    conceptual: [
      ['What is externalized configuration priority?', 'Command line, env vars, application-{profile}, defaults—later can override earlier depending on mechanism.'],
      ['What is @ConfigurationProperties vs @Value?', 'Bulk typed binding vs individual strings—validation support.'],
      ['What is relaxed binding?', 'kebab-case, camelCase, env var mapping—SPRING_DATASOURCE_URL style.'],
      ['What is Actuator /env /configprops?', 'Inspect resolved properties—debug mismatches.'],
      ['What is refresh scope (Cloud)?', 'Refresh beans on /refresh—@RefreshScope beans recreated.'],
      ['What is config server (Spring Cloud)?', 'Centralized git-backed config for distributed systems.'],
      ['What is encryption of properties?', 'Cipher values with key management—bootstrap carefully.'],
      ['What is Kubernetes ConfigMap vs Secret?', 'Mount as env or volume—Spring Cloud Kubernetes integration.'],
      ['What is spring.config.import?', 'Import additional property files or config tree—Boot 2.4+.'],
      ['What is random.* placeholder?', 'Random values for secrets in dev—don’t use for real secrets uncontrolled.'],
      ['What is logging.file.name?', 'File output rotation with logback/spring defaults.'],
      ['What is management.metrics export?', 'Micrometer to Prometheus, etc.—enable registry.'],
      ['What is info.* build properties?', 'Expose version via /info from build plugin metadata.'],
      ['What is spring.docker.compose?', 'Boot 3.1+ optional compose integration for dev—testcontainers overlap.'],
      ['What is feature flags integration?', 'Toggle beans via properties—LaunchDarkly etc.'],
    ],
    codeBased: [
      ['@ConfigurationProperties("app") record or class', 'Validated constraints.'],
      ['application.yml multi-document ---', 'Separate profiles in one file.'],
      ['@Value("${missing:default}")', 'Default values.'],
      ['Environment acceptsProfiles("dev")', 'Conditional code paths.'],
      ['TestPropertySource override properties', 'Slice tests.'],
      ['logging.pattern.console JSON', 'Structured logging.'],
      ['management.endpoints.web.exposure.include=health,info', 'Limit exposure.'],
      ['spring.cloud.config.uri for config client', 'Legacy cloud config.'],
      ['PropertySource order debugging', 'EnvironmentEndpoint or debug logging.'],
      ['@TestPropertySource properties inline', 'Quick test overrides.'],
    ],
    seniorScenario: [
      ['Wrong database URL in prod—how slipped?', 'Missing env in deployment manifest; add validation on startup fail-fast.'],
      ['Secret in git history—response?', 'Rotate credentials, purge history, secret scanning CI.'],
      ['Config drift across regions?', 'GitOps single source; diff environments with tooling.'],
      ['Actuator env exposure GDPR?', 'PII in properties—restrict endpoints, audit access.'],
      ['Hot reload config without restart—limits?', 'Only @RefreshScope beans; many components not refreshable.'],
      ['Micrometer cardinality explosion—symptom?', 'High memory in Prometheus—label discipline.'],
    ],
    wrongAnswers: [
      'application.properties always overrides environment variables.',
      '@Value cannot use default values.',
      'Actuator /env should be public for easier debugging in production.',
      'ConfigurationProperties works on any private field without setters.',
      'spring.config.location only accepts classpath: resources.',
      'Random values in application.yml are cryptographically secure secrets.',
    ],
  },

  44: {
    conceptual: [
      ['What is JPA?', 'Java Persistence API—ORM mapping entities to relational tables.'],
      ['What is Hibernate?', 'Popular JPA implementation—Session/EntityManager wraps JDBC.'],
      ['What is EntityManager?', 'Persistence context managing entity lifecycle—persist, merge, remove, find.'],
      ['What is @Entity @Table @Id?', 'Map class to table; primary key definition.'],
      ['What is lazy vs eager fetching?', 'Lazy loads associations on access—N+1 risk; eager loads immediately—overfetch risk.'],
      ['What is N+1 query problem?', 'One query for parent list + N queries for each child—fix with join fetch or batch size.'],
      ['What is JPQL vs Criteria API?', 'String queries vs programmatic query building—type-safe criteria.'],
      ['What is first-level cache?', 'Persistence context per transaction—identity map.'],
      ['What is second-level cache?', 'SessionFactory-level cache across transactions—EhCache, Infinispan—explicit config.'],
      ['What is @Transactional propagation isolation?', 'REQUIRED default; isolation READ_COMMITTED typical.'],
      ['What is optimistic locking @Version?', 'Detect concurrent updates with version column—OptimisticLockException.'],
      ['What is cascade types?', 'PERSIST, MERGE, REMOVE—dangerous if misused—orphanRemoval.'],
      ['What is fetch join in JPQL?', 'JOIN FETCH to load association in same query—avoid N+1.'],
      ['What is @Embeddable?', 'Value types composed into entity—shared table columns.'],
      ['What is inheritance mapping strategies?', 'SINGLE_TABLE, JOINED, TABLE_PER_CLASS—trade-offs normalization vs simplicity.'],
    ],
    codeBased: [
      ['Simple @Entity with generated Id.', '@GeneratedValue(strategy=IDENTITY)'],
      ['Repository extends JpaRepository', 'CRUD out of box.'],
      ['@Query("select u from User u join fetch u.roles")', 'Fetch join.'],
      ['Specification or Querydsl dynamic query', 'Type-safe predicates.'],
      ['@Modifying @Query update—clearAutomatically', 'Bulk updates bypass context—careful.'],
      ['EntityGraph attributePaths', 'Declarative fetch plan.'],
      ['DTO projection interface/class', 'Select subset fields—performance.'],
      ['@Transactional readOnly on query service', 'Optimization hint.'],
      ['Pageable Page<User> findBy', 'Pagination.'],
      ['Map native query to DTO SqlResultSetMapping or interface projection', 'Complex reports.'],
    ],
    seniorScenario: [
      ['Production Hibernate OOM loading graph?', 'Eager accidental; fetch plans; pagination; projections.'],
      ['Long transaction holding DB connection?', 'Split transaction; async outbox; reduce scope.'],
      ['Schema migration Flyway vs Liquibase choice?', 'SQL-first vs XML—team preference; both fine.'],
      ['Lost updates without versioning?', 'Add @Version; retry on conflict UX.'],
      ['Leaking EntityManager across threads?', 'Not thread-safe—one per request typically in Spring.'],
      ['Database round trips microservice chatty ORM?', 'Batch operations, jdbcTemplate for hot paths, caching.'],
    ],
    wrongAnswers: [
      'JPA entities are always detached from the persistence context.',
      'Lazy loading works the same after the EntityManager is closed.',
      'Hibernate and JPA are the same thing.',
      '@Transactional on private methods works in Spring.',
      'N+1 problem means you have N+1 databases.',
      'Second-level cache is enabled by default for all entities.',
    ],
  },

  45: {
    conceptual: [
      ['What is @Transactional boundary?', 'Starts commit/rollback around method—proxy-based in Spring.'],
      ['What is propagation REQUIRED?', 'Join existing transaction or create new—default.'],
      ['What is REQUIRES_NEW?', 'Suspend outer and create new—inner commits independently.'],
      ['What is readOnly=true?', 'Hint for optimization; no guarantee across all drivers.'],
      ['What is isolation level?', 'READ_UNCOMMITTED to SERIALIZABLE—phantom vs dirty reads trade-offs.'],
      ['What is rollbackFor checked exception?', 'Default rollback unchecked only—configure for IOException etc.'],
      ['What is local vs global (JTA) transaction?', 'Single resource vs distributed XA—avoid XA if possible—Saga/outbox.'],
      ['What is pessimistic lock?', 'SELECT FOR UPDATE—serializes access—deadlock risk.'],
      ['What is optimistic lock @Version?', 'Compare-and-set on commit—retry on conflict.'],
      ['What is transaction timeout?', 'Prevent long locks—configure per transaction manager.'],
      ['What is savepoint nested transaction?', 'JDBC savepoints—not full nested transactions in all engines.'],
      ['What is @Transactional self-invocation issue?', 'Internal call bypasses proxy—same as AOP—split bean.'],
      ['What is connection pool HikariCP?', 'Fast pool—size = connections not threads—tune max pool vs DB max connections.'],
      ['What is leak detection threshold?', 'Hikari warns when connection held too long—debug leaks.'],
      ['What is transaction synchronization afterCommit?', 'Register callback run after successful commit—outbox pattern.'],
    ],
    codeBased: [
      ['@Transactional(rollbackFor = Exception.class)', 'Force rollback checked.'],
      ['REQUIRES_NEW on audit log service', 'Separate transaction commits even if outer rolls back—careful design.'],
      ['EntityManager lock(LockModeType.PESSIMISTIC_WRITE)', 'Pessimistic lock example.'],
      ['@Transactional(propagation=SUPPORTS)', 'Join if exists else non-transactional.'],
      ['Programmatic TransactionTemplate', 'execute without annotation.'],
      ['Isolation.READ_COMMITTED enum', 'Spring transaction config.'],
      ['ChainedTransactionManager legacy', 'Multiple datasources—complex; prefer single or orchestration.'],
      ['@Transactional on test @Rollback default', 'Tests roll back—override if commit needed.'],
      ['DataSource routing AbstractRoutingDataSource', 'Multi-tenant datasource key.'],
      ['Connection pool metrics HikariPoolMXBean', 'Monitor active/idle.'],
    ],
    seniorScenario: [
      ['Intermittent deadlock in DB—analysis?', 'Lock ordering, index scans, transaction size, retry with backoff idempotent.'],
      ['XA transaction performance poor—alternative?', 'Saga choreography, outbox pattern, eventual consistency.'],
      ['Connection pool exhausted under load?', 'Tune pool, reduce transaction duration, check leaks, scale DB connections.'],
      ['Read replica lag wrong reads?', 'Sticky session or sync read-your-writes strategy; not pure transaction issue only.'],
      ['@Transactional on microservice REST call?', 'Doesn’t span network—distributed transaction myth.'],
      ['Long running batch @Transactional whole batch?', 'Bad—chunk commits, restartability.'],
    ],
    wrongAnswers: [
      '@Transactional always rolls back on any Exception including checked by default.',
      'REQUIRES_NEW joins the current transaction always.',
      'Connection pool size should equal number of HTTP threads always.',
      'Optimistic locking requires SELECT FOR UPDATE.',
      'Nested transactions are fully supported in all databases the same way.',
      'readOnly=true guarantees the database will reject writes.',
    ],
  },

  46: {
    conceptual: [
      ['What is authentication vs authorization?', 'Who you are vs what you may do—Spring Security separates concerns.'],
      ['What is SecurityFilterChain?', 'Ordered filters processing request—replaces XML security config.'],
      ['What is UserDetailsService?', 'Load user by username for authentication.'],
      ['What is PasswordEncoder?', 'BCrypt etc.—never store plaintext passwords.'],
      ['What is form login vs httpBasic vs OAuth2?', 'Different authentication mechanisms—choose per app type.'],
      ['What is CSRF protection?', 'Synchronizer token for session cookie based web—often disabled for stateless JWT APIs with care.'],
      ['What is method security @PreAuthorize?', 'SpEL expressions on methods—enable method security.'],
      ['What is SecurityContextHolder?', 'Thread-local current authentication—clear in async carefully.'],
      ['What is remember-me?', 'Persistent token cookie—security trade-offs.'],
      ['What is session fixation mitigation?', 'Change session id on login—Spring default behaviors.'],
      ['What is cors integration security?', 'Allow origins deliberately—wildcard with credentials dangerous.'],
      ['What is rate limiting?', 'Not core Spring Security—add Bucket4j, gateway, or WAF.'],
      ['What is principal in SecurityContext?', 'Typically UserDetails or OAuth2 principal object.'],
      ['What is anonymous authentication?', 'Special anonymous user when not logged in—authorize accordingly.'],
      ['What is logout handler?', 'Invalidate session, clear cookies, CSRF token rotation.'],
    ],
    codeBased: [
      ['SecurityFilterChain bean authorizeHttpRequests', 'requestMatchers("/public").permitAll()'],
      ['httpBasic() or formLogin deprecated style vs lambda DSL', 'Modern SecurityFilterChain config.'],
      ['PasswordEncoder bean BCryptPasswordEncoder', 'Encode passwords.'],
      ['@PreAuthorize("hasRole(\'ADMIN\')")', 'Method security.'],
      ['Authentication.getPrincipal()', 'Access user after login.'],
      ['Request getRemoteUser servlet', 'Container auth integration.'],
      ['Test with @WithMockUser', 'Security test slice.'],
      ['csrf().disable() when stateless JWT', 'Document threat model.'],
      ['authorizeHttpRequests requestMatchers(HttpMethod.GET)', 'Method-specific.'],
      ['exceptionHandling authenticationEntryPoint', '401 custom body.'],
    ],
    seniorScenario: [
      ['JWT in localStorage XSS—risk?', 'Prefer httpOnly cookies or strict CSP; sanitize XSS.'],
      ['Broken access control IDOR—fix?', 'Authorize resource ownership server-side every time.'],
      ['Session replication cluster security?', 'Sticky sessions or shared session store; secure cookie flags.'],
      ['Default Spring Boot security open endpoints?', 'Actuator, error pages—verify lockdown.'],
      ['Pen test finding weak bcrypt rounds?', 'Increase strength; migrate hashes on login.'],
      ['Async @Async SecurityContext lost?', 'DelegatingSecurityContextAsyncTaskExecutor propagate context.'],
    ],
    wrongAnswers: [
      'Spring Security replaces the need for HTTPS.',
      'CSRF protection is irrelevant for all REST APIs.',
      'PasswordEncoder stores passwords in reversible encryption.',
      '@PreAuthorize works without enabling method security.',
      'SecurityContextHolder is automatically propagated to all child threads without configuration.',
      'Anonymous users have a null Authentication object always.',
    ],
  },

  47: {
    conceptual: [
      ['What is OAuth2 roles?', 'Resource owner, client, authorization server, resource server—clear separation.'],
      ['What is authorization code flow?', 'Browser redirects to auth server, exchanges code for tokens—most secure for SPAs with PKCE.'],
      ['What is JWT structure?', 'Header.payload.signature—verify signature with JWK—check exp, aud, iss.'],
      ['What is refresh token rotation?', 'Issue new refresh on use—detect reuse theft.'],
      ['What is scope in OAuth2?', 'Delegated permissions—fine-grained access control.'],
      ['What is opaque token vs JWT?', 'Reference token introspected at server vs self-contained JWT—trade-offs.'],
      ['What is Spring Authorization Server?', 'Framework to build authorization server—separate from Spring Security resource server.'],
      ['What is resource server configuration?', 'Validate JWT on APIs—issuer-uri, jwk-set-uri in Boot.'],
      ['What is PKCE?', 'Proof key for code exchange—protects public clients.'],
      ['What is client credentials flow?', 'Machine-to-machine—no user—client id secret.'],
      ['What is consent screen?', 'User approves scopes—UX and compliance.'],
      ['What is SSO vs OAuth2?', 'SSO outcome; OAuth2/OIDC protocols—related but distinct vocabulary.'],
      ['What is OIDC id_token?', 'Identity assertion distinct from access_token for APIs.'],
      ['What is audience claim aud?', 'Token intended recipient resource—validate to prevent misuse.'],
      ['What is confidential vs public client?', 'Can store secret vs cannot—PKCE required for public.'],
    ],
    codeBased: [
      ['spring.security.oauth2.resourceserver.jwt.issuer-uri', 'Boot resource server JWT.'],
      ['@AuthenticationPrincipal Jwt jwt', 'Access claims in controller.'],
      ['oauth2Login() in SecurityFilterChain', 'Social login integration.'],
      ['GrantedAuthority from scope claim', 'Convert SCOPE_ roles.'],
      ['Test with mockMvc jwt()', 'Security test utilities.'],
      ['RestTemplate exchange token endpoint', 'Legacy—use WebClient.'],
      ['parse JwtDecoder bean Nimbus', 'Custom validation.'],
      ['@PreAuthorize(\'hasAuthority("SCOPE_read")\')', 'Scope-based authz.'],
      ['CORS + OAuth2 browser client', 'Complex—PKCE, same-site cookies.'],
      ['Logout OIDC RP-initiated', 'End session endpoint discovery.'],
    ],
    seniorScenario: [
      ['Token stolen replay—mitigation?', 'Short TTL, rotation, binding, detect IP change, step-up auth.'],
      ['Misconfigured issuer-uri accepting wrong tokens?', 'Strict metadata validation; allowlist issuers.'],
      ['Microservices each validating JWT—key rotation?', 'Central JWK rotation with cache TTL; handle kid rollover.'],
      ['Compliance storing refresh tokens?', 'Encrypt at rest, device binding, user revocation UX.'],
      ['BFF pattern vs public SPA direct token?', 'Trade-offs XSS, deployment complexity.'],
      ['Breaking OAuth2 client change—semver?', 'Redirect URI changes coordinated with IdP.'],
    ],
    wrongAnswers: [
      'JWTs cannot be revoked before expiry.',
      'Client secret is safe to embed in single-page applications.',
      'OAuth2 is only for user login buttons, not machine auth.',
      'Resource server should trust any JWT signed by anyone if signature verifies.',
      'Authorization code flow works without redirect URIs.',
      'Refresh tokens should never be rotated.',
    ],
  },

  48: {
    conceptual: [
      ['What is reactive programming?', 'Asynchronous data streams with backpressure—Publisher Subscriber.'],
      ['What is Project Reactor Mono vs Flux?', '0-1 vs 0-N elements—Spring WebFlux foundation.'],
      ['What is backpressure?', 'Slow consumer signals producer to slow—Reactive Streams Subscription.request.'],
      ['What is WebFlux vs MVC?', 'Non-blocking stack on Netty vs servlet threads—different programming model.'],
      ['What is RouterFunction?', 'Functional routing alternative to @RestController.'],
      ['What is block() danger?', 'Blocks event loop thread—defeats reactive benefits—use on bounded elastic scheduler.'],
      ['What is Schedulers.boundedElastic?', 'Offload blocking calls from reactive chain—limited threads.'],
      ['What is WebClient?', 'Non-blocking HTTP client—replace RestTemplate for reactive.'],
      ['What is R2DBC?', 'Reactive database driver—alternative to JDBC blocking.'],
      ['What is hot vs cold publisher?', 'Cold per subscriber; hot shared broadcast—different lifecycle.'],
      ['What is retry backoff in Reactor?', 'retryWhen with exponential backoff—transient errors.'],
      ['What is context propagation tracing?', 'Reactor Context for tracing ids across operators—MDC tricky.'],
      ['What is SSE in WebFlux?', 'Server-sent events streaming text/event-stream.'],
      ['What is functional endpoints WebFlux?', 'Cohesive routing handlers—testing style.'],
      ['When not use reactive?', 'Simple CRUD team unfamiliar—complexity cost; blocking stack fine at scale with threads.'],
    ],
    codeBased: [
      ['Flux.range(1,10).map(i->i*2).subscribe()', 'Pipeline basics.'],
      ['Mono.zip combine async results', 'Wait multiple monos.'],
      ['WebClient.get().retrieve().bodyToMono(String.class)', 'HTTP GET.'],
      ['onErrorResume fallback', 'Error recovery.'],
      ['publishOn vs subscribeOn', 'Thread shifting operators.'],
      ['blockOptional last resort in test', 'Convert to sync in tests only.'],
      ['RouterFunction route GET /hello', 'Functional web.'],
      ['SecurityWebFilterChain reactive security', 'Authorize exchanges.'],
      ['R2DBC DatabaseClient query', 'Reactive SQL.'],
      ['StepVerifier.create(flux).expectNext(1,2).verifyComplete()', 'Testing.'],
    ],
    seniorScenario: [
      ['Accidentally called JDBC in WebFlux handler—symptom?', 'Thread starvation blocking event loop—move to boundedElastic or go MVC.'],
      ['Debugging reactive stack traces hard?', 'Checkpoint operator, structured logging, metrics.'],
      ['Mixing MVC and WebFlux in same app?', 'Possible in transition—careful thread model; not trivial.'],
      ['R2DBC connection pool sizing?', 'Different from JDBC—still tune; monitor acquisition time.'],
      ['Memory leaks cold vs hot Flux?', 'Hot must be disposed—subscription management.'],
      ['Grafana metrics reactive streams lag?', 'Backlog metrics; request concurrency limits.'],
    ],
    wrongAnswers: [
      'WebFlux eliminates the need for thread pools entirely.',
      'Mono can emit multiple elements like Flux.',
      'block() is recommended in production WebFlux controllers.',
      'Reactive Streams are only for browser WebSocket APIs.',
      'RestTemplate is the recommended client for WebFlux services.',
      'Backpressure means the server always pushes data faster.',
    ],
  },

  49: {
    conceptual: [
      ['What is REST architectural style?', 'Resource-oriented HTTP verbs status codes hypermedia optional—Roy Fielding constraints.'],
      ['What is idempotency of PUT?', 'Repeated identical PUT should yield same resource state—design carefully.'],
      ['What is safe method?', 'GET HEAD OPTIONS should not change server state—cacheable implications.'],
      ['What is pagination strategy?', 'offset/limit vs cursor-based—deep pagination problems with offset.'],
      ['What is API versioning?', 'URI /v1, header, media type—trade-offs caching and discovery.'],
      ['What is HATEOAS links?', 'Discover actions via links—maturity model.'],
      ['What is Problem Details RFC 7807?', 'Standard error JSON type/title/detail/instance—Spring ProblemDetail support.'],
      ['What is rate limiting 429?', 'Client backoff Retry-After header—resilience.'],
      ['What is content negotiation 406?', 'Cannot produce acceptable representation—client Accept header mismatch.'],
      ['What is idempotency-key header?', 'Duplicate POST protection for payments—store key server-side.'],
      ['What is bulk operations design?', 'Batch endpoints vs many single calls—trade-offs consistency.'],
      ['What is API deprecation policy?', 'Sunset headers, version timeline, documentation—communication.'],
      ['What is JSON merge patch vs JSON patch?', 'Partial update semantics—different RFCs.'],
      ['What is OpenAPI description?', 'Machine-readable contract—generate docs and clients.'],
      ['What is semantic versioning for APIs?', 'Breaking changes major bump—clarity for consumers.'],
    ],
    codeBased: [
      ['Return 201 Created Location header URI', 'REST create pattern.'],
      ['Return 204 No Content delete success', 'No body.'],
      ['ProblemDetail for validation errors', 'Spring 6 style.'],
      ['Page DTO with page,size,totalElements', 'Pagination response.'],
      ['ETag conditional GET If-None-Match', 'Caching optimization.'],
      ['Version in Accept header application/vnd.api+json;version=1', 'Content negotiation versioning.'],
      ['Idempotency-Key storage sketch', 'Map key to response replay.'],
      ['Cursor pagination nextCursor opaque token', 'Stable ordering required.'],
      ['Bulk POST array validation partial success 207 Multi-Status', 'Advanced pattern.'],
      ['Map exception to status 409 Conflict', 'Resource conflict semantics.'],
    ],
    seniorScenario: [
      ['Breaking change without version bump—outage?', 'Consumer contract tests in CI; compatibility matrix.'],
      ['Public API SLAs with third parties?', 'Legal, deprecation windows, usage analytics.'],
      ['Pagination offset slow on large tables?', 'Keyset pagination indexed columns.'],
      ['International error messages API?', 'i18n keys with locale negotiation—ProblemDetail extensions.'],
      ['GraphQL vs REST for mobile clients?', 'Overfetching arguments—different trade-offs.'],
      ['API gateway vs direct microservice exposure?', 'Cross-cutting auth, rate limit, routing—operational complexity.'],
    ],
    wrongAnswers: [
      'REST requires using JSON exclusively.',
      'POST is always idempotent.',
      'HTTP status codes are optional hints clients can ignore.',
      'API versioning should change every sprint.',
      'HATEOAS means every response must include HTML links only.',
      '204 responses must include a JSON body.',
    ],
  },

  50: {
    conceptual: [
      ['What is OpenAPI Specification?', 'YAML/JSON describing paths, schemas, security schemes—Swagger ecosystem.'],
      ['What is springdoc-openapi?', 'Auto-generate OpenAPI from Spring controllers—replaces springfox often.'],
      ['What is codegen from OpenAPI?', 'Generate server stubs or client SDKs—contract-first workflow.'],
      ['What is contract testing?', 'Consumer-driven Pact or Spring Cloud Contract—verify provider implements contract.'],
      ['What is API documentation vs specification?', 'Human docs vs machine spec—ideally generated from same source.'],
      ['What is semantic versioning in OAS?', 'openapi 3.0 vs 3.1 differences—tooling compatibility.'],
      ['What is discriminator in polymorphic schemas?', 'JSON inheritance union types—codegen mapping.'],
      ['What is examples in spec?', 'Sample payloads—improve developer experience.'],
      ['What is securitySchemes bearer JWT?', 'Describe auth for Swagger UI try-it-out.'],
      ['What is global vs operation security?', 'Default security applied unless overridden per operation.'],
      ['What is tags grouping operations?', 'Organize endpoints in UI navigation.'],
      ['What is server URLs multiple environments?', 'Dev/stage/prod server objects—select in UI.'],
      ['What is deprecation in OAS deprecated true?', 'Signal sunset in docs—automation.'],
      ['What is JSON Schema subset in OAS?', 'Validation alignment between spec and runtime—consistency challenges.'],
      ['What is Postman collections vs OpenAPI?', 'Different tools—convert between with tooling.'],
    ],
    codeBased: [
      ['@Operation @ApiResponses springdoc annotations', 'Customize docs.'],
      ['GroupedOpenApi beans multiple groups', 'Split APIs.'],
      ['springdoc.swagger-ui.path', 'Customize swagger path.'],
      ['OpenAPI bean programmatic customization', 'OpenApiCustomiser add security.'],
      ['Generate client openapi-generator-maven-plugin', 'Java client from yaml.'],
      ['@Schema example on DTO', 'Documentation hints.'],
      ['springdoc.api-docs.path', 'JSON endpoint.'],
      ['Disable swagger in prod profile', 'Security—no public spec leakage.'],
      ['Bean Validation @NotNull reflected in schema', 'Automatic if configured.'],
      ['WebFlux springdoc reactive support', 'RouterFunction documentation nuances.'],
    ],
    seniorScenario: [
      ['Swagger UI exposed production leak?', 'Network policies, auth, disable, separate internal only.'],
      ['Spec drift from implementation—fix?', 'Generate spec from code or test contract compatibility in CI.'],
      ['Breaking codegen upgrade openapi generator?', 'Regenerate clients, semver, communicate SDK releases.'],
      ['Multi-module monorepo shared API spec?', 'Central artifact versioned—consumers pin.'],
      ['Internationalized descriptions in spec?', 'Extensions or external docs—tooling limits.'],
      ['GraphQL schema registry vs OpenAPI—different governance?', 'Similar need for evolution discipline.'],
    ],
    wrongAnswers: [
      'OpenAPI and Swagger are completely unrelated technologies.',
      'springdoc requires Springfox to work.',
      'Contract testing guarantees performance SLAs.',
      'OpenAPI specs should never be checked into git.',
      'Swagger UI can safely be public on the internet without auth for internal APIs.',
      'codegen always produces perfect idiomatic code for every language.',
    ],
  },

  51: {
    conceptual: [
      ['What is DDD strategic design?', 'Bounded contexts, ubiquitous language, context maps—align business and software boundaries.'],
      ['What is aggregate?', 'Cluster of entities with invariant root—transactions scoped to aggregate.'],
      ['What is domain event?', 'Something happened in business—past tense facts—drive workflows.'],
      ['What is anti-corruption layer?', 'Translate foreign model to your domain—integration boundary.'],
      ['What is ubiquitous language?', 'Shared terms devs and domain experts use—reduces mistranslation bugs.'],
      ['What is bounded context?', 'Autonomous model boundary—microservice often maps 1:1 not always.'],
      ['What is CQRS relation to DDD?', 'Separate read/write models—often paired—not mandatory for DDD.'],
      ['What is value object vs entity?', 'Immutable identity-less vs mutable identity-tracked—design clarity.'],
      ['What is repository pattern?', 'Domain interface to retrieve aggregates—persistence behind abstraction.'],
      ['What is factory in DDD?', 'Complex aggregate creation enforcing invariants at birth.'],
      ['What is domain service?', 'Logic not belonging to single entity—still domain layer.'],
      ['What is application service?', 'Orchestrate use cases—transaction boundaries often here.'],
      ['What is anemic domain model anti-pattern?', 'Entities only getters/setters—behavior in services—lose OO benefits.'],
      ['What is event storming workshop?', 'Collaborative discovery of events and aggregates—process technique.'],
      ['What is context map patterns?', 'Partnership, customer-supplier, conformist—integration relationships.'],
    ],
    codeBased: [
      ['Order aggregate addLine checks inventory', 'Invariant enforcement method.'],
      ['Domain event OrderPlaced record', 'Immutable event payload.'],
      ['Repository interface OrderRepository domain', 'Infrastructure implements JPA.'],
      ['Anti-corruption PaymentGatewayAdapter', 'Maps Stripe DTO to domain Payment.'],
      ['Value object Money BigDecimal currency', 'No primitive obsession.'],
      ['Factory Order.create for first placement', 'Ensures valid initial state.'],
      ['Application service placeOrder transactional', 'Coordinates aggregates repositories.'],
      ['Domain exception OutOfStock', 'Typed error over generic.'],
      ['Map legacy customer id translation', 'ACL internal class.'],
      ['Test aggregate invariants unit pure', 'No Spring context needed.'],
    ],
    seniorScenario: [
      ['Microservice per entity CRUD—problem?', 'Wrong bounded context slicing—chatty coupling distributed monolith.'],
      ['Shared database across contexts—issue?', 'Coupling—leaks models; prefer integration events or APIs.'],
      ['DDD in CRUD app overkill?', 'Yes sometimes—pragmatic DDD light patterns.'],
      ['Event-driven saga lost messages?', 'Outbox pattern idempotent consumers—reliability engineering.'],
      ['Ubiquitous language drift over years?', 'Glossary documentation, code reviews align naming.'],
      ['Aggregates too large—performance?', 'Split reevaluate boundaries; eventual consistency between aggregates.'],
    ],
    wrongAnswers: [
      'DDD requires microservices.',
      'An aggregate can span multiple databases easily.',
      'Domain events must always be implemented with Kafka.',
      'Repositories should contain business rules.',
      'Value objects must always map to database tables.',
      'Anti-corruption layer means rejecting all external data.',
    ],
  },

  52: {
    conceptual: [
      ['What is service discovery?', 'Dynamic registry of service instances—clients find healthy endpoints.'],
      ['What is Eureka/Consul/etcd?', 'Discovery backends—Spring Cloud Netflix Eureka common in Java ecosystem.'],
      ['What is client-side vs server-side discovery?', 'Client queries registry vs load balancer asks registry—trade-offs coupling.'],
      ['What is API gateway pattern?', 'Single entry routing auth rate limit aggregation—Kong, Spring Cloud Gateway.'],
      ['What is health check registration?', 'Only healthy instances registered—failing instances removed.'],
      ['What is load balancing round robin vs least conn?', 'Algorithms differ for CPU vs long-lived connections.'],
      ['What is DNS-based discovery?', 'Simpler but coarse TTL caching issues—Kubernetes headless services.'],
      ['What is service mesh Istio?', 'Sidecar proxies handle traffic policy observability—different layer than Spring Cloud.'],
      ['What is circuit breaker at gateway?', 'Fail fast when downstream unhealthy—resilience4j.'],
      ['What is blue-green deployment with gateway?', 'Switch traffic between versions—routing rules.'],
      ['What is canary release?', 'Route small percentage to new version—metrics driven promotion.'],
      ['What is sticky sessions vs stateless?', 'Session affinity vs JWT—gateway implications.'],
      ['What is mTLS between services?', 'Mutual TLS for service identity—mesh often handles.'],
      ['What is global vs regional discovery?', 'Latency and partition tolerance—multi-region architecture.'],
      ['What is Eureka self-preservation?', 'Keeps instances during network partitions—understand false positives.'],
    ],
    codeBased: [
      ['Spring Cloud LoadBalancer @LoadBalanced RestTemplate', 'Service name resolution.'],
      ['Gateway route predicates Path=/api/**', 'Spring Cloud Gateway config.'],
      ['Eureka client registration spring.application.name', 'Service id.'],
      ['Kubernetes Service ClusterIP DNS', 'my-svc.namespace.svc.cluster.local'],
      ['Consul health check HTTP /actuator/health', 'TTL deregister.'],
      ['Ribbon deprecated replacement', 'Spring Cloud LoadBalancer.'],
      ['Reactive WebClient with load-balanced', 'WebClient.Builder bean.'],
      ['Gateway filter AddRequestHeader', 'Trace propagation.'],
      ['DiscoveryClient.getInstances("orders")', 'Programmatic lookup.'],
      ['Weight-based routing canary', 'Custom LoadBalancer—advanced.'],
    ],
    seniorScenario: [
      ['Split brain Eureka clusters—symptoms?', 'Stale registrations; tune renewal thresholds; prefer K8s native discovery.'],
      ['Gateway SPOF?', 'Scale replicas; health checks; multi-AZ.'],
      ['Cross-region discovery latency?', 'Geo-DNS, regional gateways, data locality.'],
      ['Service mesh operational complexity?', 'Team skills vs benefits—incremental adoption.'],
      ['Cost of client-side discovery library upgrades?', 'Coordinate Spring Cloud BOM with Boot versions.'],
      ['Zombie instances after crash?', 'Health checks TTL; outlier detection.'],
    ],
    wrongAnswers: [
      'Service discovery eliminates the need for load balancing.',
      'API gateways should contain all business logic.',
      'DNS always has instant updates when instances change.',
      'Eureka is the only service discovery option for Spring.',
      'Client-side discovery means the user’s browser queries Eureka.',
      'A service mesh replaces Kubernetes Services entirely.',
    ],
  },

  53: {
    conceptual: [
      ['What is OpenFeign?', 'Declarative HTTP client interface—Spring Cloud OpenFeign integrates.'],
      ['What is WebClient?', 'Non-blocking alternative to RestTemplate—reactive stack.'],
      ['What is resilience4j circuit breaker?', 'States closed/open/half-open—fail fast when errors spike.'],
      ['What is retry with backoff?', 'Transient failures—exponential backoff jitter avoid thundering herd.'],
      ['What is bulkhead isolation?', 'Separate thread pools—failure isolation.'],
      ['What is timeout configuration?', 'Connect vs read timeout—different failure modes.'],
      ['What is RestTemplate deprecation?', 'Prefer WebClient for new code—even in servlet apps for async.'],
      ['What is Feign fallback factory?', 'Provide fallback bean when circuit open—degraded response.'],
      ['What is client-side load balancing with Feign?', 'Ribbon legacy replaced by Spring Cloud LoadBalancer.'],
      ['What is Micrometer metrics for resilience4j?', 'Monitor circuit state transitions counts.'],
      ['What is HTTP/2 multiplexing benefit?', 'Single connection many streams—client server support needed.'],
      ['What is connection pooling HttpClient?', 'Reuse TCP connections—tune max connections per route.'],
      ['What is idempotent retry safety?', 'Only retry GET/PUT with care—POST duplicate risk.'],
      ['What is chaos engineering relation?', 'Test resilience assumptions—inject faults.'],
      ['What is gRPC vs HTTP JSON clients?', 'Binary protobuf efficiency—different tooling.'],
    ],
    codeBased: [
      ['@FeignClient(name="orders", path="/api")', 'Interface methods map to HTTP.'],
      ['@CircuitBreaker name="orders" fallbackMethod', 'Resilience4j annotation style.'],
      ['WebClient.builder().baseUrl(...).build()', 'Create client bean.'],
      ['Retry backoff exponential Resilience4j RetryConfig', 'Configure max attempts.'],
      ['TimeLimiter for async calls', 'Bound execution time.'],
      ['RestTemplate exchange ResponseEntity', 'Legacy synchronous.'],
      ['Feign ErrorDecoder map status to exceptions', 'Typed errors.'],
      ['WebClient retrieve onStatus error', 'Handle 4xx/5xx.'],
      ['BulkheadRegistry configure thread pools', 'Isolation tuning.'],
      ['OkHttpClient connection pool tuning', 'If using underlying OkHttp—advanced.'],
    ],
    seniorScenario: [
      ['Retry storm on DB outage—symptom?', 'Amplified load—disable retries under cascade; bulkhead.'],
      ['Feign timeouts vs gateway timeouts ordering?', 'Align layers—inner shorter than outer.'],
      ['Thread pool exhaustion bulkhead?', 'Tune limits; queue depth metrics; reject fast.'],
      ['Partial failure distributed call graph?', 'Saga compensations; graceful degradation UX.'],
      ['Observability trace feign calls?', 'OpenTelemetry propagation headers.'],
      ['Breaking API feign client compile errors?', 'Consumer-driven contract catch early.'],
    ],
    wrongAnswers: [
      'Circuit breakers open on first failed request always.',
      'WebClient is blocking by default.',
      'Feign works without any HTTP implementation.',
      'Retry is safe for all HTTP methods without conditions.',
      'RestTemplate is the recommended client for new Spring Boot 3 projects.',
      'Bulkhead and circuit breaker are identical patterns.',
    ],
  },

  54: {
    conceptual: [
      ['What is gRPC?', 'RPC over HTTP/2 with protobuf—strongly typed contracts—efficient binary.'],
      ['What is protobuf?', 'IDL generates code—versioning compatibility forward backward—field numbers.'],
      ['What is GraphQL?', 'Client queries shape of data—single endpoint—resolver architecture.'],
      ['What is N+1 problem in GraphQL?', 'Resolvers per field may query DB repeatedly—DataLoader batching fixes.'],
      ['What is schema stitching vs federation?', 'Compose multiple GraphQL services—governance complexity.'],
      ['What is gRPC streaming?', 'Unary, server streaming, client streaming, bidirectional—use cases differ.'],
      ['What is HTTP/2 vs gRPC-Web?', 'Browser clients need gRPC-Web proxy—different limitations.'],
      ['What is protobuf optional vs singular?', 'Proto3 optional restores explicit presence—syntax evolution.'],
      ['What is GraphQL introspection security?', 'Disable in production or protect—information disclosure.'],
      ['What is gRPC deadlines?', 'Propagate timeout metadata—distributed tracing alignment.'],
      ['What is GraphQL mutations?', 'Writes with side effects—design idempotency keys.'],
      ['What is protobuf backward compatibility?', 'Never reuse field numbers; reserve deleted numbers.'],
      ['What is JSON vs protobuf on wire?', 'JSON human readable larger; protobuf compact faster parse.'],
      ['What is GraphQL pagination connections spec?', 'Edges cursors—relay specification pattern.'],
      ['What is gRPC status codes mapping?', 'Richer than HTTP codes in layer—map carefully to REST gateways.'],
    ],
    codeBased: [
      ['proto service Greeter { rpc SayHello(HelloRequest) returns (HelloReply); }', 'Define RPC.'],
      ['Maven protobuf compile plugin', 'Generate Java stubs.'],
      ['ManagedChannel ManagedChannelBuilder.forAddress', 'gRPC client channel.'],
      ['GraphQL Java DataFetcher', 'Resolve field.'],
      ['DataLoader batch load users by id', 'Solve N+1.'],
      ['Spring GraphQL @QueryMapping', 'Controller style.'],
      ['gRPC server ServerBuilder', 'Add service implementation.'],
      ['GraphQL error extensions custom codes', 'Client handling.'],
      ['protobuf json_format parse print', 'Interop debugging.'],
      ['grpc-spring-boot-starter @GrpcService', 'Integration pattern.'],
    ],
    seniorScenario: [
      ['GraphQL public API DoS complex queries?', 'Query depth/complexity limits, timeouts, persisted queries.'],
      ['gRPC through corporate HTTP proxies?', 'Often blocked—need special ports or grpc-web bridge.'],
      ['Protobuf breaking change in production?', 'Dual write read migration; feature flags; careful rollout.'],
      ['GraphQL microservices BFF pattern?', 'Aggregate downstream REST/gRPC—avoid god resolver.'],
      ['Observability grpc tracing OpenTelemetry?', 'Instrument interceptors metadata propagation.'],
      ['Team skill split REST vs gRPC—migration?', 'Gateway translation gradual; shared protobuf contracts.'],
    ],
    wrongAnswers: [
      'gRPC requires JSON payloads.',
      'GraphQL replaces the need for any database indexes.',
      'Protobuf field names are what matter on the wire, not field numbers.',
      'gRPC cannot stream data.',
      'GraphQL resolvers always run in parallel safely without coordination.',
      'REST and gRPC cannot coexist in the same system.',
    ],
  },

  55: {
    conceptual: [
      ['What is synchronous HTTP between services?', 'Caller blocks until response—simple but ties threads—cascade latency.'],
      ['What is asynchronous messaging?', 'Producer sends event consumer processes later—decouples availability.'],
      ['What is message broker role?', 'Durability routing delivery guarantees abstraction—Kafka RabbitMQ etc.'],
      ['What is fan-out pattern?', 'One event to many consumers—topics subscriptions.'],
      ['What is competing consumers?', 'Multiple instances share queue partition for scale—ordering implications.'],
      ['What is dead-letter queue?', 'Failed messages after retries—isolation for analysis reprocessing.'],
      ['What is idempotent consumer?', 'Processing same message twice safe—business keys dedupe.'],
      ['What is message ordering guarantees?', 'Single partition FIFO; multiple partitions parallel—design keys.'],
      ['What is outbox pattern?', 'Transactionally write DB + outbox event—relay to broker—exactly-once illusion.'],
      ['What is choreography vs orchestration saga?', 'Events only vs central coordinator—trade-offs visibility coupling.'],
      ['What is API composition BFF?', 'Backend for frontend aggregates calls—reduce chatty mobile apps.'],
      ['What is anti-corruption between services?', 'Translate foreign events to local domain—bounded contexts.'],
      ['What is back-pressure in messaging?', 'Slow consumer pulls less—Kafka consumer lag monitoring.'],
      ['What is poison message?', 'Always fails processing—move to DLQ after threshold.'],
      ['What is schema evolution Avro/Protobuf?', 'Compatible readers writers—registry enforcement.'],
    ],
    codeBased: [
      ['Kafka producer send ProducerRecord', 'key value topic.'],
      ['RabbitTemplate convertAndSend exchange routingKey', 'AMQP send.'],
      ['@KafkaListener topics groups', 'Consumer annotation.'],
      ['@RabbitListener queues', 'Spring AMQP listener.'],
      ['Idempotent consumer insert DB unique key', 'ON CONFLICT DO NOTHING pattern.'],
      ['Outbox table insert in @Transactional', 'Same tx as business row.'],
      ['WebClient chaining calls zip merge', 'Parallelize HTTP aggregation.'],
      ['CompletableFuture allOf downstream calls', 'Scatter-gather sync style.'],
      ['Resilience4j bulkhead separate pools', 'Isolation between dependency calls.'],
      ['Saga orchestrator state machine sketch', 'Steps compensate previous.'],
    ],
    seniorScenario: [
      ['Thundering herd cache stampede on event?', 'Jittered backoff randomization single-flight protection.'],
      ['Distributed tracing across async messages?', 'Trace id propagation headers metadata—W3C trace context.'],
      ['Message size limits broker config?', 'Large payloads to object storage reference in message.'],
      ['Ordering vs throughput Kafka partitions?', 'More partitions more parallelism but per-key order only per partition.'],
      ['BFF becomes monolith—smell?', 'Too much logic—split by domain or move to dedicated services.'],
      ['Dual writes DB and broker without outbox—risk?', 'Inconsistency on crash—classic distributed systems bug.'],
    ],
    wrongAnswers: [
      'Messaging always guarantees exactly-once delivery end-to-end without extra design.',
      'Synchronous REST is always wrong between microservices.',
      'Dead-letter queues mean messages are lost forever.',
      'Fan-out requires duplicate messages to each consumer always.',
      'Outbox pattern eliminates the need for a message broker.',
      'BFF should contain all domain business rules.',
    ],
  },

  56: {
    conceptual: [
      ['What is saga pattern?', 'Long-lived transaction split into local transactions with compensating actions.'],
      ['What is choreography saga?', 'Each service reacts to events—no central brain—harder to trace.'],
      ['What is orchestration saga?', 'Orchestrator drives steps—clear flow central point of failure mitigation.'],
      ['What is compensating transaction?', 'Undo business action—like refund after reserve—must be designed idempotent.'],
      ['What is two-phase commit 2PC?', 'Distributed atomic commit—blocking availability concerns—avoid in microservices often.'],
      ['What is TCC Try-Confirm-Cancel?', 'Reserves resources then confirms—explicit three phases—complex.'],
      ['What is eventual consistency?', 'System becomes consistent over time—UX handles temporary inconsistency.'],
      ['What is idempotency key in payments?', 'Duplicate request detection—critical for sagas.'],
      ['What is SAGA timeout handling?', 'Compensate incomplete steps—timeouts per step saga state machine.'],
      ['What is distributed deadlock?', 'Circular waits across services—avoid lock ordering global IDs.'],
      ['What is outbox + process manager?', 'Reliable events + orchestration state—robust combo.'],
      ['What is human intervention in saga?', 'Manual compensation for complex failures—operations runbooks.'],
      ['What is CDC change data capture relation?', 'Event sourcing adjacent—capture DB changes to events.'],
      ['What is CAP in distributed transactions?', 'Partition tolerance forces trade-off C vs A—2PC blocks.'],
      ['What is business invariant across services?', 'Cannot rely on ACID cross DB—design sagas carefully.'],
    ],
    codeBased: [
      ['State machine states PENDING RESERVED PAID SHIPPED', 'Transitions with events.'],
      ['Compensate cancelReservation after payment fail', 'Saga step example.'],
      ['Orchestrator calls REST then on failure call compensate', 'Pseudo flow.'],
      ['Idempotency store table request_id primary key', 'Dedup.'],
      ['2PC XA DataSource sketch', 'Rare modern—know existence.'],
      ['Choreography event OrderCreated PaymentReserved', 'Event names past tense.'],
      ['Timeout scheduled job saga stuck detection', 'Alert ops.'],
      ['Transactional outbox relay polling', 'Separate process.'],
      ['Saga log append-only audit', 'Replay debugging.'],
      ['REST POST retry safe if idempotent PUT semantics', 'Design payment APIs carefully.'],
    ],
    seniorScenario: [
      ['Partial saga failure money taken not shipped—ops?', 'Manual reconciliation compensating transactions customer support tools.'],
      ['2PC in microservices outage?', 'Coordinator failure blocks participants—availability hit—why sagas preferred.'],
      ['Exactly-once myth marketing?', 'End-to-end exactly-once is composite idempotency + dedupe + offsets.'],
      ['Regulatory audit saga logs retention?', 'Immutable store compliance—years.'],
      ['Cross-border payment saga compliance steps?', 'Additional verification steps asynchronous—long-running.'],
      ['Testing sagas?', 'Model-based tests fault injection simulate failures each step.'],
    ],
    wrongAnswers: [
      'Saga means you have ACID transactions across all microservices.',
      'Compensating actions can always perfectly undo any real-world effect.',
      'Two-phase commit is the default approach in Spring Cloud.',
      'Choreography sagas are always simpler than orchestration.',
      'Distributed transactions are free from performance overhead.',
      'Eventual consistency means the system is always wrong.',
    ],
  },

  57: {
    conceptual: [
      ['What is CQRS?', 'Command Query Responsibility Segregation—separate models for read and write.'],
      ['What is event sourcing?', 'Store sequence of events as source of truth—rebuild state by replay.'],
      ['What is projection in event sourcing?', 'Read model built from events—materialized view updated asynchronously.'],
      ['What is snapshot in event sourcing?', 'Periodic state snapshot to shorten replay—trade-off storage complexity.'],
      ['What is CQRS without event sourcing?', 'Separate read/write DB schemas—simpler than full event store.'],
      ['What is eventual consistency in read models?', 'Query may lag behind commands—UX staleness indicators.'],
      ['What is command side validation?', 'Enforce invariants before emitting events—aggregate boundaries.'],
      ['What is event store requirements?', 'Ordering per aggregate, global sequence, retention—Kafka or specialized DB.'],
      ['What is idempotent projection processor?', 'At-least-once delivery means replay safe—dedupe by event id.'],
      ['What is CQRS complexity cost?', 'More moving parts—only when read/write scale differently.'],
      ['What is event versioning?', 'Upcasters migrate old events to new schema—evolution discipline.'],
      ['What is GDPR delete in event sourcing?', 'Crypto-shredding tombstones—hard problem—design early.'],
      ['What is saga vs event sourcing?', 'Related but distinct—saga orchestrates; ES stores facts.'],
      ['What is read model denormalization?', 'Optimize queries—joins precomputed in projection.'],
      ['What is Axon/Eventuate frameworks?', 'CQRS/ES infrastructure in Java ecosystem—patterns packaged.'],
    ],
    codeBased: [
      ['Command PlaceOrder handled emits OrderPlaced', 'Event naming.'],
      ['Projection OrderView update on event', 'Event handler method.'],
      ['Aggregate load from events foldLeft', 'Functional fold current state.'],
      ['SnapshotRepository save every 100 events', 'Performance tuning.'],
      ['Kafka compacted topic changelog', 'Key-value retention.'],
      ['Separate read DB update with Spring @TransactionalEventListener AFTER_COMMIT', 'Consistency timing.'],
      ['Query side simple SELECT from view table', 'Fast reads.'],
      ['Event schema Avro with compatibility BACKWARD', 'Registry test.'],
      ['Idempotent projection insert event_id unique', 'Dedup table.'],
      ['Replay events in test assert final state', 'Regression testing.'],
    ],
    seniorScenario: [
      ['Projection lag customer sees stale balance?', 'SLA on lag monitoring; sync read for critical path if needed.'],
      ['Event store corruption replay disaster?', 'Backups immutable logs multi-region replication.'],
      ['CQRS for simple CRUD app?', 'Overengineering—YAGNI.'],
      ['Team lacks ES experience—risk?', 'Training incremental adoption maybe CQRS first without ES.'],
      ['Debugging event replay ordering bugs?', 'Deterministic handlers versioning careful concurrency per aggregate.'],
      ['Analytics on raw events vs projections?', 'Lake raw events; warehouse aggregates—different pipelines.'],
    ],
    wrongAnswers: [
      'CQRS requires Kafka.',
      'Event sourcing means you never store current state anywhere.',
      'Read models must be updated synchronously in the same transaction as writes.',
      'Projections cannot be rebuilt from scratch.',
      'CQRS eliminates the need for aggregates and transactions.',
      'Event sourcing makes deletes trivial without any design.',
    ],
  },

  58: {
    conceptual: [
      ['What is strangler fig pattern?', 'Gradually replace legacy by routing increasing traffic to new system.'],
      ['What is anti-corruption layer again?', 'Boundary protecting new model from legacy mess—important in migration.'],
      ['What is bulkhead pattern?', 'Isolate thread pools resources—failure containment.'],
      ['What is sidecar pattern?', 'Auxiliary container with main app—proxy logging mesh—shared lifecycle.'],
      ['What is ambassador pattern?', 'Proxy helping service speak foreign protocol—network translation.'],
      ['What is backends for frontends?', 'Different APIs per client type—optimize payloads—not only microservices.'],
      ['What is service mesh benefits?', 'mTLS traffic policy observability—operational complexity.'],
      ['What is API gateway aggregation?', 'Combine calls server-side—reduce chatty mobile—latency trade-off.'],
      ['What is feature toggle in architecture?', 'Runtime routing A/B experiments progressive delivery.'],
      ['What is dark launch?', 'New code runs shadow traffic compare results—validation without user impact.'],
      ['What is chaos monkey?', 'Random instance termination—resilience validation—careful prod policies.'],
      ['What is multi-region active-active?', 'Hard—data replication conflicts—often active-passive per domain.'],
      ['What is idempotent infrastructure operations?', 'Retries safe—Terraform Kubernetes controllers.'],
      ['What is cell-based architecture?', 'Shards of infrastructure failure isolation—large scale.'],
      ['What is evolutionary architecture?', 'Support guided change—fitness functions metrics architecture.'],
    ],
    codeBased: [
      ['Feature flag LaunchDarkly if (flag)', 'Runtime branch.'],
      ['Istio VirtualService weight 90/10', 'Canary example yaml concept.'],
      ['Kubernetes Deployment maxSurge', 'Rolling update params.'],
      ['Spring Cloud Gateway route predicates', 'Route new path to new service.'],
      ['Resilience4j bulkhead threadPoolMaxSize', 'Config isolate.'],
      ['Sidecar nginx proxy_pass', 'Classic pattern.'],
      ['Ambassador translate REST to gRPC', 'Adapter service.'],
      ['Terraform module version pin', 'Safe infra evolution.'],
      ['Synthetic canary metric compare error rate', 'Automated promotion.'],
      ['Database read replica routing @Transactional readOnly', 'CQRS light.'],
    ],
    seniorScenario: [
      ['Strangler incomplete both systems inconsistent?', 'Synchronization reconciliation jobs monitoring divergence.'],
      ['Mesh mTLS cert rotation outage?', 'Automated cert-manager vigilance short TTL alerts.'],
      ['Dark launch doubles infrastructure cost?', 'Sampling shadow traffic subset—cost control.'],
      ['Multi-region data laws GDPR residency?', 'Route users region pinned data—architecture constraint.'],
      ['Org not ready microservices patterns?', 'Modular monolith first—extract services when boundaries clear.'],
      ['Chaos in production without guardrails?', 'Blast radius controls environment isolation executive buy-in.'],
    ],
    wrongAnswers: [
      'Strangler pattern means deleting the old system in one day.',
      'Service mesh removes the need for application security.',
      'Sidecar must be written in the same language as the main app.',
      'Bulkhead pattern means one thread pool for the entire company.',
      'Canary releases require zero monitoring.',
      'Evolutionary architecture means no planning upfront.',
    ],
  },

  59: {
    conceptual: [
      ['What is Kafka topic?', 'Category feed of messages—immutable log segments.'],
      ['What is partition?', 'Ordered immutable sequence within topic—unit of parallelism.'],
      ['What is broker?', 'Kafka server storing partitions—cluster of brokers.'],
      ['What is replication factor?', 'Copies per partition—ISR in-sync replicas leader follower.'],
      ['What is consumer group?', 'Set of consumers dividing partitions—scale consumption horizontally.'],
      ['What is offset?', 'Position in partition log—committed offset tracks progress.'],
      ['What is retention policy?', 'Time or size based retention—compaction for changelog topics.'],
      ['What is key in Kafka record?', 'Same key goes to same partition—ordering per key.'],
      ['What is ZooKeeper vs KRaft?', 'Legacy metadata quorum vs Kafka Raft mode—new clusters KRaft.'],
      ['What is log compaction?', 'Retain latest key value—changelog semantics—tombstone deletes.'],
      ['What is exactly-once in Kafka?', 'Idempotent producer transactions consumer isolation—EOS semantics.'],
      ['What is consumer lag?', 'Difference high-water mark and committed offset—backlog metric.'],
      ['What is rebalance?', 'Consumer group membership change redistributes partitions—stop-the-world impact.'],
      ['What is idempotent producer enable.idempotence?', 'Deduplicate retries PID sequence numbers.'],
      ['What is transactions in Kafka?', 'Atomic write multiple partitions—consume-transform-produce pattern.'],
    ],
    codeBased: [
      ['ProducerRecord with key partition routing', 'Same user id key.'],
      ['Consumer poll loop commitSync commitAsync', 'Offset commit strategies.'],
      ['subscribe(List topics) vs assign partitions manual', 'Low-level control.'],
      ['Kafka Streams KStream filter map', 'DSL example.'],
      ['AdminClient createTopics NewTopic', 'Automation IaC.'],
      ['configs cleanup.policy compact', 'Topic config.'],
      ['Exactly-once initTransactions beginTransaction send commitTransaction', 'Producer API sequence.'],
      ['ConsumerConfig AUTO_OFFSET_RESET earliest', 'Read from start new group.'],
      ['Metrics kafka.consumer.records-lag-max', 'Monitoring alert.'],
      ['Serialization JsonSerializer Avro serializer', 'Schema integration.'],
    ],
    seniorScenario: [
      ['Broker disk full cluster halt?', 'Monitor disk retention sizing alerts tiered storage.'],
      ['Rebalance storm during deploy?', 'Cooperative sticky assignors tuning session timeouts.'],
      ['Ordering guarantee cross partition?', 'Not global—design keys carefully single partition hot spots.'],
      ['Kafka as database anti-pattern?', 'Operational complexity; use proper DB for query patterns.'],
      ['Multi-region Kafka MirrorMaker?', 'Latency offset lag disaster recovery complexity.'],
      ['PII in topics GDPR?', 'Encryption masking access control retention minimization.'],
    ],
    wrongAnswers: [
      'Kafka is a traditional message queue deleting messages after consume.',
      'A topic always has exactly one partition.',
      'Consumer groups allow multiple consumers to read the same partition in parallel.',
      'Kafka brokers store messages in PostgreSQL.',
      'Offsets are managed only by the broker, never by clients.',
      'Kafka guarantees global ordering across all partitions in a topic.',
    ],
  },

  60: {
    conceptual: [
      ['What is Kafka producer batching?', 'linger.ms batch.size accumulate records throughput vs latency trade-off.'],
      ['What is compression?', 'lz4 snappy gzip—CPU vs network trade-off.'],
      ['What is acks configuration?', '0 fire-and-forget, 1 leader ack, all ISR ack—durability trade-off.'],
      ['What is retries and ordering?', 'With max.in.flight >1 without idempotence reorder risk—tune carefully.'],
      ['What is sticky partitioner?', 'Better batching same partition until batch full—throughput.'],
      ['What is buffer memory?', 'Producer buffer before send—block or fail when full.'],
      ['What is max.block.ms?', 'How long metadata fetch buffer allocation block—latency impact.'],
      ['What is delivery timeout?', 'Upper bound send attempt including retries—align with broker settings.'],
      ['What is transactional producer?', 'Exactly-once produce multiple partitions atomic—overhead.'],
      ['What is schema evolution with producer?', 'Compatible serializers—fail fast on mismatch.'],
      ['What is partitioner customization?', 'Custom routing beyond key hash—business logic.'],
      ['What is record headers?', 'Metadata per message—tracing propagation without payload pollution.'],
      ['What is idempotent producer sequence numbers?', 'PID epoch per producer instance—broker dedupe.'],
      ['What is linger trade-off?', 'Higher linger better throughput worse latency tail.'],
      ['What is client DNS cache refresh?', 'Broker discovery changes—rare but painful incidents.'],
    ],
    codeBased: [
      ['producer.send callback RecordMetadata exception', 'Async handling.'],
      ['Future get send synchronous wait', 'Blocking style.'],
      ['flush close producer lifecycle', 'Graceful shutdown drain.'],
      ['partition null round-robin', 'No key behavior.'],
      ['metrics num.records.errors.record_error_total', 'Monitor failures.'],
      ['configure interceptor ProducerInterceptor onSend', 'Add headers trace id.'],
      ['buffer.memory 33554432 tuning', 'Size awareness.'],
      ['compression.type lz4', 'Config example.'],
      ['transactional.id my-producer-1', 'EOS config.'],
      ['bootstrap.servers list', 'Initial cluster connection.'],
    ],
    seniorScenario: [
      ['Producer throughput collapse latency spike?', 'Batch too small? Network partition? Broker hot partition? Profile.'],
      ['Duplicate events after network blip?', 'Idempotent producer and consumer dedupe keys.'],
      ['Ordered delivery violated?', 'Retries in flight settings idempotence enable—verify config.'],
      ['Memory leak producer buffer?', 'Close producers on shutdown; avoid per-request new producer.'],
      ['Schema registry down producer fail?', 'Cache schemas fallback strategy degrade gracefully.'],
      ['Cross-datacenter produce latency?', 'Local produce to mirror—architecture pattern.'],
    ],
    wrongAnswers: [
      'acks=all means the producer waits for all brokers in the cluster including observers.',
      'linger.ms=0 always minimizes end-to-end latency in every scenario.',
      'Producers should create a new KafkaProducer per message for isolation.',
      'Compression never increases CPU usage.',
      'Transactional producers are free and have no performance impact.',
      'max.in.flight can be unlimited without risk.',
    ],
  },

  61: {
    conceptual: [
      ['What is consumer poll loop?', 'Long-polling fetch records batch processing commit offsets.'],
      ['What is auto commit vs manual?', 'enable.auto.commit periodic vs commitSync after processing—at-least-once vs control.'],
      ['What is consumer group rebalance protocol?', 'Assign partitions when consumers join leave—EAGER vs COOPERATIVE.'],
      ['What is static membership group.instance.id?', 'Reduce unnecessary rebalance on transient restarts—sticky identity.'],
      ['What is fetch.min.bytes max.wait.ms?', 'Consumer batching trade-off latency throughput.'],
      ['What is isolation.level read_committed?', 'Only read transactional commits—EOS consumers.'],
      ['What is max.poll.interval.ms?', 'If processing too long between polls—consider pause partitions async processing.'],
      ['What is heartbeats session.timeout.ms?', 'Detect failed consumers—tune with GC pauses mind.'],
      ['What is assign vs subscribe?', 'Manual partition assignment vs dynamic group—advanced.'],
      ['What is incremental cooperative rebalancing?', 'Reduce stop-the-world during rebalance—Kafka 2.4+.'],
      ['What is consumer lag monitoring?', 'Critical SLO—alert thresholds scale consumers.'],
      ['What is idempotent consumer?', 'Processing twice safe—business keys idempotency store.'],
      ['What is pause/resume partitions?', 'Backpressure slow processing pipeline—stop fetching temporarily.'],
      ['What is deserialization error handler?', 'DLQ poison messages—skip fail strategies.'],
      ['What is exactly-once consumer?', 'Read process write transactional outbox EOS—complex.'],
    ],
    codeBased: [
      ['@KafkaListener concurrency=3', 'Multiple threads listener container.'],
      ['AckMode MANUAL_IMMEDIATE', 'Commit after each record Spring Kafka.'],
      ['ConsumerRecords loop for ConsumerRecord', 'Batch processing.'],
      ['seekToBeginning after subscribe reset', 'Reprocess carefully.'],
      ['ErrorHandler SeekToCurrentErrorHandler', 'Retry policy Spring Kafka.'],
      ['pause Consumer pause assigned partitions', 'Backpressure API.'],
      ['ConsumerConfig MAX_POLL_RECORDS tune', 'Batch size.'],
      ['listener container factory ConcurrentKafkaListenerContainerFactory', 'Spring config.'],
      ['@RetryableTopic dlt', 'Spring Kafka retry DLT.'],
      ['commitOffsets sync after DB transaction', 'Outbox pattern alignment.'],
    ],
    seniorScenario: [
      ['Consumer lag growing unbounded—ops?', 'Scale consumers partitions enough poison messages stuck.'],
      ['Rebalance loop crash repeating?', 'Processing exceeds max.poll.interval—async processing pause pattern.'],
      ['Duplicate processing money movement?', 'Idempotency keys ledger—detect replay.'],
      ['Consumer reading old messages after deploy?', 'Offset reset misconfiguration auto.offset.reset.'],
      ['Multi-tenant noisy neighbor partition hot?', 'Key skew monitoring rebalance keys.'],
      ['GDPR erase events consumed already?', 'Compensating delete downstream systems—hard.'],
    ],
    wrongAnswers: [
      'Consumers pull messages from Kafka; Kafka pushes to consumers continuously without polling.',
      'enable.auto.commit guarantees exactly-once processing.',
      'Increasing max.poll.interval.ms fixes all slow consumer problems without design changes.',
      'Consumer group id is optional and ignored.',
      'Manual commit always means at-most-once semantics.',
      'Rebalances never pause consumption.',
    ],
  },

  62: {
    conceptual: [
      ['What is at-most-once delivery?', 'Messages may be lost—fire and forget—rarely acceptable for money.'],
      ['What is at-least-once delivery?', 'Duplicates possible—consumers must dedupe—common default.'],
      ['What is exactly-once semantics end-to-end?', 'Composite: idempotent producers, transactions, idempotent consumers—hard.'],
      ['What is Kafka EOS transaction?', 'Producer initTransactions begin commit atomic multi partition.'],
      ['What is read_committed consumer?', 'Skips open transactions aborted—sees only committed transactional messages.'],
      ['What is zombie fencing?', 'Transactional id epoch prevents old producer instances writing—fence older zombies.'],
      ['What is outbox pattern relation?', 'Local DB transaction + event ensures atomicity with business row—EOS illusion.'],
      ['What is idempotent consumer dedupe store?', 'Unique constraint on message id processed flag.'],
      ['What is log compaction EOS?', 'Compacted topics still need ordering idempotence—careful.'],
      ['What is end-to-end latency vs EOS overhead?', 'Transactions add latency coordination—measure.'],
      ['What is duplicate detection window?', 'Time bounded dedupe store size—TTL old keys.'],
      ['What is JMS exactly-once limitations?', 'Different model—Kafka EOS more explicit modern.'],
      ['What is cloud provider messaging guarantees?', 'SQS at-least-once typically—design idempotency always.'],
      ['What is financial ledger double-entry with events?', 'Immutable append-only compensations—audit friendly.'],
      ['What is testing EOS?', 'Chaos duplicate delivery simulation property tests.'],
    ],
    codeBased: [
      ['producer initTransactions beginTransaction send partitions commitTransaction', 'Sequence.'],
      ['consumer isolation.level read_committed', 'Config.'],
      ['insert into processed(id) values(?) on conflict do nothing', 'Dedup SQL.'],
      ['Spring @Transactional + KafkaTemplate executeInTransaction', 'Spring Kafka transactional producer.'],
      ['idempotency key HTTP header store response replay', 'API layer dedupe.'],
      ['UUID message id in envelope', 'Correlation dedupe.'],
      ['Outbox relay process marked sent', 'Reliable publishing.'],
      ['Exactly-once connect streams EOS enable', 'Kafka Streams config.'],
      ['Retry with same idempotent producer PID', 'Broker dedupe.'],
      ['Unit test duplicate delivery twice assert once effect', 'Testing strategy.'],
    ],
    seniorScenario: [
      ['Finance claims “exactly-once” marketing—engineering response?', 'Clarify boundaries end-to-end guarantees operational dedupe.'],
      ['EOS overhead unacceptable latency SLA?', 'Maybe at-least-once + strong idempotency cheaper.'],
      ['Cross-system EOS database + Kafka?', 'Outbox inbox patterns distributed transaction alternative 2PC.'],
      ['Bug duplicate charges—postmortem?', 'Missing idempotency keys replay storm—fix dedupe monitoring.'],
      ['Zombie instance cloud autoscaler?', 'Epoch fencing verification deployment uniqueness.'],
      ['Regulatory audit prove no duplicates?', 'Immutable logs reconciliation reports signatures.'],
    ],
    wrongAnswers: [
      'Kafka exactly-once means you never need idempotent consumers.',
      'At-most-once is the safest default for payments.',
      'Transactions in Kafka remove all performance costs.',
      'read_uncommitted is required for exactly-once.',
      'Idempotency keys can be reused forever without storage growth concerns.',
      'EOS guarantees exactly-once across external HTTP calls automatically.',
    ],
  },

  63: {
    conceptual: [
      ['What is Kafka Streams?', 'Library for stream processing on top of Kafka—state stores interactive queries.'],
      ['What is KStream vs KTable?', 'Record stream vs changelog table—dual semantics important.'],
      ['What is stateful processing?', 'Aggregates joins need RocksDB state stores changelog topics.'],
      ['What is windowing?', 'Tumbling hopping sliding time windows—event time processing.'],
      ['What is punctuator?', 'Periodic processing wall-clock time—watermarks advanced.'],
      ['What is repartition topic?', 'Kafka Streams internal repartition for key changes—hidden topics.'],
      ['What is exactly-once in Streams?', 'processing.guarantee exactly_once_v2—EOS config.'],
      ['What is interactive queries?', 'Query local state stores from app—embedding serving layer.'],
      ['What is changelog compaction state?', 'Restore state on restart—size retention tuning.'],
      ['What is join stream-stream windowed?', 'Both sides within window—time synchronization critical.'],
      ['What is processor API lower level?', 'Transform punctuate custom—advanced.'],
      ['What is DSL vs Processor API trade-off?', 'DSL concise; Processor flexible harder test.'],
      ['What is standby replicas?', 'Kafka Streams fault tolerance—state sync.'],
      ['What is consumer lag in streams tasks?', 'Task stuck processing poison—dead-letter strategies.'],
      ['What is migration from batch ETL?', 'Incremental stream processing lower latency—operational shift.'],
    ],
    codeBased: [
      ['StreamsBuilder stream topics groupBy count', 'Word count classic.'],
      ['Materialized as store name', 'State store naming.'],
      ['toStream to topic output', 'Sink.'],
      ['GroupedStream reduce aggregator', 'Custom agg.'],
      ['TimeWindows of Duration.ofMinutes(5)', 'Tumbling example.'],
      ['join windowed streams', 'Inner join windows.'],
      ['suppress untilWindowCloses', 'Emit after window close.'],
      ['KafkaStreams start close', 'Lifecycle.'],
      ['Topology describe', 'Debug topology graph.'],
      ['stateDir configure location', 'Disk sizing.'],
    ],
    seniorScenario: [
      ['RocksDB disk full streams crash?', 'Monitor disk state store size retention changelog compaction.'],
      ['Reprocessing historical data streams job?', 'Reset offsets carefully duplicate side effects idempotent sinks.'],
      ['Event time vs processing time skew?', 'Late data windows incomplete—watermark strategies.'],
      ['Interactive queries consistency?', 'Eventually consistent across instances—cache coherence issues.'],
      ['Upgrade Kafka Streams version incompatible state?', 'Migration tooling backup plan—risky.'],
      ['Complex join business logic in streams vs external DB?', 'Maintainability trade-off team skills.'],
    ],
    wrongAnswers: [
      'Kafka Streams requires a separate Spark cluster.',
      'KTable and KStream are identical concepts.',
      'State stores are stored only in memory never on disk.',
      'Kafka Streams cannot join streams.',
      'Windowing is only possible with processing time.',
      'Exactly-once in Streams requires no configuration.',
    ],
  },

  64: {
    conceptual: [
      ['What is Schema Registry?', 'Central store for Avro/Protobuf/JSON schemas with compatibility rules.'],
      ['What is subject naming strategies?', 'TopicNameStrategy RecordNameStrategy TopicRecordNameStrategy—field evolution impact.'],
      ['What is backward compatibility?', 'New schema can read data written by old schema—consumers upgrade first typical.'],
      ['What is forward compatibility?', 'Old schema can read data written by new—less common pattern.'],
      ['What is full compatibility?', 'Both directions—strictest.'],
      ['What is Kafka Connect?', 'Framework connectors source/sink systems—configurable scalable.'],
      ['What is SMT single message transforms?', 'Tweak records in flight—mask fields rename—careful complexity.'],
      ['What is Debezium CDC connector?', 'Stream DB changes to Kafka—outbox alternative capture.'],
      ['What is dead letter queue in Connect?', 'Failed records route DLQ—replay tooling.'],
      ['What is connector task parallelism?', 'Tasks scale partitions—ordering per partition preserved.'],
      ['What is schema id in wire format?', 'Confluent wire format 0x0 magic byte schema id payload—efficient registry lookup.'],
      ['What is protobuf vs avro in registry?', 'Both supported—tooling differences codegen.'],
      ['What is connector offset management?', 'Exactly-once sink tricky—idempotent writes upsert.'],
      ['What is self-managed registry HA?', 'Clustered registry deployment backup—critical dependency.'],
      ['What is governance approval workflow?', 'Schema evolution PR reviews automated compatibility tests CI.'],
    ],
    codeBased: [
      ['curl schema registry POST /subjects/.../versions', 'Register schema REST.'],
      ['Avro GenericRecord vs SpecificRecord', 'Codegen vs dynamic.'],
      ['KafkaAvroSerializer with registry url', 'Producer config.'],
      ['Connector config key.converter value.converter', 'Serialization stack.'],
      ['Debezium sourceConnector table include list', 'Config snippet.'],
      ['ReplaceField SMT example', 'Transform chain.'],
      ['compatibility BACKWARD config subject', 'Registry setting.'],
      ['Wire format byte magic schemaId', 'Understanding decoding.'],
      ['REST get /schemas/ids/1', 'Fetch schema by id.'],
      ['Maven avro-maven-plugin generate', 'Build integration.'],
    ],
    seniorScenario: [
      ['Registry outage producers fail?', 'Cache schemas local resilience modes degrade carefully.'],
      ['Breaking schema deployed production?', 'Rollback consumers producers coordination freeze fixes.'],
      ['PII in schema evolution masking?', 'SMT redaction field-level security—compliance.'],
      ['Connect connector zombie tasks?', 'Monitoring task failure restart backoff stuck.'],
      ['Multi-tenant schema namespaces?', 'Subject naming isolation governance policies.'],
      ['Cost of registry HA infrastructure?', 'Business critical dependency—SRE ownership.'],
    ],
    wrongAnswers: [
      'Schema Registry is optional because JSON is self-describing enough.',
      'Backward compatibility means old consumers can read data produced by new schemas in all cases without rules.',
      'Kafka Connect only supports reading from Kafka, not writing to databases.',
      'Avro and JSON Schema cannot be stored in the same registry.',
      'SMTs should contain all business logic.',
      'Schema IDs are random UUIDs on every message.',
    ],
  },

  65: {
    conceptual: [
      ['What is Spring Kafka?', 'Spring integration KafkaTemplate listeners container factories—idiomatic Spring.'],
      ['What is KafkaTemplate send?', 'Producer wrapper with sync async ListenableFuture.'],
      ['What is @KafkaListener?', 'Annotation-driven consumer method—container underneath.'],
      ['What is ConcurrentMessageListenerContainer?', 'Multiple consumer threads—scale within JVM.'],
      ['What is ChainedKafkaTransactionManager legacy?', 'Kafka + DB transaction bridging—deprecated patterns careful.'],
      ['What is @Transactional Kafka producer spring?', 'KafkaTransactionManager synchronize with DB—advanced EOS.'],
      ['What is DeadLetterPublishingRecoverer?', 'Send failed records to DLT topic—Spring Retry.'],
      ['What is ErrorHandler vs DefaultErrorHandler?', 'Seek behavior classification recoverable fatal—Spring Kafka 2.8+.'],
      ['What is RecordInterceptor?', 'Mutate records before listener—headers enrichment.'],
      ['What is batch listener?', 'Receive List ConsumerRecords—higher throughput careful commits.'],
      ['What is Micrometer Kafka metrics?', 'Spring Boot auto metrics—bind to Prometheus.'],
      ['What is EmbeddedKafka for tests?', 'In-memory broker tests—Testcontainers alternative more realistic.'],
      ['What is KafkaAdmin bean?', 'Declarative topic creation NewTopic beans.'],
      ['What is ProducerListener callback?', 'Observe success failure send metrics.'],
      ['What is spring.kafka.ssl configuration?', 'Security protocol SASL_SSL truststore keystore production.'],
    ],
    codeBased: [
      ['kafkaTemplate.send("topic", key, value).get()', 'Sync wait.'],
      ['@KafkaListener topics = "orders" groupId', 'Listener basics.'],
      ['ConcurrentKafkaListenerContainerFactory setConcurrency', 'Threads per listener.'],
      ['@RetryableTopic attempts = 3 dltStrategy', 'Retry DLT Spring Kafka.'],
      ['SeekToCurrentErrorHandler classifier', 'Retry only certain exceptions.'],
      ['NewTopic bean replicas partitions', 'Topic creation.'],
      ['ConsumerFactory configs deserializer error handler', 'Deserialization resilience.'],
      ['@KafkaHandler class-level @KafkaListener', 'Multi method routing.'],
      ['KafkaTransactionManager bean EOS', 'Transactional producer sync DB.'],
      ['Test @EmbeddedKafka topics', 'Slice integration test.'],
    ],
    seniorScenario: [
      ['Spring Kafka upgrade breaking ErrorHandler behavior?', 'Read migration guide seek semantics classification.'],
      ['Transactional Kafka + DB same transaction pitfalls?', 'XA rare; outbox often simpler—understand boundaries.'],
      ['Listener throws exception infinite retry loop?', 'Backoff max attempts DLQ alert ops.'],
      ['High lag container paused processing bug?', 'Thread pool saturation backpressure design.'],
      ['Serialization poison message stuck partition?', 'Skip to DLQ with classifier monitoring.'],
      ['Multi-cluster Kafka Spring config?', 'Multiple factories templates—complexity isolation.'],
    ],
    wrongAnswers: [
      '@KafkaListener works without a ConsumerFactory bean.',
      'Spring Kafka guarantees exactly-once end-to-end with default settings.',
      'KafkaTemplate only supports synchronous sends.',
      'EmbeddedKafka is recommended for production smoke tests in clusters.',
      'DeadLetterPublishingRecoverer always deletes the original message.',
      'Spring Kafka replaces the need for native Kafka clients entirely.',
    ],
  },
};
