/** Interview Drill — Days 66–90 (15 / 10 / 6 / 6) */

export const B_66_90 = {
  66: {
    conceptual: [
      ['What is RabbitMQ model?', 'Producers publish to exchanges; routes to queues via bindings; consumers pull ack.'],
      ['What is AMQP 0-9-1?', 'Protocol RabbitMQ implements—queues durable exclusive auto-delete properties.'],
      ['What is exchange types direct topic fanout headers?', 'Routing strategies—topic wildcards useful.'],
      ['What is acknowledgment modes?', 'Auto ack vs manual—reliability trade-off message loss vs duplicate.'],
      ['What is prefetch count?', 'Consumer prefetch limits unacked messages—backpressure fairness.'],
      ['What is dead letter exchange?', 'Route failed messages after retries—inspection requeue.'],
      ['What is TTL on messages or queues?', 'Expire messages—time-sensitive tasks.'],
      ['What is priority queue?', 'Priority property limited support—ordering caveats.'],
      ['What is quorum queues RabbitMQ 3.8+?', 'Replicated queues safer—classic mirrored queues legacy.'],
      ['What is AWS SQS?', 'Managed queue service—visibility timeout at-least-once—different semantics than Rabbit.'],
      ['What is SNS fan-out?', 'Pub/sub push to many SQS—integration pattern.'],
      ['What is FIFO SQS?', 'Ordering dedupe—throughput limits—exactly-once-ish with dedupe window.'],
      ['What is Kinesis vs Kafka?', 'Managed streams AWS—different operational model.'],
      ['What is message size limits?', 'SQS 256KB Rabbit large messages disk—design chunking reference storage.'],
      ['What is cross-cloud messaging?', 'VPN private links security costs—architecture constraints.'],
    ],
    codeBased: [
      ['RabbitTemplate convertAndSend', 'Spring AMQP send.'],
      ['@RabbitListener queues', 'Listener method.'],
      ['Queue durable exclusive autoDelete builder', 'Declare queue.'],
      ['TopicExchange binding routing key pattern', 'Topic routing.'],
      ['Manual ack channel.basicAck deliveryTag multiple', 'Low-level ack.'],
      ['SQS ReceiveMessage waitTimeSeconds long poll', 'AWS API.'],
      ['SNS publish TopicArn Message', 'Fan-out.'],
      ['VisibilityTimeout change inflight', 'SQS tuning.'],
      ['DeadLetterPolicy redrive policy', 'AWS DLQ config.'],
      ['RabbitMQ federation shovel plugin', 'Bridge brokers—advanced.'],
    ],
    seniorScenario: [
      ['Rabbit cluster split brain messages duplicated?', 'Design idempotent consumers federation carefully.'],
      ['SQS poison message loop?', 'DLQ maxReceiveCount alarm replay tooling.'],
      ['Cost SQS at scale?', 'Per request pricing batching long poll efficiency.'],
      ['On-prem Rabbit to cloud migration?', 'Dual write bridge gradual cutover monitoring.'],
      ['Ordering guarantees Rabbit single queue?', 'Single consumer ordering; multiple consumers interleaved.'],
      ['Compliance message encryption KMS?', 'SQS SSE KMS policies rotation.'],
    ],
    wrongAnswers: [
      'RabbitMQ and Kafka are identical log-based systems.',
      'SQS guarantees exactly-once delivery always.',
      'Auto acknowledgment is the safest choice for payments.',
      'FIFO SQS has unlimited throughput.',
      'AMQP and MQTT are the same protocol.',
      'Dead letter queues automatically fix bad messages.',
    ],
  },

  67: {
    conceptual: [
      ['What is CAP theorem?', 'Consistency Availability Partition tolerance—during partition must choose CP or AP trade-off.'],
      ['What is linearizability?', 'Strong consistency model operations appear atomic instant—hard distributed.'],
      ['What is eventual consistency?', 'Replicas converge later—acceptable many systems with UX handling staleness.'],
      ['What is quorum reads writes?', 'R+W > N ensures overlap—tunable consistency latency.'],
      ['What is vector clocks?', 'Detect concurrent updates causal ordering—Dynamo style.'],
      ['What is Lamport logical clocks?', 'Partial ordering events without physical clock sync.'],
      ['What is FLP impossibility?', 'No deterministic consensus in async network with one faulty process—foundational.'],
      ['What is Paxos Raft?', 'Consensus algorithms leader election log replication—etcd Raft.'],
      ['What is Byzantine failures?', 'Malicious nodes—blockchain concerns—different from crash faults.'],
      ['What is gossip protocol?', 'Epidemic dissemination membership info—scalable but eventual.'],
      ['What is split brain cluster?', 'Two partitions both think primary—data divergence dangerous—fencing tokens.'],
      ['What is lease vs lock?', 'Time-bounded lock reduce stuck forever—clock skew risks.'],
      ['What is hinted handoff?', 'Temporary responsibility during failures—Dynamo technique.'],
      ['What is read repair?', 'Read triggers reconciliation replicas—anti-entropy.'],
      ['What is Merkle trees?', 'Compare replica data efficiently—Cassandra repair.'],
    ],
    codeBased: [
      ['Etcd raft election term', 'Conceptual leadership.'],
      ['Cassandra QUORUM read write CL', 'Consistency level tuning.'],
      ['Redis SETNX expire lease lock', 'Distributed lock sketch—Redlock controversy.'],
      ['Compare-and-swap optimistic concurrency', 'ETag HTTP If-Match.'],
      ['Hazelcast partition map near-cache', 'Data grid concepts.'],
      ['Zookeeper ephemeral sequential nodes leader election', 'Pattern description.'],
      ['Vector clock merge function', 'Pick max per node increment own.'],
      ['Bloom filter membership false positives', 'Probabilistic structures.'],
      ['CRDT grow-only counter', 'Conflict-free replicated data type basics.'],
      ['Spanner TrueTime external clock uncertainty', 'Google distributed DB concept.'],
    ],
    seniorScenario: [
      ['Outage split brain two primaries writes?', 'STONITH fencing durable storage epoch tokens—operations nightmare.'],
      ['“Strong consistency” marketing vs reality?', 'Clarify model linearizable serializable session causal—precise language.'],
      ['Global clock sync across regions impossible?', 'TrueTime bounded uncertainty engineering trade-offs.'],
      ['Blockchain for internal ledger hype?', 'Usually overkill CRDT or SQL sufficient—cost.'],
      ['Testing distributed systems failures?', 'Jepsen chaos frameworks partition injection.'],
      ['SLA 99.999% requires formal methods?', 'Often extensive testing redundancy—not only math.'],
    ],
    wrongAnswers: [
      'CAP says you can have all three in practice always.',
      'Eventual consistency means data is never consistent.',
      'Raft and Paxos are unrelated to distributed consensus.',
      'Vector clocks give total order of all events in the system automatically.',
      'Byzantine fault tolerance is required for all cloud databases.',
      'Quorum reads always guarantee the latest write immediately.',
    ],
  },

  68: {
    conceptual: [
      ['What is SQL JOIN types?', 'INNER LEFT RIGHT FULL CROSS—different result shapes null padding.'],
      ['What is index clustered vs non-clustered?', 'Table order vs separate structure—PK often clustered SQL Server specifics vary.'],
      ['What is covering index?', 'Index includes all columns needed—avoid table lookup—INCLUDE columns SQL Server.'],
      ['What is query plan?', 'Optimizer chooses join order index seeks scans—EXPLAIN ANALYZE.'],
      ['What is N+1 in ORM?', 'Already covered—SQL batching joins fetch strategies.'],
      ['What is window functions ROW_NUMBER RANK?', 'Analytics without self-join explosion—PARTITION BY ORDER BY.'],
      ['What is CTE WITH clause?', 'Readable subqueries; optimization varies by DB—materialization hints.'],
      ['What is recursive CTE?', 'Hierarchical queries org charts—watch cycles termination.'],
      ['What is EXPLAIN plans cardinality estimates?', 'Wrong stats cause bad plans—ANALYZE update stats.'],
      ['What is isolation level phenomena?', 'Dirty read non-repeatable read phantom—ANSI SQL definitions.'],
      ['What is MVCC?', 'Multi-version concurrency control—Postgres Oracle style snapshots readers don’t block writers.'],
      ['What is partitioning tables?', 'Range hash list partitions—pruning queries maintenance trade-offs.'],
      ['What is columnar analytics?', 'OLAP column stores compression vectorized execution—different from row OLTP.'],
      ['What is slow query log?', 'Identify bad queries threshold—continuous profiling.'],
      ['What is SQL injection prevention?', 'Prepared statements parameter binding—never string concat user input.'],
    ],
    codeBased: [
      ['SELECT ... FOR UPDATE SKIP LOCKED', 'Queue job claiming pattern.'],
      ['Window function ROW_NUMBER PARTITION BY user_id', 'Dedup latest row per user.'],
      ['LEFT JOIN ON ... WHERE right.id IS NULL anti-join', 'Find missing.'],
      ['EXPLAIN ANALYZE SELECT', 'Postgres profiling.'],
      ['CREATE INDEX CONCURRENTLY', 'Postgres non-blocking index build.'],
      ['MERGE upsert dialect specific', 'SQL Server Postgres ON CONFLICT.'],
      ['Recursive WITH tree org', 'Manager hierarchy.'],
      ['COUNT FILTER WHERE condition', 'Conditional aggregation.'],
      ['LATERAL join Postgres', 'Per-row subquery correlated efficient.'],
      ['JSON functions JSON_EXTRACT MySQL dialect', 'JSON in SQL—portability caution.'],
    ],
    seniorScenario: [
      ['DB CPU 100% after deploy—check?', 'New query missing index plan regression cardinality estimate.'],
      ['Long transaction locks entire table?', 'Reduce scope index lock escalation patterns vary DB.'],
      ['Read replica lag analytics wrong dashboard?', 'Monitor replication lag route critical reads to primary.'],
      ['Sharding SQL monolith to horizontal shards?', 'Cross-shard joins painful—application aggregation.'],
      ['PII in logs SQL queries?', 'Redact parameter binding logging configuration.'],
      ['Vendor lock-in stored procedures?', 'Portability team skills—consider domain layer abstraction.'],
    ],
    wrongAnswers: [
      'Indexes always make every query faster.',
      'SELECT * is always the best practice for maintainability.',
      'LEFT JOIN and INNER JOIN are identical when columns match.',
      'Transactions are not needed for single-row updates.',
      'EXPLAIN output is identical across PostgreSQL, MySQL, and Oracle.',
      'Window functions require a GROUP BY in the same query always.',
    ],
  },

  69: {
    conceptual: [
      ['What is JDBC connection pooling?', 'Reuse TCP connections to DB—avoid per-request connect overhead.'],
      ['What is HikariCP tuning?', 'maximumPoolSize minimumIdle connectionTimeout leakDetectionThreshold—align with DB max connections.'],
      ['What is transaction isolation default?', 'Often READ_COMMITTED varies—explicit when needed REPEATABLE_READ financial.'],
      ['What is connection validation query?', 'Test connection alive on checkout—SELECT 1—small overhead.'],
      ['What is prepared statement cache?', 'Server-side parse cache—reuse plans—security performance.'],
      ['What is JDBC batch updates?', 'addBatch executeBatch reduce round trips—bulk inserts.'],
      ['What is fetch size cursor streaming?', 'Avoid loading huge ResultSet memory—setFetchSize hints.'],
      ['What is read-only transaction routing?', 'Route to replica—lag awareness—Spring @Transactional readOnly routing.'],
      ['What is XA datasource?', 'Distributed two-phase commit—avoid complexity if possible.'],
      ['What is connection leak?', 'Forgot close in finally—pool exhaustion—metrics.'],
      ['What is RDS proxy?', 'AWS connection multiplexing reduce DB connection storms—serverless scaling.'],
      ['What is pgbouncer?', 'Postgres connection pooler transaction vs session pooling modes implications.'],
      ['What is statement timeout?', 'Cancel long queries—set at JDBC driver session.'],
      ['What is deadlock detection DB?', 'Automatic victim rollback—retry idempotent transactions.'],
      ['What is connection storm on cold start?', 'Lambdas scaling—RDS Proxy pool sizing—caution.'],
    ],
    codeBased: [
      ['DataSource getConnection try finally close', 'Classic JDBC pattern use try-with-resources.'],
      ['PreparedStatement setString parameter index', 'Bind values.'],
      ['setAutoCommit false commit rollback', 'Manual transaction JDBC.'],
      ['@Transactional Spring on service DataSourceTransactionManager', 'Declarative vs programmatic.'],
      ['HikariConfig setMaximumPoolSize', 'Programmatic config.'],
      ['JdbcTemplate batchUpdate', 'Spring JDBC batch.'],
      ['NamedParameterJdbcTemplate', 'Named params safer readability.'],
      ['@Transactional readOnly routing AbstractRoutingDataSource', 'Replica read pattern.'],
      ['SET TRANSACTION ISOLATION LEVEL', 'Session isolation JDBC.'],
      ['Connection.isValid timeout', 'Validation API JDBC4.'],
    ],
    seniorScenario: [
      ['Pool exhausted alerts nights batch jobs?', 'Separate pool batch vs online adjust sizes.'],
      ['DB max connections reached microservices?', 'Math instances pool size < DB max aggregate—coordination.'],
      ['Long running report JDBC connection held?', 'Separate read-only replica bigger statement timeout streaming.'],
      ['Cloud Aurora failover connections dropped?', 'Retry transient errors application side Hikari suspend.'],
      ['Secrets rotation RDS credentials pool?', 'Refresh datasource beans dynamic—complex.'],
      ['Serverless RDS Data API vs JDBC?', 'HTTP stateless different latency trade-offs.'],
    ],
    wrongAnswers: [
      'Connection pools create a new TCP connection for every SQL statement.',
      'HikariCP maximumPoolSize should always equal the number of CPU cores.',
      'readOnly=true on JDBC prevents any database write including temp tables.',
      'Prepared statements are mainly for security, not performance.',
      'You should never set a maximum lifetime on pooled connections.',
      'XA transactions are free and recommended for all microservices.',
    ],
  },

  70: {
    conceptual: [
      ['What is MongoDB document model?', 'BSON JSON-like nested documents arrays—flexible schema.'],
      ['What is Cassandra wide column?', 'Partition key clustering key—query patterns must match design—no ad hoc joins.'],
      ['What is eventual consistency Cassandra?', 'Tunable ONE QUORUM ALL—latency vs consistency per query.'],
      ['What is MongoDB replica set?', 'Primary secondary elections failover—write concern read concern.'],
      ['What is sharding MongoDB?', 'Shard key choice hot shard problem—hard to change later.'],
      ['What is aggregation pipeline?', 'Multi-stage transformations $match $group—server-side compute.'],
      ['What is Cassandra compaction strategies?', 'SizeTiered Leveled TimeWindow—disk IO trade-offs.'],
      ['What is tombstones Cassandra?', 'Deletes are inserts of deletion markers—compaction lag disk issues.'],
      ['What is MongoDB transactions multi-document?', 'Since 4.0—performance overhead compared to single doc atomicity.'],
      ['What is index types Mongo?', 'Single compound multikey text geospatial—choose wisely.'],
      ['What is CQL vs SQL?', 'Cassandra query language limited joins—denormalize application side.'],
      ['What is DynamoDB partition sort key?', 'AWS managed key-value + sort—similar access patterns design.'],
      ['What is TTL index Mongo?', 'Automatic document expiry—session caches ephemeral data.'],
      ['What is change streams Mongo?', 'Oplog tailing reactive updates—CDC-like.'],
      ['What is anti-pattern relational modeling in document DB?', 'Deep joins emulated—wrong tool—use SQL or redesign.'],
    ],
    codeBased: [
      ['db.collection.find({status:"A"}).sort({date:-1})', 'Mongo query example.'],
      ['updateMany filter update upsert', 'Bulk updates.'],
      ['aggregate pipeline $group $sum', 'Aggregation example.'],
      ['createIndex compound fields', 'Indexing command.'],
      ['Cassandra SELECT WHERE partition key', 'Must include partition key equality.'],
      ['INSERT INTO table JSON', 'Cassandra insert.'],
      ['Mongo transaction session startTransaction', 'Multi-doc tx.'],
      ['DynamoDB Query KeyConditionExpression', 'AWS API pattern.'],
      ['MongoDB BSON ObjectId generation', 'Time-ordered ids roughly.'],
      ['Cassandra BATCH logged unlogged', 'Atomicity partition scope.'],
    ],
    seniorScenario: [
      ['Hot partition DynamoDB throttling?', 'Shard key redesign write sharding bursts—on-demand vs provisioned.'],
      ['MongoDB global write lock myth legacy?', 'WiredTiger document-level concurrency—still design matters.'],
      ['Cassandra repair operations ops burden?', 'Incremental repair scheduling cluster load—SRE time sink.'],
      ['MongoDB schema evolution migrations?', 'Tools Mongock—discipline similar SQL Flyway mindset.'],
      ['Cost athena query doc store wrong tool?', 'Use columnar warehouse analytics—architecture review.'],
      ['GDPR delete distributed NoSQL?', 'Tombstones TTL eventual—verify compliance latency.'],
    ],
    wrongAnswers: [
      'MongoDB is always schemaless so validation is impossible.',
      'Cassandra supports arbitrary JOINs like PostgreSQL.',
      'DynamoDB automatically shards perfectly without any design.',
      'NoSQL means you never need indexes.',
      'MongoDB ObjectIds are guaranteed globally unique across all universes forever.',
      'Cassandra tombstones improve read performance immediately.',
    ],
  },

  71: {
    conceptual: [
      ['What is Redis in-memory data structure server?', 'Strings lists sets sorted sets hashes streams—sub-ms latency.'],
      ['What is cache-aside pattern?', 'App loads DB on miss populates cache—stale data TTL invalidation.'],
      ['What is write-through vs write-behind?', 'Write synchronously to cache+DB vs async queue—consistency trade-offs.'],
      ['What is TTL eviction?', 'Expire keys—memory protection—sliding vs absolute expiration.'],
      ['What is LRU eviction when memory full?', 'Approximate LRU—tunable maxmemory-policy.'],
      ['What is Redis single-threaded model?', 'One thread commands—CPU bound single core—scale sharding.'],
      ['What is Redis Cluster?', 'Sharding hash slots 16384—multi-master—failover replicas.'],
      ['What is pub/sub Redis?', 'Fire-and-forget messaging—no persistence—different from streams.'],
      ['What is Redis Streams?', 'Log-like consumer groups approximate Kafka use cases smaller scale.'],
      ['What is distributed lock Redlock?', 'Controversial algorithm—prefer lease fencing tokens DB consensus.'],
      ['What is cache stampede thundering herd?', 'Many requests miss cache simultaneously—single-flight protection early recompute.'],
      ['What is probabilistic early expiration?', 'Jitter TTL spread expirations—smooth load.'],
      ['What is Memcached vs Redis?', 'Simple key-value vs rich structures persistence optional—choose per workload.'],
      ['What is Spring Cache abstraction?', '@Cacheable Redis backend—AOP proxy limits self-invocation same issue.'],
      ['What is Redis persistence RDB AOF?', 'Snapshots vs append log—durability recovery trade-offs.'],
    ],
    codeBased: [
      ['SET key value EX 300 NX', 'Set if not exists with TTL lock pattern.'],
      ['GET SET INCR DECR', 'Atomic counters.'],
      ['ZADD leaderboard score member ZRANGE', 'Sorted set ranking.'],
      ['HSET user:1 name email', 'Hash fields.'],
      ['EVAL lua script atomic', 'Server-side scripting complex ops.'],
      ['RedisTemplate opsForValue setIfAbsent Spring', 'Distributed lock attempt.'],
      ['@Cacheable cacheNames key', 'Spring caching.'],
      ['Lettuce reactive Redis reactive API', 'Non-blocking client.'],
      ['SCAN cursor match pattern', 'Iterate keys production not KEYS *'],
      ['Pipeline batch commands', 'Reduce round trips.'],
    ],
    seniorScenario: [
      ['Redis memory full eviction lost sessions?', 'Monitor memory alerts persistence strategy volatile-lru policies.'],
      ['Cache inconsistency DB updated cache not?', 'TTL short write-through events eventual—choose strategy.'],
      ['Redis single-thread hot key?', 'Shard key app-level multi-key hot spot—CPU maxed.'],
      ['Elasticache failover client behavior?', 'Reconnect cluster mode discover topology—test resilience.'],
      ['Secrets in Redis unencrypted?', 'TLS in transit encryption at rest compliance—ACL users Redis 6.'],
      ['Rate limiting Redis INCR sliding window?', 'Design edge cases race conditions Lua scripts atomic.'],
    ],
    wrongAnswers: [
      'Redis is a relational database.',
      'Redis Cluster provides ACID transactions across all shards for all commands.',
      'KEYS * is safe to run in production anytime.',
      'Pub/sub guarantees message persistence.',
      'Memcached supports rich data structures like sorted sets natively.',
      'Cache-aside means the database writes to the cache first always.',
    ],
  },

  72: {
    conceptual: [
      ['What is Docker container?', 'Packaged app dependencies isolated process namespaces—not full VM.'],
      ['What is image vs container?', 'Immutable template vs running instance—layers union filesystem.'],
      ['What is Dockerfile instructions?', 'FROM RUN COPY CMD ENTRYPOINT—build recipe cache layers order matters.'],
      ['What is multi-stage build?', 'Build stage JDK compile runtime JRE slim—smaller attack surface.'],
      ['What is .dockerignore?', 'Exclude files from context—faster build smaller context.'],
      ['What is container registry?', 'ECR Docker Hub—image storage scanning signing SBOM.'],
      ['What is JVM in container cgroup awareness?', 'Use -XX:MaxRAMPercentage—avoid heap larger than cgroup limit OOMKill.'],
      ['What is distroless images?', 'Minimal runtime no shell—security smaller—harder debug.'],
      ['What is rootless containers?', 'Non-root user inside image—security best practice.'],
      ['What is BuildKit cache mounts?', 'Faster Maven Gradle builds—persistent cache mounts.'],
      ['What is docker compose?', 'Local multi-container orchestration dev parity—not production cluster replacement.'],
      ['What is image layer caching order?', 'Put less frequently changing layers earlier COPY pom before source.'],
      ['What is healthcheck Dockerfile?', 'Container health for orchestrators—different from app readiness.'],
      ['What is SBOM software bill materials?', 'Dependency transparency security audits—supply chain.'],
      ['What is Cosign sign images?', 'Verify image integrity—prevent tampering.'],
    ],
    codeBased: [
      ['FROM eclipse-temurin:17-jre', 'Base image.'],
      ['COPY target/app.jar /app.jar', 'Fat jar deploy.'],
      ['ENTRYPOINT java -jar /app.jar', 'Start command.'],
      ['USER 1000 nonroot', 'Security.'],
      ['HEALTHCHECK CMD curl', 'Liveness style—curl may be missing in distroless use wget alternative.'],
      ['docker build -t myapp:1 .', 'Build command.'],
      ['multi-stage FROM maven AS build', 'Build stage.'],
      ['--mount=type=cache,target=/root/.m2', 'BuildKit maven cache.'],
      ['JAVA_TOOL_OPTIONS env', 'Flags injection.'],
      ['docker run -e JAVA_OPTS', 'Runtime tuning.'],
    ],
    seniorScenario: [
      ['Container OOMKilled but JVM heap ok?', 'Check native memory direct buffers thread stacks metaspace.'],
      ['Image CVE critical base image outdated?', 'Renovate bot automated PRs scanning pipelines.'],
      ['Fat jar slow startup layered jars Spring Boot?', 'Extract layers docker build cache efficiency.'],
      ['PID 1 zombie processes Java?', 'Use tini init wrapper signal handling—though Java ok often.'],
      ['Docker compose prod misuse?', 'Not HA rolling updates—Kubernetes proper orchestration.'],
      ['Build context huge slow CI?', 'dockerignore monorepo selective context git sparse?'],
    ],
    wrongAnswers: [
      'Containers include a full guest operating system kernel per container.',
      'Dockerfile RUN order does not affect layer caching.',
      'You should always run JVM as root inside containers for performance.',
      'A .dockerignore file increases build context size.',
      'JVM automatically detects cgroup limits in all Java versions without flags.',
      'Multi-stage builds always produce larger final images.',
    ],
  },

  73: {
    conceptual: [
      ['What is Kubernetes Pod?', 'Smallest deployable unit one or more containers sharing network storage namespaces.'],
      ['What is Deployment?', 'Desired replicas rolling updates rollbacks—ReplicaSet underneath.'],
      ['What is Service ClusterIP?', 'Stable virtual IP load balance pods selectors—service discovery.'],
      ['What is Ingress?', 'HTTP routing TLS termination—ingress controller required.'],
      ['What is ConfigMap Secret?', 'Configuration injection env volume—secrets base64 not encryption at rest default.'],
      ['What is liveness vs readiness probe?', 'Restart unhealthy vs remove from Service endpoints—different purposes critical.'],
      ['What is resource requests limits?', 'CPU memory QoS scheduling OOMKill throttling—set properly.'],
      ['What is HorizontalPodAutoscaler?', 'Scale replicas based on CPU custom metrics—not magic fix.'],
      ['What is Namespace?', 'Isolation quotas rbac multi-tenancy soft—not strong security boundary alone.'],
      ['What is StatefulSet?', 'Stable identity persistent volumes ordered deployment—databases cautiously.'],
      ['What is DaemonSet?', 'One pod per node—logging monitoring agents.'],
      ['What is Job CronJob?', 'Batch workloads schedules—retry backoff.'],
      ['What is kubelet?', 'Node agent ensures pods running—heartbeats.'],
      ['What is etcd?', 'Kubernetes control plane datastore—Raft consensus backups critical.'],
      ['What is CNI network plugin?', 'Calico Cilium pod networking policies—security.'],
    ],
    codeBased: [
      ['kubectl get pods -n prod', 'Basic command.'],
      ['deployment.yaml replicas image resources', 'Manifest sketch.'],
      ['livenessProbe httpGet path /actuator/health', 'Spring Boot health.'],
      ['readinessProbe failureThreshold', 'Tune startup slow apps.'],
      ['HorizontalPodAutoscaler targetCPUUtilization', 'Autoscaling config.'],
      ['ConfigMap volumeMount', 'Mount properties file.'],
      ['Secret envFrom secretRef', 'Inject secrets env.'],
      ['Ingress host path backend service port', 'Routing rules.'],
      ['kubectl logs -f pod', 'Debugging.'],
      ['kubectl describe pod events', 'Scheduling failures.'],
    ],
    seniorScenario: [
      ['Pod CrashLoopBackOff Java OOMKilled?', 'Tune heap limits requests JVM cgroup awareness.'],
      ['Ingress 502 backend not ready?', 'Readiness failing service selector mismatch network policy.'],
      ['Cluster upgrade etcd backup?', 'Disaster recovery plan tested restores—production incident learned.'],
      ['Multi-tenant namespace isolation blast radius?', 'NetworkPolicy RBAC quotas—not VM isolation.'],
      ['StatefulSet DB operators complexity?', 'Use managed DB often simpler—Kubernetes not always best home.'],
      ['Cost unbounded HPA max replicas?', 'Set max reasonable budget alerts.'],
    ],
    wrongAnswers: [
      'A Pod always maps 1:1 to a physical machine.',
      'Readiness probe failure always restarts the container.',
      'Secrets are encrypted by default in etcd without any configuration.',
      'Services provide stable DNS names for pods.',
      'Kubernetes replaces the need for load balancers outside the cluster.',
      'HorizontalPodAutoscaler scales nodes automatically in all clusters without Cluster Autoscaler.',
    ],
  },

  74: {
    conceptual: [
      ['What is Helm chart?', 'Packaged Kubernetes manifests templated values—release management.'],
      ['What is values.yaml?', 'Default configuration overrides per environment—gitops friendly.'],
      ['What is release upgrade rollback?', 'helm upgrade --install history rollback—track revisions.'],
      ['What is chart dependencies?', 'Subcharts umbrella charts—version pinning important.'],
      ['What is hook pre-install?', 'Job runs before resources—db migrations carefully ordering.'],
      ['What is Kustomize vs Helm?', 'Overlay patches vs templating—different philosophies sometimes combined.'],
      ['What is GitOps ArgoCD Flux?', 'Declarative continuous deployment reconcile cluster desired state git.'],
      ['What is sealed secrets?', 'Encrypt secrets commit git safely—controller decrypt cluster.'],
      ['What is progressive delivery Flagger?', 'Canary analysis metrics promotion automated—mesh integration.'],
      ['What is pod disruption budget?', 'Limit voluntary disruptions during node drains—availability guard.'],
      ['What is cluster autoscaling?', 'Add remove nodes based on pending pods—cost performance trade-off.'],
      ['What is taints tolerations?', 'Dedicated nodes GPU workloads—scheduling constraints.'],
      ['What is priority classes?', 'Preemption scheduling critical workloads—careful starvation.'],
      ['What is admission controllers?', 'Validate mutate requests—OPA Gatekeeper policies security.'],
      ['What is multi-cluster federation?', 'Higher complexity—disaster recovery active-active rare—network latency.'],
    ],
    codeBased: [
      ['helm install myapp ./chart -f values-prod.yaml', 'Install command.'],
      ['helm template . --debug', 'Render locally.'],
      ['{{ .Values.replicaCount }}', 'Helm templating.'],
      ['kustomize build overlays/prod', 'Kustomize build.'],
      ['ArgoCD Application spec source repo path', 'GitOps manifest.'],
      ['kubectl rollout undo deployment', 'Rollback native.'],
      ['PodDisruptionBudget minAvailable', 'PDB example.'],
      ['ClusterIssuer cert-manager ACME', 'TLS automation.'],
      ['HorizontalPodAutoscaler behavior scaleDown stabilizationWindowSeconds', 'HPA tuning.'],
      ['helm test release hooks', 'Chart tests.'],
    ],
    seniorScenario: [
      ['Helm upgrade failed partial state?', 'Rollback helm history diagnose stuck hooks atomic operations expectations.'],
      ['GitOps drift manual kubectl changes?', 'ArgoCD detect outofsync reconcile policies—discipline.'],
      ['Canary promotion wrong metrics?', 'False positive latency normal—define SLIs carefully.'],
      ['Secrets in git plaintext team habit?', 'Culture shift sealed secrets external vault—audit.'],
      ['Multi-cluster GitOps complexity?', 'Repo structure bootstrap blast radius—start simple.'],
      ['Cost cluster autoscaling aggressive?', 'Thrashing scale up down—stabilization windows.'],
    ],
    wrongAnswers: [
      'Helm is the only way to deploy to Kubernetes.',
      'values.yaml should contain production secrets in plain text.',
      'GitOps means you never need CI pipelines.',
      'helm rollback deletes all history permanently.',
      'Kustomize and Helm cannot be used together.',
      'PodDisruptionBudget prevents all pod evictions including involuntary ones.',
    ],
  },

  75: {
    conceptual: [
      ['What is AWS IAM?', 'Identity access management users roles policies least privilege—foundation security.'],
      ['What is IAM role for service account IRSA EKS?', 'Pods assume AWS roles OIDC—avoid static keys—best practice.'],
      ['What is S3 bucket policies vs IAM?', 'Resource policy + identity policy intersection—both must allow.'],
      ['What is VPC subnets AZs?', 'High availability isolate failures—public private subnets routing NAT.'],
      ['What is RDS managed database?', 'Backups patching failover Multi-AZ—operational offload trade cost.'],
      ['What is Lambda serverless?', 'Event-driven pay per invocation cold start limitations CPU memory duration.'],
      ['What is API Gateway?', 'HTTP API management auth throttling integration Lambda HTTP.'],
      ['What is CloudWatch metrics logs?', 'Observability foundation alarms SNS paging—structured logs important.'],
      ['What is KMS encryption?', 'Key management envelope encryption S3 EBS RDS—rotation policies.'],
      ['What is Secrets Manager vs Parameter Store?', 'Rotation automation vs simpler cheaper—choose per secret type.'],
      ['What is ELB ALB NLB?', 'Layer 7 vs layer 4 load balancing—gRPC TLS termination differences.'],
      ['What is ECS Fargate?', 'Serverless containers no EC2 management—cost model different.'],
      ['What is ECR?', 'Docker registry integrated IAM image scanning.'],
      ['What is STS AssumeRole?', 'Temporary credentials cross-account access—audit trail.'],
      ['What is cost optimization pillars?', 'Right sizing reserved instances savings plans spot—FinOps culture.'],
    ],
    codeBased: [
      ['DefaultCredentialsProvider AWS SDK Java', 'Chain env profile instance role.'],
      ['S3Client putObject PutObjectRequest', 'SDK v2 example.'],
      ['software.amazon.awssdk.services.sqs.SqsClient', 'SQS client.'],
      ['@EnableSqs @SqsListener Spring Cloud AWS', 'Listener integration.'],
      ['Region.US_EAST_1 static import', 'Region selection.'],
      ['Presigner presignGetObject duration', 'Presigned URL.'],
      ['DynamoDbClient query QueryRequest', 'Dynamo API.'],
      ['StsClient assumeRole', 'Temporary creds.'],
      ['CloudWatch putMetricData', 'Custom metrics.'],
      ['SecretsManagerClient getSecretValue', 'Fetch secret.'],
    ],
    seniorScenario: [
      ['IAM policy too permissive breach?', 'Least privilege continuous review automated policy analysis Access Analyzer.'],
      ['S3 bucket public exposure incident?', 'Block public access account settings audit logs CloudTrail.'],
      ['Lambda VPC cold start RDS access?', 'ENI creation latency—architecture trade-offs RDS Proxy.'],
      ['Cross-region replication failover RPO RTO?', 'Business requirements technology alignment drills.'],
      ['Cost spike surprise bill?', 'Budgets anomaly detection tagging accountability FinOps.'],
      ['SDK retry storm outage?', 'Exponential backoff jitter circuit breaker client side resilience.'],
    ],
    wrongAnswers: [
      'AWS access keys in git are fine if the repo is private.',
      'IAM users are preferred over roles for applications on EC2.',
      'S3 buckets are private by default in all accounts forever without configuration.',
      'Lambda functions can run infinitely long for any workload.',
      'CloudWatch Logs automatically parse JSON without configuration.',
      'Multi-AZ RDS duplicates data synchronously to another region by default.',
    ],
  },

  76: {
    conceptual: [
      ['What is CI continuous integration?', 'Automated build test on each commit—fast feedback merge main often.'],
      ['What is CD continuous delivery vs deployment?', 'Always releasable vs auto prod—different risk maturity.'],
      ['What is pipeline stages?', 'Build test security scan package deploy promote—quality gates.'],
      ['What is GitHub Actions GitLab CI Jenkins?', 'CI orchestrators—YAML pipelines secrets runners.'],
      ['What is artifact repository Nexus Artifactory?', 'Store jars docker images SBOM—immutable versioning.'],
      ['What is blue-green / canary deployment?', 'Release strategies reduce downtime risk—monitor promote.'],
      ['What is observability pillars?', 'Metrics logs traces—three pillars not only logs.'],
      ['What is OpenTelemetry?', 'Vendor-neutral instrumentation traces metrics logs—CNCF standard.'],
      ['What is Prometheus pull model?', 'Scrape metrics HTTP endpoints—Alertmanager routing.'],
      ['What is Grafana dashboards?', 'Visualization datasource Prometheus Loki Tempo unified.'],
      ['What is structured JSON logging?', 'Parseable fields trace_id—better queries than plain text.'],
      ['What is SLI SLO error budget?', 'Service level indicators objectives—balance reliability velocity.'],
      ['What is on-call rotations?', 'PagerDuty escalation runbooks—human processes matter.'],
      ['What is chaos engineering in prod?', 'Controlled experiments—safety guardrails—not random.'],
      ['What is DORA metrics?', 'Deployment frequency lead time failure rate MTTR—research-backed benchmarks.'],
    ],
    codeBased: [
      ['GitHub Actions on push branches main', 'Workflow trigger.'],
      ['mvn -B verify', 'Maven CI build.'],
      ['docker build push registry', 'Image publish pipeline.'],
      ['trivy image scan fail on critical', 'Security gate.'],
      ['JUnit surefire reports upload', 'Test reporting.'],
      ['OpenTelemetry Java agent -javaagent', 'Auto instrumentation.'],
      ['Micrometer registry Prometheus', 'Metrics export Spring Boot.'],
      ['Logback JSON encoder', 'Structured logs.'],
      ['curl -f health check deploy', 'Smoke test step.'],
      ['helm upgrade --atomic rollback on failure', 'Safe deploy.'],
    ],
    seniorScenario: [
      ['Pipeline green prod broken?', 'Tests insufficient monitoring gaps feature flags canary—holistic quality.'],
      ['Alert fatigue on-call burnout?', 'Tuning thresholds SLO based paging actionable runbooks.'],
      ['Tracing overhead unacceptable?', 'Sampling head-based tail-based balancing observability cost.'],
      ['Compliance audit need deployment traceability?', 'Immutable artifacts signed provenance SBOM attestations SLSA.'],
      ['Multi-region active deployment coordination?', 'Progressive traffic DNS health checks data replication lag.'],
      ['CI minutes cost explosion monorepo?', 'Affected targets caching distributed remote execution Bazel.'],
    ],
    wrongAnswers: [
      'CI/CD guarantees zero bugs in production.',
      'Logs alone are sufficient observability for microservices.',
      'Prometheus push gateway is the default for all service metrics.',
      'You should page the team for every warning log line.',
      'SLOs should be set to 100% for all services always.',
      'GitHub Actions workflows run on your production servers by default.',
    ],
  },

  77: {
    conceptual: [
      ['What is SOLID S?', 'Single Responsibility—class/module one reason to change—cohesion.'],
      ['What is Open/Closed?', 'Open for extension closed for modification—interfaces inheritance composition.'],
      ['What is Liskov Substitution?', 'Subtypes substitutable without breaking expectations—behavioral contract.'],
      ['What is Interface Segregation?', 'Small focused interfaces—not fat god interfaces forcing empty methods.'],
      ['What is Dependency Inversion?', 'Depend on abstractions not concretions—DI frameworks help.'],
      ['What is Clean Architecture layers?', 'Entities use cases interface adapters frameworks—dependency rule inward.'],
      ['What is hexagonal architecture?', 'Ports and adapters—domain core independent infrastructure—testability.'],
      ['What is bounded context DDD relation?', 'Aligns with modular architecture—microservices mapping cautiously.'],
      ['What is coupling vs cohesion?', 'Inter-module dependency strength vs internal module relatedness—metrics.'],
      ['What is package by feature vs layer?', 'Organize code vertical slices vs horizontal layers—maintainability trade-offs.'],
      ['What is technical debt metaphor?', 'Shortcuts interest payments—quantify refactor planning.'],
      ['What is architecture fitness functions?', 'Automated checks modularity cycles performance budgets—continuous guidance.'],
      ['What is evolutionary architecture?', 'Support guided change—principles over upfront big design only.'],
      ['What is anti-pattern god object?', 'Class knows/does everything—hard to test change.'],
      ['What is YAGNI?', 'You aren’t gonna need it—avoid speculative generality—balance with future likely changes.'],
    ],
    codeBased: [
      ['interface PaymentGateway charge()', 'DIP abstraction.'],
      ['class StripeGateway implements PaymentGateway', 'Concrete implementation.'],
      ['Split UserService god class into smaller services', 'SRP refactor sketch.'],
      ['Use composition over inheritance extends', 'OCP composition pattern.'],
      ['Mock PaymentGateway in unit test', 'Testing DIP.'],
      ['Package com.myapp.billing.invoice', 'Feature packaging example.'],
      ['Domain entity pure Java no framework imports', 'Clean Architecture rule.'],
      ['Adapter converts Stripe DTO to domain Payment', 'Hexagonal adapter.'],
      ['Avoid static singletons for testability', 'DIP testing issues.'],
      ['Record ReadModel separate from Entity', 'CQRS read/write separation light.'],
    ],
    seniorScenario: [
      ['SOLID dogma blocks pragmatic fix deadline?', 'Balance principles delivery—document trade debt.'],
      ['Clean Architecture layers leaking JPA entities everywhere?', 'Anemic boundaries—enforce module compile rules ArchUnit.'],
      ['Microservices “do SOLID” but distributed monolith?', 'Coupling via shared DB synchronous chains—architecture smell.'],
      ['Refactor big ball of mud risk?', 'Strangler incremental tests characterization tests.'],
      ['Conway’s law organization mirrors architecture?', 'Team structure impacts modularity—reorg considerations.'],
      ['Fitness functions failing CI merge blocked?', 'Developer experience balance—tune thresholds incremental adoption.'],
    ],
    wrongAnswers: [
      'SOLID applies only to object-oriented code, never functional.',
      'Dependency Inversion means you must use a Spring bean for everything.',
      'Clean Architecture forbids frameworks like Spring in the outer layer.',
      'A class with many methods always violates Single Responsibility.',
      'Interface Segregation means one interface per class only.',
      'YAGNI means you should never refactor early code.',
    ],
  },

  78: {
    conceptual: [
      ['What is Factory Method pattern?', 'Creator subclass decides which product to instantiate—flexible construction.'],
      ['What is Abstract Factory?', 'Families of related objects—UI themes cross-platform widget sets.'],
      ['What is Singleton pattern?', 'Single global instance—use sparingly testability issues threading—enum singleton Java.'],
      ['What is Builder pattern?', 'Stepwise construction complex objects—readability immutability fluent API.'],
      ['What is Prototype pattern?', 'Clone/copy objects—Java Cloneable fragile—copy constructors preferred.'],
      ['What is Object Pool pattern?', 'Reuse expensive objects DB connections—pooling frameworks implement.'],
      ['What is Simple Factory (idiom)?', 'Not GoF strictly—static method create—pragmatic.'],
      ['When prefer builder over telescoping constructors?', 'Many optional parameters—Lombok @Builder generation.'],
      ['What is dependency injection vs service locator?', 'Injection explicit dependencies vs hidden lookups—testability.'],
      ['What is Spring Bean scope singleton prototype?', 'Creational container-managed lifecycle patterns.'],
      ['What is anti-pattern singleton abuse?', 'Global mutable state concurrency testing nightmares.'],
      ['What is creational vs structural?', 'Object creation mechanisms vs composition relationships—GoF categories.'],
      ['What is lazy initialization holder idiom?', 'Thread-safe lazy singleton without synchronized heavy—class loading trick.'],
      ['What is Enum singleton serialization safety?', 'JVM guarantees single instance across serialization—preferred.'],
      ['What is factory in domain-driven design?', 'Aggregate creation enforcing invariants—not only GoF pattern.'],
    ],
    codeBased: [
      ['public static Foo of(...)', 'Static factory naming.'],
      ['Lombok @Builder', 'Generated builder.'],
      ['enum Singleton { INSTANCE; ... }', 'Enum singleton.'],
      ['Supplier<T> factory method injection', 'Functional factory.'],
      ['Spring @Bean factory method', 'Container factory.'],
      ['newBuilder().setA().setB().build()', 'Classic builder fluent.'],
      ['ObjectPool borrowObject returnObject Apache Commons Pool', 'Pooling library.'],
      ['Records builder pattern still useful?', 'Many optional fields—yes sometimes.'],
      ['AbstractFactory WindowsButton MacButton', 'Cross-platform example.'],
      ['Avoid Cloneable clone()', 'Copy constructor preferred Java.'],
    ],
    seniorScenario: [
      ['Singleton Spring bean stateful—risk?', 'Concurrency bugs in singleton—scope prototype or externalize state.'],
      ['Builder misuse mandatory inconsistent state?', 'Validate in build() throw—illegal combinations.'],
      ['Abstract factory explosion subclasses?', 'Maintenance burden—balance pragmatism.'],
      ['Object pool premature optimization?', 'GC improvements often reduce need—profile first.'],
      ['Testing static singleton legacy?', 'Refactor dependency injection wrappers PowerMock last resort brittle.'],
      ['Factory beans Spring complexity?', 'Indirection debugging harder—document purpose.'],
    ],
    wrongAnswers: [
      'Singleton is always the best way to share configuration.',
      'Builder pattern requires Lombok.',
      'Abstract Factory is the same as Factory Method.',
      'Prototype pattern in GoF means Spring prototype scope only.',
      'You should create a new String with new String("x") for performance.',
      'Object pools are always faster than allocation.',
    ],
  },

  79: {
    conceptual: [
      ['What is Adapter pattern?', 'Convert interface of class into another clients expect—legacy integration.'],
      ['What is Decorator pattern?', 'Add responsibilities dynamically wrappers—Java IO BufferedInputStream stacks.'],
      ['What is Proxy pattern?', 'Surrogate control access—lazy loading security remote stub—Spring AOP proxies related.'],
      ['What is Facade pattern?', 'Simplified interface to complex subsystem—reduce coupling clients.'],
      ['What is Flyweight pattern?', 'Share intrinsic state many objects—text editor characters example—memory.'],
      ['What is Bridge pattern?', 'Separate abstraction from implementation—two orthogonal hierarchies reduce explosion.'],
      ['What is Composite pattern?', 'Tree structures uniform treatment leaf composite—UI components file systems.'],
      ['What is Wrapper vs Adapter naming confusion?', 'Often similar—adapter translation composite tree—intent differs.'],
      ['What is dynamic vs static proxy?', 'JDK Proxy interface only vs CGLIB subclass—Spring choice implications.'],
      ['What is immutability with decorators?', 'Each decorator returns new decorated—functional style.'],
      ['What is performance layers decorators?', 'Deep stacks overhead—measure hot paths.'],
      ['What is anti-pattern god facade?', 'Facade becomes omniscient knows everything—still coupling.'],
      ['What is REST API facade BFF?', 'Backend for frontend simplified client API—structural pattern at architecture level.'],
      ['What is stream decorators Java IO?', 'Composition of InputStream filters—classic GoF.'],
      ['What is virtual proxy loading heavy object?', 'Lazy initialization placeholder—Hibernate lazy associations conceptually similar.'],
    ],
    codeBased: [
      ['new BufferedReader(new InputStreamReader(...))', 'Decorator stack.'],
      ['Adapter implements ClientInterface wraps Adaptee', 'Adapter UML sketch code.'],
      ['java.lang.reflect.Proxy newProxyInstance', 'Dynamic proxy example.'],
      ['Composite FileSystem Node file directory', 'Recursive structure.'],
      ['Facade orderService.placeOrder single call many subservices', 'Simplified API.'],
      ['@Transactional proxy around service bean', 'Spring structural proxy.'],
      ['HttpClient wrapper add logging decorator', 'Cross-cutting layering.'],
      ['Flyweight Integer cache -128..127', 'JVM intrinsic flyweight-like caching.'],
      ['Bridge pattern JDBC Driver abstraction', 'DriverManager bridge example.'],
      ['Avoid deep decorator stacks readability?', 'Refactor pipeline explicit stages.'],
    ],
    seniorScenario: [
      ['Too many decorators latency?', 'Profiling aspect ordering deep stacks—flatten or codegen.'],
      ['Adapter translating corrupt assumptions?', 'Bugs at boundary—contract tests both sides.'],
      ['Facade hiding too little still leaky?', 'Clients still depend many types—improve abstraction.'],
      ['Hibernate lazy proxy LazyInitializationException?', 'Session closed—open-in-view anti-pattern trade-offs.'],
      ['Microservices API gateway as facade pitfalls?', 'Business logic creep gateway—thin routing only guideline.'],
      ['Composite pattern UI trees performance?', 'Virtualization large lists—different technique.'],
    ],
    wrongAnswers: [
      'Adapter and Facade are identical patterns.',
      'Decorator requires inheritance only.',
      'Proxy pattern can only be used for remote objects.',
      'Composite pattern forbids leaf nodes.',
      'Flyweight means every object is shared always.',
      'Spring AOP proxies never use CGLIB.',
    ],
  },

  80: {
    conceptual: [
      ['What is Observer pattern?', 'Subject notifies observers on change—event-driven decoupling.'],
      ['What is Strategy pattern?', 'Family of interchangeable algorithms—dependency injection selection runtime.'],
      ['What is Command pattern?', 'Encapsulate request as object—undo queues macro logging.'],
      ['What is State pattern?', 'Object behavior changes when internal state changes—finite state machines formalized.'],
      ['What is Chain of Responsibility?', 'Pass request along chain until handled—servlet filters middleware.'],
      ['What is Iterator pattern?', 'Traverse collection without exposing internals—Java Iterator.'],
      ['What is Mediator pattern?', 'Central hub reduces many-to-many communication—chat room analogy.'],
      ['What is Memento pattern?', 'Snapshot state for undo—careful memory encapsulation.'],
      ['What is Template Method?', 'Skeleton algorithm subclasses override steps—inheritance-based.'],
      ['What is Visitor pattern?', 'Separate operations from object structure—double dispatch—compiler AST visitors.'],
      ['What is Null Object pattern?', 'Default no-op behavior instead of null checks—optional alternative.'],
      ['What is RxJava reactive extension?', 'Observer on steroids streams—complex lifecycle.'],
      ['What is Event-driven architecture?', 'Domain events integration—Kafka observers distributed.'],
      ['What is middleware pipeline?', 'HTTP request passes chain—security logging—behavioral composition.'],
      ['What is specification pattern?', 'Composable business rules boolean logic—DDD advanced.'],
    ],
    codeBased: [
      ['List<Command> undo stack', 'Command pattern undo.'],
      ['interface TaxStrategy BigDecimal compute', 'Strategy injection.'],
      ['enum State { A, B } transition methods', 'State machine simple.'],
      ['FilterChain doFilter Servlet', 'Chain of responsibility.'],
      ['ApplicationListener<ContextRefreshedEvent> Spring', 'Observer in Spring.'],
      ['Visitor pattern accept visit Node', 'Double dispatch sketch.'],
      ['Template method abstract class step1 hook step2', 'Subclass overrides hooks.'],
      ['Optional or NullObject logger noOp()', 'Avoid null checks.'],
      ['Comparator as strategy for sort', 'Built-in strategy pattern.'],
      ['Middleware Express.js style pipeline concept', 'Cross-language analogy.'],
    ],
    seniorScenario: [
      ['God Observer explosion subscriptions?', 'Memory leaks unregister lifecycle event bus complexity.'],
      ['Strategy explosion subclasses?', 'Map of enum to strategy lambda table-driven alternative.'],
      ['Command queue asynchronous processing failure?', 'Idempotent commands persistence sagas.'],
      ['Visitor adding new operation easy new type hard?', 'Visitor trade-off open/closed tension—choose wisely.'],
      ['Reactive streams backpressure observer overload?', 'Different problem domain—use appropriate toolkit.'],
      ['Chain of responsibility security filters order bug?', 'Authentication before authorization—document ordering tests.'],
    ],
    wrongAnswers: [
      'Observer pattern requires threads.',
      'Strategy pattern is only for sorting.',
      'Command pattern cannot support undo.',
      'Chain of Responsibility always stops at the first handler.',
      'Visitor pattern is the best choice for every data structure problem.',
      'Template Method cannot use final methods.',
    ],
  },

  81: {
    conceptual: [
      ['What is horizontal scaling?', 'Add more machines—stateless services easier than DB scaling.'],
      ['What is vertical scaling?', 'Bigger machine—limits cost downtime simpler short term sometimes.'],
      ['What is latency vs throughput?', 'Time per request vs requests per second—optimize different bottlenecks.'],
      ['What is bottleneck analysis?', 'Find limiting component—CPU disk network DB—profile don’t guess.'],
      ['What is caching layers?', 'Browser CDN reverse-proxy app cache DB replica—each trade-off staleness.'],
      ['What is load balancing algorithms?', 'Round robin least conn IP hash—session affinity implications.'],
      ['What is rate limiting?', 'Protect system fairness abuse—token bucket leaky bucket—gateway enforcement.'],
      ['What is back-of-envelope estimation?', 'Orders of magnitude QPS storage bandwidth—sanity check designs.'],
      ['What is availability 99.9% vs 99.99%?', 'Downtime per year differs order magnitude—cost engineering trade-off.'],
      ['What is CAP in system design interview?', 'Explain trade-offs partitions—practical not theorem recitation only.'],
      ['What is idempotency in APIs?', 'Safe retries—critical payment APIs—keys dedupe.'],
      ['What is graceful degradation?', 'Reduce features under load—non-core features off—maintain core SLA.'],
      ['What is bulkhead isolation?', 'Separate pools threads connections—failure containment resilience patterns.'],
      ['What is multi-AZ vs multi-region?', 'High availability within region vs disaster recovery cross-region latency cost.'],
      ['What is CDN edge caching?', 'Static assets closer users—invalidation challenges dynamic content.'],
    ],
    codeBased: [
      ['Estimate QPS: 1M DAU 10 requests/day average', 'Rough division seconds—sanity.'],
      ['Storage estimate: 1KB per event * 1B events/day', 'Bytes per day TB scaling.'],
      ['Bandwidth: 1MB response * 1000 RPS', 'Gbps network capacity planning.'],
      ['Thread pool sizing CPU cores * (1 + wait time / service time)', 'Little’s law intuition.'],
      ['Cache hit ratio 90% reduces DB load factor', 'Effective QPS to origin.'],
      ['Sharding users by user_id hash mod N', 'Partitioning sketch.'],
      ['Read replica lag 100ms user experience', 'Stale reads business acceptance.'],
      ['Rate limit 100 req/min per API key', 'Token bucket parameters.'],
      ['Session sticky vs JWT stateless trade-off', 'Architecture choice.'],
      ['Connection pool 20 * 100 instances vs DB max connections', 'Aggregate math.'],
    ],
    seniorScenario: [
      ['CEO demands five nines cheap?', 'Explain cost complexity diminishing returns error budgets.'],
      ['Over-engineered microservices premature?', 'Start modular monolith evidence-based extraction—YAGNI at org scale too.'],
      ['Black Friday capacity planning?', 'Load testing autoscaling caches queues graceful degradation playbooks.'],
      ['Vendor SLA 99.95% composite system SLA math?', 'Serial dependencies multiply downtime probabilities approximate.'],
      ['Global low latency single DB?', 'Physics speed of light—impossible single master worldwide active writes—CP trade.'],
      ['Cost optimization vs reliability conflict?', 'Error budget policy product alignment FinOps collaboration.'],
    ],
    wrongAnswers: [
      'You should always microservice everything from day one.',
      'Caching solves all performance problems.',
      '99.999% availability is free if you use Kubernetes.',
      'Horizontal scaling means you never need to optimize code.',
      'Latency and throughput are always the same metric.',
      'A single load balancer has infinite capacity.',
    ],
  },

  82: {
    conceptual: [
      ['What is URL shortener core function?', 'Map short code to long URL—bijective or collision handling—redirect HTTP 302.'],
      ['What is base62 encoding?', 'Short strings from numeric ids—avoid ambiguous characters optionally.'],
      ['What is hash vs id generation?', 'Hash long URL may collide—use unique constraint retry—sequential id simpler.'],
      ['What is read-heavy workload?', 'Caching CDN redirects—eventual analytics separate pipeline.'],
      ['What is rate limiting creation abuse?', 'Auth CAPTCHA quotas per user IP—prevent spam URLs.'],
      ['What is expiration TTL links?', 'Garbage collection storage—cron job delete expired.'],
      ['What is analytics click counting?', 'Async stream counts—approximate structures count-min sketch high scale.'],
      ['What is custom short code vs auto?', 'Uniqueness validation profanity filter—business rules.'],
      ['What is private vs public short links?', 'Authorization layer before redirect—different design.'],
      ['What is global scale data locality?', 'GeoDNS route nearest redirect service—cache replication.'],
      ['What is collision probability birthday paradox?', 'Plan unique indexes retry—monitor collisions.'],
      ['What is 301 vs 302 redirect SEO?', 'Permanent vs temporary semantics—short links often 302 temporary marketing.'],
      ['What is database schema keys?', 'short_code PK, long_url, created_at, expires_at, user_id indexes.'],
      ['What is system design interview structure?', 'Requirements constraints API capacity data model deep dive bottlenecks trade-offs.'],
      ['What is malicious URL detection?', 'Phishing scanning blocklists—safety responsibility.'],
    ],
    codeBased: [
      ['HTTP 302 Location: longUrl', 'Redirect response.'],
      ['SELECT long_url FROM links WHERE short_code=?', 'Lookup query index.'],
      ['Base62 encode bigint from DB sequence', 'Code generation.'],
      ['Redis cache short->long with TTL', 'Hot path cache.'],
      ['Rate limit token bucket per IP', 'Abuse mitigation sketch.'],
      ['Bloom filter check possibly seen URL', 'Probabilistic dedupe.'],
      ['Kafka click events async analytics', 'Decouple read path.'],
      ['UUID vs snowflake id generation distributed', 'Unique ids trade-offs.'],
      ['HTTP HEAD vs GET redirect counts?', 'Analytics careful caching CDNs.'],
      ['SQL unique constraint on short_code', 'Enforce uniqueness.'],
    ],
    seniorScenario: [
      ['Short link phishing brand abuse?', 'Reporting abuse workflow block domains legal compliance.'],
      ['Collision after hash shrink space?', 'Migration lengthen code painful—design early.'],
      ['Redirect latency SLA global?', 'Edge caching DNS anycast measure tail latencies.'],
      ['GDPR delete user links?', 'Cascade delete caches analytics logs—complex distributed.'],
      ['Competing bit.ly scale interview—humility?', 'High level patterns not exact numbers—communicate assumptions.'],
      ['Monetization analytics privacy?', 'Consent regulations CTR tracking minimization.'],
    ],
    wrongAnswers: [
      'URL shorteners never need databases.',
      '302 redirects are always cached forever by browsers.',
      'Hashing guarantees uniqueness without checking the database.',
      'You should use only UUIDs as short codes without shortening.',
      'Analytics must be synchronous in the redirect path.',
      'A single MySQL instance is always enough for global Twitter-scale URLs.',
    ],
  },

  83: {
    conceptual: [
      ['What is notification service responsibilities?', 'Deliver email push SMS in-app—multi-channel fan-out preferences.'],
      ['What is user preference management?', 'Opt-in categories quiet hours frequency caps—compliance CAN-SPAM GDPR.'],
      ['What is templating emails?', 'Internationalization variables brand layout—separate content engineering.'],
      ['What is idempotency notifications?', 'Dedupe same logical notification retries—business keys.'],
      ['What is rate limiting per user?', 'Avoid notification fatigue churn—product analytics feedback.'],
      ['What is push notification providers?', 'FCM APNS WebPush—device tokens registration invalidation.'],
      ['What is SMS cost reliability?', 'Twilio etc.—delivery receipts failures international regulations.'],
      ['What is queue-based sending?', 'Asynchronous workers scale bursts—retry DLQ poison messages.'],
      ['What is observability delivery metrics?', 'Open rate actually biased—delivery success latency bounce handling.'],
      ['What is A/B testing notifications?', 'Experiment framework holdout groups—ethical UX.'],
      ['What is localization time zones?', 'Schedule local time quiet hours—correct instant conversions.'],
      ['What is transactional vs marketing email?', 'Different infrastructure reputation IPs SPF DKIM DMARC.'],
      ['What is webhook callbacks status?', 'Provider delivery webhooks update state async correlation ids.'],
      ['What is privacy sensitive content notifications?', 'Minimize PII in payloads encryption device security.'],
      ['What is multi-tenant isolation?', 'Org boundaries data leakage prevention SaaS notifications.'],
    ],
    codeBased: [
      ['SQS queue NotificationJob JSON payload', 'Async processing pattern.'],
      ['SES sendEmail template data', 'AWS email API sketch.'],
      ['FCM HTTP v1 OAuth bearer token', 'Push API modern.'],
      ['Thymeleaf FreeMarker email template', 'Server-side templating.'],
      ['Dedupe table notification_idempotency_key unique', 'DB constraint.'],
      ['Cron quiet hours check ZoneId user', 'Scheduling logic.'],
      ['Feature flag kill switch notifications', 'Incident response.'],
      ['Metrics Counter notifications.sent', 'Micrometer.'],
      ['Retry exponential backoff provider 429', 'Resilience.'],
      ['User prefs JSON column or normalized table', 'Schema choice.'],
    ],
    seniorScenario: [
      ['Email blast reputation IP blacklisted?', 'Warmup pools dedicated IPs monitoring bounce rates.'],
      ['Push token invalid after app reinstall?', 'Stale tokens cleanup job provider feedback loops.'],
      ['Regulatory SMS quiet hours country laws?', 'Compliance matrix product legal alignment.'],
      ['Duplicate charges subscription emails billing?', 'Idempotency keys finance integration careful QA.'],
      ['Notification storm during incident?', 'Circuit break user comms prioritize critical channels.'],
      ['Observability noise alerts on notification failures?', 'Tune signal-to-noise actionable thresholds.'],
    ],
    wrongAnswers: [
      'Email delivery is guaranteed exactly once by SMTP.',
      'Push notifications work without device tokens.',
      'You should send all marketing emails from your primary transactional domain.',
      'User preferences are irrelevant for system notifications.',
      'SMS is free and unlimited worldwide.',
      'Queues guarantee ordering across all channels globally.',
    ],
  },

  84: {
    conceptual: [
      ['What is e-commerce order service scope?', 'Cart checkout payment inventory shipping orchestration—bounded context.'],
      ['What is inventory reservation vs oversell?', 'Hold stock during checkout TTL—release on timeout payment fail—race conditions.'],
      ['What is idempotent order placement?', 'Client idempotency key duplicate submit safe—network retries mobile.'],
      ['What is saga for order payment shipment?', 'Compensate cancel authorize capture—distributed transaction patterns.'],
      ['What is pricing snapshot at order time?', 'Price changes shouldn’t alter placed orders—store line item prices.'],
      ['What is tax calculation jurisdiction?', 'Complex rules services external Avalara—accuracy compliance.'],
      ['What is fraud scoring?', 'Stripe Radar rules manual review—latency SLA checkout.'],
      ['What is warehouse split shipments?', 'Multiple packages partial fulfillment state machine complexity UX.'],
      ['What is returns refunds workflows?', 'Reverse logistics credit notes inventory restock—edge cases.'],
      ['What is concurrency cart checkout?', 'Optimistic locking version field inventory rows—prevent oversell.'],
      ['What is gift cards promotions stacking?', 'Business rules engine complexity testing matrix.'],
      ['What is PCI scope reduction?', 'Tokenization hosted fields—never store PAN raw—compliance architecture.'],
      ['What is order search analytics OLAP?', 'Separate read models CDC—reporting not OLTP queries.'],
      ['What is peak traffic Black Friday?', 'Autoscaling queues caching degrade non-critical features gracefully.'],
      ['What is marketplace multi-vendor orders?', 'Split payouts commissions tax—additional complexity—Uber Etsy patterns.'],
    ],
    codeBased: [
      ['POST /orders Idempotency-Key header', 'API design pattern.'],
      ['Order aggregate state machine PLACED PAID SHIPPED', 'Statuses transitions.'],
      ['SELECT ... FOR UPDATE inventory WHERE sku', 'Pessimistic lock row.'],
      ['Outbox OrderCreated event publish', 'Reliable events.'],
      ['Saga compensate PaymentFailed', 'Rollback inventory reservation.'],
      ['LineItem record price snapshot', 'Immutability per order.'],
      ['Optimistic lock version column JPA @Version', 'Concurrency control.'],
      ['Cart merge on login user session', 'Edge case UX.'],
      ['Tax service HTTP call timeout circuit breaker', 'Resilience integration.'],
      ['Refund idempotent POST /refunds idempotency', 'Money movement safety.'],
    ],
    seniorScenario: [
      ['Black Friday inventory oversell incident?', 'Postmortem locking saga testing load tests race detection chaos.'],
      ['PCI audit failure card data logged?', 'Scrub logs secret scanning pipeline training.'],
      ['Vendor API outage payment stuck orders?', 'Manual intervention playbook compensation customer comms SLA.'],
      ['Global currency tax compliance complexity?', 'Regional teams legal engineering coupling careful boundaries.'],
      ['Fraud false positives angry customers?', 'Balance ML rules manual review UX verification steps.'],
      ['Microservices order bounded context boundaries?', 'Avoid distributed monolith synchronous chains observability debt.'],
    ],
    wrongAnswers: [
      'Inventory should always be checked only at shipping time.',
      'Idempotency keys are optional for payment APIs.',
      'Order prices should always reference live catalog prices after purchase.',
      'Sagas are unnecessary if you use a single SQL database.',
      'PCI compliance is only the payment provider’s problem.',
      'Returns never affect inventory systems.',
    ],
  },

  85: {
    conceptual: [
      ['What is JUnit 5 architecture?', 'Jupiter platform vintage—annotations @Test @BeforeEach extensions model.'],
      ['What is Mockito?', 'Mocking framework stubbing verify—@Mock @InjectMocks lenient strictness.'],
      ['What is test pyramid?', 'Many unit fewer integration fewer e2e—cost speed reliability balance.'],
      ['What is AAA pattern?', 'Arrange Act Assert—readable tests structure.'],
      ['What is stub vs mock?', 'Stub returns canned data; mock asserts interactions occurred—terminology often blurred Mockito.'],
      ['What is parameterized tests?', '@ParameterizedTest multiple inputs edge cases data driven.'],
      ['What is test doubles taxonomy?', 'Fake dummy stub spy mock—Gerard Meszaros precise language sometimes overkill.'],
      ['What is AssertJ fluent assertions?', 'Readable assertions chaining soft assertions multiple failures.'],
      ['What is Mockito verify times never', 'Interaction verification—avoid overspecified brittle tests.'],
      ['What is static mocking Mockito inline?', 'Mockito 3+ inline mockStatic—use sparingly design for testability better.'],
      ['What is Spring test slices?', '@WebMvcTest @DataJpaTest focused context faster.'],
      ['What is flaky tests?', 'Non-deterministic timing order—quarantine fix root cause not ignore.'],
      ['What is code coverage metric?', 'Line branch coverage—tool not goal missing assertions meaningless.'],
      ['What is mutation testing PIT?', 'Tests quality kill mutants—stronger than coverage alone expensive.'],
      ['What is TDD red green refactor?', 'Discipline write failing test minimal code refactor—benefits debate pragmatic.'],
    ],
    codeBased: [
      ['@Test void shouldX_whenY()', 'Naming pattern.'],
      ['when(mock.foo()).thenReturn(1)', 'Mockito stub.'],
      ['verify(mock, times(1)).save(any())', 'Verify interaction.'],
      ['@ExtendWith(MockitoExtension.class)', 'JUnit5 Mockito extension.'],
      ['assertThat(actual).isEqualTo(expected)', 'AssertJ.'],
      ['@ParameterizedTest @CsvSource', 'Data-driven.'],
      ['@SpringBootTest @Transactional rollback', 'Integration test DB rollback.'],
      ['Mockito.lenient stubbing', 'Avoid unnecessary stubbing exception strict stubs.'],
      ['ArgumentCaptor<Order> capture', 'Verify argument values.'],
      ['@MockBean replace bean in Spring test', 'Override configuration.'],
    ],
    seniorScenario: [
      ['CI flaky tests ignored culture?', 'Dangerous—quarantine track fix ownership—quality culture.'],
      ['Mocking domain behavior too much?', 'Tests pass but production fails—prefer real domain unit pure.'],
      ['Coverage 90% still bugs?', 'Assertions weak mutation testing reviews.'],
      ['Testing private methods directly?', 'Test via public behavior refactor extract class if needed.'],
      ['Parallel test execution Spring context cache?', 'Reuse contexts @DirtiesContext expensive misuse.'],
      ['Contract testing vs unit tests investment?', 'Balance pyramid consumer-driven Pact ROI.'],
    ],
    wrongAnswers: [
      'JUnit 4 and JUnit 5 use the exact same package names.',
      'Mockito can mock final classes and static methods in all versions without setup.',
      '100% code coverage guarantees correctness.',
      'verify() should be used on every mock in every test.',
      '@SpringBootTest is the best choice for every unit test.',
      'Flaky tests should be retried indefinitely in CI without investigation.',
    ],
  },

  86: {
    conceptual: [
      ['What is @SpringBootTest?', 'Full application context integration test—slower broad scope.'],
      ['What is @WebMvcTest?', 'Slice only web layer MockMvc controllers—mock beans fast.'],
      ['What is @DataJpaTest?', 'JPA slice embedded database default—repository tests.'],
      ['What is Testcontainers?', 'Docker containers for real DB Kafka etc.—integration fidelity—CI requirements Docker.'],
      ['What is @DynamicPropertySource Testcontainers?', 'Inject random ports JDBC URL into Spring context dynamic.'],
      ['What is @MockBean vs @MockitoBean?', 'Spring Boot 3.4+ MockitoBean refined—mock injection clarity evolving.'],
      ['What is slice vs full context trade-off?', 'Speed vs confidence—choose appropriate layer.'],
      ['What is WireMock?', 'Stub external HTTP services—deterministic tests no real third party.'],
      ['What is Awaitility async tests?', 'Poll until condition timeout—reactive async flows.'],
      ['What is Spring Security test @WithMockUser?', 'Security context in tests—authorize requests.'],
      ['What is @Sql scripts test database?', 'Seed data before test—cleanup scripts.'],
      ['What is TestRestTemplate vs WebTestClient?', 'Servlet vs reactive testing stacks.'],
      ['What is @Nested JUnit 5?', 'Organize test classes hierarchical structure readability.'],
      ['What is ArchUnit architecture tests?', 'Enforce package dependencies cycles—CI guardrails.'],
      ['What is testcontainers reuse Ryuk?', 'Resource reaper container—speed local dev mode experimental.'],
    ],
    codeBased: [
      ['@Testcontainers static PostgreSQLContainer', 'JUnit5 extension pattern.'],
      ['@DynamicPropertySource static void props(DynamicPropertyRegistry r)', 'Register jdbc url.'],
      ['mockMvc.perform(get("/api")).andExpect(status().isOk())', 'WebMvcTest.'],
      ['@Import(TestConfig.class)', 'Additional beans slice.'],
      ['@SpringBootTest(webEnvironment=RANDOM_PORT) TestRestTemplate', 'Full stack HTTP.'],
      ['@AutoConfigureMockMvc', 'Inject MockMvc.'],
      ['@Transactional rollback test', 'DB isolation.'],
      ['@Sql("/data.sql")', 'Seed data.'],
      ['WireMock.stubFor(get(urlEqualTo("/x")).willReturn(okJson("{}")))', 'External stub.'],
      ['await().atMost(5, SECONDS).until(() -> condition)', 'Awaitility.'],
    ],
    seniorScenario: [
      ['Testcontainers CI slow flaky docker?', 'Ryuk permissions daemon rootless docker—stabilize runners.'],
      ['Shared test database pollution?', 'Isolation per test class transactions random schema Testcontainers fresh.'],
      ['Full Spring context every unit test suite 30 min?', 'Refactor slices architecture faster feedback loops.'],
      ['Production-like data volume tests?', 'Subset generation anonymized GDPR compliant performance tests separate env.'],
      ['Contract drift consumer provider?', 'Spring Cloud Contract Pact pipeline gates releases.'],
      ['Flaky docker port collisions parallel CI?', 'Random ports dynamic properties serialization race conditions rare.'],
    ],
    wrongAnswers: [
      '@DataJpaTest loads the entire Spring Boot application always.',
      'Testcontainers runs containers in-memory without Docker.',
      'MockMvc requires a running servlet container always.',
      '@SpringBootTest is faster than @WebMvcTest.',
      'WireMock can only stub HTTPS with a valid public certificate always.',
      'Integration tests should never use transactions or rollbacks.',
    ],
  },

  87: {
    conceptual: [
      ['What is consumer-driven contract testing?', 'Consumer defines expected interaction provider verifies—Pact popular.'],
      ['What is Pact broker?', 'Contract repository versioning deployment coordination—can I deploy matrix.'],
      ['What is provider verification?', 'Replay requests from contract against provider—fail if breaks consumers.'],
      ['What is schema registry compatibility CI?', 'Avro breaking change detection automated—similar governance.'],
      ['What is Spring Cloud Contract?', 'Groovy DSL wiremock generation producer tests—alternative to Pact.'],
      ['What is end-to-end test drawbacks?', 'Slow flaky expensive—few high value journeys not everything.'],
      ['What is synthetic monitoring canary?', 'Prod traffic simulation monitoring SLIs proactive—different from CI tests.'],
      ['What is chaos testing in testing strategy?', 'Different from unit—validate resilience assumptions complement not replace.'],
      ['What is mutation testing in CI cost?', 'CPU time expensive selective critical modules periodic nightly maybe.'],
      ['What is test data management?', 'Anonymized realistic GDPR fixtures factories—maintainability investment.'],
      ['What is parallel CI test execution?', 'JUnit parallel surefire forks—test isolation thread safety static state bugs.'],
      ['What is quality gates SonarQube?', 'Coverage thresholds duplication smells—enforced thoughtfully avoid gaming.'],
      ['What is shift-left security testing?', 'SAST DAST dependencies early pipeline DevSecOps culture.'],
      ['What is performance testing types?', 'Load stress spike soak—different goals tools k6 JMeter Gatling.'],
      ['What is accessibility testing?', 'Automated axe checks manual screen reader—quality inclusive product.'],
    ],
    codeBased: [
      ['@Pact(provider="order", consumer="payment")', 'Pact annotation sketch.'],
      ['pact.verify()', 'Provider test runner.'],
      ['@SpringBootTest + WireMock @AutoConfigureWireMock', 'Spring contract style.'],
      ['JsonSchemaValidator.validate(schema, json)', 'JSON schema tests.'],
      ['RestAssured given when then', 'API testing fluent.'],
      ['k6 script http duration checks', 'Load test snippet concept.'],
      ['JUnit @Tag("integration") surefire groups', 'Selective runs.'],
      ['ArchUnit noClassesThat dependOn', 'Dependency rule example.'],
      ['Awaitility catch async assertion', 'Already mentioned—important.'],
      ['Testcontainers Kafka module', 'Broker integration tests.'],
    ],
    seniorScenario: [
      ['Pact broker downtime blocks deploy?', 'Cache artifacts fallback process resilience business continuity.'],
      ['Contracts green prod broken?', 'Environment differences auth data contracts incomplete coverage gaps.'],
      ['E2E suite 6 hours nightly only feedback slow?', 'Shift tests earlier pyramid balance investment automation ROI.'],
      ['Security scan false positives developer fatigue?', 'Triage workflow suppress with justification not blanket ignore.'],
      ['Performance tests non-representative data?', 'Production-like shape masking privacy sampling techniques.'],
      ['Accessibility last minute audit fail release?', 'Continuous a11y linting design system shift left culture.'],
    ],
    wrongAnswers: [
      'Contract testing replaces the need for any integration tests.',
      'Pact guarantees your microservices will never fail in production.',
      'E2E tests should cover every possible user click path.',
      'Mutation testing is fast and should run on every commit always.',
      'Schema registry compatibility checks replace the need for code review.',
      'Synthetic monitoring replaces real user monitoring entirely.',
    ],
  },

  88: {
    conceptual: [
      ['What is JVM profiling?', 'Analyze CPU allocation locks threads—find hotspots bottlenecks—not guessing.'],
      ['What is JFR Java Flight Recorder?', 'Low overhead profiling events—JDK Mission Control analysis—production safe often.'],
      ['What is async-profiler?', 'CPU flame graphs wall clock modes—combined with JFR powerful.'],
      ['What is heap dump analysis?', 'MAT Eclipse find dominator tree memory leaks retained objects—OOME debugging.'],
      ['What is GC log analysis?', 'Pause times allocation rate promotion failures tuning collectors G1 ZGC.'],
      ['What is JIT compilation profiling?', 'Tiered compilation deoptimization uncommon—understand warmup benchmarks.'],
      ['What is lock contention profiling?', 'JFR thread states parking monitors—scale threads or reduce locking.'],
      ['What is allocation profiling?', 'TLAB allocations object churn—reduce allocations hot loops.'],
      ['What is native memory tracking?', 'Direct ByteBuffers JNI metaspace thread stacks—off-heap leaks.'],
      ['What is continuous profiling production?', 'Datadog Continuous Profiler Pyroscope—always-on overhead budget.'],
      ['What is benchmarking pitfalls?', 'JMH correct warmup forks blackholes dead code elimination—scientific rigor.'],
      ['What is flame graph interpretation?', 'Width time cumulative—plateau hotspots focus optimization ROI.'],
      ['What is safepoint bias profiling?', 'Some profilers distort—be aware async profiler mitigations.'],
      ['What is JDWP remote debugging overhead?', 'Never leave enabled production—massive performance security risks.'],
      ['What is Arthas Alibaba diagnostic?', 'Dynamic tracing attach production advanced—power danger.'],
    ],
    codeBased: [
      ['jcmd <pid> JFR.start settings=profile', 'Start flight recording.'],
      ['java -XX:+FlightRecorder -XX:StartFlightRecording=duration=60s', 'CLI start.'],
      ['jmap -dump:live,format=b,file=heap.hprof', 'Heap dump command careful prod impact.'],
      ['-Xlog:gc*:file=gc.log:time,uptime:filecount=5,filesize=20M', 'GC logging unified logging.'],
      ['AsyncProfiler -e cpu -d 30 -f cpu.svg', 'Flamegraph generation sketch.'],
      ['JMH @BenchmarkMode(Mode.AverageTime)', 'Microbenchmark framework.'],
      ['VisualVM attach local JVM', 'Heap thread sampling GUI.'],
      ['jstack <pid> thread dump', 'Deadlock detection.'],
      ['Native Memory Tracking summary.diff', 'jcmd NMT compare baseline.'],
      ['YourKit/JProfiler commercial features heap inspection', 'Mention awareness.'],
    ],
    seniorScenario: [
      ['Production CPU spike profiling authorization?', 'Legal privacy sampling consent incident response process.'],
      ['Profiling shows GC not issue CPU app—still tune GC?', 'Focus app algorithm first measurement-driven.'],
      ['Heap dump contains PII GDPR?', 'Secure handling encrypted storage limited access delete after resolution.'],
      ['Benchmark shows fast but prod slow?', 'Different data JIT warmup infrastructure noise—reproduce prod-like.'],
      ['Continuous profiler overhead unacceptable tier?', 'Sampling frequency trade-offs budget alerts.'],
      ['Arthas in prod regulatory bank?', 'Change management risk approval audit trails strong controls.'],
    ],
    wrongAnswers: [
      'Profiling always has zero overhead.',
      'Heap dumps should be taken on every request in production.',
      'JFR is only for development laptops.',
      'More heap always solves OutOfMemoryError.',
      'Microbenchmarks in main() without JMH are always valid.',
      'GC logs are irrelevant if average pause is low.',
    ],
  },

  89: {
    conceptual: [
      ['What is STAR method?', 'Situation Task Action Result—behavioral interview structure metrics concise.'],
      ['What is system design interview flow?', 'Clarify requirements estimate API data model deep dive scale bottlenecks trade-offs.'],
      ['What is trade-off communication?', 'Explicit CAP latency consistency cost—interviewers want reasoning not buzzwords only.'],
      ['What is estimation sanity?', 'Round numbers orders of magnitude—show structured thinking assumptions stated.'],
      ['What is clarifying questions importance?', 'Avoid solving wrong problem—requirements ambiguous intentionally sometimes.'],
      ['What is drawing diagrams?', 'Sequence diagrams capacity sketches—whiteboard communication clarity.'],
      ['What is behavioral + system combo rounds?', 'Companies mix—Amazon LP + system design—prepare both.'],
      ['What is coding vs system design seniority?', 'More design less Leetcode sometimes—not universal—research company.'],
      ['What is “tell me about a failure” question?', 'Honesty learning accountability—no blaming others excessively.'],
      ['What is conflict resolution story?', 'Collaboration empathy outcome—team dynamics signal.'],
      ['What is leadership without authority?', 'Influence persuasion data-driven decisions cross-team initiatives.'],
      ['What is diversity inclusion question?', 'Respect inclusive language policies—authenticity not rehearsed platitudes only.'],
      ['What is salary negotiation timing?', 'After offer in hand—ranges research levels.fyi tactfully—varies region culture.'],
      ['What is mock interview value?', 'Feedback loop reduce anxiety time management practice—peers platforms.'],
      ['What is continuous learning narrative?', 'Side projects certifications open source—growth mindset evidence.'],
    ],
    codeBased: [
      ['Estimate QPS rough order magnitude', 'Practice mental math.'],
      ['Sketch REST endpoints CRUD', 'API design clarity.'],
      ['Draw DB schema primary foreign keys', 'Normalization trade-offs denormalization when.'],
      ['Hash partition vs range partition trade-off', 'Hot spots vs range queries.'],
      ['Write pseudocode rate limiter token bucket', 'Algorithm clarity.'],
      ['List failure modes redundancy backups', 'Reliability thinking.'],
      ['CAP choice for bank vs social feed', 'Different domains different priorities.'],
      ['Caching layers CDN browser', 'End-to-end path.'],
      ['Back-of-envelope storage video streaming', 'Bandwidth storage estimates.'],
      ['SLA calculation downtime minutes per year', 'Nine nines math practice.'],
    ],
    seniorScenario: [
      ['Tell me production outage you led—structure?', 'Detection mitigation root cause prevention metrics communication.'],
      ['Disagreed with manager technical decision?', 'Data respect escalation outcomes—maturity signal.'],
      ['Scaled team hiring mentoring?', 'Onboarding quality bar diversity interviewing experience.'],
      ['Inherited legacy system strategy?', 'Strangler incremental risk management stakeholder communication.'],
      ['Security incident communication?', 'Transparency legal obligations customer trust timelines.'],
      ['Prioritization tech debt vs features?', 'Framework quantifying risk product partnership error budgets.'],
    ],
    wrongAnswers: [
      'You should never ask clarifying questions in a system design interview.',
      'STAR stories should be at least 20 minutes long.',
      'The only goal of behavioral interviews is to test memorized answers.',
      'System design interviews never require any math.',
      'You should criticize your previous employer to show honesty.',
      'Negotiation should happen before you know the role scope.',
    ],
  },

  90: {
    conceptual: [
      ['What is full mock interview simulation?', 'Timed multi-section coding system design behavioral—mirror real process reduce anxiety.'],
      ['What is interviewer roleplay feedback?', 'External coach peer—blind spots communication clarity time management.'],
      ['What is rubric self-assessment?', 'Grade communication correctness trade-offs depth—structured improvement plan.'],
      ['What is time boxing practice?', '45 min problem—force prioritization MVP partial solutions better than incomplete perfectionism paralysis.'],
      ['What is articulating thought process?', 'Think aloud—interviewers evaluate reasoning not only final answer silent genius fails communication.'],
      ['What is managing stress physiology?', 'Sleep breathing breaks growth mindset—performance psychology underrated.'],
      ['What is company-specific research?', 'Engineering blog values interview loop—tailor examples stories—authenticity.'],
      ['What is follow-up thank you note?', 'Some cultures companies matter—brief professional gratitude not desperate.'],
      ['What is offer evaluation beyond salary?', 'Equity benefits growth manager team tech stack remote flexibility holistic life decision.'],
      ['What is continuous iteration?', 'Each mock interview one improvement focus communication speed edge cases testing habit.'],
      ['What is portfolio GitHub polish?', 'Readme clarity runnable demos—recruiters skim quickly first impression.'],
      ['What is reference preparation?', 'Align stories with references former managers—consistent narrative ethical honesty.'],
      ['What is negotiation multiple offers?', 'Ethical transparency timelines respectful—burning bridges costly small industry.'],
      ['What is onboarding plan after offer?', 'Learning roadmap first 30 60 90—hit ground running reputation early.'],
      ['What is lifelong interview skill?', 'Even as hiring manager interviewing candidates—symmetry empathy calibration.'],
    ],
    codeBased: [
      ['Timed LeetCode contest mode practice', 'Pressure simulation.'],
      ['Pramp interviewing.io platforms', 'External mock.'],
      ['Record yourself solve problem review', 'Communication critique awkward valuable.'],
      ['Checklist before interview sleep food materials', 'Logistics reduce anxiety.'],
      ['Flashcards system design concepts spaced repetition', 'Memory retention.'],
      ['Write stories STAR file spreadsheet', 'Organize examples multiple prompts reuse adapt.'],
      ['Company values map stories Amazon LP', 'Prepared examples not generic.'],
      ['System design template outline personal', 'Headings reuse accelerate structure under pressure.'],
      ['Test IDE setup shortcuts', 'Efficiency reduces stress live coding.'],
      ['Practice explaining Big-O while coding', 'Multitasking interview realism.'],
    ],
    seniorScenario: [
      ['Mock interview feedback brutal—emotion?', 'Growth mindset separate self-worth from performance iteration professional athlete mindset.'],
      ['Imposter syndrome strong?', 'Common high performers—evidence journal achievements objective reality therapy resources.'],
      ['Burnout during job search?', 'Sustainable schedule boundaries support network health priority long career.'],
      ['Multiple rejections demoralizing?', 'Stochastic process variance—learn per round persistence calibrated improvement not luck only.'],
      ['Onsite travel logistics remote hybrid?', 'Adapt preparation environment camera lighting internet backup plan.'],
      ['Post-offer negotiation fear conflict?', 'Framing collaboration mutual fit preparation scripts professional respect—practice roleplay.'],
    ],
    wrongAnswers: [
      'Mock interviews are useless compared to only reading books.',
      'You should memorize one story that answers every behavioral question.',
      'Full mock simulations guarantee you will pass real interviews.',
      'Communication skills do not matter if your code is perfect.',
      'You should accept the first offer immediately without questions.',
      'Preparation ends when you get the job offer.',
    ],
  },
};
