/** Interview Drill — Days 19–40 (15 / 10 / 6 / 6) — topic-specific */

export const B_19_40 = {
  19: {
    conceptual: [
      ['What does Big-O measure?', 'Upper bound on how runtime or memory grows as input size n increases—ignore constants and lower-order terms.'],
      ['Difference between O(n) and O(n²)?', 'Linear work scales proportionally to n; quadratic doubles impact when n doubles—nested loops over data often yield O(n²).'],
      ['What is amortized analysis?', 'Average cost per operation over a sequence—e.g., dynamic array append is O(1) amortized though occasional resize costs O(n).'],
      ['What is Ω and Θ?', 'Ω is lower bound; Θ means tight bound (same growth upper and lower)—interviews often focus on Big-O upper bounds.'],
      ['Why compare algorithms asymptotically?', 'Predict behavior at large n; constants matter for small n but scalability dominates in system design.'],
      ['What is space complexity?', 'Extra memory beyond input—O(1) extra means constant auxiliary space regardless of n.'],
      ['What is worst-case vs average-case?', 'Worst guarantees under adversarial input; average assumes distribution—both matter for different SLAs.'],
      ['How do you analyze a single loop over array?', 'Typically O(n) if body is O(1) per element.'],
      ['How do you analyze nested loops?', 'Multiply depths if each depends on n—e.g., i and j both to n often O(n²).'],
      ['What is binary search complexity?', 'O(log n) on sorted array—halves search space each step.'],
      ['What is hash map average lookup?', 'O(1) average for get/put; O(n) worst case if many collisions—know your hash function and load factor.'],
      ['What is the master theorem (sketch)?', 'Recurrence T(n)=aT(n/b)+f(n) solves many divide-and-conquer recurrences—compare f(n) to n^(log_b a).'],
      ['Why can sorting dominate complexity?', 'O(n log n) sort + O(n) scan may beat O(n²) brute force for structured problems.'],
      ['What is pseudo-polynomial?', 'Looks polynomial in numeric value but exponential in bit length—relevant for subset-sum style DP.'],
      ['How does parallelism change Big-O?', 'Big-O is sequential steps; wall-clock may drop with parallel hardware but work complexity may stay the same.'],
    ],
    codeBased: [
      ['Given nested for i,j to n, state complexity.', 'O(n²) time, O(1) extra space if no large aux structures.'],
      ['Binary search: why mid = lo + (hi-lo)/2?', 'Avoids integer overflow from (lo+hi)/2 in large indices.'],
      ['Count operations in: for i 0..n: for j i..n', 'Roughly n²/2 iterations—still O(n²).'],
      ['When does HashMap degrade to O(n)?', 'Many collisions under poor hash or adversarial keys—use balanced structures or crypto hash if needed.'],
      ['Space of merge sort vs heap sort?', 'Merge sort O(n) extra; heap sort O(1) extra—trade memory for stability and constants.'],
      ['Two-pointer on sorted array for pair sum—complexity?', 'O(n) time after sort O(n log n) if not already sorted.'],
      ['Analyze recursion depth for factorial n.', 'O(n) stack frames—may overflow for large n.'],
      ['DP with n states and O(1) transition each?', 'O(n) time and O(n) space—or rolling array for O(1) space if applicable.'],
      ['Compare BFS vs DFS on graph with V,E.', 'BFS/DFS O(V+E) time with adjacency list.'],
      ['What complexity to build heap from n elements?', 'O(n) heapify all elements—not O(n log n) repeated insert for building from array.'],
    ],
    seniorScenario: [
      ['Service latency p99 spikes when data doubled—how investigate?', 'Profile hot paths, check algorithmic regression (O(n²) creep), DB indexes, and GC—not just CPU%.'],
      ['Interview: “Is this O(n) or O(n log n)?”—ambiguous code.', 'Walk through loops/recursion, state transitions; mention amortized if relevant.'],
      ['Capacity planning: algorithm O(n²) in batch job—ops fix?', 'Shard input, parallelize independent chunks, or replace algorithm; don’t only scale hardware.'],
      ['Cache complexity in real systems?', 'Memory hierarchy effects dominate at scale—locality matters even if Big-O same.'],
      ['Competitive online algorithms—relate?', 'Different model (future unknown); mention when streaming constraints apply.'],
      ['Team ships “fast” hash map abuse—risk?', 'Worst-case DoS or unbounded memory—need bounds and monitoring.'],
    ],
    wrongAnswers: [
      'Big-O tells you exact milliseconds on a given machine.',
      'O(2n) is fundamentally larger than O(n) in asymptotic terms.',
      'Nested loops always mean O(n³).',
      'Space complexity includes the input array itself.',
      'Binary search works on any array without precondition.',
      'HashMap worst-case lookup is always O(1).',
    ],
  },

  20: {
    conceptual: [
      ['What is the two-pointer technique?', 'Two indices move through array/string—often from both ends or both forward—to reduce brute force O(n²) to O(n).'],
      ['When is two pointers applicable?', 'Sorted arrays, palindromes, pair-sum with ordering, merging sorted lists—monotonic movement exploits structure.'],
      ['Difference from sliding window?', 'Sliding window maintains a subarray range; two pointers often meet or chase on fixed structure—related but different patterns.'],
      ['What is Dutch national flag problem?', 'Partition array into regions by value with linear scan—related pointer discipline.'],
      ['Why sort before two-sum sometimes?', 'Sorting enables moving pointers based on comparison to target—trade index loss if original indices needed.'],
      ['What is “collision” of pointers?', 'When left and right pointers cross or meet—termination condition.'],
      ['Can two pointers work on linked lists?', 'Yes—detect cycle (Floyd), merge sorted lists, middle node.'],
      ['What is three-sum reduction?', 'Fix one element, two-pointer on remainder—O(n²) after sort.'],
      ['In-place removal of duplicates sorted array?', 'Slow/fast pointer writes unique elements forward.'],
      ['What is trapping rain water intuition?', 'Left/right max arrays or two pointers with running max—O(n) time.'],
      ['Two-pointer vs binary search?', 'Binary search halves search space on sorted data; two pointers often scan with two moving indices simultaneously.'],
      ['What if input not sorted for pair sum?', 'Hash map O(n) space for complements, or sort losing stability of indices—choose per requirements.'],
      ['Stability of partition algorithms?', 'Some partition schemes stable, many quicksort partitions are not—know interview variant.'],
      ['What is merge step in merge sort?', 'Two pointers walk two sorted halves—classic pattern.'],
      ['Edge case: empty or length-1 array?', 'Pointers may not enter loop—always test boundaries.'],
    ],
    codeBased: [
      ['Palindrome check with two pointers on char array.', 'while (l<r) if (s[l++]!=s[r--]) return false; return true;'],
      ['Pair sum sorted: move lo/hi based on sum vs target.', 'if sum<target lo++; else if sum>target hi--; else found.'],
      ['Remove duplicates in-place sorted array return new length.', 'Slow pointer tracks write position; fast scans.'],
      ['Merge two sorted arrays without extra space (if fits).', 'Fill from end when merging into buffer with space at end.'],
      ['Container with most water: move shorter line.', 'Greedy two-pointer proof often asked—know intuition.'],
      ['Three-sum avoid duplicates after sort.', 'Skip equal adjacent values when advancing pointers.'],
      ['Fast/slow pointer start same for cycle detection.', 'If fast meets slow, cycle exists.'],
      ['Partition array around pivot (Lomuto/Hoare sketch).', 'Know one variant’s loop invariants.'],
      ['Two arrays merge pointer i,j.', 'Compare a[i], b[j], advance smaller—like merge step.'],
      ['Minimum window substring—related?', 'Sliding window with need counts—often separate pattern but contrasts with simple two-pointer.'],
    ],
    seniorScenario: [
      ['Image processing pipeline O(n²) per frame—missed SLA.', 'Downsample, GPU offload, or algorithm change; profile before blaming GC.'],
      ['Security: two-pointer on user string in C—risk?', 'Buffer bounds—Java safer but still validate lengths for DoS.'],
      ['Streaming data: can’t sort full array?', 'Use heaps, reservoir sampling, or approximate algorithms—two-pointer may not apply.'],
      ['Parallel two-pointer patterns?', 'Harder—partition first then parallel merge; sequential two-pointer often inherently sequential.'],
      ['Database index scan vs two-pointer in app?', 'Push work to DB when possible—less data movement.'],
      ['Regression: “optimized” pair sum wrong on duplicates.', 'Add test cases with repeated values and negative numbers.'],
    ],
    wrongAnswers: [
      'Two pointers always require sorted input.',
      'Two-pointer pair sum is O(n²) after sorting.',
      'Fast/slow pointers only work on arrays, never linked lists.',
      'You never need hash map if you use two pointers.',
      'Three-sum is always O(n log n).',
      'Two pointers from both ends always move both every step.',
    ],
  },

  21: {
    conceptual: [
      ['What is a singly linked list node?', 'Object with value and reference to next—no random access by index.'],
      ['Why O(n) to access element i?', 'Must walk from head i steps—unlike array O(1).'],
      ['What is dummy head sentinel?', 'Fake node before head simplifies insertion/deletion at head without special cases.'],
      ['How detect cycle?', 'Floyd’s tortoise/hare—fast moves 2 steps, slow 1; meeting implies cycle.'],
      ['How reverse linked list iteratively?', 'prev/cur/next pointers rewiring—O(n) time, O(1) space.'],
      ['Recursive reverse—complexity?', 'O(n) time, O(n) stack space—risk overflow on long lists.'],
      ['Merge two sorted lists?', 'Compare heads, attach smaller, advance—like merge sort merge.'],
      ['Find middle element?', 'Slow/fast—when fast reaches end, slow at middle (careful even count).'],
      ['What is doubly linked list benefit?', 'O(1) delete given node with prev pointer—used in LRU caches.'],
      ['Intersection of two lists?', 'Align lengths then walk together—or use hash set of nodes identity.'],
      ['Clone graph/list with random pointer?', 'Map old→new nodes—two-pass linking.'],
      ['Why avoid stack overflow on deep recursion?', 'Prefer iterative for production-sized lists.'],
      ['What is null-terminated list end?', 'next==null marks tail—always check NPE.'],
      ['Compare ArrayList vs LinkedList in Java?', 'ArrayList cache-friendly; LinkedList node overhead—most apps prefer ArrayList unless proven need.'],
      ['What is skip list (mention)?', 'Probabilistic structure for O(log n) search—alternative to balanced trees.'],
    ],
    codeBased: [
      ['Write iterative reverse of singly linked list.', 'Classic three-pointer while loop.'],
      ['Detect cycle return node or boolean?', 'Know Floyd variant to find start of cycle.'],
      ['Merge two sorted linked lists recursively.', 'Compare head1.data vs head2.data, recurse.'],
      ['Remove nth node from end one pass.', 'Two pointers n apart or length minus n.'],
      ['Add two numbers represented as reversed digit lists.', 'Carry digit, create new list.'],
      ['Palindrome linked list O(1) space?', 'Reverse second half, compare halves.'],
      ['Delete node with only pointer to that node (not head).', 'Copy next value into node and delete next—classic trick.'],
      ['Deep copy list with random pointer—sketch.', 'HashMap original→copy; second pass assign random.'],
      ['Rotate list by k places.', 'Connect tail to head, find new break point.'],
      ['Middle of linked list—even length pick second?', 'Clarify in interview which middle definition.'],
    ],
    seniorScenario: [
      ['Concurrent modification of LinkedList—fail-fast?', 'Iterator throws CME; use concurrent structures or synchronize.'],
      ['Memory overhead of LinkedList in JVM?', 'Node objects + references—GC pressure vs ArrayList for large sequences.'],
      ['LRU cache implementation choice?', 'HashMap + doubly linked list for O(1) get/put eviction.'],
      ['Distributed linked structures?', 'Usually not—use IDs and DB relations; pointer swizzling in ORMs.'],
      ['Stack overflow in recursive list walk on huge list?', 'Switch to iterative or increase stack (last resort).'],
      ['Serialization of cyclic list?', 'Need protocol—by design acyclic or break cycle with sentinel IDs.'],
    ],
    wrongAnswers: [
      'Linked list supports O(1) random access by index.',
      'Floyd cycle detection always finds cycle length in first pass.',
      'Java LinkedList is always faster than ArrayList for all workloads.',
      'Reversing a list requires O(n) extra space always.',
      'Dummy head changes asymptotic complexity.',
      'Merge sorted lists cannot be done recursively.',
    ],
  },

  22: {
    conceptual: [
      ['What is a stack (LIFO)?', 'Push/pop at one end—call stacks, undo, DFS.'],
      ['What is a queue (FIFO)?', 'Enqueue tail, dequeue head—BFS, scheduling.'],
      ['Java Deque implementations?', 'ArrayDeque (resizable array) often preferred over LinkedList for stacks/queues.'],
      ['What is priority queue?', 'Heap-backed—poll returns highest (or lowest) priority element.'],
      ['Stack with min in O(1)?', 'Auxiliary stack tracking min so far or store pairs (value, currentMin).'],
      ['Monotonic stack use?', 'Next greater element, histogram problems—maintain increasing/decreasing property.'],
      ['BFS with queue on graph?', 'Level-order tree traversal; shortest path in unweighted graph.'],
      ['Circular buffer / ring queue?', 'Fixed-size array with head/tail pointers—bounded queues.'],
      ['BlockingQueue in Java?', 'put/take block for producer-consumer—ArrayBlockingQueue, LinkedBlockingQueue.'],
      ['Stack from queues (interview puzzle)?', 'Possible with two queues—simulate recursion depth.'],
      ['What is double-ended queue Deque?', 'addFirst/addLast—used in sliding window max.'],
      ['Compare Stack class vs Deque?', 'Stack legacy; prefer Deque interface—Stack extends Vector oddly.'],
      ['Amortized cost ArrayDeque push?', 'O(1) amortized resizing.'],
      ['What is work-stealing deque?', 'ForkJoinPool parallel tasks—advanced concurrency structure.'],
      ['Priority queue with custom comparator?', 'Min vs max heap depending on comparator order.'],
    ],
    codeBased: [
      ['Valid parentheses with stack.', 'Push opens, pop match closes; stack empty at end.'],
      ['Evaluate RPN with stack.', 'Push numbers, apply operator to two pops.'],
      ['BFS level-order binary tree using Queue.', 'Queue of nodes; poll, offer children.'],
      ['Sliding window maximum with deque.', 'Remove smaller indices from back when new larger arrives; pop front if out of window.'],
      ['Min stack push/pop/getMin all O(1).', 'Auxiliary stack or store (val, min) pairs.'],
      ['Implement queue using two stacks.', 'Transfer between stacks amortized O(1).'],
      ['Next greater element array—monotonic stack.', 'Iterate, pop while smaller than current.'],
      ['DFS iterative using stack.', 'Push nodes, pop explore—mimic recursion.'],
      ['PriorityQueue top K elements.', 'Maintain size-k max-heap for smallest K or min-heap for largest K—clarify.'],
      ['ArrayDeque as stack—methods?', 'push/pop/peek vs addLast/removeLast/peekLast—be consistent.'],
    ],
    seniorScenario: [
      ['Unbounded queue in messaging—risk?', 'Memory exhaustion; need back-pressure, bounded queues, drop policies.'],
      ['Priority inversion with priority queue threads?', 'OS scheduling issue—mention when discussing real-time systems.'],
      ['Kafka partition as queue—ordering?', 'Per-partition order; parallel consumers across partitions.'],
      ['Web server request queue overload?', '503, load shedding, circuit breakers—queue depth metrics.'],
      ['Thread pool queue full—policy?', 'CallerRuns, Abort, Discard—each has trade-offs.'],
      ['Stack trace depth in production errors?', 'Deep recursion or framework bug—monitor stack size.'],
    ],
    wrongAnswers: [
      'Queue always means FIFO in every Java class named Queue.',
      'PriorityQueue guarantees FIFO among equal priorities.',
      'java.util.Stack is the preferred stack implementation today.',
      'ArrayDeque cannot be used as a LIFO stack.',
      'BFS always uses a stack data structure.',
      'BlockingQueue never blocks the caller.',
    ],
  },

  23: {
    conceptual: [
      ['How does HashMap work?', 'Buckets from hash(key)%n; collision chains or trees; equals verifies key match.'],
      ['equals/hashCode contract?', 'Equal objects must have same hashCode; unequal may collide—must handle collisions.'],
      ['Load factor and resize?', 'When entries exceed capacity*loadFactor, table doubles (roughly)—rehash all entries.'],
      ['Java 8+ treeify?', 'Long chains convert to balanced trees—O(log n) worst per bucket vs O(n).'],
      ['Why immutable keys preferred?', 'If key mutates after insert, bucket lookup breaks.'],
      ['What is consistent hashing?', 'Distributed caches—minimize key movement when nodes add/remove.'],
      ['Open addressing vs chaining?', 'Alternative collision strategies—Java HashMap uses chaining (with treeify).'],
      ['Complexity average vs worst?', 'Average O(1); worst O(n) all collide—design hashes well.'],
      ['What is IdentityHashMap?', 'Uses == instead of equals—reference identity keys.'],
      ['WeakHashMap use?', 'Entries garbage-collected when key only weakly reachable—caches with auto eviction.'],
      ['LinkedHashMap access order?', 'LRU mode moves entries on get—useful for caches.'],
      ['ConcurrentHashMap vs Collections.synchronizedMap?', 'CHM finer locking/CAS segments—better concurrent throughput.'],
      ['What makes a good hash function?', 'Uniform distribution, fast, uses all key fields relevant to equality.'],
      ['Hash flooding attack?', 'Adversarial keys same bucket—mitigate with salted hashing or treeify.'],
      ['ComputeIfAbsent?', 'Atomic “get or compute” for maps—careful with recursive compute.'],
    ],
    codeBased: [
      ['Count frequencies with HashMap merge.', 'map.merge(k,1,Integer::sum);'],
      ['Group list of strings by first char.', 'Map<Character, List<String>> or computeIfAbsent.'],
      ['Detect anagrams via character counts hash.', 'Normalize sorted string or count array as key.'],
      ['Two-sum complement with HashSet/Map.', 'Store seen values; check target-current in map.'],
      ['Implement equals/hashCode for value class.', 'Use Objects.hash(field1,field2); equals on same fields.'],
      ['Rehashing on resize—what happens?', 'Buckets redistributed; iterator may fail-fast if concurrent mod.'],
      ['Use IdentityHashMap example.', 'Dedup object graph by reference not equals.'],
      ['ConcurrentHashMap compute—thread safety?', 'Atomic per-bin; still document compound operations.'],
      ['HashSet backed by HashMap—add complexity?', 'Same as map put—O(1) average.'],
      ['Bad hash: only high bits—symptom?', 'Collisions cluster in low buckets—mask with spread functions (like HashMap mix).'],
    ],
    seniorScenario: [
      ['Redis cluster resharding—conceptual tie?', 'Consistent hashing, slot migration—similar problem domain.'],
      ['Large HashMap pause on resize?', 'Long pause if huge table—consider pre-sizing or off-heap structures.'],
      ['Custom key type in distributed map—serialization?', 'Stable equals across versions—schema evolution.'],
      ['Security: hashDoS on servlet parameter map?', 'JDK mitigations; limit input sizes; randomized hash seeds historically.'],
      ['ORM L2 cache keying—pitfall?', 'Include all relevant fields; mutable entities break cache.'],
      ['Metrics: HashMap memory per entry?', 'Footprint of nodes, pointers—tune initial capacity if known size.'],
    ],
    wrongAnswers: [
      'hashCode must be unique for every distinct object.',
      'Equal objects can have different hashCodes if equals is overridden.',
      'HashMap iteration order matches insertion order by default.',
      'You can safely use mutable StringBuilder as HashMap key.',
      'ConcurrentHashMap allows null keys like HashMap.',
      'Worst-case HashMap get is always O(1).',
    ],
  },

  24: {
    conceptual: [
      ['Binary tree vs binary search tree?', 'BST property: left < node < right for all nodes—enables ordered search.'],
      ['Tree traversals?', 'Preorder, inorder, postorder, level-order—each serves different use cases.'],
      ['BST search complexity?', 'O(h) height; balanced O(log n), skewed O(n).'],
      ['What is balanced tree?', 'AVL, Red-Black—guarantee O(log n) height with rotations.'],
      ['What is heap?', 'Complete binary tree with heap property—used in priority queues.'],
      ['Trie (prefix tree)?', 'Strings share prefixes—efficient autocomplete, O(m) per query length.'],
      ['Lowest common ancestor in BST?', 'Walk from root comparing keys—O(h).'],
      ['Serialize binary tree?', 'Preorder with null markers or level-order with BFS—reconstruct carefully.'],
      ['Diameter of tree?', 'Longest path between any two nodes—often two DFS or height recursion.'],
      ['What is segment tree / Fenwick?', 'Range query structures—advanced competitive programming topics.'],
      ['Morris traversal?', 'O(1) space inorder—threaded tree trick—rare in interviews but impressive.'],
      ['N-ary tree representation?', 'List of children per node—serialize to bracket strings.'],
      ['Red-black vs AVL?', 'AVL stricter balance faster lookups more rotations; RB fewer rotations better insert—Java TreeMap is RB.'],
      ['B-tree use case?', 'Databases disk blocks—wide nodes reduce height for disk I/O.'],
      ['Tree DP on rooted tree?', 'Post-order accumulate subtrees—common pattern.'],
    ],
    codeBased: [
      ['Max depth of binary tree recursive.', '1+max(left,right) base null 0.'],
      ['Validate BST—pass min/max bounds.', 'Or inorder must be strictly increasing.'],
      ['Level-order traversal with queue.', 'Queue nodes; track size per level if needed.'],
      ['Invert binary tree.', 'Swap children recursively or iteratively.'],
      ['Path sum equals target—backtrack or recursion.', 'Track current sum along path.'],
      ['Kth smallest in BST?', 'Inorder counter or augmented tree with subtree sizes.'],
      ['Lowest common ancestor binary tree (not BST).', 'Post-order return pointer if found in subtrees.'],
      ['Same tree structure and values?', 'Simultaneous recursion p,q.'],
      ['Serialize to string—example approach.', 'Preorder with "null" for missing.'],
      ['Count nodes complete tree—formula?', 'If complete, use math; else recurse—interview variant.'],
    ],
    seniorScenario: [
      ['DB index B-tree vs app in-memory tree?', 'Different cost models—disk page size matters.'],
      ['GC and deep object graphs of trees?', 'Stack depth for traversal; prefer iterative if millions of nodes.'],
      ['XML/JSON DOM trees memory?', 'SAX vs DOM—streaming vs tree—large files.'],
      ['Distributed consensus tree (Raft log)—related?', 'Append-only log structure—not binary tree but ordered thinking.'],
      ['Decision tree ML model serialization?', 'Different domain—avoid confusing with CS trees in same answer.'],
      ['Threaded binary tree in UI component trees?', 'React fiber-like structures—traversal for rendering.'],
    ],
    wrongAnswers: [
      'Inorder traversal of any binary tree always yields sorted order.',
      'BST height is always log n.',
      'Heaps allow efficient search for arbitrary element in O(1).',
      'Binary tree must have exactly two children per node.',
      'TreeMap is implemented as a simple linked list.',
      'Trie can only store English lowercase letters.',
    ],
  },

  25: {
    conceptual: [
      ['What is a binary heap?', 'Complete binary tree with heap property: min-heap parent ≤ children; max-heap opposite.'],
      ['Array representation of heap?', 'Index i: children 2i+1,2i+2; parent (i-1)/2—no pointers needed.'],
      ['Heapify up vs down?', 'After insert sift up; after replace root sift down—O(log n).'],
      ['Build heap from array complexity?', 'O(n) bottom-up heapify—not O(n log n) n inserts.'],
      ['PriorityQueue in Java min or max?', 'Min-heap by default; reverse Comparator for max.'],
      ['What is d-ary heap?', 'More children per node—shallower, wider—used in some algorithms.'],
      ['Heap sort steps?', 'Build max heap, swap root with end, heapify reduced heap—O(n log n) in-place unstable.'],
      ['Median from two heaps?', 'Low max-heap + high min-heap balance—O(log n) insert, O(1) median.'],
      ['Fibonacci heap (mention)?', 'Theoretical improvements for decrease-key—rare in practice interviews.'],
      ['When heap beats sorting full array?', 'When only top K needed—not full sort.'],
      ['Indexed priority queue?', 'Supports decrease-key by index—Dijkstra optimizations.'],
      ['Latency of poll vs peek?', 'peek O(1) root; poll O(log n) restore heap.'],
      ['Parallel heaps?', 'Hard—need concurrent priority structures (lock-free heaps advanced).'],
      ['External memory heap?', 'For data larger than RAM—layered with disk.'],
      ['Compare TreeSet vs PriorityQueue ordering?', 'TreeSet sorted unique; PQ allows duplicates, only min/max efficient.'],
    ],
    codeBased: [
      ['Top K frequent elements—heap approach.', 'Min-heap size k of pairs (freq,key) or bucket sort alternative.'],
      ['Merge k sorted lists with heap.', 'Poll min head, push next from that list.'],
      ['Implement heapify down for max heap.', 'Compare with left/right child swap down.'],
      ['PriorityQueue with Comparator.reverseOrder.', 'Max-heap for integers.'],
      ['kth largest element—quickselect vs heap?', 'Trade average time vs worst and memory.'],
      ['Sliding window median (hard)—data structures?', 'Two heaps or multiset—know existence.'],
      ['Dijkstra PQ relaxation sketch.', 'Dist map + PQ of nodes by tentative distance.'],
      ['Heap sort in-place swap root/end.', 'Classic loop.'],
      ['Insert into min heap array manually.', 'Add end, sift up.'],
      ['Why offer/poll vs add/remove in PriorityQueue?', 'add throws on failure; offer returns false—prefer offer in bounded settings.'],
    ],
    seniorScenario: [
      ['Job scheduler priority inversion?', 'Lower priority task holds lock needed by high—OS topic related to priorities.'],
      ['Storm of timer tasks in PQ—lag?', 'O(log n) each; millions of timers—time wheel alternative.'],
      ['GC root scanning vs heap?', 'Different “heap”—don’t confuse memory heap with data structure heap.'],
      ['Distributed priority queue?', 'Hard—often shard by priority bands or use external broker priority topics.'],
      ['Real-time system missed deadline—heap size?', 'Check priority ordering bugs and clock skew.'],
      ['Cache eviction LFU with heap?', 'Frequency counts + min-heap complexity—often combined structures.'],
    ],
    wrongAnswers: [
      'Binary heap allows O(1) search for any element.',
      'PriorityQueue in Java iterates elements in priority order.',
      'Heaps are always implemented with pointers, never arrays.',
      'Build heap from n elements is always Ω(n log n).',
      'Max heap means largest element is at the leaves.',
      'Heap sort is stable by default.',
    ],
  },

  26: {
    conceptual: [
      ['Stable sort definition?', 'Equal elements keep relative order—important for multi-key sorts.'],
      ['Which sorts are stable in Java?', 'TimSort (objects), merge sort stable; typical quicksort unstable.'],
      ['Quicksort average vs worst?', 'Average O(n log n); worst O(n²) bad pivot—randomize or median-of-three.'],
      ['Merge sort properties?', 'O(n log n) worst, O(n) extra space, stable.'],
      ['Insertion sort when good?', 'Small n nearly sorted—O(n) best case adaptive.'],
      ['Counting sort radix sort?', 'Linear when range constraints—not comparison lower bound.'],
      ['Binary search precondition?', 'Monotonic ordering on indexed access—array sorted or rotated variants with care.'],
      ['Find rotation point in rotated sorted array?', 'Modified binary search O(log n).'],
      ['Lower_bound / upper_bound concepts?', 'First position where predicate true—Arrays.binarySearch variants.'],
      ['External sort?', 'Merge sorted chunks from disk—streaming large data.'],
      ['Parallel sort Arrays.parallelSort?', 'ForkJoin for large primitive arrays—speed vs overhead.'],
      ['Inversion count?', 'Merge sort augmentation—count cross inversions while merging.'],
      ['Selection vs quickselect?', 'Quickselect finds kth element average O(n).'],
      ['Bitonic sort (mention)?', 'Parallel sorting networks—niche.'],
      ['Compare sort vs heap for “top K”.', 'Heap O(n log k) often beats full O(n log n) sort when k small.'],
    ],
    codeBased: [
      ['Binary search first >= target (lower bound).', 'lo/hi loop variants—know one by heart.'],
      ['Merge two sorted arrays in place (with extra space at end).', 'Three pointers from end.'],
      ['Quicksort partition Lomuto outline.', 'Pivot placement; i,j pointers.'],
      ['Count inversions merge step.', 'When a[i]>b[j] add remaining left elements to count.'],
      ['Arrays.sort int[] vs Integer[]?', 'Primitives dual-pivot quicksort; objects TimSort.'],
      ['Comparator nullsFirst for sort.', 'Handle null keys safely.'],
      ['Search insert position in sorted array.', 'Binary search boundary.'],
      ['Rotated array find minimum index.', 'Compare mid with right boundary.'],
      ['Stable counting sort for small range integers.', 'Prefix sums for positions.'],
      ['Parallel sort threshold?', 'JDK uses size threshold before parallel—tunable implementation detail.'],
    ],
    seniorScenario: [
      ['DB ORDER BY vs app sort—when which?', 'Large data: sort in DB with index; paginate—avoid loading all rows.'],
      ['Sort huge file on disk—approach?', 'External merge sort chunks; k-way merge.'],
      ['Non-transitive Comparator bug—symptom?', 'IllegalArgumentException from TimSort or inconsistent ordering—deadly in production.'],
      ['Locale-sensitive sort mismatch?', 'Use Collator; binary sort wrong for human display.'],
      ['Distributed sort (MapReduce)?', 'Shuffle by key, sort partitions—different paradigm.'],
      ['Time-series data out-of-order ingest?', 'Sort windows or use data structures accepting disorder.'],
    ],
    wrongAnswers: [
      'Arrays.sort on primitives uses TimSort.',
      'Binary search works on unsorted array if you check each step.',
      'Quicksort worst case cannot be avoided.',
      'Merge sort is in-place with O(1) extra space typically.',
      'Stable sort means equal elements swap randomly.',
      'Binary search always returns an index when element missing.',
    ],
  },

  27: {
    conceptual: [
      ['What is dynamic programming?', 'Break problem into overlapping subproblems; cache results to avoid exponential recomputation.'],
      ['Top-down vs bottom-up?', 'Memoization recursion vs iterative table filling—same math, different stack/space trade-offs.'],
      ['What is optimal substructure?', 'Optimal solution built from optimal solutions to subproblems.'],
      ['Classic 0/1 knapsack recurrence?', 'dp[i][w] max value using first i items with weight limit w—take or skip item.'],
      ['Unbounded knapsack difference?', 'Can reuse items—infinite loop variant in inner loop order.'],
      ['LCS longest common subsequence?', 'Match/mismatch recurrence; O(nm) table.'],
      ['Edit distance?', 'Insert/delete/substitute costs; DP table.'],
      ['Fibonacci memo vs tabulation?', 'Memo O(n) stack depth; tabulation O(1) space rolling.'],
      ['Coin change variants?', 'Count ways vs min coins—different recurrences; infinite vs finite coins.'],
      ['Palindrome DP?', 'Table[i][j] whether substring palindrome—expand or fill diagonally.'],
      ['State compression bitmask DP?', 'NP-hard subsets—2^n states—small n only.'],
      ['DAG shortest path as DP?', 'Topological order relaxation—linear time on DAG.'],
      ['When DP fails?', 'If optimal substructure or overlapping subproblems don’t hold—greedy may apply instead.'],
      ['Space optimization in DP?', 'If recurrence only needs previous row, keep two arrays or rolling variables.'],
      ['Digit DP (mention)?', 'Count numbers in range with digit constraints—competitive programming pattern.'],
    ],
    codeBased: [
      ['Fibonacci bottom-up O(n) time O(1) space.', 'Keep a,b iterate.'],
      ['Climbing stairs distinct ways—Fib variant.', 'dp[i]=dp[i-1]+dp[i-2].'],
      ['House robber linear—adjacent constraint.', 'dp[i]=max(dp[i-1], dp[i-2]+nums[i]).'],
      ['Coin change min coins—BFS or DP.', 'Initialize INF; relax.'],
      ['LIS O(n log n) patience sorting.', 'Binary search on tails array.'],
      ['Matrix chain multiplication order?', 'Split at k; minimize cost—O(n³).'],
      ['Subset sum exists—boolean DP.', 'Bitset optimization possible.'],
      ['Decode ways string digits—DP.', 'Single/double digit transitions.'],
      ['Unique paths grid with obstacles.', 'dp[i][j] sum from top and left.'],
      ['Longest palindromic substring expand centers.', 'O(n²) time—also DP table possible.'],
    ],
    seniorScenario: [
      ['DP solution too slow in production—n large?', 'Greedy proof, approximation algorithms, or mathematical closed form.'],
      ['Memory blow-up 2D DP table?', 'Rolling array, sparse representation, or switch algorithm.'],
      ['Caching recursive microservice—DP analogy?', 'Memoization across requests—invalidate correctness carefully.'],
      ['Scheduling weighted interval DP?', 'Sort by end time; dp[i] max profit—classic.'],
      ['ML hyperparameter grid search vs DP?', 'Different—avoid confusing ML tuning with algorithmic DP.'],
      ['Stack overflow in deep memo recursion?', 'Convert to iterative DP.'],
    ],
    wrongAnswers: [
      'DP always runs faster than brute force for every problem.',
      'Greedy algorithms never work when DP applies.',
      'Memoization and tabulation always use the same asymptotic time.',
      '0/1 knapsack can be solved greedily by value/weight ratio always.',
      'Fibonacci DP must keep entire table of size n.',
      'Dynamic programming requires the problem to be NP-hard.',
    ],
  },

  28: {
    conceptual: [
      ['What is a generic type parameter?', 'Placeholder like T that becomes concrete at compile time—type safety without casting everywhere.'],
      ['Type erasure?', 'Generics compiled to raw types + casts; no T at runtime—limits some checks.'],
      ['Bounded type parameters T extends Number?', 'T must be subtype of Number—allows doubleValue etc.'],
      ['Wildcard ? extends vs ? super?', 'PECS: producer extends, consumer super—for flexibility and safety.'],
      ['Why can’t new T()?', 'Erasure—constructor unknown at runtime—use factories or Class<T>.'],
      ['Raw types still allowed?', 'Legacy interop—avoid; unchecked warnings.'],
      ['Generic array creation?', 'Illegal new T[]—use reflection Array.newInstance or List<T>.'],
      ['Bridge methods?', 'Compiler generates for overriding generic methods—rare debugging topic.'],
      ['Type inference var and diamond <>?', 'Reduce verbosity; still compile-time checked.'],
      ['Reifiable types?', 'Primitives, raw types, arrays—know generics limitations with arrays.'],
      ['What is Class<T> used for?', 'Runtime type token for reflection when erasure hides T.'],
      ['Generic methods static <T> T middle(T[] a)?', 'Type parameter on method, not class.'],
      ['Covariance in Java arrays vs generics?', 'Arrays covariant (unsafe); generics invariant—different design.'],
      ['Kotlin reified (mention)?', 'Different language—inline reified—not in Java.'],
      ['Spring BeanFactory getBean(Class<T>) pattern?', 'Passes Class token to recover type after erasure.'],
    ],
    codeBased: [
      ['Generic class Box<T> with get/set.', 'Field T value; compile-time safety.'],
      ['Sort List<Person> with Comparator—no raw.', 'Comparator.comparing(Person::getName).'],
      ['copy(List<? super T> dest, List<? extends T> src) example.', 'PECS illustration.'],
      ['Wildcard capture compile error fix?', 'Helper generic method with explicit type parameter.'],
      ['Avoid heap pollution varargs generic array.', 'Use @SafeVarargs or List.of.'],
      ['instanceof with generic in old code?', 'Raw checks only at runtime—use Class tokens.'],
      ['Define generic interface Repository<T,ID>.', 'CRUD signatures.'],
      ['Stream<T> map with generics inference.', 'map(Function<? super T,? extends R>).'],
      ['Pair<L,R> generic record Java 16+.', 'record Pair<L,R>(L l,R r){}'],
      ['Cannot catch T extends Throwable—why?', 'Erasure conflicts with catch mechanism—use wrappers.'],
    ],
    seniorScenario: [
      ['Jackson TypeReference for generic collections?', 'Preserves nested generic types for deserialization.'],
      ['Protobuf/Avro schemas vs Java generics?', 'Code generation separate—mapping layer handles types.'],
      ['API evolution add type parameter to class?', 'Binary compatibility challenges—use overloads or new types.'],
      ['Performance cost of generics?', 'Essentially none—erasure to casts; focus elsewhere.'],
      ['GSON TypeToken runtime generic—how?', 'Anonymous subclass preserves super type args via reflection.'],
      ['Framework proxies and generic signatures?', 'Sometimes need Annotation processing or Spring ResolvableType.'],
    ],
    wrongAnswers: [
      'Generics exist at runtime as reified T in the JVM.',
      'You can create new T() if T has a no-arg constructor.',
      'List<String> is a subtype of List<Object>.',
      'Wildcards ? have no difference from Object in generics.',
      'Type erasure means all type checks are removed at compile time.',
      'Generic methods cannot be static.',
    ],
  },

  29: {
    conceptual: [
      ['What is a functional interface?', 'Single abstract method interface—target for lambda expressions.'],
      ['Lambda vs anonymous class?', 'Lambda lighter syntax; captures effectively final vars; generates invokedynamic.'],
      ['What is method reference?', 'String::length shorthand for s->s.length()—four kinds static, instance, ctor, arbitrary.'],
      ['What is effectively final?', 'Local variable assigned once—can be captured by lambdas.'],
      ['Functional interfaces in java.util.function?', 'Predicate, Function, Consumer, Supplier—common shapes.'],
      ['Exception handling in lambdas?', 'Checked exceptions must be handled or wrapped—can’t throw checked without signature allowing.'],
      ['Serialization of lambdas?', 'Fragile—avoid unless stable capturing rules understood.'],
      ['Default methods interaction?', 'Functional interface can have many defaults if single abstract method remains.'],
      ['Composition Predicate.and/or/negate?', 'Combine boolean functions fluently.'],
      ['Currying (mention)?', 'Partial application—higher-order functions in FP style.'],
      ['Lambda performance vs anonymous?', 'Similar after JIT—avoid premature micro-optimization.'],
      ['this in lambda vs anonymous?', 'Lambda uses enclosing this; anonymous has own this for inner class.'],
      ['Target typing?', 'Compiler infers functional interface from assignment context.'],
      ['@FunctionalInterface purpose?', 'Compiler error if not exactly one abstract method—documentation.'],
      ['Parallel streams and lambdas?', 'Side effects dangerous—thread-safe operations required.'],
    ],
    codeBased: [
      ['Runnable lambda sleep.', '() -> { try { Thread.sleep(100);} catch...}'],
      ['Comparator.comparing(Person::getAge).reversed()', 'Method references chain.'],
      ['Predicate<String> not blank.', 's -> s != null && !s.isBlank().'],
      ['Function<String,Integer> parseInt safe.', 'Wrap parseInt in try or return Optional.'],
      ['Consumer chain andThen.', 'log.andThen(metrics).'],
      ['Supplier for lazy init.', '() -> expensiveCompute().'],
      ['Sort with lambda Comparator.', '(a,b) -> Integer.compare(a.x,b.x).'],
      ['Replace anonymous Runnable with lambda.', 'new Thread(() -> ...).start()'],
      ['Constructor reference ArrayList::new.', 'Supplier<ArrayList<String>>.'],
      ['Stream filter map collect with lambdas.', 'Classic pipeline.'],
    ],
    seniorScenario: [
      ['Framework passes lambdas to threads—thread safety?', 'Capture only immutable or thread-safe state.'],
      ['Debugging lambda stack traces?', 'Line numbers and method names sometimes obscure—use named methods if complex.'],
      ['Kotlin SAM vs Java functional—interop?', 'SAM conversion rules in Kotlin for Java APIs.'],
      ['Reactive APIs functional style—errors?', 'Signal propagation, not exceptions through streams casually.'],
      ['Code coverage on lambda branches?', 'May need extract method for meaningful branch coverage names.'],
      ['Serialization of captured closures in actors?', 'Dangerous—keep messages data-only.'],
    ],
    wrongAnswers: [
      'Lambdas can modify any local variable they read.',
      'Functional interface can have two abstract methods if defaults exist.',
      'Method references always allocate fewer objects than lambdas.',
      'Lambda syntax works in Java 7.',
      'You can throw checked exceptions freely from any lambda.',
      'Anonymous inner class and lambda are identical at runtime always.',
    ],
  },

  30: {
    conceptual: [
      ['What is the Streams API?', 'Declarative pipeline on data: source, intermediate ops (lazy), terminal op (eager).'],
      ['Lazy vs eager?', 'Intermediate ops build pipeline; nothing runs until terminal like collect/count/forEach.'],
      ['What is spliterator?', 'Splitting iterator backing parallel streams—correct splitting affects speedup.'],
      ['Parallel stream pitfalls?', 'Side effects, order, wrong data structures (LinkedList), fork/join overhead small data.'],
      ['map vs flatMap?', 'map 1:1; flatMap one-to-many flattening streams.'],
      ['collect Collectors.groupingBy?', 'Downstream collectors for aggregation—powerful but verbose.'],
      ['Optional from findFirst?', 'Represents absence safely—avoid get without isPresent or orElse.'],
      ['Primitive streams IntStream?', 'Avoid boxing in numeric pipelines—mapToInt etc.'],
      ['What is Stream builder?', 'When source not standard collection—Stream.builder().'],
      ['Short-circuit operations?', 'anyMatch, findFirst may not process entire stream—lazy benefit.'],
      ['Stateful intermediate operations distinct/sorted?', 'May buffer entire stream—memory cost.'],
      ['peek for debugging?', 'Side-effect only debugging—not guaranteed to execute if optimized away—don’t rely for logic.'],
      ['Iterator vs Stream?', 'Stream not reusable; Iterator imperative—choose per style and performance.'],
      ['try-with-resources on streams?', 'Files.lines must be closed—use try-with-resources.'],
      ['Custom collector?', 'Collector.of supplier/accumulator/combiner/finisher for domain aggregation.'],
    ],
    codeBased: [
      ['Filter map collect to list.', 'list.stream().filter(...).map(...).toList() (Java 16+).'],
      ['groupingBy count frequency.', 'Collectors.groupingBy(Function.identity(), Collectors.counting())'],
      ['partitioningBy predicate.', 'Map<Boolean, List<T>> split.'],
      ['reduce sum ints.', 'IntStream.of(1,2,3).sum()'],
      ['flatMap lines to words.', 'lines.stream().flatMap(line -> Arrays.stream(line.split("\\\\s+")))'],
      ['distinct sort limit pipeline.', 'Know order of ops matters.'],
      ['findFirst Optional handling.', 'ifPresent or orElseThrow.'],
      ['parallel stream wrong for LinkedList why?', 'Poor splitting—use ArrayList.'],
      ['Collect joining delimiter.', 'Collectors.joining(",")'],
      ['mapToObj boxed to List<String>.', 'IntStream.range(0,n).mapToObj(i -> ...)'],
    ],
    seniorScenario: [
      ['Production OOM on giant Stream distinct?', 'Buffered uniqueness or external sort—don’t hold all keys in memory.'],
      ['Parallel stream in web request—risk?', 'Steals common ForkJoinPool—may starve other work; use custom pool.'],
      ['Database pagination vs Stream of all rows?', 'Don’t load entire table into Stream without chunking.'],
      ['Logging inside stream peek in prod?', 'Noise and ordering issues—use proper tracing.'],
      ['Migration from loops to streams readability?', 'Not always clearer—team style guide.'],
      ['Stream closed twice exception?', 'IllegalStateException—streams single-use.'],
    ],
    wrongAnswers: [
      'Intermediate stream operations execute immediately when called.',
      'Parallel streams always make code faster.',
      'You can reuse a Stream after terminal operation.',
      'peek is intended for business logic side effects.',
      'map and flatMap are identical for collections of collections.',
      'findAny always returns the first element in encounter order.',
    ],
  },

  31: {
    conceptual: [
      ['What is Optional?', 'Container for absent or present value—avoid null returns as convention.'],
      ['When not to use Optional?', 'Fields, parameters, collections of Optionals—often overkill; use nullable with docs.'],
      ['orElse vs orElseGet?', 'orElseGet supplier lazy—avoids expensive default if present.'],
      ['flatMap in Optional?', 'Chaining possibly empty computations without nested Optionals.'],
      ['ifPresent vs map?', 'Side effect vs transform—map returns Optional.'],
      ['Optional.get danger?', 'Throws if empty—prefer orElseThrow with message.'],
      ['Stream findFirst Optional?', 'Natural fit—empty if no match.'],
      ['Optional serialization?', 'Not recommended—Optional not intended as DTO field.'],
      ['Kotlin nullable vs Optional?', 'Different idioms—interop awareness.'],
      ['API design return Optional?', 'Clearer than null for “no result” methods—document semantics.'],
      ['Optional empty singleton?', 'Optional.empty() reused—identity safe.'],
      ['filter on Optional?', 'Becomes empty if predicate false—like positive guard.'],
      ['Optional of nullable?', 'Optional.ofNullable(x)—empty if null.'],
      ['Combining Optionals?', 'map/flatMap chain; or use helper libraries in larger codebases.'],
      ['Performance of Optional?', 'Small object overhead—usually negligible vs clarity.'],
    ],
    codeBased: [
      ['Parse string to Optional<Integer> safely.', 'try/catch return Optional.empty on failure.'],
      ['Chain map flatMap without null checks.', 'opt.map(String::trim).filter(s->!s.isEmpty())'],
      ['Return first non-empty optional from list—pattern?', 'Stream of suppliers findFirst present—advanced.'],
      ['orElseThrow with message supplier.', 'orElseThrow(() -> new NotFoundException("x"))'],
      ['Optional in stream reduce?', 'Combine Optionals carefully—often flatMap.'],
      ['Legacy null return wrapped.', 'Optional.ofNullable(legacy())'],
      ['ifPresentOrElse Java 9+.', 'Both branches without separate isPresent.'],
      ['stream of Optionals filter present.', 'flatMap(Optional::stream) Java 9+.'],
      ['Do not use Optional.of(null)—what happens?', 'NPE—use ofNullable.'],
      ['JUnit assert optional present.', 'assertTrue(opt.isPresent()); or AssertJ assertions.'],
    ],
    seniorScenario: [
      ['JPA repository Optional return?', 'Spring Data supports Optional find—align with domain “not found”.'],
      ['RPC returning Optional across services?', 'May not serialize—use explicit response DTO with boolean found.'],
      ['Reactive Mono Optional anti-pattern?', 'Mono already nullable signal—double wrapper confusing.'],
      ['JSON Optional field Jackson?', 'Configure absent vs null carefully—defaults matter.'],
      ['Team bans Optional in public API—reasons?', 'Interop, style—document team rule.'],
      ['Performance critical path Optional allocation?', 'Rarely bottleneck—profile first.'],
    ],
    wrongAnswers: [
      'Optional eliminates the need for null checks everywhere in Java.',
      'Optional is a primitive type.',
      'Optional.of(null) returns Optional.empty().',
      'Optional should be used for every method parameter.',
      'Optional.get is the recommended default way to retrieve values.',
      'Optional serializes cleanly to JSON by default without configuration.',
    ],
  },

  32: {
    conceptual: [
      ['What is a record?', 'Immutable data carrier with generated accessors, equals, hashCode, toString—less boilerplate.'],
      ['Canonical constructor in record?', 'Compact constructor validates without repeating field list.'],
      ['Can record implement interfaces?', 'Yes; cannot extend classes (implicitly extends Record).'],
      ['Are record components mutable if object mutable?', 'Shallow immutability—don’t expose mutable lists without defensive copy.'],
      ['What is sealed class/interface?', 'Permits only listed subclasses—compiler enforced hierarchy.'],
      ['Exhaustive switch with sealed?', 'Compiler can verify all cases covered—fewer bugs.'],
      ['Pattern matching for instanceof?', 'if (o instanceof Point p) use p directly—Java 16+.'],
      ['Record serialization?', 'Works with compatible frameworks—watch evolution adding fields.'],
      ['Migration class to record breaking?', 'Constructors and accessors names differ—API breakage.'],
      ['Record vs Lombok @Value?', 'Language feature vs annotation processing—trade-offs.'],
      ['Accessor naming x() not getX?', 'Record accessors use component names—framework interop considerations.'],
      ['sealed permits clause?', 'permits Sub1, Sub2 in same module/package constraints.'],
      ['non-sealed subclass?', 'Opt out child can be extended further—escape hatch.'],
      ['Record reflection java.lang.Record?', 'Common superclass—limited methods.'],
      ['JavaBeans compatibility with records?', 'May need adapters for tools expecting get/set.'],
    ],
    codeBased: [
      ['record Point(int x,int y){}', 'Usage new Point(1,2).x()'],
      ['Compact constructor validation.', 'record Email(String v){ if(!v.contains("@")) throw ... }'],
      ['sealed interface Shape permits Circle,Rect', 'pattern switch'],
      ['Switch on sealed type exhaustive.', 'Compiler error if case missing (with settings).'],
      ['Record with List<String> defensive copy.', 'Use List.copyOf in compact constructor.'],
      ['Implement Comparable in record.', 'record Person(String n) implements Comparable<Person>'],
      ['equals/hashCode not written manually.', 'Trust generated—don’t duplicate.'],
      ['nested record inside class.', 'static nested often for DTOs.'],
      ['deconstruction preview patterns—future.', 'Know evolution direction.'],
      ['Jackson record module—annotation?', 'Often works out of the box—field names.'],
    ],
    seniorScenario: [
      ['Hibernate entity as record?', 'Generally not—mutability and proxies; use for DTOs projections.'],
      ['API versioning add component to record?', 'Breaking for clients—use new record type or optional wrapper.'],
      ['Spring Data projections interface vs record?', 'Class-based DTOs + records popular for reads.'],
      ['Sealed classes and frameworks generating subclasses?', 'Permits list must include generated classes—config complexity.'],
      ['Binary compatibility adding sealed permits?', 'Clients recompile—semver major.'],
      ['Records in public library API stability?', 'Great for immutable events—document evolution policy.'],
    ],
    wrongAnswers: [
      'record can extend another concrete class besides Record.',
      'Record components can be reassigned after construction.',
      'sealed types allow unlimited subclasses in any package.',
      'Records automatically deep-clone mutable fields.',
      'Pattern matching works only with legacy instanceof casts.',
      'sealed is the same as final for a class.',
    ],
  },

  33: {
    conceptual: [
      ['What is pattern matching for switch?', 'Combine type tests and binding in switch—less casting clutter.'],
      ['Switch expression vs statement?', 'Expression yields value; must be exhaustive or default where required.'],
      ['Guard clauses in case with when?', 'Additional boolean condition on case labels—Java 21 feature path.'],
      ['Record patterns in switch?', 'Deconstruct record components in case labels—reduce accessors.'],
      ['Exhaustiveness checking?', 'Compiler ensures all sealed/interface variants handled—safer refactors.'],
      ['Null handling in switch?', 'Separate null case or use null-safe dispatch before switch.'],
      ['enum switch legacy vs expression?', 'Expression can yield value; break not used with arrows.'],
      ['Multiple labels case 1,2,3?', 'Shared body—concise.'],
      ['Yield in switch expression?', 'For classic blocks returning value from complex case.'],
      ['Pattern dominance errors?', 'Order cases so more specific before general—compiler errors if unreachable.'],
      ['Switch on String compiled how?', 'hashCode/equals—null throws NPE.'],
      ['Performance of pattern matching?', 'Generally same as equivalent instanceof chain after JIT.'],
      ['Preview vs final features?', 'Know your JDK version in interview—enable preview flags in dev only.'],
      ['Algebraic data types analogy?', 'Sealed hierarchy + exhaustive switch similar to ADTs in FP.'],
      ['Migration from if-else chain to switch?', 'Readability win when dispatch central.'],
    ],
    codeBased: [
      ['Switch expression on enum Color.', 'int rgb = switch(c){ case RED -> 0xFF0000; ... };'],
      ['instanceof pattern matching.', 'if (o instanceof String s) return s.length();'],
      ['sealed interface Expr with record cases—switch.', 'return switch(e){ case Add a -> ...; case Num n -> n.v(); };'],
      ['Traditional switch with yield.', 'case 1: compute; yield result;'],
      ['String switch with guard when available.', 'case "x" when flag -> ...'],
      ['Combine null case first.', 'case null -> handleNull();'],
      ['Arrow labels without fall-through.', 'No accidental fall-through bugs.'],
      ['Replace equals chain with pattern switch.', 'Cleaner dispatch on types.'],
      ['Record pattern case Point(int x, int y)', 'Deconstruct in case (version dependent).'],
      ['Compile error unreachable case—fix?', 'Reorder patterns—specific before generic.'],
    ],
    seniorScenario: [
      ['Library adds sealed subclass—clients switch breaks?', 'Exhaustive switch fails compile—good failure vs runtime bug.'],
      ['Framework reflection on switch generated code?', 'Generally same as ordinary calls—watch bytecode differences.'],
      ['Kotlin when vs Java switch migration?', 'Interop patterns in mixed codebases.'],
      ['Android desugaring new switch features?', 'Older API levels—toolchain support considerations.'],
      ['Performance critical dispatch—tableswitch vs lookupswitch?', 'JVM chooses; large string switches use hash-based strategies.'],
      ['Legal/compliance logging switch on country?', 'Centralize rules; test exhaustively when enum grows.'],
    ],
    wrongAnswers: [
      'Switch expressions can fall through like classic switch without care.',
      'Pattern matching removes the need for equals/hashCode.',
      'You can switch on float primitive directly.',
      'default case is optional in all switch expressions.',
      'instanceof pattern variables are in scope after the if block unconditionally.',
      'Switch on null String is silently ignored.',
    ],
  },

  34: {
    conceptual: [
      ['What is a thread in Java?', 'Independent path of execution; shares heap with other threads in same process.'],
      ['What is synchronized?', 'Intrinsic lock on object—mutual exclusion for critical sections.'],
      ['What is volatile?', 'Visibility guarantee for reads/writes—not compound atomicity for i++.'],
      ['What is java.util.concurrent?', 'Higher-level utilities: ExecutorService, ConcurrentHashMap, locks, atomics.'],
      ['What is ExecutorService?', 'Thread pool abstraction—submit tasks, manage lifecycle.'],
      ['What is Callable vs Runnable?', 'Callable returns value and throws checked exceptions—use with Future.'],
      ['What is CountDownLatch/CyclicBarrier?', 'Coordination primitives for threads meeting at points.'],
      ['What is deadlock?', 'Circular wait for locks—prevent with lock ordering and timeouts.'],
      ['What is race condition?', 'Outcome depends on timing—unsynchronized shared mutable state.'],
      ['What is AtomicInteger?', 'CAS-based atomic updates without synchronized for single variable.'],
      ['What is ReentrantLock?', 'Explicit lock with tryLock, fairness option—more flexible than synchronized.'],
      ['What is thread pool sizing heuristic?', 'CPU-bound ~ cores; IO-bound higher—measure.'],
      ['What is ForkJoinPool?', 'Work-stealing for divide-and-conquer parallel tasks.'],
      ['What is ThreadLocal?', 'Per-thread variable storage—use carefully to avoid leaks in pools.'],
      ['What is happens-before?', 'JMM rule establishing visibility ordering between actions.'],
    ],
    codeBased: [
      ['synchronized method vs block.', 'Lock object scope differs—use private final lock.'],
      ['ExecutorService submit Callable.', 'Future<Integer> f = ex.submit(() -> 42);'],
      ['AtomicInteger incrementAndGet.', 'Lock-free counter increments.'],
      ['volatile boolean flag visibility.', 'Reader thread sees writer update with volatile.'],
      ['join thread.', 'main waits for thread completion.'],
      ['ReentrantLock tryLock timeout.', 'Avoid indefinite deadlock.'],
      ['ConcurrentHashMap compute.', 'Atomic transformation per key.'],
      ['ScheduledExecutorService scheduleAtFixedRate.', 'Periodic tasks—handle exceptions or task stops.'],
      ['Semaphore limit concurrency.', 'acquire/release permits.'],
      ['ReadWriteLock read lock many writers exclusive.', 'Read-heavy caches pattern.'],
    ],
    seniorScenario: [
      ['Thread pool task queue unbounded—risk?', 'OOM from queued tasks; use bounded queues and back-pressure.'],
      ['ThreadLocal in pooled threads—leak?', 'remove() in finally—especially in app servers.'],
      ['Debugging deadlock in prod?', 'Thread dump jstack; lock ordering; timeouts.'],
      ['synchronized on Integer—bad?', 'Integer cached objects—unrelated locks; use dedicated Object.'],
      ['Virtual threads vs platform threads—when?', 'IO-bound scalability—Java 21+; CPU-bound still need cores.'],
      ['Distributed locking vs in-JVM locks?', 'Redis/etcd locks for cluster coordination—different failure modes.'],
    ],
    wrongAnswers: [
      'volatile makes i++ atomic on an int field.',
      'synchronized blocks can never deadlock.',
      'Creating a new thread per request is always the best scalability approach.',
      'ConcurrentHashMap allows null keys like HashMap.',
      'ExecutorService automatically shuts down when the app exits.',
      'Thread.sleep releases locks held by the thread.',
    ],
  },

  35: {
    conceptual: [
      ['What is java.util.concurrent.locks.Lock?', 'Explicit lock interface with tryLock, lockInterruptibly—unlike synchronized keywords only.'],
      ['What is fairness in ReentrantLock?', 'Longest-waiting thread acquires next—reduces starvation but lowers throughput.'],
      ['What is StampedLock?', 'Optimistic read locking for read-heavy scenarios—tricky API.'],
      ['What is CompletableFuture?', 'Composable async tasks with thenApply, thenCombine, exception handling.'],
      ['What is blocking queue in producer-consumer?', 'put/take coordinate back-pressure—LinkedBlockingQueue etc.'],
      ['What is CopyOnWriteArrayList?', 'Copy-on-write for rare writes many reads—snapshot iterators.'],
      ['What is ExecutorService lifecycle?', 'shutdown vs shutdownNow—wait termination with awaitTermination.'],
      ['What is fork/join misuse?', 'Tiny tasks overhead—thresholds matter.'],
      ['What is CompletableFuture thread pool?', 'Common ForkJoinPool or custom executor—specify for production control.'],
      ['What is parallelStream common pool?', 'Shared—can saturate; dangerous for blocking tasks.'],
      ['What is lock striping?', 'Split lock scope to reduce contention—ConcurrentHashMap segments historical.'],
      ['What is ABA problem?', 'CAS pitfalls in lock-free—AtomicStampedReference mitigates.'],
      ['What is LongAdder?', 'Scalable counters under contention—cells reduce CAS failures.'],
      ['What is Phaser?', 'Flexible barrier for dynamic number of parties—advanced.'],
      ['What is Exchanger?', 'Two threads swap objects at rendezvous point—niche.'],
    ],
    codeBased: [
      ['CompletableFuture supplyAsync thenApply.', 'Async pipeline.'],
      ['handle whenComplete exception.', 'Recover or log both success and failure.'],
      ['allOf CompletableFuture join.', 'Wait all tasks—exception handling aggregate.'],
      ['tryLock with timeout avoid deadlock.', 'if (lock.tryLock(1, SECONDS)) {...} finally unlock.'],
      ['BlockingQueue put take.', 'Producer consumer loop.'],
      ['ScheduledExecutor scheduleWithFixedDelay vs rate.', 'Understand drift vs fixed period.'],
      ['invokeAll ExecutorService batch.', 'Wait all Callables complete.'],
      ['ReadWriteLock cache get read lock.', 'Multiple readers single writer pattern.'],
      ['StampedLock optimistic read validate.', 'validate(stamp) after read—fallback to read lock.'],
      ['LongAdder sum.', 'sum() aggregation—eventual for high contention counters.'],
    ],
    seniorScenario: [
      ['CompletableFuture.get blocks—async lost?', 'Use thenAccept async callbacks or compose without blocking event threads.'],
      ['Common pool exhaustion from blocking CF?', 'Use custom executor for blocking IO tasks.'],
      ['Metrics for thread pool queue depth?', 'Alert before OOM; tune max pool and queue.'],
      ['Distributed transaction vs local locks?', 'Different consistency—don’t confuse JDBC transaction with Lock.'],
      ['Reactive vs CompletableFuture style?', 'Different ecosystems—interop carefully.'],
      ['GC pauses vs low-latency locks?', 'Consider Shenandoah/ZGC and avoid full STW phases in SLA paths.'],
    ],
    wrongAnswers: [
      'ReentrantLock automatically releases when the method returns like synchronized.',
      'CompletableFuture always runs on a new thread for each stage.',
      'CopyOnWriteArrayList is best for write-heavy workloads.',
      'StampedLock is the simplest lock for beginners.',
      'LongAdder is always faster than AtomicLong for every use case.',
      'shutdownNow guarantees all tasks completed successfully.',
    ],
  },

  36: {
    conceptual: [
      ['What is CompletableFuture?', 'Non-blocking composition of async tasks with callbacks and combining futures.'],
      ['What is thenApply vs thenCompose?', 'thenApply maps value; thenCompose flattens CompletableFuture-returning function.'],
      ['What is ForkJoinPool.commonPool?', 'Shared pool for parallel streams and default async executor—limited threads.'],
      ['What are virtual threads (Java 21)?', 'Lightweight threads mapped to carrier threads—great for blocking IO at huge scale.'],
      ['What is structured concurrency (preview)?', 'Scopes child tasks lifetime—fail together—emerging pattern.'],
      ['What is executor choice for CF?', 'Specify Executor for blocking work—don’t block common pool.'],
      ['What is exceptionally / handle?', 'Recover from failures in pipeline—typed handling.'],
      ['What is orTimeout / completeOnTimeout (Java 9+)?', 'Bound wait times—avoid hanging futures.'],
      ['What is join vs get on CompletableFuture?', 'join unchecked; get throws checked ExecutionException.'],
      ['What is runAsync vs supplyAsync?', 'No return vs Supplier return value.'],
      ['Virtual thread pinning issue?', 'Synchronized block or native code can pin to carrier—use reentrant locks or avoid.'],
      ['What is carrier thread?', 'OS thread backing many virtual threads—scheduling layer.'],
      ['Platform thread cost?', 'Megabytes stack vs virtual kilobytes—scalability difference.'],
      ['What is CompletableFuture delayedExecutor?', 'Schedule tasks with delay—Java 9+.'],
      ['Thread-per-request vs virtual threads for servlet?', 'Virtual threads improve throughput under blocking workloads.'],
    ],
    codeBased: [
      ['CompletableFuture.supplyAsync(() -> fetch()).thenApply(String::toUpperCase)', 'Pipeline.'],
      ['thenCombine add two async ints.', 'cf1.thenCombine(cf2, Integer::sum)'],
      ['exceptionally ex -> default', 'Recover from failure.'],
      ['allOf futures then run.', 'CompletableFuture.allOf(fs).thenRun(...).'],
      ['custom Executor for supplyAsync.', 'supplyAsync(task, executor).'],
      ['join multiple with CompletableFuture.anyOf?', 'First success—careful semantics.'],
      ['Virtual thread ExecutorService Java 21.', 'Executors.newVirtualThreadPerTaskExecutor()'],
      ['Future get with timeout.', 'future.get(1, TimeUnit.SECONDS)'],
      ['handle (result, ex) both.', 'Unified success/failure path.'],
      ['thenAccept async logging.', 'End pipeline consumer.'],
    ],
    seniorScenario: [
      ['Outage: thread pool saturated—symptoms?', 'Latency spikes, rejected executions—metrics on active count and queue.'],
      ['Blocking call inside CF common pool—impact?', 'Starves parallel streams and other async—dedicate pool.'],
      ['Distributed trace across CF stages?', 'Propagate trace context manually or with framework support.'],
      ['Virtual threads and JDBC drivers?', 'Ensure drivers release pinning; monitor thread dumps.'],
      ['Choosing CompletableFuture vs Project Reactor?', 'Ecosystem integration—Spring WebFlux uses Reactor.'],
      ['Cancellation of CompletableFuture chains?', 'cancel may not stop running task—cooperative cancellation.'],
    ],
    wrongAnswers: [
      'CompletableFuture.get never blocks the calling thread.',
      'Virtual threads replace the need for thread pools entirely.',
      'thenApply runs on the same thread that completed the previous stage always.',
      'ForkJoinPool.commonPool has unlimited threads.',
      'CompletableFuture cannot complete exceptionally.',
      'join() throws checked InterruptedException like get().',
    ],
  },

  37: {
    conceptual: [
      ['What is JVM heap?', 'Runtime data area for object allocation—Garbage Collector manages reclamation.'],
      ['What is stack vs heap?', 'Stack per-thread frames with local vars; heap shared objects—escape analysis may stack-allocate.'],
      ['What is GC root?', 'Reachability starting points—threads, static fields, JNI refs.'],
      ['What is generational hypothesis?', 'Most objects die young—Young gen collections frequent, Old gen less.'],
      ['What is Stop-The-World pause?', 'Some GC phases halt application threads—latency sensitive apps care.'],
      ['What is G1 GC?', 'Region-based, targets pause time goals—common default in modern JDK.'],
      ['What is ZGC / Shenandoah?', 'Low-latency concurrent collectors—large heaps, sub-ms goals under conditions.'],
      ['What is Metaspace?', 'Class metadata since Java 8—replaces PermGen; unbounded unless MaxMetaspaceSize.'],
      ['What is JIT compilation tiers?', 'C1 fast compile, C2 optimized—tiered compilation balances startup vs peak.'],
      ['What is class loading delegation?', 'Parent-first model—security and consistency.'],
      ['What is -Xmx -Xms?', 'Max and initial heap—sizing for containers important.'],
      ['What is Native Memory Tracking?', 'Diagnose native leaks outside heap—JNI, metaspace, thread stacks.'],
      ['What is safepoint?', 'Points where threads pause for GC/deoptimization coordination.'],
      ['What is heap dump?', 'Snapshot for MAT analysis—find leaks retaining objects.'],
      ['What is container-aware ergonomics?', 'JDK reads cgroup limits to set default heap—avoid OOMKill mismatch.'],
    ],
    codeBased: [
      ['Print Runtime maxMemory totalMemory freeMemory.', 'Runtime.getRuntime() snapshot.'],
      ['Trigger System.gc()—should you?', 'Hint only—not guaranteed; don’t rely in prod logic.'],
      ['jcmd <pid> VM.flags', 'Inspect effective flags.'],
      ['-Xlog:gc* example purpose.', 'GC logging for pause analysis.'],
      ['Object creation in tight loop microbench sketch.', 'Measure allocation rate and GC impact.'],
      ['Use jmap -heap pid (careful prod).', 'Heap summary—may pause.'],
      ['Flight Recorder JFR start command.', 'jcmd <pid> JFR.start—low overhead profiling.'],
      ['StackOverflowError vs OOM.', 'Stack depth vs heap space—different fixes.'],
      ['WeakReference use case.', 'Caches that should not prevent GC of referent.'],
      ['finalize deprecated—alternative?', 'Cleaner API or try-with-resources.'],
    ],
    seniorScenario: [
      ['K8s pod OOMKilled but heap low?', 'Check native memory, direct buffers, thread stacks, metaspace.'],
      ['GC pause SLA breach after upgrade?', 'Review collector changes defaults; tune pause goal; profile allocation.'],
      ['Large heap Full GC storms?', 'Tune region sizes, humongous objects G1, avoid allocation spikes.'],
      ['Classloader leak in redeploys?', 'Metaspace growth—unload loaders properly; framework bugs.'],
      ['JVM flags from multiple sources conflict?', 'Args file, JAVA_TOOL_OPTIONS, container—order of precedence.'],
      ['Choosing ZGC vs G1?', 'Latency vs throughput trade-offs—benchmark representative workloads.'],
    ],
    wrongAnswers: [
      'Garbage collection runs only when System.gc() is called.',
      'Stack memory holds all Java objects.',
      'Metaspace is fixed size and never grows.',
      'More heap always reduces GC time.',
      'The JIT compiles all bytecode to native code before any execution.',
      'WeakReference prevents an object from ever being garbage collected.',
    ],
  },

  38: {
    conceptual: [
      ['What is Inversion of Control?', 'Framework controls flow and calls your code—contrasts with library you call.'],
      ['What is Dependency Injection?', 'Dependencies provided from outside (constructor/setter) rather than created internally—testability.'],
      ['What is Spring ApplicationContext?', 'IoC container managing bean lifecycle and wiring.'],
      ['What is @Autowired?', 'Injection by type (and qualifier)—constructor injection preferred for immutability.'],
      ['What is @Component @Service @Repository?', 'Stereotypes marking Spring beans—semantics and AOP proxies differ slightly.'],
      ['What is @Configuration @Bean?', 'Java-based bean definitions replacing XML.'],
      ['What is bean scope singleton default?', 'One instance per container—stateless services ideal.'],
      ['What is @Primary @Qualifier?', 'Disambiguate multiple beans of same type.'],
      ['What is circular dependency problem?', 'Bean A needs B needs A—constructor injection fails; refactor or setter injection cautiously.'],
      ['What is ApplicationContext vs BeanFactory?', 'ApplicationContext superset—events, i18n, eager init of singletons by default.'],
      ['What is stereotype component scanning?', 'Classpath scanning for annotated classes—@SpringBootApplication includes.'],
      ['What is PropertySources and @Value?', 'Externalize configuration—12-factor app pattern.'],
      ['What is Spring profiles?', 'Beans activated per environment—dev, test, prod.'],
      ['What is conditional beans @Conditional?', 'Register beans based on classpath, properties, etc.'],
      ['What is FactoryBean?', 'Advanced indirection creating complex beans—rare interview depth.'],
    ],
    codeBased: [
      ['Constructor injection with final field.', 'public S(Repo r){ this.repo=r; }'],
      ['@Bean method returns Interface impl.', '@Bean PaymentGateway stripe(){ return new StripeGateway(); }'],
      ['@Qualifier("mock") on test bean.', 'Test slice configuration.'],
      ['@ConfigurationProperties binding prefix.', 'type-safe config classes.'],
      ['Optional dependency @Autowired(required=false).', 'Handle missing bean.'],
      ['@Import another config class.', 'Modular configuration assembly.'],
      ['SpEL @Value("#{systemProperties[\'user.home\']}")', 'Dynamic expressions—use sparingly.'],
      ['Prototype scope bean example.', '@Scope("prototype") new instance each injection.'],
      ['ApplicationContext getBean usage—when?', 'Generally avoid in application code—prefer injection.'],
      ['@PostConstruct init method.', 'Lifecycle callback after injection.'],
    ],
    seniorScenario: [
      ['Huge Spring context slow startup?', 'Lazy beans, trimming classpath, spring-native/AOT strategies.'],
      ['Wrong bean in prod—debug?', 'Actuator beans endpoint, conditional report, logging.'],
      ['Library brings unwanted component scan?', 'Exclude auto-configurations carefully—explicit imports.'],
      ['Testing without Spring context—approach?', 'Pure unit tests with manual mocks vs @SpringBootTest slices.'],
      ['Microservices shared library Spring configs conflict?', 'Namespace properties, starter modules discipline.'],
      ['Memory leak Spring singleton holding HTTP session?', 'Design stateless services; scope session carefully.'],
    ],
    wrongAnswers: [
      '@Autowired always injects by name first, never by type.',
      'Spring beans are always prototype scope unless specified.',
      'You should call new on @Service classes in your code.',
      'IoC means objects create themselves more easily.',
      'ApplicationContext and BeanFactory are identical in features.',
      'Constructor injection cannot be used with final fields.',
    ],
  },

  39: {
    conceptual: [
      ['What is Spring bean lifecycle?', 'Instantiate → populate properties → initialize callbacks → use → destroy.'],
      ['What is BeanPostProcessor?', 'Hook to wrap/modify beans during creation—advanced extension.'],
      ['What is InitializingBean vs @PostConstruct?', 'Callbacks after properties set—prefer standard annotations.'],
      ['What is DisposableBean / @PreDestroy?', 'Cleanup on shutdown—close connections.'],
      ['What is Aware interfaces?', 'Bean gets ApplicationContext, Environment—use sparingly.'],
      ['What is lazy initialization?', 'Bean created on first request—faster startup vs first-hit latency.'],
      ['What is @DependsOn?', 'Force bean creation order when implicit wiring insufficient.'],
      ['What is FactoryBean vs factory method?', 'Spring FactoryBean special interface vs @Bean method factory pattern.'],
      ['What is bean definition inheritance?', 'parent attribute in XML—less common in annotation era.'],
      ['What is @Scope proxyMode?', 'Scoped proxies for singleton injecting request scope bean—interface required.'],
      ['What is ObjectProvider<T>?', 'Lazy lookup of bean or multiple candidates—avoid eager resolution.'],
      ['What is Provider<T> injection?', 'JSR-330 lazy retrieval—similar use cases.'],
      ['What is @RefreshScope (Cloud)?', 'Recreate bean on config refresh—state careful.'],
      ['What is AOT processing Spring 6?', 'Ahead-of-time hints for native image—startup implications.'],
      ['What is bean overriding default behavior?', 'Spring Boot 2.1+ false by default—prevent accidental replace.'],
    ],
    codeBased: [
      ['@PostConstruct void init()', 'After injection setup.'],
      ['@PreDestroy void cleanup()', 'Close DataSource etc.'],
      ['BeanPostProcessor wrap with proxy example concept.', 'Return wrapped bean from postProcessAfterInitialization.'],
      ['ObjectProvider.getIfAvailable optional bean.', 'Graceful optional dependency.'],
      ['@DependsOn("dataSource") on bean.', 'Ordering guarantee.'],
      ['Lazy @Bean @Lazy on injection point.', 'Proxy until first use.'],
      ['Test @DirtiesContext when?', 'Mutates singleton context—slow tests.'],
      ['@Configuration proxyBeanMethods false why?', 'Avoid CGLIB overhead when no cross-bean calls.'],
      ['Environment getProperty with default.', 'env.getProperty("x","default")'],
      ['Profile-specific @Configuration @Profile("dev")', 'Activate with spring.profiles.active.'],
    ],
    seniorScenario: [
      ['Startup failure missing bean after refactor?', 'Conditional missing property; use --debug or failure analyzer.'],
      ['BeanPostProcessor order issues?', 'Implement Ordered or @Order—ordering bugs subtle.'],
      ['Hot reload devtools restart vs live reload?', 'Classloader restart vs resource refresh—limitations.'],
      ['Cloud native buildpacks lifecycle vs Spring lifecycle?', 'Container build layers separate concerns.'],
      ['Memory leak static field holding BeanFactory?', 'Avoid static references to context.'],
      ['GraalVM native image reflection on beans?', 'Register hints for dynamic features—Spring Boot helps.'],
    ],
    wrongAnswers: [
      '@PostConstruct runs before dependency injection.',
      'Singleton beans are destroyed after every HTTP request.',
      'BeanPostProcessor is used in every typical business service.',
      'Lazy beans are never proxies.',
      'DisposableBean is the only way to run code on shutdown.',
      '@Configuration classes are never subclassed by Spring CGLIB.',
    ],
  },

  40: {
    conceptual: [
      ['What is AOP?', 'Aspect-Oriented Programming—cross-cutting concerns like logging, transactions, security modularized.'],
      ['What is advice, pointcut, aspect?', 'Advice is action; pointcut matches join points; aspect bundles them.'],
      ['What is @Around advice?', 'Wraps method—can proceed or short-circuit—most powerful.'],
      ['What is proxy-based AOP in Spring?', 'JDK dynamic proxies (interfaces) or CGLIB (classes)—method calls intercepted.'],
      ['What limitations of Spring AOP?', 'Only public method calls through proxy intercepted—self-invocation bypasses aspect.'],
      ['What is @Transactional AOP?', 'Declarative transaction boundaries—rollback rules, propagation, isolation.'],
      ['What is pointcut expression language?', 'execution(...), @annotation, within, args—AspectJ syntax subset.'],
      ['What is weaving?', 'Compile-time, load-time, or runtime proxy—weaving differs; Spring uses proxy at runtime.'],
      ['What is Advice order @Order?', 'Multiple aspects on same join point—ordering matters.'],
      ['What is introduction in AOP?', 'Declare additional interface implementation on existing bean—advanced.'],
      ['What is TargetSource?', 'Advanced proxy target swapping—rare.'],
      ['What is self-invocation problem fix?', 'Inject self proxy @Lazy or split service; or AspectJ compile-time weaving.'],
      ['Performance overhead AOP?', 'Usually small—measure hot paths; avoid heavy work in aspects.'],
      ['What is @EnableAspectJAutoProxy?', 'Enables aspect processing in Spring Boot auto-config included.'],
      ['What is transaction proxy with rollbackFor?', 'Checked exceptions don’t rollback by default—configure.'],
    ],
    codeBased: [
      ['@Around advice signature ProceedingJoinPoint.', 'pjp.proceed() continue method.'],
      ['Pointcut @annotation(Logged)', 'Intercept methods annotated.'],
      ['@Before execution(*..Service.*(..))', 'Wildcard execution expression.'],
      ['Transactional readOnly=true on query service.', 'Optimization hint to provider.'],
      ['@Transactional propagation REQUIRES_NEW', 'New transaction for nested call.'],
      ['@Transactional noRollbackFor', 'Exclude certain exceptions from rollback.'],
      ['Aspect @Order(1)', 'Control precedence.'],
      ['Programmatic TransactionTemplate usage.', 'execute status -> { ... }'],
      ['SpEL in @Value in aspect—careful.', 'Dynamic—test thoroughly.'],
      ['Test aspect applied—use @SpringBootTest assert advice called.', 'Or unit test aspect in isolation.'],
    ],
    seniorScenario: [
      ['Transaction not rolling back—cause?', 'Caught exception, self-invocation, wrong exception type, read-only resource.'],
      ['Security audit aspect silently failing open?', 'Dangerous—fail closed; monitor aspect health.'],
      ['Latency added by metrics aspect?', 'Sampling, async export, avoid heavy serialization in advice.'],
      ['Monolithic God aspect doing everything?', 'Split concerns—single responsibility aspects.'],
      ['Distributed transactions vs @Transactional local?', 'Different—Saga/outbox patterns for microservices.'],
      ['Upgrade Spring AOP behavior change?', 'Read release notes—proxy differences JDK versions.'],
    ],
    wrongAnswers: [
      'Spring AOP intercepts all method calls including private and self-invoked ones.',
      '@Transactional works on private methods reliably.',
      'Aspects are only for logging, not transactions.',
      'JDK dynamic proxies work for any class without interfaces.',
      'Around advice must always call proceed() exactly once.',
      'Pointcuts are evaluated at compile time for Spring AOP.',
    ],
  },
};
