/**
 * Interview Drill — topic-specific Q&A for Days 1–18
 * Counts: 15 conceptual, 10 codeBased, 6 seniorScenario, 6 wrongAnswers
 */

export const INTERVIEW_BANK = {
  1: {
    conceptual: [
      ['What is the JDK and what tools does it include?', 'The JDK (Java Development Kit) is the full development bundle: it includes javac (compiler), jar, javadoc, jdb, and the JRE so you can compile and run Java programs.'],
      ['What is the JRE and can you compile Java with only the JRE?', 'The JRE (Java Runtime Environment) contains the JVM and libraries needed to run Java applications. You cannot compile new .java files with JRE alone—you need the JDK for javac.'],
      ['What is the JVM’s role?', 'The JVM loads .class bytecode, verifies it, and executes it on the host OS. It provides memory management (heap, GC) and the execution engine for your program.'],
      ['What is the relationship between .java, .class, and running a program?', 'You write .java source, javac produces .class bytecode, and the java launcher starts the JVM to execute the bytecode for the named class.'],
      ['Why is main() declared public static void main(String[] args)?', 'public so the JVM can call it from outside the class; static so it runs without constructing an object first; void because the JVM does not use a return value; String[] args holds command-line arguments.'],
      ['What does “platform independence” mean for Java?', 'Source compiles to bytecode that any compatible JVM can run, so the same .class can run on Windows, Linux, or macOS without recompiling for each CPU instruction set.'],
      ['How do you check that JDK (not only JRE) is installed correctly?', 'Run javac -version in the terminal. If javac is missing or errors, the JDK is not on PATH or only a JRE was installed.'],
      ['What is JAVA_HOME and why do build tools use it?', 'JAVA_HOME points to the JDK installation root. Maven, Gradle, and IDEs use it to find the compiler and standard libraries consistently across machines.'],
      ['What happens if the public class name does not match the file name?', 'For a public top-level class, the file must be named ClassName.java. A mismatch causes a compile-time error.'],
      ['What is the difference between compiling with javac and running with java?', 'javac translates source to bytecode files; java starts the JVM and loads the class by name (with package-aware classpath).'],
      ['Can two JVM versions behave differently for the same bytecode?', 'Generally bytecode is portable, but behavior can differ if you rely on version-specific APIs, preview features, or different default GC/security settings.'],
      ['What is classpath and when does it matter?', 'Classpath tells the JVM where to find .class files and JARs. Wrong classpath causes ClassNotFoundException even if the code compiled.'],
      ['What is JIT compilation in the JVM?', 'The JIT (Just-In-Time) compiler translates hot bytecode to native machine code at runtime to speed up frequently executed code after profiling.'],
      ['What does bytecode verification do?', 'Before execution, the JVM checks bytecode for type safety, stack consistency, and illegal jumps—reducing certain classes of memory corruption and invalid calls.'],
      ['What is the difference between classpath and module path (Java 9+)?', 'Classpath loads classes/JARs the classic way; module path activates the module system (strong encapsulation, reliable configuration). Many apps still use classpath; libraries may publish as modules.'],
    ],
    codeBased: [
      ['Show how to print Java version and Java home from code.', 'Use System.getProperty("java.version") and System.getProperty("java.home") and print them in main.'],
      ['Write the minimal HelloWorld class and the exact commands to compile and run it.', 'public class Hello { public static void main(String[] a){ System.out.println("Hello"); } } then javac Hello.java and java Hello.'],
      ['How do command-line arguments appear in Java?', 'They are in the String[] args parameter: args[0] is the first argument after the class name.'],
      ['What error do you get if you run java Hello but the class is in package com.example?', 'You must use the fully qualified name (com.example.Hello) or run from the correct classpath root matching the package directory structure.'],
      ['How would you detect if the program is running on Java 17 or higher?', 'Parse System.getProperty("java.version")—for modern Java it often starts with "17", "21", etc.—or use Runtime.version().feature().'],
      ['What is the output of java -cp . Hello if Hello.class is missing?', 'The JVM throws java.lang.ClassNotFoundException or similar because it cannot load the class.'],
      ['Why might java work but javac fail on the same machine?', 'Only a JRE is installed or PATH points to a JRE bin without javac; install full JDK and put JDK bin before other Java entries on PATH.'],
      ['Write one line that prints all system properties keys containing "java."', 'Use Properties p = System.getProperties(); p.stringPropertyNames().stream().filter(k->k.startsWith("java.")).forEach(System.out::println);'],
      ['How can you run a single-file program without separate javac step (Java 11+)?', 'Use java Hello.java — the launcher compiles and runs in one step for single-file programs.'],
      ['What does java --list-modules show?', 'It lists observable platform modules on the module path—useful when debugging module visibility and dependencies.'],
    ],
    seniorScenario: [
      ['CI builds with Java 11 but developers use Java 17 locally. What do you standardize?', 'Pin the JDK in the build (toolchains, Gradle JVM, Maven enforcer), align CI image and local dev with the same major version, and fail the build on mismatch.'],
      ['A service fails at startup: "Error: Could not find or load main class". What do you check?', 'Verify the main class name, package declaration, classpath, JAR manifest Main-Class entry, and that you run from the correct working directory.'],
      ['Someone installed JDK but terminal still says javac is not recognized on Windows. What steps?', 'Confirm JDK bin path, add it to user/system PATH, set JAVA_HOME to JDK root, open a new terminal, and ensure no conflicting older java earlier in PATH.'],
      ['You need to run the same JAR on Linux servers with different Java patch levels. What policy?', 'Standardize minimum supported LTS, test on lowest supported patch, document required flags, and use container images with pinned JDK versions.'],
      ['How do you explain JVM vs JDK to a non-technical stakeholder?', 'JDK is the full developer kit to build and run; JVM is only the engine that runs the program once built—like needing a factory (JDK) to make a car part, then an engine (JVM) to run the car.'],
      ['Several JDKs are installed; `java -version` differs from `javac -version`. How do you fix it?', 'Ensure PATH lists the same JDK bin for both; on Windows use `where java` and `where javac`; align JAVA_HOME with the intended JDK and remove stale shims.'],
    ],
    wrongAnswers: [
      'JDK and JVM are the same thing.',
      'You can compile .java files using only the JRE.',
      'Java source code runs directly on the CPU without bytecode.',
      'main can be private static void main and the JVM will still start it.',
      'Classpath is only needed for web applications, not console programs.',
      'The `java` command executes `.java` source files directly without compilation in all Java versions.',
    ],
  },

  2: {
    conceptual: [
      ['List Java primitive types and their main use cases.', 'byte/short/int/long for integers (int default choice; long for large counts); float/double for decimals (double default); boolean for flags; char for single characters.'],
      ['What is the difference between int and Integer?', 'int is a primitive stored by value; Integer is an object wrapper that can be null and is used with generics and collections.'],
      ['What is autoboxing? Give an example.', 'Autoboxing converts int to Integer automatically, e.g. Integer x = 5;. Unboxing is int y = x;.'],
      ['Why can int arithmetic overflow silently?', 'Integral types wrap around modulo 2^bits—Integer.MAX_VALUE + 1 becomes Integer.MIN_VALUE without throwing unless you use methods like Math.addExact.'],
      ['When should you use BigDecimal instead of double for money?', 'BigDecimal gives exact decimal arithmetic; double uses binary floating-point and can show 0.1 + 0.2 != 0.3 style errors.'],
      ['What is widening vs narrowing conversion?', 'Widening (e.g. int to long) is safe implicitly; narrowing (long to int) requires explicit cast and may lose high bits.'],
      ['What does the L suffix mean in literals?', '123L is a long literal; without L, integer literals default to int and may overflow at compile time if too large.'],
      ['Can you use == to compare two Integer objects?', '== compares references; two different Integer objects with value 200 may not be ==. Use equals() for value comparison, or compare unboxed ints.'],
      ['What is Unicode and how does char relate?', 'Java char is 16-bit UTF-16 code units; supplementary characters may need two chars (surrogate pairs).'],
      ['What is the default value of an uninitialized instance int field?', '0. Local variables must be assigned before use; fields get default values.'],
      ['Why might you choose short or byte over int?', 'Rarely for space in large arrays or binary protocols; usually int is simpler unless you have measured memory constraints.'],
      ['What is NaN in floating-point and how does == behave with it?', 'NaN means not-a-number; NaN == NaN is false—you must use Float.isNaN or Double.isNaN.'],
      ['What is var (Java 10+) and when is it allowed for locals?', 'var infers the type of a local variable from the initializer; it cannot be used without an initializer or for parameters.'],
      ['Why avoid float for loop counters or money?', 'float has limited precision; money needs exact decimals (BigDecimal); loop indices are clearer as int/long.'],
      ['What does underscore in numeric literals do (Java 7+)?', 'Underscores in literals like 1_000_000 improve readability and are ignored by the compiler.'],
    ],
    codeBased: [
      ['Write code that demonstrates int overflow.', 'int x = Integer.MAX_VALUE; System.out.println(x + 1); prints -2147483648.'],
      ['Show widening from int to long without cast.', 'long y = 1_000_000_000 * 3L; or assign int to long variable.'],
      ['Show narrowing cast from long to int with data loss.', 'long big = 3000000000L; int small = (int) big; print both—value truncates to lower 32 bits.'],
      ['Compare double sum 0.1+0.2 vs BigDecimal sum.', 'double prints imprecise; new BigDecimal("0.1").add(new BigDecimal("0.2")) is exact for decimal scale.'],
      ['Parse user input string "42" to int safely.', 'Use Integer.parseInt with try/catch NumberFormatException for invalid input.'],
      ['Create a List<Integer> and add primitives—what happens?', 'Autoboxing: list.add(5) boxes 5 to Integer.'],
      ['When is Integer.valueOf(100) == Integer.valueOf(100) possibly true?', 'Small integers may be cached (-128 to 127); always use equals for value comparison across arbitrary ranges.'],
      ['Write a guard for division by zero for int and for double.', 'For int, check divisor != 0 before divide; for double, dividing by 0.0 yields Infinity or NaN, not exception.'],
      ['Declare a final local variable and show it cannot be reassigned.', 'final int x = 1; x = 2; // compile error.'],
      ['Use Optional.ofNullable with Integer—when to use empty?', 'Optional.ofNullable(maybeInt) represents absent nullable Integer without null checks at call sites.'],
    ],
    seniorScenario: [
      ['Counters in analytics hit negative values—suspected overflow. Fix?', 'Move counters to long or AtomicLong, add bounds checks, and alert on anomalous deltas.'],
      ['Payment microservice shows cent mismatches in reports. Likely cause?', 'Floating-point in money paths; migrate to BigDecimal with RoundingMode and explicit scale, audit all arithmetic sites.'],
      ['GC pressure from excessive Integer boxing in hot loop. Mitigation?', 'Use primitive int where possible, IntStream, or specialized collections to reduce allocation.'],
      ['API returns price as double; clients see rounding bugs. Policy?', 'Use BigDecimal in domain layer, serialize as string or scaled long (cents), never raw double for money.'],
      ['How do you document numeric ranges for a public API field?', 'State min/max, unit, overflow behavior, and whether null/zero are allowed—especially for int vs long vs BigDecimal.'],
      ['Serialization of large long IDs to JavaScript: what goes wrong?', 'JS Number is IEEE double—integers above 2^53 lose precision; send IDs as strings or use dedicated types on the client.'],
    ],
    wrongAnswers: [
      'double is the best type for all currency calculations.',
      'Autoboxing means Integer and int are always interchangeable with no performance cost.',
      'Casting long to int never loses data.',
      'Integer.parseInt("abc") returns 0.',
      'char is the same as String with one character.',
      'NaN == NaN is true, so you can compare floats with == safely.',
    ],
  },

  3: {
    conceptual: [
      ['What is short-circuit evaluation in && and ||?', 'For &&, if the left operand is false, the right is not evaluated. For ||, if the left is true, the right is skipped.'],
      ['Difference between while and do-while?', 'while checks condition before each iteration; do-while checks after, so the body runs at least once.'],
      ['What is the difference between break and continue?', 'break exits the innermost loop or switch; continue skips to the next iteration of the innermost loop.'],
      ['What is wrong with if (x = 5) in Java?', 'Single = is assignment, not comparison; this is a compile error for boolean context unless x is boolean (rare pitfall).'],
      ['How does the ternary operator differ from if-else?', 'It is an expression that returns a value and must be used in a value context; both branches should be type-compatible.'],
      ['What is fall-through in switch (classic style)?', 'Without break, execution continues into the next case label—often a bug if unintended.'],
      ['What are switch expressions (Java 14+) advantages?', 'They can return values, enforce exhaustiveness with enums/sealed types, and reduce boilerplate with arrow labels.'],
      ['Why are labeled break/continue rarely used?', 'They jump out of nested loops but can harm readability; refactoring to methods is often clearer.'],
      ['What is operator precedence risk in a + b * c?', 'Multiplication binds tighter than addition; use parentheses when unsure.'],
      ['How do you avoid off-by-one errors in for loops?', 'Clearly define inclusive/exclusive end, use i < length vs i <= length-1 consistently, and test with 0, 1, and max-size inputs.'],
      ['What does the % operator do for negative numbers?', 'Sign of result follows dividend in Java; be careful in modular arithmetic for indices.'],
      ['When is a switch on String compiled differently than on int?', 'String switch uses hashCode/equals under the hood; null string throws NullPointerException.'],
      ['What is the difference between | and || for booleans?', '| always evaluates both sides; || short-circuits. For booleans, || is usually preferred for safety and performance.'],
      ['Can you use switch with long in classic switch?', 'Classic switch on long was added in Java 14+; older code often used if/else chains for long ranges.'],
      ['What does unreachable code after return mean?', 'The compiler rejects statements that can never execute—often a logic or brace mistake.'],
    ],
    codeBased: [
      ['Write a for-loop that prints only odd numbers from 1 to 20.', 'for (int i=1;i<=20;i+=2) System.out.println(i); or use i%2!=0 inside loop.'],
      ['Show switch expression returning a String grade from int score.', 'return switch(score){ case 90,100 -> "A"; default -> "Other"; }; with ranges handled via if or separate logic.'],
      ['Demonstrate break vs continue in nested loop.', 'Inner continue skips to next inner iteration; labeled break exits outer loop when condition met.'],
      ['Write code that safely divides two ints only if divisor != 0.', 'if (b==0) handle error; else System.out.println(a/b);'],
      ['Use ternary to assign min of two ints.', 'int m = a < b ? a : b;'],
      ['Print FizzBuzz for 1..15 with one loop.', 'if (i%15==0) FizzBuzz; else if (i%3==0) Fizz; else if (i%5==0) Buzz; else number.'],
      ['Show do-while that reads until input is "quit" (pseudo).', 'do { ... } while (!line.equals("quit"));'],
      ['Detect leap year with boolean expression (div by 4, except 100, unless 400).', 'boolean leap = (y%4==0 && y%100!=0) || (y%400==0);'],
      ['Use pattern matching for instanceof (Java 16+) in an if chain.', 'if (obj instanceof String s) { return s.length(); }'],
      ['Write a guard that rejects null or blank strings before processing.', 'if (s == null || s.isBlank()) return;'],
    ],
    seniorScenario: [
      ['A pricing rule engine has nested if-else bugs in production. Approach?', 'Extract rules into table-driven or strategy classes, add unit tests per rule branch, and use coverage tools.'],
      ['Infinite loop in worker thread drains CPU. Debugging?', 'Thread dump to see stack, add loop invariants and max-iteration guards, fix termination condition.'],
      ['Feature flags caused wrong branch in multi-tenant billing. Prevention?', 'Centralize flag evaluation, log decision inputs, and add integration tests per tenant scenario.'],
      ['Code review: 8-level nested if in service method. Refactor?', 'Early returns, extract methods, or polymorphism; measure cyclomatic complexity.'],
      ['How do you test complex boolean conditions?', 'Truth table or parameterized tests covering all combinations of predicates.'],
      ['A switch on enum missed a new enum constant after upgrade—runtime issue?', 'With switch expressions on enums, exhaustiveness can be compile-time checked; add default or handle new cases when enum grows.'],
    ],
    wrongAnswers: [
      'continue exits the entire method.',
      'switch without break is always safe in Java.',
      'The condition in while(true) can never cause an infinite loop.',
      'x = 5 and x == 5 mean the same in an if condition.',
      'do-while always runs zero times.',
      '|| and | behave identically for all boolean expressions.',
    ],
  },

  4: {
    conceptual: [
      ['What is the length of an array after int[] a = new int[5]?', 'a.length is 5. Length is fixed at creation and cannot be resized.'],
      ['What is valid index range for an array of length n?', '0 through n-1 inclusive; index n is out of bounds.'],
      ['What is a jagged array in Java?', 'A 2D array where each row can have different lengths—an array of int[] rows.'],
      ['Time complexity to access arr[i]?', 'O(1) random access by index.'],
      ['What does Arrays.sort do for int[] vs Object[]?', 'For primitives, uses tuned dual-pivot quicksort; for objects, uses TimSort and requires Comparable or Comparator.'],
      ['What is System.arraycopy used for?', 'Fast copying between arrays with specified source and destination offsets and length.'],
      ['Why might you prefer Arrays.copyOf over manual loops?', 'It is concise and can resize arrays (truncate or pad with defaults).'],
      ['What is the default value of new int[10] elements?', '0 for each int element.'],
      ['Can you resize an array in place?', 'No—you create a new array and copy elements, or use ArrayList for dynamic sizing.'],
      ['What exception for arr[-1] or arr[arr.length]?', 'ArrayIndexOutOfBoundsException.'],
      ['How does enhanced for (for-each) work with arrays?', 'It iterates elements without index; you cannot assign to the loop variable to change the array contents.'],
      ['What is two-pointer technique used for?', 'Often for sorted array problems: pair sum, palindrome check, removing duplicates in-place.'],
      ['What is Arrays.binarySearch precondition?', 'The array must be sorted (by natural order or comparator); otherwise the result is undefined.'],
      ['Difference between Arrays.equals and deepEquals?', 'equals compares one-dimensional content; deepEquals handles nested arrays recursively.'],
      ['Why might parallelSort help on large primitive arrays?', 'Arrays.parallelSort splits work across threads for big arrays; overhead can hurt small arrays.'],
    ],
    codeBased: [
      ['Write code to find maximum element in int[].', 'Track max = arr[0], loop from 1, update if arr[i] > max; handle empty array separately.'],
      ['Reverse an int[] in place.', 'Two pointers from both ends swap until meet.'],
      ['Copy first half of array to new array.', 'Arrays.copyOfRange(arr, 0, arr.length/2).'],
      ['Check if array contains duplicate using a Set.', 'Add elements to HashSet; if add returns false, duplicate exists.'],
      ['Sum all elements with enhanced for.', 'int s=0; for(int x: arr) s+=x;'],
      ['Create 3x3 matrix and print row sums.', 'Nested loops, inner sums each row.'],
      ['Find index of first occurrence of target or -1.', 'Linear search loop with break or return index when found.'],
      ['Sort String[] case-insensitively.', 'Arrays.sort(arr, String.CASE_INSENSITIVE_ORDER).'],
      ['Fill an array with Arrays.setAll.', 'Arrays.setAll(arr, i -> i * i);'],
      ['Compare two int[] for equality.', 'Arrays.equals(a, b) for contents, not == for reference equality.'],
    ],
    seniorScenario: [
      ['Large byte[] allocation causes OOM in service. Mitigation?', 'Stream processing, chunking, or memory-mapped files instead of loading full array.'],
      ['Array-based cache grows unbounded. Fix?', 'Use bounded structures (ring buffer, LRU), eviction policy, and monitor heap.'],
      ['Parallel sort on huge primitive array—when beneficial?', 'Arrays.parallelSort for large arrays on multicore; measure overhead for small arrays.'],
      ['Off-by-one in production batch indexing caused wrong shard. Prevention?', 'Unit tests for boundary indices, assert invariants, and code review for loop bounds.'],
      ['Migrating from array to ArrayList in hot API—risks?', 'Boxing cost, iterator invalidation patterns differ; profile and test regression.'],
      ['Varargs method receives array—what happens to callers?', 'Compiler packs arguments into an array; avoid passing null as sole vararg (ambiguous) and be careful with performance for hot paths.'],
    ],
    wrongAnswers: [
      'Array length can be changed after creation with array.resize().',
      'arr[arr.length] is the last valid index.',
      'Arrays.sort works the same for int[] and String[] without any comparator difference.',
      'Enhanced for loop allows removing elements from array during iteration safely.',
      'Two-dimensional arrays in Java are always rectangular.',
      '== compares array contents for equality.',
    ],
  },

  5: {
    conceptual: [
      ['Why is String immutable in Java?', 'Once created, the character sequence cannot be changed; methods like substring return new String objects.'],
      ['What is the string pool?', 'A JVM cache of string literals so identical literals may share the same instance to save memory.'],
      ['Difference between == and equals for String?', '== compares references; equals compares character content character by character.'],
      ['When should you use StringBuilder?', 'When building strings in loops or many concatenations to avoid creating many intermediate String objects.'],
      ['Difference between StringBuilder and StringBuffer?', 'StringBuilder is not synchronized (faster single-thread); StringBuffer methods are synchronized for thread safety.'],
      ['What does intern() do?', 'Returns the canonical representation from the pool—use sparingly and only when you understand memory implications.'],
      ['What does substring(begin, end) use for end index?', 'The end index is exclusive—substring(0,3) is first three characters.'],
      ['Why can comparing strings with == sometimes appear to work?', 'Literals may be interned and refer to same object; new String("a") == "a" is typically false.'],
      ['What does trim() do?', 'Removes leading and trailing whitespace (Unicode-aware); does not change internal spaces in the middle.'],
      ['How does split work with regex?', 'split takes a regex pattern; escape special chars like "." with "\\." for literal dot.'],
      ['What is StringJoiner or String.join for?', 'Cleaner joining of strings with delimiters without manual concatenation loops.'],
      ['Locale impact on toLowerCase/toUpperCase?', 'Turkish locale has special casing rules; use Locale.ROOT for consistent ASCII-style normalization when needed.'],
      ['What is String.formatted or String.format?', 'They format strings using printf-style specifiers without manual concatenation.'],
      ['Why can string concatenation in a loop be O(n²)?', 'Each + may create a new String and copy all characters; StringBuilder amortizes appends.'],
      ['What is text blocks (Java 15+) good for?', 'Multi-line strings with readable indentation for JSON, SQL, and templates embedded in Java source.'],
    ],
    codeBased: [
      ['Demonstrate == vs equals with literals and new String.', 'String a="hi"; String b=new String("hi"); a==b false, a.equals(b) true.'],
      ['Build a comma-separated string from List<String> efficiently.', 'Use String.join(",", list) or StringBuilder loop with delimiter logic.'],
      ['Count occurrences of substring "ab" in a string.', 'Loop with indexOf from advancing index or use regex sparingly for clarity.'],
      ['Check palindrome ignoring case and spaces.', 'Normalize: replaceAll("\\s","").toLowerCase(), then two pointers from ends.'],
      ['Extract domain from email user@domain.com.', "int at = email.lastIndexOf('@'); substring(at+1) with validation."],
      ['Use StringBuilder to append 1000 times in loop.', 'StringBuilder sb=new StringBuilder(); for(...) sb.append(x);'],
      ['Why does "a"+"b" compile differently in loop vs constant?', 'In loop, repeated concatenation may create many objects unless using StringBuilder.'],
      ['Compare two strings case-insensitively.', 's1.equalsIgnoreCase(s2) or regionMatches.'],
      ['Strip leading/trailing with strip() vs trim() (Java 11+).', 'strip() removes Unicode whitespace; trim() removes chars <= U+0020 only.'],
      ['Convert String to int safely with Optional pattern.', 'Optional.ofNullable(s).map(Integer::parseInt) with try/catch or use Integer.parseInt in try block.'],
    ],
    seniorScenario: [
      ['Logs allocate huge strings per request causing GC pressure. Fix?', 'Lazy logging APIs, parameterized messages, avoid string concatenation before log level check if expensive.'],
      ['Usernames mismatch due to Unicode normalization (lookalike chars). Approach?', 'Normalize with Normalizer, define allowed charset, and store canonical form.'],
      ['Regex DoS (catastrophic backtracking) on user input. Mitigation?', 'Timeout on regex, possessive quantifiers, simpler parsers, or input length limits.'],
      ['Migrating from String to byte[] for secrets in memory?', 'Use char[] where possible and clear arrays after use; Strings stay in pool and are harder to scrub.'],
      ['International sort order wrong in UI. Cause?', 'Use Collator with appropriate Locale and strength, not raw String.compareTo for user-visible sorting.'],
      ['Huge intern() usage caused Metaspace/GC issues. What happened?', 'intern() pins strings in the pool; unbounded intern of dynamic data can exhaust memory—prefer bounded caches or avoid intern for untrusted input.'],
    ],
    wrongAnswers: [
      'String is mutable—you can change characters in place.',
      '== is the correct way to compare all string contents.',
      'StringBuilder is always slower than using + for concatenation.',
      'substring(0,3) includes index 3 in the result.',
      'split(".") splits on literal dot without escaping.',
      'trim() removes all spaces anywhere in the string.',
    ],
  },

  6: {
    conceptual: [
      ['What is a method signature in Java?', 'The method name plus parameter types (and type parameters); return type is not part of overload resolution.'],
      ['What is method overloading?', 'Multiple methods with the same name but different parameter lists; resolved at compile time.'],
      ['What is recursion and what must every recursive method have?', 'A method that calls itself; it needs a base case that stops recursion and progress toward it.'],
      ['Why can deep recursion cause StackOverflowError?', 'Each call consumes stack space; too many nested calls exceed the thread stack limit.'],
      ['Difference between pass-by-value for primitives vs references?', 'Java passes copies of primitive values and copies of reference values—reassigning the parameter does not change the caller’s variable.'],
      ['What is tail recursion?', 'A recursive call that is the last operation; Java does not guarantee tail-call optimization.'],
      ['What does static mean on a method?', 'Belongs to the class, not instances; cannot access instance fields directly without an object reference.'],
      ['What is varargs and how is it compiled?', 'Type... args becomes an array parameter; callers can pass zero or more arguments.'],
      ['Can you overload methods differing only by return type?', 'No—compile error if parameter lists are identical; return type alone is not enough.'],
      ['What is the call stack?', 'Frames holding local variables and return addresses; recursion depth equals stack frames.'],
      ['When prefer iteration over recursion?', 'When depth may be large or performance is critical—iteration avoids stack growth.'],
      ['What is a helper method pattern?', 'Public method validates input and delegates to private recursive helper with extra parameters (e.g., indices).'],
      ['What does void mean for return type?', 'The method returns nothing; return; is allowed without value.'],
      ['Can main be overloaded?', 'Yes, but only public static void main(String[] args) is the JVM entry point.'],
      ['What is method hiding vs overriding?', 'static methods are hidden by subclass static methods (not polymorphic); instance methods override with dynamic dispatch.'],
    ],
    codeBased: [
      ['Write factorial recursive with base case n<=1.', 'if (n<=1) return 1; return n * factorial(n-1);'],
      ['Write iterative factorial to avoid deep recursion.', 'long r=1; for (int i=2;i<=n;i++) r*=i;'],
      ['Show method overloading: add(int,int) and add(double,double).', 'Both named add; compiler picks by argument types.'],
      ['Detect stack risk: what n breaks naive recursive Fibonacci?', 'Exponential calls—use iteration or memoization for large n.'],
      ['Write gcd(a,b) recursively (Euclidean).', 'return b==0 ? a : gcd(b, a % b);'],
      ['Pass array to method—can method change contents?', 'Yes, same array object; reassignment of parameter does not affect caller reference.'],
      ['Show varargs: sum(int... nums).', 'Loop nums array inside method.'],
      ['Add guard for negative n in factorial.', 'if (n < 0) throw new IllegalArgumentException();'],
      ['Explain binary search recursive variant base cases.', 'if (lo>hi) return -1; mid compare and recurse left or right.'],
      ['Use tail-recursive style for sum 1..n with accumulator helper.', 'static int sum(int n,int acc){ return n==0?acc: sum(n-1,acc+n);}'],
    ],
    seniorScenario: [
      ['Production stack overflow in parsing nested JSON—fix?', 'Replace recursion with explicit stack/iterator, or limit depth and validate input size.'],
      ['Team debates recursion vs iteration for tree walk—criteria?', 'Depth bounds, clarity, stack limits, and performance; use iteration or explicit stack for very deep trees.'],
      ['Log shows unbounded recursion in scheduled job—response?', 'Kill task, add circuit breaker, fix base case, add max depth counter, deploy with regression tests.'],
      ['How to test recursive methods?', 'Unit test base case, one step, and known small inputs; mock or spy only if side effects.'],
      ['Memoization for overlapping subproblems—where?', 'Top-down DP with cache (Map) for Fibonacci-like problems to cut exponential time.'],
      ['Code review: public API exposes recursive helper—issue?', 'Hide helpers as private; document complexity and stack risk for public recursive APIs.'],
    ],
    wrongAnswers: [
      'Java passes objects by reference so modifying the reference changes the caller’s variable.',
      'Tail recursion is always optimized by the JVM.',
      'You can overload two methods that differ only by return type.',
      'Recursive methods do not need a base case if n is small.',
      'static methods participate in runtime polymorphism like instance methods.',
      'Increasing -Xss fixes all StackOverflowError causes permanently.',
    ],
  },

  7: {
    conceptual: [
      ['What is a class vs an object?', 'A class is a blueprint; an object is an instance with state in the heap.'],
      ['What is encapsulation?', 'Hiding internal state behind methods (getters/setters) to control invariants.'],
      ['What is a constructor?', 'Special method that runs on new; initializes object state; can be overloaded.'],
      ['What is this used for?', 'Refers to current instance; disambiguates fields from parameters; can delegate to other constructors with this(...).'],
      ['What is inheritance?', 'Subclass extends superclass, inherits accessible members, can override behavior.'],
      ['What is polymorphism?', 'Same interface or superclass type can refer to different subclass instances; overridden methods dispatch dynamically.'],
      ['What is composition vs inheritance?', 'Composition: class has-a dependency; inheritance: is-a relationship—favor composition when behavior varies.'],
      ['What is an abstract class?', 'Cannot be instantiated; may contain abstract methods subclasses must implement.'],
      ['What is an interface?', 'Contract of abstract methods (and default/static methods in modern Java) a class implements.'],
      ['What is Object superclass?', 'Every class extends Object implicitly; equals, hashCode, toString inherited.'],
      ['What is method overriding?', 'Subclass replaces superclass instance method with same signature; needs @Override for clarity.'],
      ['What is covariant return type in overriding?', 'Subclass method may return a subtype of the superclass return type.'],
      ['What is final on a class or method?', 'final class cannot be extended; final method cannot be overridden.'],
      ['What is instanceof used for?', 'Runtime type check before cast; pattern matching binds variable in newer Java.'],
      ['Why avoid God classes?', 'Single class doing everything violates cohesion; split responsibilities.'],
    ],
    codeBased: [
      ['Minimal class with field, constructor, getter.', 'private final String name; ctor sets; public String getName().'],
      ['Subclass extends superclass and calls super(...).', 'Child(String x){ super(x); }'],
      ['Override toString for debugging.', 'return "User("+name+")";'],
      ['Demonstrate polymorphism: Animal a = new Dog(); a.speak();', 'Runtime calls Dog.speak if overridden.'],
      ['Use instanceof before cast.', 'if (o instanceof Dog d) d.bark();'],
      ['Implement equals/hashCode contract sketch.', 'equals on business keys; hashCode consistent with equals.'],
      ['Interface with default method implemented by class.', 'interface Logger { default void log(String m){ System.out.println(m);} }'],
      ['Abstract class with abstract method.', 'abstract void draw(); concrete subclasses implement.'],
      ['final class cannot be extended—example.', 'final class Config { }'],
      ['Record vs class for DTO (Java 16+).', 'record Point(int x,int y){}'],
    ],
    seniorScenario: [
      ['Deep inheritance hierarchies in domain model—risk?', 'Fragile base class, hard refactors; prefer shallow trees or composition.'],
      ['Liskov substitution violation example?', 'Subclass throws on method superclass promised not to—breaks polymorphism expectations.'],
      ['Testing when logic is in subclass—approach?', 'Test each subclass behavior; use factories for complex graphs.'],
      ['Framework requires no-arg constructor—conflict with your design?', 'Use reflection-friendly patterns or provider factories; document constraints.'],
      ['Migrating from concrete inheritance to interface—steps?', 'Introduce interface, delegate old class, migrate callers gradually with adapter.'],
      ['equals symmetry broken in hierarchy—symptom?', 'a.equals(b) != b.equals(a)—fix by narrowing contract or using composition.'],
    ],
    wrongAnswers: [
      'private methods can be overridden in subclasses.',
      'You can instantiate an abstract class with new if you implement methods later.',
      'static methods override instance methods with the same name.',
      'Every class must explicitly extend Object in source code.',
      'Polymorphism means the compiler picks overridden methods at compile time.',
      'Interfaces can contain instance fields like classes.',
    ],
  },

  8: {
    conceptual: [
      ['What are the four access levels in Java?', 'private, package (default), protected, public—increasing visibility.'],
      ['What does package-private mean?', 'No modifier: visible only within the same package.'],
      ['What does protected allow?', 'Subclass access (even in other packages) and same-package access—not “more public” than package for non-subclasses.'],
      ['Why use packages?', 'Namespace organization, access control boundaries, and modular deployment.'],
      ['What is a fully qualified class name?', 'package.ClassName used when importing is ambiguous or unavailable.'],
      ['What does import do?', 'Allows short names in source; does not affect runtime classpath by itself.'],
      ['What is module-info.java (Java 9+)?', 'Declares module name, exports/opens packages, requires other modules—stronger encapsulation than classpath.'],
      ['Can you have two public top-level classes in one file?', 'No—only one public top-level class per file, matching filename.'],
      ['What is defensive copying for getters?', 'Return copies of mutable fields so callers cannot mutate internal state.'],
      ['Why hide fields with getters?', 'Preserve invariants and allow evolution (validation, lazy init, logging).'],
      ['What is API surface area?', 'Public types and members visible to other modules/packages—smaller is easier to maintain.'],
      ['Difference between same package test vs public API?', 'Tests in same package can use package-private; external clients cannot.'],
      ['What is Java Platform Module System benefit?', 'Reliable configuration and strong encapsulation of JDK internals.'],
      ['What happens if you access JDK internal sun.misc from application code?', 'May break on JDK upgrades; use supported APIs or module opens.'],
      ['How does protected differ from package for subclasses?', 'Subclass in another package can access protected members of superclass; package-private would not allow that.'],
    ],
    codeBased: [
      ['Declare class in package arch.demo; show folder layout.', 'arch/demo/Demo.java with package arch.demo;'],
      ['Use import java.util.List vs FQN.', 'import java.util.List; then List<String> x;'],
      ['Access private field from same class only.', 'private int x; only methods in class touch x.'],
      ['Subclass in another package accesses protected field.', 'extends Base in arch.child; can access protected members of Base.'],
      ['package-private class visible only in package.', 'class Helper { } no modifier.'],
      ['static import for Math.max.', 'import static java.lang.Math.max;'],
      ['Name clash: two Date classes—resolve with FQN.', 'java.util.Date vs java.sql.Date.'],
      ['module-info exports arch.api;', 'Exports package to other modules at compile/runtime.'],
      ['JAR manifest Class-Path for dependencies.', 'Manifest lists other JARs for classpath.'],
      ['Encapsulate list with unmodifiable view.', 'return List.copyOf(internal);'],
    ],
    seniorScenario: [
      ['Library exposes public mutable singleton—risk?', 'Global state, testability, threading; narrow visibility or inject dependencies.'],
      ['Splitting packages for microservices—guideline?', 'Align package boundaries with bounded contexts; avoid cyclic package dependencies.'],
      ['Security manager deprecation (modern Java)—impact?', 'Rely on OS/container isolation and module boundaries instead of legacy SM for app sandboxing.'],
      ['JPMS vs classpath in large monorepo—pain?', 'Explicit module graph helps; migration cost is real—incremental modularization.'],
      ['Protected member used from unrelated class in same package—allowed?', 'Yes, package access allows; protected adds subclass path across packages.'],
      ['Breaking binary compatibility when widening access?', 'Usually safe; narrowing access can break subclasses and clients—semver and deprecation.'],
    ],
    wrongAnswers: [
      'protected members are visible to all classes in the JVM.',
      'package-private means visible everywhere in the project.',
      'You can put two public classes in one .java file if they are small.',
      'import statements change which classes exist at runtime.',
      'private is weaker than package-private.',
      'Modules completely replace the need for classpath in all apps.',
    ],
  },

  9: {
    conceptual: [
      ['What is an exception in Java?', 'An object thrown to signal an error or exceptional condition; disrupts normal control flow.'],
      ['Checked vs unchecked exceptions?', 'Checked extend Exception (not RuntimeException) and must be declared or caught; unchecked extend RuntimeException.'],
      ['What is try-with-resources?', 'Auto-closes AutoCloseable resources in reverse order, even if exceptions occur.'],
      ['What does finally do?', 'Runs after try regardless of outcome—use for cleanup; avoid return in finally.'],
      ['Can you catch multiple exceptions in one catch (Java 7+)?', 'catch (IOException | SQLException e) { ... }'],
      ['What is suppressed exceptions?', 'Primary exception may hide close exceptions; try-with-resources attaches suppressed via addSuppressed.'],
      ['What is throw vs throws?', 'throw actually throws an instance; throws declares checked exceptions a method may emit.'],
      ['When create custom exception?', 'When domain-specific error needs typed handling and clear API contract.'],
      ['What is fail-fast vs fail-safe iterators?', 'ConcurrentModificationException on structural change vs weakly consistent copies—different collection types.'],
      ['What is Error vs Exception?', 'Error is usually unrecoverable (OutOfMemoryError); Exception is meant to be caught in application code.'],
      ['Should you catch Throwable?', 'Generally no—catches Errors and defeats purpose; catch specific types.'],
      ['What is try-with-resources variable scope?', 'Resources declared in try header are final/effectively final in try block.'],
      ['What is exception translation?', 'Catch low-level exception and wrap in domain exception to hide implementation details.'],
      ['What is try-with-resources on multiple resources?', 'Semicolon-separated; closed in reverse order of declaration.'],
      ['Why avoid empty catch blocks?', 'They swallow failures and hide bugs—at least log or rethrow wrapped.'],
    ],
    codeBased: [
      ['try/catch NumberFormatException around parseInt.', 'try { int x = Integer.parseInt(s); } catch (NumberFormatException e) { ... }'],
      ['try-with-resources on FileInputStream.', 'try (var in = new FileInputStream("f")) { ... }'],
      ['Rethrow with cause.', 'throw new ServiceException("msg", e);'],
      ['finally runs even if return in try.', 'Demonstrate log order: try return; finally prints.'],
      ['Multi-catch example.', 'catch (IllegalArgumentException | NullPointerException e)'],
      ['Custom checked exception class.', 'class MyEx extends Exception { }'],
      ['Validate arg and throw IllegalArgumentException.', 'if (x<0) throw new IllegalArgumentException("x");'],
      ['Optional instead of null return for not found.', 'return Optional.empty();'],
      ['Assert state with Objects.requireNonNull.', 'Objects.requireNonNull(name, "name");'],
      ['Convert checked to unchecked with wrapping.', 'throw new UncheckedIOException(e);'],
    ],
    seniorScenario: [
      ['Production 500s with swallowed SQLException in DAO—how found?', 'Logs missing; add error metrics, tracing, and forbid empty catch in review checklist.'],
      ['Library throws checked exception everywhere—consumer pain?', 'Consider unchecked domain exceptions or Result type; document recovery paths.'],
      ['OOM during batch—catch OutOfMemoryError?', 'Do not catch Error; fix heap, streaming, or batch sizing.'],
      ['Retry policy for transient failures—design?', 'Exponential backoff, idempotent operations, max attempts, and dead-letter queue.'],
      ['Global @ControllerAdvice vs local handling—trade-off?', 'Central consistency vs fine-grained responses; combine both.'],
      ['Circuit breaker when downstream always throws—symptom?', 'Fail fast to protect threads; surface degraded mode to users.'],
    ],
    wrongAnswers: [
      'Checked exceptions must always be caught, never declared with throws.',
      'finally always runs before return value is seen by caller.',
      'catch (Exception e) {} is good practice in libraries.',
      'RuntimeException must be declared in throws clause.',
      'try-with-resources works with any class that has close().',
      'You should catch Throwable in business logic to be safe.',
    ],
  },

  10: {
    conceptual: [
      ['What is inheritance in Java?', 'Subclass extends superclass, inheriting fields and methods (subject to access rules).'],
      ['What is polymorphism?', 'A superclass reference can point to subclass objects; overridden methods are invoked dynamically.'],
      ['What is dynamic method dispatch?', 'JVM selects implementation based on actual object type at runtime for instance methods.'],
      ['Can constructors be inherited?', 'No—subclasses call super(...) but do not inherit superclass constructors as their own.'],
      ['What is @Override for?', 'Compiler checks that you truly override an instance method—catches signature mistakes.'],
      ['What is hiding of static methods?', 'Subclass defines static with same name—compile-time binding, not polymorphic.'],
      ['What is covariant return in override?', 'Subclass may return narrower type than superclass method.'],
      ['Why avoid deep inheritance trees?', 'Hard to reason, fragile base class; composition often clearer.'],
      ['What is abstract class vs concrete?', 'Abstract cannot be instantiated; may contain abstract and concrete methods.'],
      ['What is Object.equals contract?', 'Reflexive, symmetric, transitive, consistent; with hashCode consistency.'],
      ['What is Liskov Substitution Principle?', 'Subtypes must be substitutable for base types without breaking expectations.'],
      ['What happens if subclass constructor omits super()?', 'Compiler inserts implicit super() if no args—fails if no matching superclass constructor.'],
      ['Can you make private method “override”?', 'No—private methods are not inherited; subclass method is unrelated.'],
      ['What is final class impact on inheritance?', 'Cannot subclass—useful for security and immutability guarantees.'],
      ['What is instanceof with sealed hierarchy?', 'Exhaustive switches possible with compiler help.'],
    ],
    codeBased: [
      ['Animal/Dog override speak().', 'Dog extends Animal, @Override String speak().'],
      ['Cast only after instanceof.', 'if (a instanceof Dog d) d.fetch();'],
      ['super.method() call from subclass.', 'super.toString() in subclass toString.'],
      ['Prevent inheritance with final class.', 'final class Safe { }'],
      ['Abstract Animal with abstract speak; Dog implements.', 'abstract class Animal { abstract void speak(); }'],
      ['Call superclass constructor with args.', 'Dog(String n){ super(n); }'],
      ['Demonstrate wrong overload vs override.', 'Same name different params is overload, not override.'],
      ['equals/hashCode pair for value class.', 'equals on fields; hashCode matches.'],
      ['Polymorphic collection List<Animal> with Dog instances.', 'List.of(new Dog()) iterate and speak.'],
      ['Use template method pattern with final execute.', 'final void execute(){ hook(); }'],
    ],
    seniorScenario: [
      ['Hibernate proxy breaks equals with inheritance—issue?', 'Class identity vs instance; use business keys or composition.'],
      ['JSON polymorphic deserialization—risk?', 'Open type gadgets; use allowlists, @JsonTypeInfo carefully.'],
      ['Breaking API: making method final in base—impact?', 'Subclasses can no longer override—major version bump.'],
      ['Inheritance for code reuse only—smell?', 'Often composition + delegation clearer than “is-a” lie.'],
      ['Testing abstract class behavior?', 'Concrete test subclass or Mockito spy partial mocks.'],
      ['Diamond problem in Java?', 'Single inheritance for classes; interfaces with default methods need explicit resolution rules.'],
    ],
    wrongAnswers: [
      'static methods participate in dynamic dispatch like instance methods.',
      'You can override private methods in subclasses.',
      'Constructors are inherited from the parent class.',
      'Polymorphism means the variable type decides which method runs.',
      'final class can still be extended by nested subclasses arbitrarily.',
      'equals can be symmetric even if subclasses add fields without changing contract.',
    ],
  },

  11: {
    conceptual: [
      ['What is an interface in Java?', 'A contract of abstract methods a class implements; Java 8+ allows default and static methods.'],
      ['What is an abstract class?', 'May have state, constructors, and mix abstract/concrete methods—cannot be instantiated.'],
      ['When choose interface vs abstract class?', 'Interface for capability across unrelated types; abstract class for shared implementation and state.'],
      ['What is a functional interface?', 'Exactly one abstract method—target for lambdas (@FunctionalInterface).'],
      ['What is multiple interface implementation?', 'A class can implement many interfaces; only single inheritance for classes.'],
      ['What is default method conflict?', 'If two interfaces provide default with same signature, class must override and choose.'],
      ['What is private method in interface (Java 9+)?', 'Helper for default methods, not part of API surface.'],
      ['What is sealed interface (Java 17+)?', 'Restricts which types can implement—exhaustive switches.'],
      ['What is marker interface?', 'No methods—Serializable, Cloneable signal capability (legacy pattern).'],
      ['What is Comparable vs Comparator?', 'Natural ordering inside class vs external ordering strategy.'],
      ['What is interface inheritance?', 'Interface extends other interfaces, inheriting abstract and default methods.'],
      ['Why prefer interfaces for dependencies in DI?', 'Easier testing with mocks and swapping implementations.'],
      ['What is abstract method in interface before Java 8?', 'Implicitly public abstract; still true for non-default methods.'],
      ['Can interface have static fields?', 'Yes—public static final implicitly for fields.'],
      ['What is evolution of interface with default methods?', 'Add new behavior without breaking existing implementers—careful with semantics.'],
    ],
    codeBased: [
      ['interface Drawable { void draw(); }', 'class Circle implements Drawable { public void draw(){} }'],
      ['default method in interface.', 'default void log(){ System.out.println("log"); }'],
      ['static method in interface.', 'static Utils parse(){ return new Utils(); }'],
      ['Functional interface Runnable.', 'Runnable r = () -> System.out.println("hi");'],
      ['Abstract class Shape with field color.', 'abstract class Shape { String color; }'],
      ['Anonymous class implementing interface.', 'new Runnable(){ public void run(){} };'],
      ['Private method used by defaults (Java 9+).', 'private void helper(){} default void x(){ helper(); }'],
      ['Implement two interfaces with same default—resolve.', 'public void m(){ InterfaceA.super.m(); }'],
      ['Comparable<String> natural order.', 'class X implements Comparable<X>{ public int compareTo(X o){...}}'],
      ['sealed interface Shape permits Circle, Rect', 'pattern matching switch exhaustive.'],
    ],
    seniorScenario: [
      ['Library adds default method—binary compatibility?', 'Existing implementers get default at runtime; watch behavioral changes.'],
      ['God interface with 40 methods—fix?', 'Split into cohesive interfaces (Interface Segregation Principle).'],
      ['Testing default method behavior?', 'Concrete stub class or mock implements interface.'],
      ['Framework requires no-interface bean—workaround?', 'Use concrete with interface extracted in your code at boundaries.'],
      ['Migration from abstract class to interface—strategy?', 'Introduce interface, delegate, deprecate abstract over releases.'],
      ['Default method in JDK used in lambda-heavy hot path—concern?', 'Megamorphic call sites; profile before micro-optimizing.'],
    ],
    wrongAnswers: [
      'A class can extend multiple classes in Java.',
      'interface methods can be private abstract.',
      'default methods must be overridden by implementing classes.',
      'Abstract classes cannot have constructors.',
      'Functional interfaces can have two abstract methods if one is default.',
      'Marker interfaces are deprecated and unused in modern Java.',
    ],
  },

  12: {
    conceptual: [
      ['What is encapsulation?', 'Bundling data with behavior and hiding internal representation behind accessors.'],
      ['What is immutability?', 'Object state cannot change after construction—simplifies reasoning and concurrency.'],
      ['How to make a class immutable?', 'final class, final fields, no setters, defensive copies in getters, no leaking mutable internals.'],
      ['Why defensive copy for getters returning collections?', 'Callers could modify internal list if you return reference.'],
      ['What is JavaBeans naming?', 'getX/setX conventions for tooling—may break immutability if setters added carelessly.'],
      ['What is record immutability (Java 16+)?', 'Shallow immutability: components final, accessors, equals/hashCode/toString generated.'],
      ['What is builder pattern for?', 'Construct complex immutable objects stepwise with validation at build().'],
      ['What is validation in setter?', 'Reject invalid state early—preserve class invariants.'],
      ['Why avoid exposing mutable Date from getters?', 'Caller can mutate; return Instant or immutable type or copy.'],
      ['What is unmodifiable vs immutable?', 'Unmodifiable view prevents modification through that reference; underlying may still change elsewhere.'],
      ['What is copy constructor?', 'New instance from existing, copying fields—clone alternative.'],
      ['What is String immutability benefit?', 'Safe sharing, caching in pool, hashCode cacheable.'],
      ['What is volatile for visibility?', 'Reads/writes go to main memory—related to concurrency, not full mutex.'],
      ['What is AtomicReference for immutable swaps?', 'Atomic updates to reference pointing to immutable objects.'],
      ['Why prefer final local variables?', 'Clearer data flow; required for use in lambdas in many cases.'],
    ],
    codeBased: [
      ['Private field + public getter only.', 'private final String name; public String getName(){return name;}'],
      ['Return List.copyOf internal list.', 'return List.copyOf(items);'],
      ['Immutable record.', 'record User(String id, String email){}'],
      ['Builder pattern sketch.', 'static class B{ User build(){ validate(); return new User(...);}}'],
      ['Clone vs copy constructor preference.', 'Copy constructor clearer than Cloneable.'],
      ['Validate in constructor.', 'if (id==null) throw new IllegalArgumentException();'],
      ['Unmodifiable map from factory.', 'Map.copyOf(map);'],
      ['Avoid setter for id after creation.', 'no setId—immutable identity.'],
      ['Use Instant instead of mutable Date.', 'Instant.now() immutable.'],
      ['Char array for password vs String.', 'char[] can be cleared; String stays in pool.'],
    ],
    seniorScenario: [
      ['DTOs mutable in API layer caused race—fix?', 'Immutable DTOs, separate command/query models, thread confinement.'],
      ['Hibernate entity “immutable” view—how?', 'Read-only queries, @Immutable annotation, separate projection records.'],
      ['PII in logs—encapsulation failure?', 'Redact in toString; structured logging with field filters.'],
      ['Breaking encapsulation via reflection in tests—OK?', 'Prefer package-visible test hooks or test doubles over production reflection.'],
      ['Large immutable object graphs—GC pressure?', 'Structural sharing (persistent collections) or careful batching—profile.'],
      ['Immutability and performance on hot path?', 'Object churn vs locking—measure; sometimes mutable buffers win in tight loops.'],
    ],
    wrongAnswers: [
      'Encapsulation means all fields must be public for frameworks.',
      'final class means all fields are automatically immutable.',
      'Returning internal ArrayList reference is safe if you trust callers.',
      'Records are deeply immutable for all component types.',
      'StringBuilder should be used for all string fields in entities.',
      'Immutability eliminates the need for synchronization always.',
    ],
  },

  13: {
    conceptual: [
      ['What is a static nested class?', 'Nested type not tied to outer instance; can be instantiated without outer instance.'],
      ['What is an inner class?', 'Non-static nested class holds implicit reference to outer instance.'],
      ['What is a local class?', 'Class declared inside a method; can access effectively final locals.'],
      ['What is an anonymous class?', 'Inline subclass of class or implementation of interface at instantiation site.'],
      ['Why use nested classes?', 'Logical grouping, encapsulation of helper types, access to outer private members.'],
      ['Memory leak risk with inner classes?', 'Long-lived inner holds outer reference—avoid if outer is heavy.'],
      ['Can static nested class access outer instance fields?', 'Only through an outer reference; not implicitly.'],
      ['What is effectively final?', 'Local variable not reassigned after init—can be captured by lambdas/inner classes.'],
      ['What is Enclosing instance for inner class?', 'Inner requires outer.this to construct from outside static context.'],
      ['What is private constructor with nested builder?', 'Outer controls creation via nested static builder class.'],
      ['Difference anonymous vs lambda?', 'Anonymous can implement multiple methods or stateful class; lambda is single SAM.'],
      ['Can nested interfaces exist?', 'Yes—often for namespacing callbacks.'],
      ['What is serialVersionUID with inner classes?', 'Serialization of non-static inner includes outer—careful with versioning.'],
      ['What is method-local enum (Java 16+)?', 'Enum inside method for small scoped constants.'],
      ['When prefer package-private top-level class over nested?', 'When type is reused widely—nested when truly tied to outer.'],
    ],
    codeBased: [
      ['static class Nested inside Outer.', 'Outer.Nested n = new Outer.Nested();'],
      ['Inner class instantiation.', 'Outer o = new Outer(); Outer.Inner i = o.new Inner();'],
      ['Anonymous Runnable.', 'new Runnable(){ public void run(){} };'],
      ['Local class capturing final int x.', 'int x=1; class L{ void f(){ System.out.println(x);} }'],
      ['Enum inside class.', 'static enum Kind { A,B } inside class.'],
      ['Private static nested Builder.', 'static class Builder { Product build(){...}}'],
      ['Access outer private from inner.', 'class Outer{ private int x; class I{ int g(){return x;}}}'],
      ['Lambda vs anonymous for SAM.', 'Runnable r = () -> {};'],
      ['Static import nested constants.', 'import static Outer.Nested.CONST;'],
      ['Method references to inner instance method.', 'outer::innerMethod'],
    ],
    seniorScenario: [
      ['Thread leaks: non-static inner Runnable in long-lived executor—issue?', 'Holds outer; use static nested or weak references pattern.'],
      ['Serialization of non-static inner—problem?', 'Serializes synthetic outer reference—often not what you want.'],
      ['Testing private inner—approach?', 'Test via outer public API or package-visible test hook.'],
      ['Android/embedded: inner classes and dex size?', 'Many anonymous classes inflate size; lambdas may use invokedynamic.'],
      ['Code review: 5-level deep anonymous listeners—fix?', 'Named classes or lambdas with clear lifecycle.'],
      ['Access control: inner in same compilation unit accessing private outer—OK?', 'Yes, compiler generates synthetic accessors.'],
    ],
    wrongAnswers: [
      'Inner classes can be instantiated without an outer instance.',
      'static nested classes have an implicit reference to the outer object.',
      'Anonymous classes can implement two unrelated interfaces at once.',
      'Local classes can access non-final locals that are reassigned.',
      'Nested classes are always static in Java.',
      'Lambdas always allocate fewer objects than anonymous classes.',
    ],
  },

  14: {
    conceptual: [
      ['What is the Collections Framework?', 'Unified interfaces (List, Set, Map) and implementations (ArrayList, HashMap, etc.).'],
      ['Difference between List and Set?', 'List ordered, allows duplicates; Set no duplicates (equals/hashCode contract).'],
      ['Difference between Map and Collection?', 'Map is key-value; not a Collection though part of collections package.'],
      ['What is ArrayList vs LinkedList complexity?', 'ArrayList random access O(1); LinkedList poor random access, good head/tail ops.'],
      ['What is HashMap load factor?', 'Default 0.75—balance between space and rehash frequency.'],
      ['What is TreeMap ordering?', 'Red-black tree sorted by key—O(log n) ops.'],
      ['What is LinkedHashMap iteration order?', 'Insertion order (or access-order for LRU mode).'],
      ['What is ConcurrentHashMap?', 'Thread-safe Map with segmented locking / CAS—prefer over synchronized HashMap.'],
      ['What is fail-fast iterator?', 'Throws ConcurrentModificationException on structural change during iteration (except iterator’s own remove).'],
      ['What is Collections.unmodifiableList?', 'Wrapper preventing modification through that reference—underlying may still change.'],
      ['What is equals/hashCode contract for HashMap keys?', 'Equal keys must have same hash; unequal keys should distribute hashes.'],
      ['Why avoid mutable keys in HashMap?', 'If key mutates after insert, lookup breaks—undefined behavior.'],
      ['What is Queue interface?', 'FIFO typically—offer/poll; Deque adds stack operations.'],
      ['What is PriorityQueue?', 'Heap-based—poll returns smallest according to comparator.'],
      ['What is immutable collections factories (Java 9+)?', 'List.of, Set.of, Map.of create unmodifiable structures.'],
    ],
    codeBased: [
      ['Create ArrayList and add elements.', 'List<String> x = new ArrayList<>(); x.add("a");'],
      ['Iterate with for-each.', 'for (String s : list) ...'],
      ['HashMap put/get.', 'map.put("k",1); map.get("k");'],
      ['Sort list with Comparator.', 'list.sort(Comparator.naturalOrder());'],
      ['TreeSet natural ordering.', 'new TreeSet<>(Set.of("b","a")) first is "a".'],
      ['LinkedHashMap preserve insertion.', 'Iterate keys in insert order.'],
      ['Use Iterator remove safely.', 'it.remove(); while iterating.'],
      ['Convert array to list.', 'Arrays.asList(arr) fixed-size; new ArrayList<>(...) for mutable.'],
      ['Frequency map with merge.', 'map.merge(word,1, Integer::sum);'],
      ['Immutable copy List.copyOf.', 'List.copyOf(original);'],
    ],
    seniorScenario: [
      ['HashMap infinite loop on bad hashCode—symptom?', 'CPU spin; ensure symmetric, well-distributed hash; security risk for user keys.'],
      ['Large HashMap resize pause—mitigation?', 'Pre-size capacity, G1 GC tuning, or off-heap structures if appropriate.'],
      ['Memory leak in static Map cache—fix?', 'Bounded cache, weak keys if appropriate, eviction policy.'],
      ['Concurrent modification in parallel streams—safe?', 'Source must be concurrent or side-effect free; structural change unsafe.'],
      ['Choosing List impl for workload—process?', 'Access pattern, size, memory, thread safety—benchmark.'],
      ['Deserialization gadget chains via collections—risk?', 'Avoid deserializing untrusted data; use allowlists.'],
    ],
    wrongAnswers: [
      'HashMap guarantees iteration order.',
      'Vector is preferred over ArrayList for all new code.',
      'Hashtable and HashMap are identical.',
      'You can safely use mutable object as HashMap key if you are careful.',
      'Collections.synchronizedList makes iterator thread-safe.',
      'Map extends Collection in Java.',
    ],
  },

  15: {
    conceptual: [
      ['What is Iterator interface?', 'hasNext, next, remove—uniform traversal for collections.'],
      ['Difference iterator vs enhanced for?', 'for-each uses iterator under the hood; iterator allows remove during iteration.'],
      ['What is ListIterator?', 'Bidirectional iteration for List; can add/set at cursor.'],
      ['What is Iterable?', 'Classes implementing iterator() can be used in for-each.'],
      ['Why ConcurrentModificationException?', 'Structural modification while iterating with fail-fast iterator without using iterator.remove.'],
      ['What is weakly consistent iterator?', 'Concurrent collections may not throw CME; reflects best-effort view.'],
      ['What is Spliterator (Java 8+)?', 'Splitting iterator for parallel streams—supports trySplit.'],
      ['Can you remove with for-each?', 'No—use iterator.remove or collect to new structure.'],
      ['What is Enumeration legacy?', 'Older interface (Vector)—prefer Iterator.'],
      ['What is fail-safe iterator cost?', 'Copy snapshot—memory overhead for copy-on-write structures.'],
      ['What is cursor position in ListIterator?', 'Between elements; next() moves forward; previous() backward.'],
      ['What is modCount?', 'Internal counter tracking modifications for fail-fast behavior.'],
      ['Why stream() vs iterator manually?', 'Streams add declarative pipelines; iterator lower-level control.'],
      ['What is forEachRemaining on Iterator?', 'Consumes remaining elements with one lambda.'],
      ['What is immutable iteration?', 'Iterator over immutable snapshot—no CME because source doesn’t change.'],
    ],
    codeBased: [
      ['Manual while(hasNext) loop.', 'while(it.hasNext()) System.out.println(it.next());'],
      ['Remove even numbers with iterator.', 'if (v%2==0) it.remove();'],
      ['ListIterator previous traversal.', 'while(li.hasPrevious()) ...'],
      ['forEach on list.', 'list.forEach(System.out::println);'],
      ['Spliterator trySplit sketch.', 'Spliterator sp = list.spliterator();'],
      ['Stream from spliterator.', 'StreamSupport.stream(spliterator, false);'],
      ['Avoid CME: use iterator not enhanced for when removing.', 'Compare broken vs fixed pattern.'],
      ['Iterable custom class.', 'class R implements Iterable<Integer>{ public Iterator<Integer> iterator(){...}}'],
      ['Enumeration to Iterator adapter.', 'Collections.list(enum.elements()).iterator() legacy.'],
      ['ConcurrentHashMap keySet iterator weak consistency.', 'No CME; may reflect partial updates.'],
    ],
    seniorScenario: [
      ['Big list processing OOM—iterator vs stream?', 'Use streaming from file or DB cursor instead of loading all.'],
      ['Parallel stream on ArrayList while another thread mutates—safe?', 'Unsafe—structural modification not supported; synchronize or use concurrent sources.'],
      ['Custom Spliterator for domain chunking—when?', 'Parallel pipelines over specialized data sources—correct trySplit crucial.'],
      ['Iterator contract violation in library—symptom?', 'Infinite loop or NPE; add tests for hasNext/next pairing.'],
      ['Legacy Enumeration in old API—migrate?', 'Adapter to Iterator; deprecate gradually.'],
      ['forEach on concurrent collection during update—behavior?', 'Depends on iterator type; document weak consistency to users.'],
    ],
    wrongAnswers: [
      'Enhanced for-loop supports remove() on the collection directly.',
      'Iterator.remove() works during enhanced for-each.',
      'All iterators throw ConcurrentModificationException on any concurrent update.',
      'ListIterator can traverse any Collection type.',
      'Spliterator is only used for sequential streams.',
      'modCount is part of public Iterator API.',
    ],
  },

  16: {
    conceptual: [
      ['What is Comparable?', 'Interface for natural ordering: compareTo returns negative/zero/positive.'],
      ['What is Comparator?', 'External comparison strategy; can define multiple orderings for same type.'],
      ['What is natural ordering contract?', 'compareTo must be reflexive, antisymmetric, transitive, consistent with equals ideally.'],
      ['What is Comparator.comparing?', 'Build comparator from key extractors and method references.'],
      ['What is nullsFirst/nullsLast?', 'Comparator helpers to place nulls deterministically.'],
      ['Difference compareTo vs equals inconsistency?', 'TreeSet uses compareTo; if inconsistent with equals, Set contract breaks weirdly.'],
      ['What is stable sort?', 'TimSort preserves relative order of equal elements—important for multi-key sorts.'],
      ['What is reversed() on Comparator?', 'Flips ascending/descending order.'],
      ['What is thenComparing?', 'Lexicographic multi-field comparison.'],
      ['Why primitives use Integer.compare in compareTo?', 'Avoid overflow bugs from naive a-b subtraction.'],
      ['What is Arrays.sort for objects?', 'Requires Comparator or Comparable; uses TimSort.'],
      ['What is Collator for strings?', 'Locale-aware String comparison beyond Unicode code points.'],
      ['What is partial order vs total order?', 'Some pairs may be incomparable—rare in Comparable; Comparator can throw.'],
      ['What is priority queue ordering?', 'Head is least according to comparator or natural order.'],
      ['What is equals/hashCode with SortedSet?', 'Elements must compare consistently; duplicate “equal” elements not allowed in Set.'],
    ],
    codeBased: [
      ['class Person implements Comparable<Person> by name.', 'public int compareTo(Person o){ return name.compareTo(o.name);}'],
      ['Comparator.comparing(Person::getAge).reversed()', 'Chain example.'],
      ['Sort with nullsLast.', 'Comparator.nullsLast(Comparator.naturalOrder())'],
      ['Arrays.sort custom array.', 'Arrays.sort(arr, Comparator.comparing(Point::x));'],
      ['Collections.sort list.', 'Collections.sort(list, cmp);'],
      ['Integer.compare(a,b) not a-b.', 'Safe for large ints.'],
      ['thenComparing for tie-break.', '.thenComparing(Person::getId)'],
      ['Comparator for case-insensitive.', 'String.CASE_INSENSITIVE_ORDER'],
      ['TreeMap with custom comparator.', 'new TreeMap<>(Comparator.reverseOrder())'],
      ['PriorityQueue with Comparator.', 'new PriorityQueue<>(Comparator.comparing(Task::deadline))'],
    ],
    seniorScenario: [
      ['Sorting user-visible list—wrong order in Turkish locale?', 'Use Collator.getInstance(locale) not String.compareTo.'],
      ['Database ORDER BY differs from Java sort—bug?', 'Normalize collation or sort in DB consistently with app.'],
      ['Comparator as hot path—micro-optimize?', 'Avoid boxing, cache comparators, measure before tricks.'],
      ['equals/compareTo mismatch in entity used in TreeSet—symptom?', 'Duplicates or “missing” elements—align contracts.'],
      ['Sorting JSON keys for canonical signatures—approach?', 'Recursive sort keys, defined byte encoding—security for crypto.'],
      ['Breaking change: Comparable implementation change—risk?', 'Persisted sorted sets may reorder—migration plan.'],
    ],
    wrongAnswers: [
      'compareTo should return boolean.',
      'Comparator and Comparable are the same interface.',
      'You can use a-b for all int comparisons in compareTo safely.',
      'TreeSet uses equals to decide membership only.',
      'nulls are sorted first by default in all JDK sorts.',
      'Arrays.sort on primitives uses the same TimSort as objects.',
    ],
  },

  17: {
    conceptual: [
      ['What is java.io vs java.nio?', 'Classic streams vs NIO buffers/channels—NIO.2 (java.nio.file) for modern file APIs.'],
      ['What is Path vs File?', 'Path (NIO.2) preferred; File has legacy issues.'],
      ['What is Files.readAllLines?', 'Convenience for small text files—loads entire file into memory.'],
      ['What is try-with-resources for files?', 'Ensures streams closed—Files.newBufferedReader etc.'],
      ['What is Charset/StandardCharsets?', 'Specify encoding explicitly—avoid platform default surprises.'],
      ['What is WatchService?', 'Watch directory for changes—event-driven file monitoring.'],
      ['What is FileVisitor for walkFileTree?', 'Walk directory tree with pre/post directory hooks.'],
      ['Difference InputStream vs Reader?', 'Bytes vs characters; Reader uses charset decoding.'],
      ['What is memory-mapped files?', 'MapFileChannel to ByteBuffer for large file access patterns.'],
      ['What is IOException hierarchy?', 'Many checked IO exceptions—must handle or declare.'],
      ['What is Files.createTempFile?', 'Creates temp file with proper attributes—delete on exit carefully.'],
      ['What is symbolic link handling?', 'Files.readSymbolicLink, FOLLOW_LINKS option in walk.'],
      ['What is FileSystems.getDefault?', 'Access to default provider; can get FileSystem for ZIP/JAR.'],
      ['Why avoid File.separator concatenation strings?', 'Use Path.resolve for cross-platform correctness.'],
      ['What is buffering for performance?', 'BufferedReader/BufferedWriter reduce system calls.'],
    ],
    codeBased: [
      ['Files.readString(Path.of("a.txt"))', 'Java 11+ read entire file as String with charset.'],
      ['Files.writeString(path, "hi", StandardOpenOption.CREATE)', 'Write text easily.'],
      ['try (var lines = Files.lines(path)) lines.forEach(...)', 'Stream lines lazily.'],
      ['Path.resolve sibling.', 'path.getParent().resolve("other.txt")'],
      ['Files.walk max depth.', 'Files.walk(path, 2)'],
      ['Copy with REPLACE_EXISTING.', 'Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING)'],
      ['Read all bytes for binary.', 'Files.readAllBytes(path)'],
      ['new FileInputStream vs Files.newInputStream.', 'Prefer Files.newInputStream with Path.'],
      ['Charset.forName("UTF-8")', 'Explicit encoding.'],
      ['DirectoryStream filter *.java.', 'try (DirectoryStream<Path> ds = Files.newDirectoryStream(dir, "*.java"))'],
    ],
    seniorScenario: [
      ['Log rotation fills disk—ops?', 'External logrotate, quotas, monitoring; app should not swallow IOException on write.'],
      ['Reading huge file with readAllBytes—OOM?', 'Stream with lines or channels; chunk processing.'],
      ['File locking between processes—approach?', 'FileLock on FileChannel; handle overlap and NFS caveats.'],
      ['Sensitive data in temp files—risk?', 'SecureDirectoryStream, restrictive permissions, delete in finally.'],
      ['Watching config directory—thundering herd?', 'Debounce events, reload idempotently.'],
      ['Windows vs Linux path case sensitivity—bug?', 'Test on both; normalize paths for keys.'],
    ],
    wrongAnswers: [
      'Files.readAllLines is always the best choice for any file size.',
      'Reader reads raw bytes without decoding.',
      'Path and File are unrelated—you cannot convert between them.',
      'IOException is unchecked so you can ignore it.',
      'Default charset is always UTF-8 on every JVM.',
      'Files.deleteIfExists never fails.',
    ],
  },

  18: {
    conceptual: [
      ['What is an enum in Java?', 'Type-safe fixed set of constants; full class with optional fields/methods.'],
      ['Why prefer enum over string constants?', 'Compiler-checked exhaustiveness in switch; no invalid values.'],
      ['Can enum have constructors?', 'Yes—private (implicitly) constructors initialize constant-specific state.'],
      ['What is enum ordinal?', 'Position in declaration—avoid relying on it for business logic (fragile to reorder).'],
      ['What is EnumSet?', 'Compact bit-vector set of enum elements—very efficient.'],
      ['What is EnumMap?', 'Array-backed map keyed by enum—faster than HashMap for enum keys.'],
      ['What is Java record?', 'Immutable data carrier with generated accessors, equals, hashCode, toString.'],
      ['What is compact constructor in record?', 'Validation/normalization without repeating field list.'],
      ['Can record implement interfaces?', 'Yes—cannot extend classes (already extends Record implicitly).'],
      ['What is sealed class/interface?', 'Restricts subclasses—exhaustive pattern matching with compiler.'],
      ['Difference enum singleton vs class singleton?', 'Enum singleton is serialization-safe and thread-safe by JVM.'],
      ['What is switch on enum exhaustiveness?', 'Compiler warns if cases missing (depending on settings).'],
      ['What is record pattern (Java 21+)?', 'Deconstruct record in instanceof/switch patterns.'],
      ['Why avoid enum with behavior in domain—criticism?', 'Can become God enum; sometimes strategy pattern clearer.'],
      ['What is serialization of enum?', 'Special handling by name—stable across versions if constants stable.'],
    ],
    codeBased: [
      ['enum Status { ON, OFF }', 'Status s = Status.ON;'],
      ['enum with field Http(int code)', 'constructor stores code; method code()'],
      ['EnumSet.of(Day.MONDAY, Day.FRIDAY)', 'Set of days.'],
      ['EnumMap<Day, String> schedule', 'Map keyed by enum.'],
      ['record Point(int x, int y){}', 'Immutable point.'],
      ['record User(String email){ compact constructor { if(email==null) throw ...}}', 'Validation.'],
      ['sealed interface Expr permits Add, Num', 'sealed hierarchy.'],
      ['switch (e) { case ON -> 1; case OFF -> 0; }', 'enum switch expression.'],
      ['Record equals by components.', 'new Point(1,2).equals(new Point(1,2)) true.'],
      ['Implement interface in record.', 'record R(int x) implements Comparable<R> { ... }'],
    ],
    seniorScenario: [
      ['API returns new enum constant—client switch breaks?', 'Use default branch or exhaustive handling; communicate API versioning.'],
      ['JPA enum ordinal vs string storage—trade-off?', 'String readable in DB; ordinal breaks on reorder—prefer STRING or explicit code.'],
      ['Record in public API—binary compatibility when adding field?', 'Adding component is breaking change—use versioning or wrapper.'],
      ['Large EnumSet in hot path—memory?', 'Very compact; still profile if millions of sets.'],
      ['Reflection on records—framework support?', 'Frameworks use accessor names; annotation processors adapt.'],
      ['Sealed classes and Spring proxies—issue?', 'CGLIB subclasses may conflict with sealed permits—document constraints.'],
    ],
    wrongAnswers: [
      'enum constants can be created at runtime with new.',
      'record can extend another class besides java.lang.Record.',
      'ordinal() is stable even if you reorder enum constants.',
      'EnumMap allows null keys like HashMap.',
      'sealed classes allow unlimited subclasses in any package.',
      'switch on enum requires default branch always.',
    ],
  },
};

function toQA(pairs) {
  return pairs.map(([question, answer]) => ({ question, answer }));
}

export function applyInterviewBank(data, bank = INTERVIEW_BANK) {
  for (const day of data.days) {
    const b = bank[day.day];
    if (!b) continue;
    const section = day.sections.find((s) => s.type === 'interview');
    if (!section) continue;
    section.title = 'Interview Drill';
    section.conceptual = toQA(b.conceptual);
    section.codeBased = toQA(b.codeBased);
    section.seniorScenario = toQA(b.seniorScenario);
    section.wrongAnswers = b.wrongAnswers;
  }
}
