export default {
  conceptual: [
    { question: "BST property?", answer: "Left < node < right for strict int BST; clarify duplicates." },
    { question: "Traversals list?", answer: "Preorder inorder postorder DFS; level BFS queue." },
    { question: "When inorder sorted?", answer: "Valid BST with strict ordering assumption." },
    { question: "Height vs depth?", answer: "Depth from root down; height of node longest path down to leaf." },
    { question: "BFS space?", answer: "O(w) width of frontier." },
    { question: "Balanced BST why?", answer: "Keeps h=O(log n) for ops; avoid skew." },
    { question: "Serialize tree?", answer: "Preorder with null markers; or level order with nulls." },
    { question: "Subtree sum?", answer: "Postorder aggregate." },
    { question: "BST delete cases?", answer: "Leaf; one child; two children with successor replacement." },
    { question: "Morris traversal?", answer: "O(1) space inorder using threaded links." },
    { question: "Complete tree?", answer: "All levels full except last filled left to right." },
    { question: "Heap vs BST?", answer: "Heap is complete tree with heap order; not BST sorted inorder." },
    { question: "LCA BST?", answer: "Walk from root until split between p and q values." },
    { question: "Diameter?", answer: "Longest path may not pass root—compute per node via DFS." },
    { question: "Kth smallest?", answer: "Inorder iterative k steps O(h+k)." },
    { question: "Balanced check?", answer: "Heights differ ≤1 left/right recursively." },
    { question: "60-second story?", answer: "Define BST, traversals, BFS queue, height skew, validate BST with bounds, complexities O(n)." },
  ],
  codeBased: [
    { question: "Level order result type?", answer: "List of lists per depth." },
    { question: "Max depth recursive?", answer: "1+max(left,right); null base -1 or 0." },
    { question: "Same tree?", answer: "Recursive structure compare." },
    { question: "Path sum?", answer: "DFS subtract target at leaves." },
    { question: "Has path sum root-leaf?", answer: "DFS with running sum." },
    { question: "Count nodes complete?", answer: "If complete use formula else recurse." },
    { question: "Build tree from preorder+inorder?", answer: "Root split inorder ranges." },
    { question: "Zigzag traversal?", answer: "BFS with deque direction toggle." },
    { question: "Boundary traversal?", answer: "Left boundary leaves right boundary careful." },
    { question: "Vertical order?", answer: "Column map BFS/DFS with offsets." },
    { question: "Sum root to leaf numbers?", answer: "DFS accumulate base10." },
    { question: "Trim BST range?", answer: "Recurse prune <L or >R." },
  ],
  seniorScenario: [
    { question: "Huge tree on disk?", answer: "Page-based layouts; lazy loading; B-tree family." },
    { question: "Skewed BST incident?", answer: "Rotations or rebuild from sorted array middle picks." },
    { question: "Immutable trees?", answer: "Path copying for functional structures." },
    { question: "Concurrency updates tree?", answer: "Locks, RCU, or concurrent structures—hard problem." },
    { question: "Expression tree eval?", answer: "Postorder evaluate operators." },
    { question: "Decision tree serving?", answer: "Feature thresholds; different domain but similar traversal." },
  ],
  wrongAnswers: [
    "BST inorder always sorted for any binary tree — false: need BST property.",
    "BFS uses stack — false: queue.",
    "BST search always O(log n) — false: skew O(n).",
    "Height of single node tree is 0 always — conventions differ; clarify.",
    "Preorder alone always uniquely reconstructs — false: need inorder or null markers.",
    "Heap property equals BST — false.",
    "Width O(1) — false: can be O(n).",
    "LCA in BST same as arbitrary tree algorithm always — BST has simpler walk.",
  ],
};
