export default {
  conceptual: [
    { question: "What is a record?", answer: "Immutable data carrier with generated accessors and equals/hashCode/toString." },
    { question: "Sealed type purpose?", answer: "Restrict permitted subtypes for safe exhaustive reasoning." },
    { question: "Compact constructor?", answer: "Validates/normalizes before implicit field assignment." },
    { question: "Why exhaustive switch matters?", answer: "Compiler forces updates when hierarchy grows." },
    { question: "Record vs Lombok?", answer: "Language feature; clearer semantics and reflection." },
    { question: "non-sealed meaning?", answer: "Subtype opens hierarchy again." },
    { question: "Can record extend class?", answer: "No; extends Record implicitly." },
    { question: "JPA with records?", answer: "DTOs yes; mutable entities usually classes." },
    { question: "Serialization concerns?", answer: "Compatibility and evolution of components." },
    { question: "Accessor naming?", answer: "name() not getName by default." },
    { question: "Permits across modules?", answer: "Module readability constraints." },
    { question: "Value-based warnings?", answer: "Do not synchronize on records." },
    { question: "Pattern matching synergy?", answer: "Sealed + records simplify switches." },
    { question: "Domain modeling example?", answer: "Payment events as sealed interface variants." },
    { question: "Immutability caveat?", answer: "If component is mutable object, record still mutable inside." },
    { question: "Reflection components?", answer: "RecordComponent metadata." },
    { question: "60-second record story?", answer: "DTO, validation, sealed, exhaustive switch, no setters." },
  ],
  codeBased: [
    { question: "Area switch sealed Shape?", answer: "switch (s) { case Circle c -> ... case Rect r -> ... }." },
    { question: "Validate record input?", answer: "Compact constructor throws on invalid." },
    { question: "equals two records?", answer: "Component-wise by default." },
    { question: "Implement interface in record?", answer: "record R(...) implements I { }." },
    { question: "Add method to record?", answer: "Instance methods allowed." },
    { question: "Static field in record?", answer: "Allowed." },
    { question: "Generic record?", answer: "record Pair<T>(T a, T b)." },
    { question: "Sealed permits in nested?", answer: "Inner types permitted list." },
    { question: "Switch expression yield?", answer: "Use arrow or yield in blocks." },
    { question: "Record serialization?", answer: "Same mechanisms as class; design serial form." },
    { question: "Copy with change?", answer: "with pattern manual or new record." },
    { question: "Avoid record for service?", answer: "Stateful beans not ideal as records." },
  ],
  seniorScenario: [
    { question: "API evolution add subtype?", answer: "Update permits + all switches; communicate clients." },
    { question: "JSON polymorphic sealed?", answer: "Type discriminator config in mapper." },
    { question: "Team Lombok migration?", answer: "Gradual; prefer records for new DTOs." },
    { question: "Performance record?", answer: "Similar to class; allocation normal." },
    { question: "Security sealed?", answer: "Limit implementations for sensitive parsers." },
    { question: "Code review sealed?", answer: "Ensure permits minimal; document extension policy." },
  ],
  wrongAnswers: [
    "Records have generated setters — false.",
    "Sealed allows any subclass — false permits list.",
    "Record may extend another class — false.",
    "Exhaustive switch never compile-checked — false for sealed total.",
    "Record equals is identity — false components.",
    "Sealed only for classes — false interfaces too.",
    "Compact ctor runs after fields assigned — false validates before.",
    "Records cannot implement interfaces — false.",
  ],
};
