export default {
  conceptual: [
    { question: "Define Big-O in one precise sentence.", answer: "Big-O upper-bounds how fast work grows with input size n, ignoring constant factors and lower-order terms, for sufficiently large n." },
    { question: "How is Θ different from O?", answer: "Θ is tight: the algorithm is both O(f) and Ω(f). O alone allows being faster than f; Θ says the growth rate matches f up to constants." },
    { question: "When do you cite worst case vs average case?", answer: "Worst case for SLAs and adversarial inputs; average or expected when you have a clear random model (e.g., hashing) and can explain assumptions." },
    { question: "What is amortized complexity?", answer: "Spreading rare expensive operations over many cheap ones so the long-run average per operation is small—classic example ArrayList resizing." },
    { question: "Why can O(n²) code pass tests but fail in prod?", answer: "Tests use small n where constants hide growth; production batches or tenant data hit larger n and quadratic loops dominate CPU and p99 latency." },
    { question: "What is auxiliary space?", answer: "Extra memory beyond the input storage your algorithm allocates—arrays, maps, recursion stack—not the input itself unless problem requires counting it." },
    { question: "How does recursion affect space?", answer: "Each active frame uses stack space; depth d costs O(d) even if each frame is O(1). Java lacks guaranteed TCO." },
    { question: "Why might linked-list traversal be slower than array scan at same Big-O?", answer: "Both may be O(n) time asymptotically, but pointer chasing hurts cache locality; constants and memory bandwidth dominate real time." },
    { question: "Explain why comparing all pairs is Θ(n²).", answer: "There are n choose 2 = n(n-1)/2 unordered pairs; each must be examined in the naive approach, so comparisons grow quadratically." },
    { question: "What is the complexity of binary search?", answer: "O(log n) comparisons on a sorted random-access structure because each step halves the remaining range." },
    { question: "Why is sorting often O(n log n)?", answer: "Comparison sorts need Ω(n log n) comparisons in the worst case; standard algorithms like mergesort and Java’s tuned sorts match that bound." },
    { question: "When is counting sort not O(n log n)?", answer: "When keys are integers in a bounded range and you can bucket by value—linear in n plus range—not comparison-based." },
    { question: "What breaks average-case O(1) hash map claims?", answer: "Many collisions, poor hash, or adversarial keys producing long chains or unbalanced buckets—worst per-op can become O(n)." },
    { question: "How do you detect accidental quadratic work in a service?", answer: "Plot latency vs batch size, profile hot methods, search for sort-in-loop or nested streams over collections, add guardrail tests on max size." },
    { question: "What is the master theorem used for?", answer: "Solving recurrences T(n)=aT(n/b)+f(n) from divide-and-conquer—maps to polynomial vs logarithmic work across levels." },
    { question: "Why state assumptions before complexity?", answer: "Sorted vs unsorted, distinct elements, bounded alphabet, and memory limits change which bounds are valid—precision avoids wrong algorithm choice." },
    { question: "Give a 60-second complexity answer template.", answer: "Dominant operation → loops/recursion → multiply nested dimensions → keep largest term → state time and space → note worst vs amortized → mention validation (profile or growth check)." },
  ],
  codeBased: [
    { question: "Complexity of two nested loops both to n?", answer: "Θ(n²)—inner runs n times for each of n outer iterations." },
    { question: "`for (i=0;i<n;i++) for (j=i;j<n;j++)` inner body count?", answer: "Triangular number n(n+1)/2 iterations → Θ(n²)." },
    { question: "Merging two sorted arrays lengths n and m?", answer: "O(n+m) time, O(1) extra if output given; two pointers advance monotonically." },
    { question: "Building HashMap frequency of n strings (average case)?", answer: "Expected O(n) inserts with O(1) average per op under simple hashing assumptions." },
    { question: "DFS on graph V,E adjacency lists?", answer: "O(V+E) time to visit every vertex and edge once." },
    { question: "Recursive fib(n) without memo—time and space?", answer: "Time exponential (~O(2^n) crude), space O(n) stack depth for naive recursion." },
    { question: "`Arrays.binarySearch` on sorted int[]—time?", answer: "O(log n) for the search itself; sorting first would add O(n log n)." },
    { question: "Nested loop: outer n, inner m independent?", answer: "Θ(n·m)—not n² unless m≈n." },
    { question: "PriorityQueue insert n elements each O(log n)?", answer: "O(n log n) total; note `PriorityQueue` uses heap operations." },
    { question: "Two-pointer pair sum on already sorted array?", answer: "O(n) after O(1) setup; if unsorted, O(n log n) to sort first unless extra structure." },
    { question: "Space for iterative O(n) scan returning new array same size?", answer: "O(n) output if required; sometimes O(1) extra if in-place mutation allowed." },
    { question: "Quickselect average vs worst for kth element?", answer: "Average O(n) with good pivots; worst O(n²) without randomization—interviews often ask mitigation." },
  ],
  seniorScenario: [
    { question: "p99 spikes after a refactor; CPU high on one thread. How do you tie to complexity?", answer: "Profile flame graph, identify method with superlinear growth vs payload, reproduce with scaled test data, show before/after operation counts or timing curve, ship fix with max batch and regression test." },
    { question: "PM demands feature combining every order with every coupon. What do you say?", answer: "That is Θ(orders×coupons); propose indexing, prefiltering, or approximate/batch processing with product guardrails and SLO impact analysis." },
    { question: "Microservice times out only for largest customers.", answer: "Suspect O(n²) or unbounded fan-out on tenant size; add metrics on input cardinality per request, cap work, paginate, async offload." },
    { question: "Candidate argues O(n) hash map for dedupe; you see collisions in prod.", answer: "Discuss worst-case degradation, equals/hashCode contract, treeify threshold, when to use TreeMap/LinkedHashMap for determinism." },
    { question: "How do you document complexity in a code review?", answer: "State preconditions, dominant operation, time/space, worst vs amortized, and a test or benchmark that would catch regression." },
    { question: "JIT and GC skew benchmarks—how proceed?", answer: "Warm up, fixed seeds, isolate algorithm, use JMH-style rigor or deterministic op counts; interpret as directional not gospel." },
  ],
  wrongAnswers: [
    "Big-O measures exact milliseconds on your laptop — Big-O is asymptotic growth, not wall-clock time; hardware and constants are stripped out.",
    "O(n²) always beats O(n log n) for every n — false: constants and small n can favor simpler quadratic code; asymptotics compare growth as n→∞.",
    "Space complexity never includes recursion stack — false: call depth consumes stack memory and must be counted for recursive solutions.",
    "Average case equals best case — false without a model; average requires a distribution; best and average can differ wildly (e.g., quicksort).",
    "Amortized O(1) means every single operation is O(1) worst case — false: amortized bounds allow rare expensive operations (e.g., table resize).",
    "If two algorithms are both O(n log n), they are equally fast in production — false: hidden constants, memory traffic, and cache behavior dominate real latency.",
    "Binary search works on any array — false: requires sorted order (or a sorted view) and usually random access; on linked lists it is not meaningful the same way.",
    "Θ and O are interchangeable in interviews — false: Θ is tight; claiming O without clarifying can hide that you are actually linear not quadratic.",
  ],
};
