/** 30 MCQs — ids assigned at build time */
export default [
  {
    level: "basic",
    category: "theory",
    question: "What does **O(n)** primarily describe?",
    options: {
      A: "Exact running time in milliseconds for input size n",
      B: "Upper bound on growth rate of work vs n, ignoring constants",
      C: "Memory usage of the JVM heap only",
      D: "Best-case time for every algorithm",
    },
    answer: "B",
    explanation:
      "Big-O is asymptotic upper bound on how work scales with n, not wall-clock time. A is wrong because constants and hardware differ. C confuses time with space. D is Omega/best-case territory, not Big-O by itself.",
  },
  {
    level: "basic",
    category: "theory",
    question: "Which is typically true for **Θ(f(n))**?",
    options: {
      A: "Only a lower bound",
      B: "Only an upper bound",
      C: "Tight bound: same growth class upper and lower (up to constants)",
      D: "Always equal to O(log n)",
    },
    answer: "C",
    explanation:
      "Theta means growth is sandwiched: both O and Ω of the same f. A is Omega-only, B is O-only, D is nonsense without context.",
  },
  {
    level: "basic",
    category: "code",
    question:
      "What is the tight time complexity of this loop?\n\n```java\nfor (int i = 0; i < n; i++) {\n    for (int j = 0; j < n; j++) {\n        // O(1) body\n    }\n}\n```",
    options: { A: "O(n)", B: "O(n log n)", C: "O(n^2)", D: "O(2^n)" },
    answer: "C",
    explanation: "n iterations of the outer loop each run n inner iterations → n·n = Θ(n²).",
  },
  {
    level: "basic",
    category: "theory",
    question: "Saying an algorithm is **O(n^3)** means:",
    options: {
      A: "It always runs exactly n³ steps",
      B: "It runs in cubic time for every possible input",
      C: "Work grows at most like a constant times n³ for large n",
      D: "It is slower than any O(n²) algorithm for all n",
    },
    answer: "C",
    explanation:
      "Big-O is an upper bound up to constants, not exact step counts. D is false because constants and small-n behavior differ.",
  },
  {
    level: "basic",
    category: "theory",
    question: "**Space complexity** usually counts:",
    options: {
      A: "Only the input array size",
      B: "Extra memory beyond input (auxiliary), including recursion stack when relevant",
      C: "Disk swap usage",
      D: "Number of lines of source code",
    },
    answer: "B",
    explanation:
      "Standard interview definition: auxiliary space plus stack frames for recursive algorithms. Input is often excluded unless stated otherwise.",
  },
  {
    level: "basic",
    category: "code",
    question:
      "Binary search on a sorted array of length n performs how many comparisons in the worst case (typical model)?",
    options: { A: "O(1)", B: "O(log n)", C: "O(n)", D: "O(n log n)" },
    answer: "B",
    explanation: "Each step halves the search interval → O(log n) comparisons.",
  },
  {
    level: "intermediate",
    category: "theory",
    question: "Which pair is **correct**?",
    options: {
      A: "Best case ≤ average case ≤ worst case (always, for every algorithm)",
      B: "Big-O of worst case can be looser than Theta of the same algorithm",
      C: "If T(n)=Θ(n), then T(n)=O(n) and T(n)=Ω(n)",
      D: "O(2^n) and O(n!) are the same class",
    },
    answer: "C",
    explanation:
      "Theta implies both O and Omega of same order. A is false without defining random model. B is confused wording. D is false — factorial dominates exponential.",
  },
  {
    level: "intermediate",
    category: "theory",
    question: "**Amortized** O(1) `ArrayList.add` means:",
    options: {
      A: "Every single add costs exactly one CPU cycle",
      B: "No add ever triggers resizing",
      C: "Average cost per add is constant over a long sequence, though rare adds are O(n)",
      D: "Worst-case per add is O(1)",
    },
    answer: "C",
    explanation:
      "Amortized analysis spreads cost of resizing over many cheap adds. Worst single add can still be O(n).",
  },
  {
    level: "intermediate",
    category: "code",
    question:
      "What is the complexity of building a frequency map over an array of n integers with a `HashMap` (average case, simple uniform hashing model)?",
    options: { A: "O(1)", B: "O(log n)", C: "O(n)", D: "O(n^2)" },
    answer: "C",
    explanation: "One expected O(1) put/get per element → O(n) expected time; worst-case hashing can degrade but average model is O(n).",
  },
  {
    level: "intermediate",
    category: "theory",
    question: "Which recurrence commonly yields **O(n log n)** divide-and-conquer?",
    options: {
      A: "T(n)=T(n/2)+O(1)",
      B: "T(n)=2T(n/2)+O(n)",
      C: "T(n)=T(n-1)+O(1)",
      D: "T(n)=T(n/2)+O(n^2)",
    },
    answer: "B",
    explanation: "Classic merge-sort style: two subproblems half size + O(n) merge per level → O(n log n).",
  },
  {
    level: "intermediate",
    category: "code",
    question:
      "Nested loops: outer i in [0,n), inner j in [0,i). Total inner-body executions?",
    options: { A: "n", B: "n log n", C: "n(n-1)/2", D: "n^2" },
    answer: "C",
    explanation: "Sum_{i=0}^{n-1} i = n(n-1)/2 → Θ(n²) but exact count is triangular number, not n² when j<i.",
  },
  {
    level: "intermediate",
    category: "theory",
    question: "**Polynomial** vs **exponential** in n:",
    options: {
      A: "n^100 grows slower than 2^n for all sufficiently large n",
      B: "2^n is always polynomial",
      C: "n! is O(2^n)",
      D: "Any O(n^k) eventually beats Ω(2^n)",
    },
    answer: "A",
    explanation: "Exponential 2^n eventually dominates any fixed polynomial n^k. C: n! grows faster than 2^n. D is backwards.",
  },
  {
    level: "intermediate",
    category: "theory",
    question: "Why might **micro-benchmarks** mislead complexity conclusions in Java?",
    options: {
      A: "JIT warmup and GC make short runs noisy",
      B: "Java forbids loops in benchmarks",
      C: "Big-O ignores n so benchmarks are useless",
      D: "Profiler always shows exact comparison counts",
    },
    answer: "A",
    explanation: "Warmup, GC, and OS scheduling distort wall time; still useful with care or use operation counting.",
  },
  {
    level: "intermediate",
    category: "code",
    question: "Merging two sorted arrays of lengths n and m takes:",
    options: { A: "O(1)", B: "O(log(n+m))", C: "O(n+m)", D: "O(n*m)" },
    answer: "C",
    explanation: "Two-pointer linear scan — each element pushed once.",
  },
  {
    level: "advanced",
    category: "theory",
    question: "Master theorem case for **T(n)=aT(n/b)+f(n)** when f(n)=Θ(n^{log_b a})?",
    options: {
      A: "Always O(1)",
      B: "Θ(n^{log_b a} log n)",
      C: "Θ(n^2) always",
      D: "O(log n) only",
    },
    answer: "B",
    explanation: "When work at each level matches the critical exponent, you multiply by log n depth factor (balanced tree work).",
  },
  {
    level: "advanced",
    category: "theory",
    question: "Adversarial input to naive hash map if **all keys collide**:",
    options: {
      A: "Lookups become O(1)",
      B: "Lookups degrade to O(n) per op if buckets chain linearly",
      C: "JVM throws on collision",
      D: "TreeMap is automatically used",
    },
    answer: "B",
    explanation: "Worst-case chaining devolves to list scan per bucket — why Java 8+ trees long chains, and why interviewers ask worst case.",
  },
  {
    level: "advanced",
    category: "code",
    question:
      "What is the time complexity of `Arrays.sort(int[])` in Java (dual-pivot quicksort for primitives)?",
    options: {
      A: "O(n) worst case",
      B: "O(n log n) average, O(n^2) worst case (theoretical)",
      C: "O(n^2) always",
      D: "O(log n)",
    },
    answer: "B",
    explanation: "Primitive sort is highly tuned quicksort-family: average O(n log n); pathological worst cases exist theoretically.",
  },
  {
    level: "advanced",
    category: "theory",
    question: "**Recursion depth** for naive recursive Fibonacci fib(n):",
    options: {
      A: "O(log n) stack",
      B: "O(n) stack",
      C: "O(1) stack",
      D: "O(2^n) stack",
    },
    answer: "B",
    explanation: "fib(n) calls fib(n-1) before returning — linear depth chain. Total work is exponential but stack depth is O(n).",
  },
  {
    level: "advanced",
    category: "code",
    question: "DFS on a graph with V vertices and E edges (adjacency list) time:",
    options: { A: "O(V)", B: "O(V+E)", C: "O(V*E)", D: "O(E^2)" },
    answer: "B",
    explanation: "Each vertex visited once, each edge examined once in undirected sense — O(V+E).",
  },
  {
    level: "basic",
    category: "theory",
    question: "Dropping **lower-order terms** in Big-O is valid because:",
    options: {
      A: "They are always zero",
      B: "For large n, fastest-growing term dominates",
      C: "Interviewers forbid mentioning them",
      D: "They cancel with constants always",
    },
    answer: "B",
    explanation: "Asymptotic analysis keeps term that grows fastest; n² + n is O(n²).",
  },
  {
    level: "basic",
    category: "code",
    question: "Single loop from 0 to n-1, O(1) body:",
    options: { A: "O(1)", B: "O(log n)", C: "O(n)", D: "O(n^2)" },
    answer: "C",
    explanation: "n iterations → Θ(n).",
  },
  {
    level: "intermediate",
    category: "theory",
    question: "**Two-pointer** on sorted array for pair sum often yields:",
    options: {
      A: "O(n^2)",
      B: "O(n) after sort (if input unsorted, + sort cost)",
      C: "O(log n) without sort",
      D: "O(1) always",
    },
    answer: "B",
    explanation: "On sorted data, two pointers move linearly. If unsorted, sort first → O(n log n) dominated.",
  },
  {
    level: "intermediate",
    category: "code",
    question: "How many times does the inner `while` run total for classic insertion sort on n elements (worst case)?",
    options: { A: "n", B: "n log n", C: "Θ(n^2)", D: "Θ(n^3)" },
    answer: "C",
    explanation: "Reverse-sorted input forces ~n²/2 shifts/comparisons.",
  },
  {
    level: "advanced",
    category: "theory",
    question: "**Amortized** analysis of incrementing a binary counter from 0 to n:",
    options: {
      A: "Each increment is O(n) amortized",
      B: "Total O(n log n) for n increments from 0",
      C: "Amortized O(1) per increment over the sequence",
      D: "Amortized O(log log n)",
    },
    answer: "C",
    explanation: "Bit flips amortize: many cheap + few expensive carries → O(1) amortized per increment.",
  },
  {
    level: "advanced",
    category: "code",
    question: "Memoized top-down DP for Fibonacci with memo array size n: time to compute fib(n)?",
    options: { A: "O(2^n)", B: "O(n)", C: "O(log n)", D: "O(n^2)" },
    answer: "B",
    explanation: "Each value computed once → O(n) subproblems, O(1) each.",
  },
  {
    level: "intermediate",
    category: "theory",
    question: "Which statement about **Ω (Omega)** is correct?",
    options: {
      A: "f(n)=Ω(g(n)) means f grows at least as fast as g (up to constants) for large n",
      B: "Ω describes an asymptotic upper bound",
      C: "f=Ω(g) means f(n) ≤ c·g(n) for all n",
      D: "Ω and Θ are unrelated symbols",
    },
    answer: "A",
    explanation:
      "Omega is a lower bound: f is at least on the order of g. B describes O. C reverses the inequality. D is false — Θ means both O and Ω.",
  },
  {
    level: "basic",
    category: "theory",
    question: "If an algorithm runs in **Θ(n log n)** time, which bound is always valid?",
    options: {
      A: "O(n) only",
      B: "O(n log n) and Ω(n log n)",
      C: "O(n²) only",
      D: "O(1)",
    },
    answer: "B",
    explanation: "Θ tight-binds growth: it is both O and Ω of n log n (same class).",
  },
  {
    level: "intermediate",
    category: "code",
    question:
      "What is the time to find an element in a **balanced BST** of n nodes (worst case)?",
    options: { A: "O(1)", B: "O(log n)", C: "O(n)", D: "O(n log n)" },
    answer: "B",
    explanation: "Height is O(log n) when balanced; search walks one path from root.",
  },
  {
    level: "advanced",
    category: "theory",
    question: "Why is **O(n log n)** a lower bound for comparison-based sorting?",
    options: {
      A: "Because Java uses quicksort",
      B: "Decision-tree argument: n! leaves need Ω(log(n!)) = Ω(n log n) comparisons",
      C: "Because arrays have fixed length",
      D: "Because mergesort uses linear extra space",
    },
    answer: "B",
    explanation: "Any comparison sort must distinguish all n! permutations — tree height ≥ log₂(n!) = Θ(n log n).",
  },
  {
    level: "advanced",
    category: "code",
    question:
      "Consider `for (int k = n; k > 1; k /= 2) { /* O(1) */ }`. Iterations are:",
    options: { A: "Θ(n)", B: "Θ(log n)", C: "Θ(n^2)", D: "Θ(1)" },
    answer: "B",
    explanation: "k halves each iteration → about log₂ n iterations.",
  },
];