export default {
  conceptual: [
    { question: "ReentrantLock benefits?", answer: "tryLock, timed lock, interruptible lock, Conditions." },
    { question: "Why finally unlock?", answer: "Ensure release on exception paths." },
    { question: "LongAdder when?", answer: "High increment contention; sum eventually." },
    { question: "ConcurrentHashMap iteration?", answer: "Weakly consistent; may miss concurrent updates." },
    { question: "CopyOnWrite use case?", answer: "Many readers rare writes listeners." },
    { question: "BlockingQueue bounded why?", answer: "Backpressure; memory safety." },
    { question: "Semaphore vs Mutex?", answer: "Permit count >1 throttle." },
    { question: "ReadWriteLock trade-off?", answer: "Writer starvation risk if readers constant." },
    { question: "ForkJoin blocking hazard?", answer: "ManagedBlocker or separate pool." },
    { question: "StampedLock caution?", answer: "Complex; validate optimistic reads." },
    { question: "Thread pool sizing?", answer: "CPU vs IO bound; measure queue time." },
    { question: "Rejection policies?", answer: "Abort, CallerRuns, Discard, DiscardOldest." },
    { question: "CAS retry loop?", answer: "CompareAndSet until success or backoff." },
    { question: "VarHandle vs synchronized?", answer: "Fine control; harder correctness." },
    { question: "Scheduled pool drift?", answer: "Fixed delay vs rate; clock skew." },
    { question: "Virtual thread pool?", answer: "Carrier pool; avoid pinning." },
    { question: "60-second advanced concurrency?", answer: "juc locks atomics queues pools backpressure." },
  ],
  codeBased: [
    { question: "AtomicInteger two threads 10k?", answer: "incrementAndGet loop; expect 20000." },
    { question: "ConcurrentHashMap merge?", answer: "merge key remapping function atomic." },
    { question: "tryLock timeout?", answer: "if (lock.tryLock(1, SECONDS)) try {...} finally unlock." },
    { question: "Condition signal?", answer: "await in loop checking predicate." },
    { question: "Executor fixed queue bound?", answer: "LinkedBlockingQueue(cap)." },
    { question: "invokeAll?", answer: "Submit collection; wait all futures." },
    { question: "CompletableFuture supplyAsync executor?", answer: "Pass custom executor for isolation." },
    { question: "Phaser bulk register?", answer: "Dynamic parties." },
    { question: "TransferQueue?", answer: "Blocking handoff producer consumer." },
    { question: "AtomicReferenceFieldUpdater?", answer: "CAS on selected fields." },
    { question: "Striped?", answer: "Lock striping hashed." },
    { question: "ThreadFactory naming?", answer: "Custom factory sets thread names." },
  ],
  seniorScenario: [
    { question: "Thread dump blocked on queue?", answer: "Increase capacity or speed consumer or shed load." },
    { question: "Pool exhausted under spike?", answer: "Bulkhead; separate critical path pool." },
    { question: "Metrics for pools?", answer: "Active, queue size, completed, reject count." },
    { question: "Security of Executors helpers?", answer: "Prefer explicit ThreadPoolExecutor tuning." },
    { question: "Distributed lock vs juc?", answer: "Cluster coordination different product." },
    { question: "Testing thread pools?", answer: "Deterministic latches; avoid sleep." },
  ],
  wrongAnswers: [
    "ReentrantLock unlock is optional if no exception — false; use finally.",
    "Unbounded queues are always the safest choice — false OOM risk.",
    "CAS loops cannot fail on contention — false; they retry.",
    "ReadWriteLock makes invariants automatic — false; still design carefully.",
    "Blocking inside ForkJoin tasks is free — false; it can starve the pool.",
    "ConcurrentHashMap allows null keys — false.",
    "LongAdder gives an exact live total without sum() — false; sum is coherent snapshot.",
    "ScheduledExecutor wall-clock accuracy is perfect — false; drift happens.",
  ],
};
