export default [
  { level: "basic", category: "theory", question: "ReentrantLock vs synchronized:", options: { A: "More API tryLock interruptible", B: "Identical", C: "No unlock", D: "Slower always" }, answer: "A", explanation: "Flexibility." },
  { level: "basic", category: "code", question: "unlock ReentrantLock in:", options: { A: "finally", B: "never", C: "catch only", D: "static" }, answer: "A", explanation: "Safety." },
  { level: "basic", category: "theory", question: "LongAdder vs AtomicLong:", options: { A: "Lower contention sum", B: "Always slower", C: "No sum", D: "String" }, answer: "A", explanation: "Striping." },
  { level: "intermediate", category: "code", question: "ConcurrentHashMap computeIfAbsent:", options: { A: "Atomic per key", B: "Locks whole map", C: "Always recursive", D: "Illegal" }, answer: "A", explanation: "Per-bin." },
  { level: "intermediate", category: "theory", question: "CAS may:", options: { A: "Fail spuriously? no; fail on conflict yes", B: "Never fail", C: "Throw always", D: "GC" }, answer: "A", explanation: "Retry." },
  { level: "intermediate", category: "code", question: "Semaphore permits:", options: { A: "Counting throttle", B: "Binary only", C: "No acquire", D: "Map" }, answer: "A", explanation: "Coordination." },
  { level: "advanced", category: "theory", question: "StampedLock optimistic read:", options: { A: "Validate stamp after", B: "No validation", C: "Always writes", D: "SQL" }, answer: "A", explanation: "Tricky." },
  { level: "intermediate", category: "code", question: "BlockingQueue put:", options: { A: "Waits capacity", B: "Throws always", C: "Drops", D: "Sorts" }, answer: "A", explanation: "Backpressure." },
  { level: "basic", category: "theory", question: "ReadWriteLock write:", options: { A: "Exclusive", B: "Shared with read", C: "No writers", D: "volatile" }, answer: "A", explanation: "Exclusive write." },
  { level: "intermediate", category: "code", question: "ForkJoin misuse:", options: { A: "Block inside task starves pool", B: "Always safe", C: "Faster", D: "No pool" }, answer: "A", explanation: "Pinning." },
  { level: "intermediate", category: "theory", question: "Condition await needs:", options: { A: "Hold lock", B: "No lock", C: "volatile", D: "Atomic" }, answer: "A", explanation: "API contract." },
  { level: "advanced", category: "code", question: "ABA problem awareness:", options: { A: "Pointers/versioned refs", B: "Never happens", C: "Only GC", D: "Only int" }, answer: "A", explanation: "Advanced." },
  { level: "intermediate", category: "theory", question: "CopyOnWriteArrayList:", options: { A: "Snapshot iterators", B: "Mutable iter", C: "High write rate", D: "No thread safe" }, answer: "A", explanation: "Read heavy." },
  { level: "basic", category: "code", question: "AtomicReference:", options: { A: "CAS object field", B: "int only", C: "long only", D: "void" }, answer: "A", explanation: "Generic atomic." },
  { level: "intermediate", category: "code", question: "Phaser vs CyclicBarrier:", options: { A: "More flexible parties", B: "Same always", C: "No reuse", D: "Only 2 threads" }, answer: "A", explanation: "juc." },
  { level: "advanced", category: "theory", question: "LockSupport.park:", options: { A: "Low-level wait", B: "GC", C: "JIT", D: "File" }, answer: "A", explanation: "Primitives." },
  { level: "intermediate", category: "code", question: "Executors.newFixedThreadPool:", options: { A: "Bounded threads unbounded queue risk", B: "No queue", C: "One thread", D: "Virtual" }, answer: "A", explanation: "Backpressure." },
  { level: "intermediate", category: "theory", question: "Fair lock cost:", options: { A: "More overhead lower throughput", B: "Free", C: "No wait", D: "Always faster" }, answer: "A", explanation: "Trade-off." },
  { level: "basic", category: "code", question: "CountDownLatch:", options: { A: "One-shot wait count", B: "Reusable always", C: "Map", D: "List" }, answer: "A", explanation: "Coordination." },
  { level: "advanced", category: "code", question: "CompletableFuture thread pool:", options: { A: "async uses ForkJoin common by default", B: "Always new thread", C: "Same thread always", D: "No pool" }, answer: "A", explanation: "Defaults." },
  { level: "intermediate", category: "theory", question: "LinkedBlockingQueue vs Array:", options: { A: "Linked optional unbounded footgun", B: "Same", C: "No block", D: "Primitives only" }, answer: "A", explanation: "Config." },
  { level: "intermediate", category: "code", question: "ThreadPoolExecutor core max:", options: { A: "Core idle may expire to max under load", B: "Always max", C: "No core", D: "Equal zero" }, answer: "A", explanation: "Tuning." },
  { level: "basic", category: "theory", question: "juc.atomic package:", options: { A: "Lock-free primitives", B: "Removed", C: "GUI", D: "SQL" }, answer: "A", explanation: "Package." },
  { level: "advanced", category: "code", question: "VarHandle vs Atomic:", options: { A: "Lower-level fences", B: "Same only", C: "No access", D: "Deprecated" }, answer: "A", explanation: "Advanced." },
  { level: "intermediate", category: "theory", question: "ConcurrentLinkedQueue:", options: { A: "Non-blocking MPMC style", B: "Blocking always", C: "Single thread", D: "Sorted" }, answer: "A", explanation: "Queue." },
  { level: "intermediate", category: "code", question: "ScheduledExecutorService:", options: { A: "Delayed periodic tasks", B: "No schedule", C: "Only once", D: "File cron" }, answer: "A", explanation: "Timing." },
  { level: "basic", category: "theory", question: "Deadlock with juc locks:", options: { A: "Still possible ordering", B: "Impossible", C: "Only synchronized", D: "volatile prevents" }, answer: "A", explanation: "Design." },
  { level: "advanced", category: "code", question: "Exchanger:", options: { A: "Two-party swap", B: "Many party", C: "Sort", D: "Map" }, answer: "A", explanation: "Rare." },
  { level: "intermediate", category: "theory", question: "Backpressure strategy:", options: { A: "Bounded queue + rejection policy", B: "Unbounded always", C: "Ignore", D: "GC" }, answer: "A", explanation: "Resilience." },
  { level: "intermediate", category: "code", question: "AtomicInteger getAndIncrement:", options: { A: "Returns old value", B: "Returns new", C: "void", D: "throws" }, answer: "A", explanation: "API." },
];
